image support
xtermjs/xterm.js pull request #2503
Opened 2019-10-24 01:17 UTC by jerch

Made a new apporach towards image support in xterm, mainly based on the previous addon. Currently only a playground, will see where we can get with this. Currently not high on the priority list, the discussion in the terminal-wg is still ongoing.

What works so far:
- limited SIXEL support (always scrolling, cursor at right after image insert, no sequences yet to alter behavior)

Planned:
- custom image handling based on terminal-wg discussion

Some preview:
![grafik](https://user-images.githubusercontent.com/6193135/67445071-b7309b80-f60b-11e9-8f30-378bd0ad1a41.png)

2019-10-24 14:06 UTC, jerch commented
@Tyriar Not sure how to deal with outer dependencies in addons - I kept the dep in the addon local package.json. Imho it belongs there, but our build scripts do not respect this yet. For CI I fixed it temporarily by adding another script to the pipelines, locally a `cd addons/xterm-addon-image && yarn` is needed beforehand or yarn will fail.

2019-10-24 17:10 UTC, Tyriar commented on package.json
> +    "lint": "tslint 'src/**/*.ts' 'addons/**/*.ts' -e 'addons/*/node_modules/**'",
Does `addons/src/**/*.ts` work instead?

2019-10-24 17:11 UTC, Tyriar commented on azure-pipelines.yml
> +      cd addons/xterm-addon-image
I guess we should have a `postinstall` script (the one that doesn't run when doing `npm install xterm`) that runs yarn for all addons? This problem needs to be solved to merge ligatures into the core codebase too.

2019-10-24 17:13 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
Can we overlay a canvas instead of modifying the dom elements or drawing to the main canvas? A single implementation regardless of renderer would be great, you also probably don't want to write a shader just for this as you can't acquire 2d and webgl contexts for a single canvas.

2019-10-24 17:21 UTC, Tyriar commented on azure-pipelines.yml
> +      cd addons/xterm-addon-image
If you put something together that works for this we can push it in with a separate PR, even if it doesn't really do anything since this and ligatures needs.

2019-10-24 17:32 UTC, jerch commented on package.json
> +    "lint": "tslint 'src/**/*.ts' 'addons/**/*.ts' -e 'addons/*/node_modules/**'",
Guess so, would be nicer, yepp.

2019-10-24 17:34 UTC, jerch commented on azure-pipelines.yml
> +      cd addons/xterm-addon-image
Well I plan to incorporate the foreign code later on, but atm at the stage of fiddling around with this and that its easier to just refer to outer packages. So yes, would be good to get this working in the first place. Sure, gonna try to find a more general approach.

2019-10-24 17:38 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
Yes the DOM hack is really ugly and slow as hell. Are we safe to always assume we can work on a canvas for image stuff? A "one fits all" solution would be much nicer.

2019-10-24 17:52 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
Canvas should always work for this sort of thing since it's not doing intensive things like drawing all those chars, outside of browser bugs like texture corruption after sleep that can't really be helped. You would be far far better off to batch all the drawImage calls though.

2019-10-24 17:55 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
> You would be far far better off to batch all the drawImage calls though.

Yeah might need some help at with this, you already told me that `ImageBitmap` would help alot, not sure yet how to use this lol.

2019-10-24 18:10 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
@jerch I think what I found in regards to `ImageBitmap` is drawing from it was faster than from a canvas element (at least at the time under Chrome). So you could have a canvas to draw the image to, then export it to an `ImageBitmap` and put that where ever you're caching them for fast future draws. It looks like right now you have a canvas `actual` for each image, I think holding onto so many canvases is bad practice, I know there is a limit to how many webgl contexts you can have at any one time, probably applies to 2d as well?

2019-10-24 18:43 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
Yes I have one canvas per image, which I dont like either (guess I also have to free those on dispose since they "live" on document?) The whole image handling needs some lifecycling to not overwhelm the browser with old images that are long gone, maybe even some blob url fallback (where the browser is free to store things separated from the document). Gonna have to read into the bitmap thing first...

2019-10-24 19:09 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +  private _drawToCanvas(imgId: number, tileId: number, col: number, row: number): void {
See https://github.com/xtermjs/xterm.js/blob/52c562d4b1d2f4638797d91e4d69c7dd893f206a/src/browser/renderer/atlas/DynamicCharAtlas.ts#L316 for how to create it

2019-10-25 15:45 UTC, jerch commented on azure-pipelines.yml
> +      cd addons/xterm-addon-image
See https://github.com/xtermjs/xterm.js/pull/2516 for a possible solution.

2019-10-25 15:57 UTC, jerch commented on package.json
> +    "lint": "tslint 'src/**/*.ts' 'addons/**/*.ts' -e 'addons/*/node_modules/**'",
Fixed.

2020-02-17 19:07 UTC, PerBothner commented
To repeat myself: One you have image support, it is *conceptually* easy to generalize (at least at the user level) to embedded HTML as an opaque blob, at least at the full-width `<div>` level. This is useful for [help and other documentation](http://domterm.org/Features.html#help-and-documentation).

Of course there are security implications (beyond those of images), so it probably should be an optional addon, with an HTML sanitizer (feel free to base one on DomTerm's).

2020-02-18 08:49 UTC, jerch commented
@PerBothner Well the div-overlay idea would work, but breaks with lots of grid mechanics. We most likely will have such an extension one day (as already indicated for "marker overlays"), but I am not sure if images should use that. The idea for images is still to get it working for any terminal, not only HTML based ones that can easily layer stuff on top.
Also real vector support would be nice (analogous to ReGIS), maybe a stripped down SVG variant would do (SVG-terminal or so). It needs a spec w'o any outer ref stuff to not pull in foreign content on terminal side by accident (which again would be a security nightmare). Well its just a rough idea currently.

2020-06-14 15:12 UTC, klamonte commented
@jerch

Just wanted to pass along: the freedesktop thread is basically done with everyone exhausted and throwing up their hands.  But sixel around the world is doing pretty good right now.

* DomTerm's sixel is aaaalmost there, and impressively fast.

* mintty's sixel and iTerm2 are usable now.  I reported some artifacts with it that I think are now fixed and will be in the next release.

* vte's sixel is in active testing, and appears to be solid.

* alacritty's sixel is starting implementation, and there may be a prototype for testing any day now.

* I have put some captures at https://jexer.sourceforge.io/sixel.html for testing.

2020-06-14 15:42 UTC, jerch commented
@klamonte Thx for the update :+1: 

Yeah its somewhat a shame we came to no usable conclusion in the thread. I am not blaming anyone in particular, I for myself was not able to come up with a good solution, so yeah its also partly my own fault.

Ofc I am not done with the topic, still it got somewhat out of my focus. We have a few things to get straight in the corelibs before we can integrate the prototype here further.

> DomTerm's sixel is aaaalmost there, and impressively fast.

Glad you like its speediness :wink:. JS isnt that bad after all, but gets very C-ish for max perf.

2020-09-22 20:56 UTC, jerch commented
@Tyriar Sweet, this still builds. Will see if I find some time to get at least SIXEL running as alpha addon (and once this work, the iTerm image stuff should not be hard to add). The additional canvas overlay for images you suggested above will need some work, also the right buffering is still tricky, as it might get big in terms of memory usage. Not sure yet, if this will need some advanced local storage offloading tricks for scrolled out images (prolly the alpha version will not have that yet).

2020-11-08 20:33 UTC, jerch commented
@Tyriar Slowly getting somewhere with this PR. What works so far:
- own image layer canvas with bitmap support (not renderer dependent anymore)
- autorescaling of images of changed cell metrics (partially dysfunctional due to a missing hook on metrics changes)
- marker triggered eviction of images from storage

The current implementation is quite fast, the trick to significantly speed things up was to reduce `drawImage` calls by drawing neighboring tiles at once. Also the addon shows almost no impact for high text throughput, it adds only 1 - 20 ms for my typical test with `ls -lR /usr`.

Still couple of things to do before it can go alpha:
- add `fontSize` hook / other metrics changes
- implement missing SIXEL modes (scrolling off, different cursor positioning modes)
- better eviction rules with single tile tracking and multiple markers
- some tests
- code cleanup (reduce dirty type hacks on privates in `ImageRenderer`)

And last but not least in the long run I want to add these features:
- allow transparent image overdrawing in `ImageStorage` (image composition)
- resize handling in `ImageStorage` to reduce wrapping artefacts
- iTerm image protocol support

2020-11-11 22:09 UTC, jerch commented
@Tyriar eslint is a troublemaker - it runs into an OOM since I added an API test file to the addon. Seems this is a known issue (see https://github.com/typescript-eslint/typescript-eslint/issues/1192)? My workaround to increase the allocated heap for node does not work under windows, any ideas how to get it working there? Alternatively we could just let eslint run on one of the other platform pipes (should be enough to catch linting issues).
The second test issue is prolly a cell dimension rounding problem which needs manual inspection on OSX with firefox.

Anyway - ready for a first review & test round (as alpha only) :smile_cat:.

2020-11-11 23:13 UTC, jerch commented
@Tyriar Was able to circumvent the OOM by merging the addon test folders into one config used by eslint (see 80e77ef).

2020-11-14 15:49 UTC, jerch commented
Fixed most eviction concerns with multiple rules (see list above). Also added several tests, sadly I cannot do proper nodejs based unit tests anywhere, as most functionality relies on the availability of drawing primitives (`canvas`, `ImageData` and `ImageBitmap`). I might be able to do a drop-in replacement with node-canvas here, but did not yet investigate in this option.

With the changes above the addon is ready for extensive runtime testing. @klamonte Care to test it with Jexer? :smiley_cat: 

@Tyriar, @mofux

2020-11-15 14:38 UTC, jerch commented
Some observations with the JIT on Chrome (did not test again Firefox) - rendering a 963x527 SIXEL image shows these numbers in the timeline:
- first run: 230 ms total, 100 ms for `SixelDecoder.decode`
- 3rd run: 48 ms total, 25 ms for `SixelDecoder.decode`

Idk for sure what happens behind the scenes, my guess is that the JIT somewhere in the 2nd run decided to optimize the whole call chain for the SIXEL stuff (JIT warm-up, 2nd run shows numbers between those above). The interesting bit is the fact that I can force this to happen much earlier by calling `decode` more often with smaller chunks. I wonder if the optimizer kicking in is mainly invocation count bound.

Imho this shows one important thing - a rarely used function in the code will most likely never run optimized. This leads to surprisingly bad runtime behavior and might need special care for rarely used things like the serialize addon (separate warm-up phase needed?)

2020-11-17 19:30 UTC, jerch commented
Made a first early iTerm inline image protocol implemention with the last commit. It reveals the problem that images cannot be loaded synchronously by normal brower interfaces. Unless we want to decode JPG/PNG manually in JS we are stuck with async interfaces.

A possible solution to this:
- sync:
  - pull everything needed for correct buffer allocation in front (mainly determining image dimensions)
  - announce incoming image to image storage, do needed space allocation on the terminal buffer
  - return to parser
- async:
  - collect all image data chunks (mainthread --> worker)
  - decode image data (worker)
  - create `ImageBitmap` (worker, chrome and firefox) or `Image` from blob (mainthread, possible safari workaround)
  - update record in image storage and mark for redraw (shown on the next animation frame)

Being halfway async introduces problems for the yet to come image overlay composition, as fast redraws will likely stack up in the "waiting for image decoding"-chain (data input from the parser being too fast). Not sure yet how to work around that (might need some "image dropping" workaround).

2020-11-22 01:41 UTC, mofux commented
I love it - finally I can watch the graphical weather report in my terminal

`curl v3.wttr.in/Jena.sxl`

<img width="796" alt="Screenshot 2020-11-22 at 02 21 50" src="https://user-images.githubusercontent.com/2785983/99891361-7faa7d80-2c69-11eb-94b9-f8dbc4bb88d9.png">

This seems to work very reliable, good job!

2020-11-22 14:18 UTC, jerch commented
@mofux Another maybe slightly more useful use case is for data scientists that want to visualize their data quickly. Several REPLs like Julia and gnuplot already support SIXEL, short example with gnuplot:
```gnuplot
gnuplot> set terminal sixel size 400,200 background rgb 'black' font 'monospace, 8.0'
gnuplot> set border lc rgb 'white'
gnuplot> set key tc rgb 'white'
gnuplot> plot [0:2*pi] sin(x) lc 7
```
which shows up as this:
![recorded](https://user-images.githubusercontent.com/6193135/99906149-ba49ff80-2cd5-11eb-9227-fa1d093787bd.gif)

2020-11-29 16:21 UTC, jerch commented
Oh well, seems the mpv guys work on SIXEL support:

![recorded](https://user-images.githubusercontent.com/6193135/100547137-6a36e400-3265-11eb-9147-1f7199d6cebd.gif)


The example above shows several things:
- the  in-place eviction works correctly, it does not hog memory when bombed with tons of SIXELs (see log output on right side)
- CPU usage is critical even at this low resolution: 60-90% for normal SIXEL handling (good frames at the beginning)
- mpv has still bugs in video skipping leading to broken SIXEL frames (when the terminal starts to fill the text buffer) - here our CPU gets insane (>> 100%), prolly due to heavy bufferline recycling
- there is no sound in gifs :smile_cat: 

(Note: ignore the blueish snow, it is an artefact of my gif recorder with the palette being off, was much better in terminal)

2020-12-02 21:39 UTC, avih commented
@jerch is there anything preventing reporting the size in pixels with ioctl?

2020-12-03 10:12 UTC, jerch commented
@avih 
Yes the ioctl way is the best we have currently, thats even clear among the terminal-wg. It still raises questions, as a terminal is basically not about pixels at all, but cols/rows.

There is also some discussion about virtual sixel-pixel size, which always maps with a fixed pixel size to a single test cell. The problem with this is - it is not implemented that way by most terminals currently and makes pixel perfect output almost impossible (not to mention the much higher image processing needs on terminal side). Still it would reflect stable row/col coverage and would be more in line with older devices (VT340 assumed this to be 10x20).

2020-12-03 12:02 UTC, avih commented
> There is also some discussion about virtual sixel-pixel size

Indeed, I also thought about it. I have a vague plan to add sixel support to st and I did think that a fake/virual number of pixels/cell could be a useful thing for sixel - like you said - to allow bigger (scaled) image size with less data sent to the terminal, though I'm not there yet (I am very familiar with st and occasionally contribute to it, but I didn't yet try to make it handle sixel).

Anyway, considering the current ubuquity of ioctl, together with the fact that it will not be trivial for mpv to add two-way communication with the terminal (to support other report methods), I would think your best shot is to push it with node-pty.

But even if youdon't, mpv still falls back to 320x200 on such case (at least it should in your case where 0x0 is reported - it does, right?), so it's not terrible, and if you have a way to query the terminal from the shell, then you can simply integrate it into the CLI invocation, e.g. `mpv --vo-sixel-width=$(get_term_px_width) ....` etc.

2020-12-03 12:28 UTC, jerch commented
@avih Well I dont really plan to get smooth video playback with SIXEL done in xterm.js, as even the best javascript JIT engine still roughly doubles the runtime compared to similar C code.

Still mpv is a nice testbed for the addon to spot data/memory pressure and trying to work around redrawing issues, esp. GC hiccups. The language/browser env itself is quite restricted when it comes to the need of high load concurrency. (Geez I wished we had an Erlang clone in the browser, not this JS thingy :smile_cat:).

2020-12-03 12:30 UTC, avih commented
Well, your gif in your last test looks pretty good to me, and would be even better with `--profile=sw-fast --really-quiet` ;)

2020-12-18 00:24 UTC, christianparpart commented
> Update:
> Since the discussion in terminal-wg is stalled, we should not wait for someone to come up with a "one-fits-all" image solution for terminals. Instead I think we should try to get most SIXEL primitives working, and maybe later on parts of the iTerm2 image protocol.

@jerch FYI: I am currently actively working on finishing what was started in terminal-wg about the "good image protocol" and will provide a proper specification and a PoC implementation for RFC soon. In the hope that it will satisfy the most of us. :)

2020-12-18 11:26 UTC, jerch commented
@christianparpart Good to hear that some ppl are still interested in a better image sequence, which actually honors terminal awkwardities.

Btw I started from scratch with the same idea, but got not far yet with it (see my early stub [here](https://github.com/xtermjs/xterm.js/blob/07a2d249ac237da402b831124a3a47804ed36544/addons/xterm-addon-image/src/ImageHandler.ts)). While thinking about it I basically stumbled over @egmontkob's idea to upload arbitrary blob content into a terminal and use it later on with "document specific sequences" (e.g. uploading image stuff can be used with image sequences, uploading PDFs could be used with PDF sequences, if a terminal cares to implement such a PDF interface, and so on). Such a binary blob interface sounds intriguing as it would simplify several low level handling aspects behind one sequence, while opening the terminal to any kind of document related stuff within its implemented document interfaces. Well it is still just a wild idea atm.

If you like - lets discuss things more in detail. But be aware if the "broad discussion problem" - the more peeps feel like bringing up their ideas, the more the whole discussion will be watered and the result will suffer. In the end the wg thread died because of this. So yes - feel free to say "NO" to my offer.

2020-12-18 16:06 UTC, christianparpart commented
I love that for sure. I think I am pretty far and have addressed even more issues than mentioned in the threads. You can reach out to me via email for now. Christian at parpart.family

I will love to give you all the details, status and PoC implementation state.

2020-12-18 18:15 UTC, PerBothner commented
I agree a good protocol would enable: "Here is a PNG image (possibly previously uploaded). Imagine that it's scaled to W×H character cells to fit (or fill, etc.) that area, aligned to the top-center (or wherever else).  Select an AxB subrectangle (K..A+A-1, L..L+B=1) and draw it at (X..X+A-1, Y..Y+B-1). (All numbers character columns/rows.)" So far so good.

However, you don't want to deal with the image as AxB separate tiles, at least at the implementation level, both for efficiency and to avoid stitching artifacts at cell boundaries. So that leads to complications if someone draws something (text or a smaller image) on top of part of an earlier image. It's not so difficult if the terminal does its own character rendering (painting), but it's more complicated if it uses some library to display strings - especially if using a [scene graph](https://en.wikipedia.org/wiki/Scene_graph) (like a browser's [DOM](https://en.wikipedia.org/wiki/Document_Object_Model)) or [retained mode](https://en.wikipedia.org/wiki/Retained_mode).

Specifically, if cell (X,Y) contains part of an image, and you override that cell with either text or part of some other image, then I think it should be undefined (or defined as erase) what are the contents of all of the other (unmodified) cells of the original image.  I think the use-case of *partly* overwriting an image has limited usefulness, is undefined regardless (because of  character-cell size non-determinacy), and difficult to implement using some libraries/APIs.

2020-12-25 09:47 UTC, christianparpart commented
Merry Christmas to you all!

@jerch did you receive my mail? I'd just like to know. I can wait with a reply ;-)

2021-01-02 16:42 UTC, jerch commented
@PerBothner The tiling is indeed a problem with ready-to-go libs for certain "document types" where you cannot control what shows up on the screen at certain positions. But since you agree with the cropping idea of a good image protocol - isn't it an inevitable consequence of the cropping caps, e.g. the sum of subareas is equal to the image as a whole?

To me this boils down to the question, how a terminal view can be composed with complex data types in mind, while still respecting the text cell grid of terminals in the most useful and natural way. Static images are somewhat exclusive here, as they only need a very simple source to output position mapping (pixel to cell translation), which can easily be precalculated/cached, while anything beyond static images is much harder to deal with at this level (animated GIFs already create headaches, not to speak of interactive vectors).
I would treat more complex content (if it will ever make it to the terminal) very pragmatic - where it is possible to retain the cell/tile logic, try to keep it intact, as it is the natural expectation of terminal users. This is very easy with static images. Where this is not possible with justifyable effort* - simply evict the content as a whole, maybe with some visual placeholder feedback.

[*] This again depends much on the emulator internals - an emulator which controls every bit of the output with OpenGL primitives can easily skip/map anything to any position.

2021-01-02 18:55 UTC, PerBothner commented
@jerch _"since you agree with the cropping idea of a good image protocol"._ Sort-of.  The main use-case for cropping seems to be tmux and similar multiplexers - but I think a multiplexer is the wrong tool. (Most things tmux can do DomTerm can do better.)   But for practical/political reasons it is desirable to support cropping.

_"isn't it an inevitable consequence of the cropping caps, e.g. the sum of subareas is equal to the image as a whole?"_ I don't think so.  A cropped image doesn't necessarily have subareas. The model could be "reserve this space in the terminal, and display the (possibly-cropped) image in that area (and disable line-wrapping for the affected lines)." You could specify that any subsequent write or erase in that area invalidates the reservation and the image.

_"To me this boils down to the question, how a terminal view can be composed with complex data types in mind, while still respecting the text cell grid of terminals in the most useful and natural way."_ For existing applications, yes, but for "rich" applications (including images) we really need to go beyond fixed-width (or single+double-width) characters (which are really ugly for some languages). But that is a separate discussion.  (Medium-term I plan to implement a shell+DomTerm integration to support variable-width text, probably using `fish`. It's conceptually simple: Just a flag to tell the shell's input editor to delegate line-breaking to the terminal, and treat the terminal width as conceptually infinite. This also avoids repainting glitches on resize, plus it avoids the overheads of `wcwidth`.)

_"the cell/tile logic ... is the natural expectation of terminal users."_  Is it? I don't think users care about the cell/tile logic. They certainly don't need that all cells be the same size. Users want to be able to use REPLs, and to run in the same window  certain keyboard-friendly applications controlled by the REPL.  Look at the popularity of interfaces like Jupyter. I want to integrate the features of a Jupyter-like REPL with being able to run traditional terminal-oriented programs.

Of course this doesn't effect the immediate issue of agreeing on a image protocol that can be widely implemented.  But I think we should be open to more expansive possibilities for terminals. The 2-dimensional grid of fixed-width character cells is no longer needed or sufficient.  DomTerm proves we can be backward-compatible without that limitation.

2021-03-19 11:26 UTC, jerch commented
@Tyriar Before this can go public for alpha testing I decided to do a few changes, mainly to reduce complexity of the PR:

- [ ] Remove iTerm2 protocol support. This is currently at a very early stage and def. not usable for everyday users yet. Still needs more investigation about protocol parameters and their meaning.
- [ ] Remove own image protocol draft. This is just a docs draft atm, can be re-added / implemented later on once we have a satisfying format spec.
- [ ] Move SIXEL decoding to web worker. This was my main concern and the reason for not pushing the PR to release yet, now with async handlers this can be addressed. Do you have some ready-to-go TS/webpack blueprints to get webworker builds rolling?
- [ ] Better way to access `TerminalCore` privates. Currently I maintain a fake interface mimicking the needed core properties, which was easy to get it working, but will fail once privates change. Will see if I find here something less hacky and better to maintain (at least there should be a test case probing for all needed properties).

So the idea is to reduce the addon functionality to SIXEL support with decoding done in a web worker. For now the drawing will stay in the mainthread, imho we should address the idea of an `OffscreenCanvas` drop-in as a next step afterwards. This will be huge and still needs tons of investigation to get a working failover interface with drawing primitves. Definitely qualifies for a separate PR.

2021-03-20 14:21 UTC, jerch commented
Made a first naive implementation with web worker SIXEL decoding with promising results (tested with a 22MB sixel file which decodes to an image of 6000x4000 px):

|                   | single threaded | with web worker |
| -------------- | :-------------------- | :-------------------- |
| total handler runtime (`hook` to `unhook`) |  2200 ms | 1300 ms |
| script runtime on main thread | 75% (~ 1600 ms) | 35% (~450 ms) |
| total blocking time* | 500 ms | 185 ms |

The implementation is not yet optimized by any means (no SAB, instead uses `Transferable` in only one direction without any clever mem pooling, slightly subpar sixel decoder). with optimizations in place I expect the total runtime to drop to ~1000 ms. But before dealing with optimizations I have to sanitize the exchange protocol and the lifecycling.

[*] The total blocking time gets estimated by chrome in devtools and is a good indicator for possible lag spikes on the main thread. The value is still quite high for my test case with a web worker. This happens due to moving a rather silly huge image onto a canvas with `ctx.putImageData`. This cannot be avoided unless the whole drawing was moved to the worker.

2021-03-21 20:29 UTC, jerch commented
@Tyriar Done with the worker adjustments and basic cleanup. Would be good to get a first review before messing with optimizations. Esp. the private access could need some love, not sure yet how to overcome touching so many internals. Extending the public API to expose all that stuff seems not appropriate to me. Ideas are more than welcome.

2021-03-22 14:22 UTC, jerch commented
Have stubbed a faster sixel decoder (~35% speed gain) for level2 sixel format with proper raster attributes preallocating the final image, which saves a second cache unfriendly copy step of the current decoder. With this I get indeed the total handler runtime down to 1000ms.

To get a better understanding of the ballpark we are in with the sixel decoder, some more numbers:

|               | SIXEL deactivated | single threaded | naive worker | worker v2 |
| ----------- | :------------------------ | :------------------- | :--------------- | :------------------ |
| `hook` to `unhook` | 750 ms  | 2200 ms | 1300 ms | 1000 ms |
| script on main | 250 ms | 1600 ms | 450 ms | 400 ms |
| script on worker | - | - | 1100 ms | 750 ms |
| `put` message excess | - | - | ~50 chunks (25%) | ~2 chunks (1%) |
| async `unhook` delay | - | - | 200 ms | <20 ms |

The baseline for total runtime is _SIXEL deactivated_, we cannot get below those numbers, as they mark runtime costs for getting the chunks into the browser (450 ms) and doing the UTF8 decoding and sequence parsing (230 ms), which adds up to 750 ms (+ some idle time).
Interestingly _web worker v2_ shows excess runtime costs of only 250 ms compared to baseline, which mainly adds up from `worker.postMessage` (100 ms) and `ctx.putImageData` (~150 ms, done in main thread on final image return). On code level the main differences of _v2_ are the faster sixel decoder and using pooled `Transferables`, compared to the default decoder and unpooled `Transferables` in _naive_. These are only tiny optimizations, but with a huge impact - while the _naive_ impl runs slower than chunks arrive stocking them up as messages (_`put` message excess_), _v2_ runs on par with baseline (750 ms) doing a perfect chunk recycling ping-pong. Since no excess messages have to be created anymore, the GC-major pressure drops from ~15% (eww) to <3%, and there is no `unhook` delay anymore. (The delay in _naive_ is mainly caused by the decoder catching up by digesting the excess chunks before it can return the final image.)

These numbers give some forecast about potential SAB usage for chunking:
- baseline still at 750 ms
- `ctx.putImageData` still at 150 ms
- `postMessage` overhead at 100 ms - that would prolly drop to < 30 ms with SAB
- additional manual mutex handling needed - would add ?? ms (wild guess from my pipe tests ~20ms)
- SAB creation for excess chunks needed (due to `PUT` not being async in the parser) - overhead unclear

Even without the last aspect we are down to 50 ms potential gain (0.5 %). Imho that is not worth to be considered at this stage. When doing the async parser support I left the `PUT` action out of async handling, which led to a much simpler implementation. Ofc we add that as well, but would only gain 50 ms here (prolly sacrificed again during parser stack unwinding). Without it in the parser we would have to implement some in-between buffer based on additional SABs here, again eating up the gains. Both seems inappropriate to me.

For the other way, sending the final image back to main thread, a SAB works much better - it is always a single response action, cannot get interleaved (main thread will not request a new image before processing the old one) and the SAB buffer can easily be specified prehand by some upper bounds. This might be a goal for later reworks, if pulling the drawing to the worker does not work well.

**TL;DR**
Yes we can get down to 1000 ms with a faster decoder implementation. Beyond that the air gets really thin. SABs are not worth the trouble for chunk transport from main to the worker.

2021-03-24 08:31 UTC, jerch commented
@Tyriar Lol what a TS nightmare, tried several things forth and back, even removed the worker temporarily as it was the last difference I had in mind compared to the webgl addon. Nothing worked.

Well - totally forgot about the test folder with its own tsconfig (`--traceResolution` is your friend). Added path lookups there - all working now :facepalm: && :joy:

Is there a quick way to get a more verbose error output from `tsc` I have missed? Seems in our "multi-project" setup it is sometimes hard to spot which `tsconfig.json` caused the error.

2021-03-28 19:42 UTC, jerch commented
Again more numbers, this time with `mpv` under IO pressure:

**Normal conditions**

`mpv` sends ~5 MB/s with my test movie. Thats pretty stable across different resolutions (no clue why, it prolly limits the frame rate based on CPU load or output rate, higher resolutions show a perceivable lower frame rate). With this IO rate xterm.js runs pretty smooth not entering any critical pressure area at any time:
- script load on main: ~25%
- script load on worker: ~ 35% (v1 decoder with worse runtime)
- mem usage stable over 15 min (beside lazy major GC cleanup cycling)

**Finding max. decoding speed**

To see the real throughput of the handler-worker mix I had to cheat abit and dumped the output of `mpv` into a file limited to 1 GB. Then I loaded that file with `fetch` and presented the raw bytes to the terminal with `term.write`.

Results:
- total runtime: ~65 s (~15 MB/s)
- "Scripting" load on main: ~35%
- "Scripting" load on worker: ~74%

No surprise so far, the worker heats up almost saturating the whole runtime with JS, while _main_ stays relatively "cold". Seems we are capable to do around 15 MB/s in SIXEL decoding, which is not bad (prolly can be boosted to 20 MB/s with decoder v2). But looking more closely at the timeline there popped up 2 unexpected runtime eater:
- "System" load on main: 40% (the greyish piece of the pie chart)
- Major GC on main: 15%

The root of the "Major GC" pressure was identified pretty quick, it is caused by the image data sent back from the worker and the follow-up canvas creation. None of those get recycled currently, which creates GC noise under fast image rotation. With a quick hack I was able to get rid of that (dropping below 3% again, not yet added to PR).

After reading some specs and chrome related posts it turns out, that the higher load of "System" is caused by `postMessage`, that will block for some time doing low level synchronizing stuff before JS gets the control back. Chrome seems to account those stuff under the greyish pie chart. This means that my assumption above, that `postMessage` will only create load under "Scripting" is wrong, and a SAB solution for chunking might show significant better runtime behavior here.

**Summary**

Sixel decoding runs at max. with 15 MB/s, saturating _main_ at ~70%, half from JS, half from `postMessage` system load. There are further optimizations possible with a rough estimate of 20 - 25 MB/s throughput.
Since the input-parser chain itself runs at 30-35 MB/s, it is unrealistic to get SIXEL decoding speed any higher than 25 MB/s without changes to the whole input-parser chain.

/cc @Tyriar, @mofux, @avih

2021-03-28 20:15 UTC, christianparpart commented
Hey @jerch  . You den to have put a great amount of good work in performance testing. Du you think it is possible to make that script in a way that it could be used against any Sixel based TE?

Thanks, Chris. :)

2021-03-28 20:24 UTC, jerch commented
@christianparpart Yes indeed. Well I could publish the data file to have the same test ground. Then it is just a matter of feeding it to any SIXEL capable emulator on the same machine to get comparable results. The file is rather big with 1 GB, thus not that good/easy to chew on.
If thats too big to get handled by others, I could also create a script to create it, but that would need `mpv` with sixel enabled on the target machine.
Last but not least we could also create a synthetic test script, that creates some random SIXEL output over time. This seems easier to adopt by others, but I have no such random SIXEL thingy lol.

Any other ideas?

2021-03-28 20:43 UTC, christianparpart commented
That could go into is own repo (to assist receive improvements from others
over time?) . I think both options are good. The randomized Sixel generator
shouldn't be too hard. But i think convert can generate plasma images with
Sixel output too.

On Sun, Mar 28, 2021, 22:24 jerch ***@***.***> wrote:

> @christianparpart <https://github.com/christianparpart> Yes indeed. Well
> I could publish the data file to have the same test ground. Then it is just
> a matter of feeding it to any SIXEL capable emulator on the same machine to
> get comparable results. The file is rather big with 1 GB, thus not that
> good/easy to chew on.
> If thats too big to get handled by others, I could also create a script to
> create it, but that would need mpv with sixel enabled on the target
> machine.
> Last but not least we could also create a synthetic test script, that
> creates some random SIXEL output over time. This seems easier to adopt by
> others, but I have no such random SIXEL thingy lol.
>
> Any other ideas?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xtermjs/xterm.js/pull/2503#issuecomment-808954005>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAN3O4EAD2MZXHVE4A5QJDTF6NB5ANCNFSM4JENMJAA>
> .
>

2021-03-28 20:56 UTC, jerch commented
> That could go into is own repo (to assist receive improvements from others over time?)

Yeah, good idea. Will see if I can get something up with a generative way, a repo containing a 1GB file seems just wrong.

The generative way is also not that easy - it should create at least one static pattern, to make sure ppl are testing against the same input. But here TEs could optimize for that specific pattern, thus a random thingy is also needed (but less comparable).

Furthermore SIXEL contains several aspects, that could be further performance tested (prolly to be added over time):
- compression handling
- color register overflow (and remapping)
- aspect ratios/ true DEC sixel support :see_no_evil:

2021-03-29 19:18 UTC, jerch commented
@christianparpart Here you go: https://github.com/jerch/sixel-bench. For now it contains only a sammler video dump and a test script. Feel free to add more stuff to be tested.

2021-03-29 20:27 UTC, christianparpart commented
> @christianparpart Here you go: https://github.com/jerch/sixel-bench. For now it contains only a smaller video dump and a test script. Feel free to add more stuff to be tested.
> 
> Edit:
> With this test I get slightly higher numbers across the board (xterm.js is at ~19 MB/s).

Oh very nice, you are really busy these days.

> To avoid false high throughput artefacts by aggressive prebuffering

Do you mean by this you want to avoid tearing effects? If so, that would be a nice trick but a even more nice Usecase for synchronized output (DECSET/DECRST 2026). :)

2021-03-29 20:41 UTC, jerch commented
> > To avoid false high throughput artefacts by aggressive prebuffering
> 
> Do you mean by this you want to avoid tearing effects? If so, that would be a nice trick but a even more nice Usecase for synchronized output (DECSET/DECRST 2026). :)

Ah nope, thats just to level out any big buffer on the way to the terminal, that would unblock the python code much earlier, while the terminal might still process the image data. With waiting for a report I am sure that the terminal went through all, as sequences are in-band synchronous.

xterm.js does not yet support the anti-tearing flag.

2021-03-30 14:02 UTC, Tyriar commented
> Is there a quick way to get a more verbose error output from tsc I have missed? Seems in our "multi-project" setup it is sometimes hard to spot which tsconfig.json caused the error.

In TS 4.2 there is a new `tsc --explainFiles` option which might be helpful here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#explain-files

2021-04-03 17:50 UTC, klamonte commented
Nice!  I just tried against my Swing backend: 2.83 MB/s.  Well, I'm not going to be winning speed contests anytime soon.  ;-)  Someday I'll get around to a proper image manager, for now I cut everything into brand-new cell-size pieces, so Jexer's terminal widget should probably be seen as a lower bound on performance for now.

@ismail-yilmaz , wanna give the sixel benchmark a go in Terminal-UPP?

2021-04-03 18:27 UTC, ismail-yilmaz commented
> Nice! I just tried against my Swing backend: 2.83 MB/s. Well, I'm not going to be winning speed contests anytime soon. ;-) Someday I'll get around to a proper image manager, for now I cut everything into brand-new cell-size pieces, so Jexer's terminal widget should probably be seen as a lower bound on performance for now.
> 
> @ismail-yilmaz , wanna give the sixel benchmark a go in Terminal-UPP?

@klamonte 

Ah, another benchmark.

On Linux:


TerminalCtrl (Linux 5.11, GTK, U++ release mode, with real usage *loop* for terminal (i e. not the one on stock terminal example, but similar):
`4.72s (25.13 MB/s)`

Xterm on the same config:
`26.67s (4.45 MB/s)`



Tomorrow I will have chance to benchmark it on Windows. Will report that too.

2021-04-05 17:18 UTC, jerch commented
@klamonte, @ismail-yilmaz Yeah the benchmark is known to be suboptimal for xterm, it uses private palettes and mpv flips the palette if it finds too many color changes. I still went with this as it is what most other impls support right out of the box (while shared palettes are hacky).

@ismail-yilmaz With ~25 MB/s you prolly have the fastest implementation currently, care to test with `mlterm` on your machine (was the fastest on my machine with ~36 MB/s)?

2021-04-05 17:36 UTC, ismail-yilmaz commented
> @klamonte, @ismail-yilmaz Yeah the benchmark is known to be suboptimal for xterm, it uses private palettes and mpv flips the palette if it finds too many color changes. I still went with this as it is what most other impls support right out of the box (while shared palettes are hacky).
> 
> @ismail-yilmaz With ~25 MB/s you prolly have the fastest implementation currently, care to test with `mlterm` on your machine (was the fastest on my machine with ~36 MB/s)?

@jerch , @klamonte , Yeah, but unfortunately, the result I'd shared turned out to be somewhat misleading due to a silly mistake on my side: I carelessly `cat`ed the sixel to see what it was, before I run the actual benchmark, so the image cache was "hot". (It is normalized around average `~19MB/s` after a cold restart (I get similar results on windows, btw). The implementation I use is experimental (not published or pushed to master yet, as it is somewhat unstable at this point, but it uses `instrinsics`  when available to parallellize drawing. I'll have the time to test the mlterm tomorrow on the same machine. Will report it asap.

2021-04-05 18:03 UTC, ismail-yilmaz commented
@jerch ,

I couldn't wait for tomorrow, so here's the result for mlterm (on the same machine, with similar config (same font, size etc.)):  
mlterm `5.16s (22.97 MB/s)` (Some video frames have wrong offsets/misplaced though.)

2021-04-05 18:11 UTC, jerch commented
@ismail-yilmaz Ah ok, so you are in the same ballpark as @christianparpart with `contour` (also written in C++). The results I get with the xterm.js addon is also at that region, but I had to cheat quite heavily to get there with the decoder running in a web worker (separate thread). Without a dedicated thread I cannot get it higher than 11-13 MB/s with heavy lag spikes on the main thread. JS is simply not a good choice for high IO + CPU load at the same time, and the single thread adherence of most interfaces kill the fun for higher computation needs.

> I couldn't wait for tomorrow, so here's the result for mlterm (on the same machine, with similar config (same font, size etc.)):
mlterm 5.16s (22.97 MB/s) (Some video frames have wrong offsets/misplaced though.)

Yes I figured that as well for mlterm, it also shows weird artefacts for any `backgroundSelect` trickery. Did not look up the code, prolly it implements not all aspects around the palette / background handling.

@klamonte Well since you have to re-encode things on cell tile level, 2-3 MB/s is surprisingly fast still. Note that mpv streams with ~5MB/s, thus to get smooth playback a value around 6 MB/s would be needed for smooth playback (and enough free CPU cores to handle the re-quantization).

2021-04-12 20:38 UTC, ismail-yilmaz commented
@jerch 

FYI, I have managed to get a steady 26 MB/s  on the same machine with a very simple optimization on our sixel decoder and some optimizations on the ANSI/DEC lexical parser side. (These optimizations will land with `2021.1` tag (in ~May)) The resulting numbers from these optimizations are:

`VTInStream:	 1.10s (110.00 MB/s)`-> fed with `sixel.data`. (DCS parsing, w/o image rendering.) 
`SixelRenderer: 4.60s (26.00 MB/s)` -> `sixel.data` passed through VTInStream (our parser) + the video is accurately rendered. 

This setup *does not use* any complex algorithm, MT or intrincs, etc., by the way. It is simply CPU rendered. / single threaded, on a relatively old test machine (AMD fx-6100, 8MB RAM). But the results are consistent with, and even higher on, more the modern hardware. (e.g, on DELL xps 13, I get ~29 MB/s)

However, this does not translate `1:1` on our vte, ATM.  But I am almost sure that it is possible to achieve that number with "another level of indirection", on in this case, getting rid of "another level of indirection".





> @ismail-yilmaz Ah ok, so you are in the same ballpark as @christianparpart with `contour` (also written in C++). The results I get with the xterm.js addon is also at that region, but I had to cheat quite heavily to get there with the decoder running in a web worker (separate thread). Without a dedicated thread I cannot get it higher than 11-13 MB/s with heavy lag spikes on the main thread. JS is simply not a good choice for high IO + CPU load at the same time, and the single thread adherence of most interfaces kill the fun for higher computation needs.
> 
> > I couldn't wait for tomorrow, so here's the result for mlterm (on the same machine, with similar config (same font, size etc.)):
> > mlterm 5.16s (22.97 MB/s) (Some video frames have wrong offsets/misplaced though.)
> 
> Yes I figured that as well for mlterm, it also shows weird artefacts for any `backgroundSelect` trickery. Did not look up the code, prolly it implements not all aspects around the palette / background handling.
> 
> @klamonte Well since you have to re-encode things on cell tile level, 2-3 MB/s is surprisingly fast still. Note that mpv streams with ~5MB/s, thus a value around 6 MB/s would be needed for smooth playback (and enough free CPU cores to handle the re-quantization).

2021-04-12 22:52 UTC, ismail-yilmaz commented
@jerch ,

It's getting late but I was curious and did a quick synthetic benchmark with U++worker threads (similar to future/promise pattern) on the same machine, with `data.sixel`: result: `1.70s (71.23MB/s). :)

All images are rendered correctly and in order (used a FIFO queue to hold the).
So it is definitely possible to get nice results.

2021-04-13 00:53 UTC, jerch commented
@ismail-yilmaz Yeah same observations here - tiny changes on the decoder gave a huge speed boost. I saw most gains from cleaning up the sixel-->pixel "spreading", which is a cumbersome memory intensive action with bad cache locality. By changing the pixel write order I was able to resort to contiguous memory writes for repeated sixels, plus some bit lookups removed most branching at that level. But thats almost all I can do with JS, in C/C++ one could also switch to SSE registers to even lower the mem load/write pressure directly.
My guess for C/C++ alikes is a single threaded sixel decoder speed of 15-50 MB/s for the test data without too much optimization. With SSE this is likely to further increase 2 - 4 times.

Originally I didnt want to deal with threading, as this is a mess in JS on its own. But the decoder just takes too much of the mainthread runtime with bad lag spikes and lousy throughput of 11-13 MB/s. Note that I only have one decoder thread all sixel pics have to go through. Ofc more threads would squeeze more throughput out of the system, but I do not optimize for video sixel streaming in the first place (imho thats a rather odd use case). And a single sixel decoding is serialized dependent data, which hardly can be processed in parallel. (Well, thats not quite correct, one could still write a preparser searching for sixel line delimiters and feed the line chunks to different threads under certain circumstances like predefined palette colors.)

On a sidenote - on sequence parser level the best optimization I found for JS was the switch from single byte/codepoint handling to chunkwise (inplace without copy). This greatly lowers the function call pressure, as many states stay active for some time and handles most bytes in simple loops. This also works in C, but not to the same degree (guess compilers do their job). For C I found another optimization showing big impact - computed gotos (playground parser runs at 350 MB/s for mixed `ls -lR /usr` data). Those numbers are just insane for JS, sadly.

2021-04-13 08:08 UTC, ismail-yilmaz commented
@jerch 
>  By changing the pixel write order I was able to resort to contiguous memory writes for repeated sixels, plus some bit lookups removed most branching at that level. But thats almost all I can do with JS, in C/C++ one could also switch to SSE registers to even lower the mem load/write pressure directly.
> My guess for C/C++ alikes is a single threaded sixel decoder speed of 15-50 MB/s for the test data without too much optimization. With SSE this is likely to further increase 2 - 4 times.


Yeah this seems to be the case. Changing the drawing order -and going back to simple pointer arithmetic- has boosted the performance of our sixel decoder:

Nobody asked, but let me share the code that made the biggest difference.

 The original sixel drawing code: (where ib: ImageBuffer (ARGB/RGBA  canvas),  ink: Color component, a `uint32`)

```C++
	while(repeatcount-- > 0) {
			Point pt = cursor;
			for(int n = 0; pt.y < cursor.y + 6; pt.y++, n++) {
				if(pt.x < size.cx && pt.y < size.cy)
					if(c & (1 << n))
						 ib[pt.y][pt.x] = ink;
			}
			cursor.x++;
		}

```

This was inefficient for three reasons: 

1.  Drawing order:  Moving up and down like this on an x-axis was never a good idea. All should have been done in one pass for each pixel line, for efficient CPU cache usage.
2. Color component  has an operator so that it is implicitly converted to an aligned 4 bytes structure (RGBA). This also hit the performance hard. Intuitively one might think that both uint32 and RGBA structure can be easily converted without a performance hit, since their size is equal, but this is not the case.

3) Using the index operator of a C++ canvas component (ImageBuffer) has some costs.

So instead I moved to the below approach where I draw (ink is now a RGBA structure, i.e. no conversion is done):

```C++
	for(int n = 0, r = repeat; n < 6; ++n, r = repeat) {
		if(c & (1 << n)) {
			RGBA *rgba = ib[cursor.y + n] + cursor.x; // this seems to be a bit faster than ib[y][x++] = ink ...
			while(r--)
				*rgba++ = ink;
		}
	}

```

This works perfectly well, for "obvious" reasons.

> Originally I didnt want to deal with threading, as this is a mess in JS on its own. But the decoder just takes too much of the mainthread runtime with bad lag spikes and lousy throughput of 11-13 MB/s. Note that I only have one decoder thread all sixel pics have to go through. Ofc more threads would squeeze more throughput out of the system, but I do not optimize for video sixel streaming in the first place (imho thats a rather odd use case). And a single sixel is serialized dependent data, which hardly can be processed in parallel. (Well, thats not quite correct, one could still write a preparser searching for sixel line delimiters and feed the line chunks to different threads under certain circumstances like predefined palette colors.)

Well, `MT` with sixels is a different issue, IMO.  Using worker threads to render individual images isn't really problematic. I just did it last night and it gives a nice performance boost. But it was a simple test. The real challenge is rendering a single sixel stream in parallel. I have tried this. And I regret it. All the book-keeping needed for color register management and overwriting sixels simply made it nonviable for me.   I gave up on this front,  until some brave soul comes up with a reasonably managble code for such a task. :)


> On a sidenote - on sequence parser level the best optimization I found for JS was the switch from single byte/codepoint handling to chunkwise (inplace without copy). This greatly lowers the function call pressure, as many states stay active for some time and handle most bytes in simple loops. This also works in C, but not to the same degree (guess compilers do their job). For C I found another optimization showing big impact - computed gotos (playground parser runs at 350 MB/s for mixed ls -lR /usr data). Those numbers are just insane for JS, sadly.

This is exactly what I've done to improve the parser (which enhanced it's performance from ~80 MB/s to ~140 MB/s). We are using the plain old state-table approach where each byte gets processed by the state table and dispatched accordingly. However, this is inefficient for one big reason: vt sequences can contain long byte-chains without going out of a given state: And they can be read as chunks. So I allowed our parser to read chunks of data in vt states where the input is *potentially* and predictably longer, such as in parameter collection, passthrough OSC/APC string collection, and ground state (for ASCII/unicode characters).

2021-04-13 10:00 UTC, jerch commented
@ismail-yilmaz Seems we basically did the same optimizations at the sixel decoding. Minus the pointer thingy, in JS all you get with array buffer views are indexed memory cells with 8/16/32 bit word size with their corresponding byte alignment.
Given how small the flipped pixel writing on code level is, it is quite fascinating how much of a difference it creates just by better cache utilization. Well it is the old _working with_ or _working against_ the machine, for high perf things some low level knowledge always comes handy.

> The real challenge is rendering a single sixel stream in parallel. I have tried this. And I regret it. All the book-keeping needed for color register management and overwriting sixels (all the "return"s) simply made it nonviable for me. I gave up on this front, until some brave soul comes up with a reasonably managble code for such a task. :)

Thats what I meant above - sixel is simply not specced for concurrent processing, no global header, no stable color definition (can lit. be changed at any data position), no easy chewable chunk structure, cache unfriendly and what else. It is a nightmare for serious parallelization. Is it worth to work around these limitations and still try some concurrency? I dont think so, mostly because I think sixel is not worth it, compared to modern formats with great color features, better compression and so on. It should have been kept, where is was for 2 decades - in computer history tales. :smile_cat:

2021-04-13 11:20 UTC, ismail-yilmaz commented
> Is it worth to work around these limitations and still try some concurrency? I dont think so, mostly because I think sixel is not worth it, compared to modern formats with great color features, better compression and so on. It should have been kept, where it was for 2 decades - in computer history tales.

I totally agree.  IMO, it would be better if we could just move on to a modern inline-images protocol and keep the sixel  protocol only for legacy software support (and interestingly enough, apps with sixel support are even rare among legacy terminal apps). 

terminal-wg sometimes lead me to despair on this issue, but not everything is gloomy.

IMO a good step in for moving forward was/is @klamonte's [ jexer protocol](https://gitlab.com/klamonte/jexer/-/wikis/jexer-images).

And over a year of usage I strongly believe she did a great job there and here is the [summary](https://gitlab.com/klamonte/jexer/-/commit/83787cfb2eb1501a328f8c5f2416c2532e3fef1c#note_239282572) of why I think it is a step in right direction. 
 
The key point *for me*, as I've stressed in the summary, is that the wire protocol -in this case, jexer- *should not* use unordered `key=value` pairs (as iterm2, or AFAIK, kitty does). Instead, it *should* use strictly ordered plain o'l sequential structure which can be predictable so that the parser can be easily optimized.

2021-04-20 18:21 UTC, jerch commented
@ismail-yilmaz Yeah, sixel is not yet wide-spread (again), but is getting more and more momentum. Soon we can congratulate ourselves for re-establishing this old crap, lol.

About a new image protocol - I hear you, the idea is not yet dead, there are still ideas flaoting around (@christianparpart has a sketch-up repo, I have some early [sequence draft](https://github.com/xtermjs/xterm.js/blob/07a2d249ac237da402b831124a3a47804ed36544/addons/xterm-addon-image/src/ImageHandler.ts) here in the PR). My plan is to go public with SIXEL support first, and add the new protocol on top of the internal storage abstraction, once we have that (only needs a new sequence handler as the internal image basics can be shared).

I am well aware of jexers image protocol, imho @klamonte created it around the time, we had that nasty protocol discussion in terminal-wg. I think it is still missing some crucial aspects (like banning pixel size notions, instead clamp size notion to cell coverage, or the upload-reference thingy for more advanced apps not to re-upload stuff over and over).
And since you mentioned the parameter format - yes, I'd prefer a fixed parameter set as well, either as numercial DCS params or as some custom header format at the beginning of OSC payload. Technically I'd prefer a new DCS sequence for it, but realistically an OSC function is more suitable to not break with 50% of the TEs out there.

2021-04-21 14:11 UTC, klamonte commented
I am definitely not married to the Jexer protocol.  As soon as any 24-bit protocol (not iTerm2 or Kitty) gains real traction, or something is picked up by xterm, we should all switch to that.

2021-04-21 22:38 UTC, ismail-yilmaz commented
@jerch 

> About a new image protocol - I hear you, the idea is not yet dead, there are still some stubs floating around (@christianparpart has a sketch-up repo, I have some early [sequence draft](https://github.com/xtermjs/xterm.js/blob/07a2d249ac237da402b831124a3a47804ed36544/addons/xterm-addon-image/src/ImageHandler.ts) here in the PR). My plan is to go public with SIXEL support first, and add the new protocol on top of the internal storage abstraction, once we have a working protocol (only needs a new sequence handler as the internal image basics can be shared).


I have just peeked into both your and @christianparpart's drafts, and I have to say that I find these attempts valuable. They seem to cover a range of potential issues, as any good draft would do. (I would like to share my opinions on them later, after I read them thoroughly - as a humble vte devoloper, of course.)   But allow me to share my  general observation on all these attempts in general:  

IMO, we, vte developers, should first come up with an *absolute minimum requirements* set (as per K.I.S.S.) for a realizable new image display protocol. 

- It must require the existing tools and concepts (cell, cursor movement to draw image at certain location, traditional sequence parsing and composing rules, etc..) as its minimum and default.

- Accordingly, not everything should be done on the vte-side. We should not treat vtes as if they are web browser engines. CLI applications already use the tools and concepts all vtes provide. Some operations, such as calculating a canvas size from the given font size and converting it back to vte's page size (rows/cols) can be easily -and IMO, better- done on the client-side.

- It should be extensible and allow granularity only as an option that can be safely compensated by the *required minimum information* (fallback).

> blending mode param to deal with partial image updates and composition with old one

This sounds somewhat scary. I feel that it has the potential to make image cache handling much more complex. But then again, I haven't yet thought it through :)

As for the other stuff: 

About the image IDs: We took the approach of using the 32 bit hash (folded 64bit hash, actually) of the incoming payload string (the operation is quite cheap.)  This also made the image cache  handling a lot easier. I understand that assigning reusable numbers may have its other uses though.

About the FIFO cache: I remember reading the argument against LRU caches on terminal-wg, but from our experience, I have to say that LRU works really well, possibly better, if properly implemented.

2021-04-22 12:24 UTC, jerch commented
> IMO, we, vte developers, should first come up with an absolute minimum requirements set (as per K.I.S.S.) for a realizable new image display protocol.

Yes thats true, we def. should identify minimal requirements first (much in the sense @klamonte did). My list above is more like a wishlist, thats not yet condensed but still/again in brainstorming phase. I dont want to discuss the detail here, this is better done when getting down to it. At least lemme explain, why I think a blending mode is useful:

Imho we all agree, that the application is in control and it should stay that way for now. Furthermore we have only one data stream as source of truth (the PTY connection), side-channelling is a bad idea mainly for security concerns (might also change over time, buts lets deal with that for now).
Now on the other hand we have applications like gnuplot, that are used to draw things with some idea of interactivity (like you can rotate or zoom plots). In terms of pixel graphics thats equivalent to a series of images, where the new image replaces the older one.
Now on TE side - currently we have sixels, that have a concept of transparent BG pixels with the contraint, that old pixels stay untouched. Here we already have a blending mode, where those pixels are "carried forward", while everything else gets overwritten. Means - we already have to implement image compostion.
Imho a new protocol should not fall behind in terms of capabilties, thus should at least also support that blending mode. Since newer image formats support more transparency settings, the blending caps should not be limited to some awkward old sixel mode, instead I think we should take some time to spec out some useful modes to deal with the enhanced transparency settings.

For the apps mentioned above this gives a huge advantage - they now dont have to re-send the full image, but can send diff-images. And apps that dont care can still re-send the full image.

But I think thats better to be discussed in a separate context.

2021-04-22 15:15 UTC, jerch commented
@ismail-yilmaz I suggest to carry the new protocol's discussion over to @christianparpart's repo here: https://github.com/christianparpart/terminal-good-image-protocol. If thats ok for you @christianparpart :smile_cat:

2021-04-22 15:25 UTC, christianparpart commented
That is fine and awesome. X sorry for just passively reading until now. I
am with my family. I will react on the other side of the fence then. Many
thanks for three interest and see you soon. :)

On Thu, Apr 22, 2021, 17:15 jerch ***@***.***> wrote:

> @ismail-yilmaz <https://github.com/ismail-yilmaz> I suggest to carry the
> new protocol's discussion over to @christianparpart
> <https://github.com/christianparpart>'s repo here:
> https://github.com/christianparpart/terminal-good-image-protocol. If
> thats ok for you @christianparpart <https://github.com/christianparpart>
> 😸
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/xtermjs/xterm.js/pull/2503#issuecomment-824931369>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAN3O5QB4SF4RDTE4LHUOLTKA4RHANCNFSM4JENMJAA>
> .
>

2021-05-20 16:14 UTC, jerch commented
@Tyriar Any chance to review this soon to get an alpha release done?

FYI there are a few open issues, that I dont want to address in a first release:
- no blending/composition yet, new image will delete old pixels
- resize does not expand images to the right yet (needs onResize hook)
- not tested on safari due to no dev access
- minor output glitches on DOM renderer when changing font size (cell alignment partially broken)

2021-05-20 16:32 UTC, PerBothner commented
_"not tested on safari due to no dev access"_

If you have a Linux machine with Gnome, you can test with the `epiphany` browser (renamed to "gnome web`).  It uses AppleWebKit, so it's close.

2021-05-22 05:24 UTC, anthonypwest commented
@jerch
I just tried the addon-images branch on Safari (macOS 11.3.1 on M1 Mac mini, Safari 14.1) using the xterm.js demo, and I did notice a problem. When the sixel image width is larger than the terminal window, the image displays correctly (truncated on the right, of course). When the image width is smaller than the terminal width, no image appears - there's just blank (black) space where the image should be. If I then manually, gradually reduce the terminal width, then the already printed, but not-displayed image suddenly appears in the previously blank space when the terminal width about equals the image width. The same images display correctly with Firefox regardless of the terminal width.

I use Safari frequently, so I would be glad to test a future version of addon-images.

2021-05-23 19:13 UTC, anthonypwest commented
@jerch
Regarding the Safari issue I mentioned, this is due to a bug in Safari's CanvasRenderingContext2D.drawImage() when called with parameters outside the image bounds - as noted at [stackoverflow](https://stackoverflow.com/questions/35500999/cropping-with-drawimage-not-working-in-safari)  
  
The following changes around line 163 of ImageRenderer.ts in the draw() method seem to resolve the issue:  
<pre>
    ...
    const cols = Math.ceil(img.width / width);
    <b>const boundedWidthXCount = Math.min(width * count, img.width);</b>
    this._ctx.drawImage(  
      img,  
      (tileId % cols) * width,  
      Math.floor(tileId / cols) * height,  
      <b>boundedWidthXCount</b>,  
      height,  
      col * width,  
      row * height,  
      <b>boundedWidthXCount</b>,  
      height  
    );  
</pre>

2021-05-23 19:35 UTC, jerch commented
@anthonypwest Thx for the detailed investigating. So basically this is some sort of pixel offset rounding issue? I was under the impression, that trying to draw outside of the source is basically a NOOP (so safari cannot do that?). Ofc those should be avoided in general for weak performance (JS engine tend to deopt any out of bound access).

2021-05-23 23:42 UTC, anthonypwest commented
@jerch I didn't go upstream to understand what the range of the count argument of draw() should have been - I guess if count*width was meant to be less than or equal to the image width, then maybe there was a pixel offset rounding issue when calculating the count argument (or the width variable?). About Safari, the comments on stackoverflow indicate that the draw bounds problem occurs for some image sources but not others.

I do see a slight banding artefact when displaying palette.six, but this seems like a minor problem. When I check palette.six on iTerm 2, it only prints half the image - so the banding in comparison is a small issue. On the images that I would like to use xterm.js for the quality is good. I've compared the sixel capabilities of iTerm 2 and Miguel de Icaza's SwiftTerm. SwiftTerm produces really excellent images, but rather slowly. iTerm 2 produces somewhat fuzzy images, but it's much faster. Your addon-images seems even faster and looks good (I haven't been able to do a side-by-side comparison due to image size differences).  When I print the big.sixel image on iTerm 2 and SwiftTerm, the image is scaled down to fit the terminal. This doesn't seem to happen with the addon. Is it intended to scale large images to fit?

2021-05-24 10:32 UTC, jerch commented
@anthonypwest Your fix points to the right direction, works for me with `epiphany` and `GtkMiniBrowser`. :+1: 

What happens here is not just a simple rounding offset, it is caused by the tile logic sent to `draw` - during image receiving I spread the image to text cells as single tiles and save the tile information in the terminal buffer with Math.ceil, which creates an "at least this many cells" extend for width/height in number of tiles rounding up to full cells pixels.
On render I retrieve the tile ids and stitch together a line of tiles to a single draw for perf reasons, which carries forward the up-rounding. But instead I should correct the width for the rightmost cell to `img.width % cellwidth`, same for the height at the lowest line.

Before this up-rounding to full cells was not an issue, as I created a cell-normalized canvas, but removed it later again to due issues with overlapping images and background color issues at those underfull cells. Need to re-think the whole tiling/drawing process, esp. for those floating pixel cell borders as seen in the DOM renderer.

_about fitting to the terminal_
I dont plan to implement that for the SIXEL protocol, there is no fitting notion in the specs. The yet to come image protocol will have something similar - most likely it will be based on cell metrics directly for origin and extend, thus you can tell the emulator, that a rather big image shall only cover this many cells in height/width.

2021-05-24 11:17 UTC, jerch commented
Oh well, my fav browser Firefox is slowest with https://github.com/jerch/sixel-bench:
- Firefox ~11 MB/s
- Epiphany (Webkit) ~16 MB/s
- Chrome ~19 MB/s

Lol, thats almost half the speed of Chrome. Is Firefox known to be slower for data transfers from/to workers?

2021-05-24 12:27 UTC, jerch commented
@anthonypwest Can you test if the last commit works for you in safari? It should work now for underfull cells in both directions (width and height).

about the banding:
In theory there should not be any banding at all, since I do a perfect pixel aligned clipping. The banding you might have spotted with palette.six is prolly due the default palette only holding 256 colors (default in the spec). You can change that by setting `sixelPaletteLimit` to 512 in the ctor options and relaunching the addon. Then you should see the image in its full glory (https://raw.githubusercontent.com/jerch/node-sixel/master/palette.png). Idk why iTerm only shows half of the image, it prolly skips color registers it cannot assign (although the spec clearly states, that out of bound colors should map back into existing registers).

2021-05-24 14:27 UTC, jerch commented
@anthonypwest The last commit adds a banding test, which you can run from the repo source path as:
```bash
node addons/xterm-addon-image/fixture/growing_rect.js
```
This should create a continuous green rect for all renderers without any banding. Note that the output will flicker here and there (xterm.js currently does not support the force sync output sequence as mentioned above).

2021-05-25 05:17 UTC, anthonypwest commented
@jerch The last commit looks good in Safari, and you were correct about increasing the `sixelPaletteLimit` - palette.six looks perfect when that's done. The banding test also looked good.

I understand fitting oversized images to the terminal not being part of the SIXEL spec, but it might be nice to offer an option to enable that; besides being the behavior seen in some other SIXEL implementations, I think many users would prefer that. BTW, my use case is a REPL that occasionally prints SIXEL images made with gnuplot. The image protocol looks powerful, but the timing of that seems unclear.

2021-05-25 05:30 UTC, PerBothner commented
_"my use case is a REPL that occasionally prints SIXEL images made with gnuplot."_

In that case, you might consider [Gnuplot display on DomTerm](https://per.bothner.com/blog/2016/gnuplot-in-domterm/) which uses SVG.

2021-05-25 06:20 UTC, jerch commented
@anthonypwest I second @PerBothner, for plots vector graphics are more suitable in general. But I am also aware, that vectors are not a thing yet again on terminals, and SIXEL is the closest we have to get some graphics dumps working across emulators. There are some efforts to revive ReGIS (again old crap, kinda the vector brother of SIXEL), but in the long run I think we gonna need something like a down-stripped SVG spec for terminals.

Can you describe, how fitting oversized images should work? Should it fit width to the remaining space? What about height? What about aspect ratio? What shall happen, if the user resizes the emulator viewport? I am currently not aware of any SIXEL implementation doing those things, can you point me to some emulators doing it?

2021-05-25 17:07 UTC, klamonte commented
@jerch

> @anthonypwest The last commit adds a settings to fit oversized images to viewport width (with stable aspect ratio). This needs abit more thinking and detail works, currently it is only a ctor setting. I think this should be a runtime setting, and even be a sequence scriptable from appside. It also might cause havoc for multiplexers, thus I am abit reluctant to add something like that.

Are you thinking of another state flag (CSI [ ? {somehing} h) to affect rendering, like is done for xterm private color registers and sixel cursor position?

> A general purpose simplification might be a "REPL plot mode", that if activated, always assumes images to take full viewport width (either up or down scaled). If properly done, we might be able to get it working with multiplexers as well.

Small bits of scaling such as when the user selects a different font aspect ratio didn't seem to harm the output, so long as anti-aliasing is enabled, as we saw back on the "simple images" discussion.

If this could turn into a sequence like:

1. The next bitmap image shall be scaled to fully fit within X cols and Y rows (stretch on both axes)
2. Cursor position
3. Sixel image data

...then one would only need to add a sequence to say "the next image shall be clipped to the region (x0, y0, width, height)" and the terminal multiplexer case would be solved without having to decode / encode image data. tmux et al would only have to parse and rewrite the the clip region sequence, but otherwise pass the scaling and sixel image sequences directly to the host terminal:

1. Bitmap images shall be scaled to fully fit within X cols and Y rows (stretch on both axes)
2. Bitmap images shall be clipped to (x0, y0, width, height) cells <-- this is the only thing tmux et al have to change
3. Cursor position
4. Sixel image data

A bit uglier than a single sequence, but not much different than scrolling regions.  Replace step 4 with a 24/32-bit image format, and we have most of the "good" image protocol done.

2021-05-25 17:51 UTC, anthonypwest commented
@jerch Your last commit did exactly what I was imagining - thanks for writing this and trying this out so quickly! Two emulators that (by default) rescale large images are iTerm 2 and SwiftTerm. I just tried X windows xterm compiled with sixel support, and it printed palette.six fine, but gave no output for big.sixel, so I can't say what its behavior is.
When run in Safari, the image produced for big.sixel by your addon seems identical to that produced by iTerm 2 - and your addon is about twice as fast. When run in Firefox, the image seems slightly sharper, but a bit more pixelated (good either way).

I'm completely new to javascript/node/web development, so my thoughts about these things may be naive. Thinking about what a novice user would expect, I don't think small images should be scaled to the full terminal. But most of the time I think a rescaled large image is more expected/desired than a truncated image. I barely know the difference between a ctor setting and a runtime setting - I guess the ctor determines the setting for the whole session? Either seems fine to me.

For my own use case, I don't actually need the rescaling - I can control the gnuplot plot size. Rescaling is a plus in the sense that I write code for iTerm 2 and xterm.js without being concerned about the scale. My suggestion is more based on the general case rather than my use. The performance of your addon is great - so SVG may not be necessary in many cases.

2021-05-25 17:55 UTC, anthonypwest commented
@PerBothner Thanks for the heads up on DomTerm. That does seem like a viable alternative - well designed for situations similar to mine. I'll have to read more of the documentation and think about whether to build a version using that.

2021-05-26 08:15 UTC, jerch commented
@klamonte Well it is just a brainstorming idea currently, but yes I basically thought of another DECSET mode here. We all now that we have a hard time to figure out, how to do correct image sizing and aligning relative to the text content. Furthermore we know, that most active SIXEL implementations do the rasterization slightly wrong with their direct 1:1 pixel mapping (see discussion in VTE gitlab). While the proposed solution over there would solve the stable text cell coverage issue for SIXELs, I dont like its rigid underlying metrics being hardcoded into the sequence, as it does not fit well to nowadays emulator caps with freely adjustable cols * rows metrics and even floating pixel sizes (font size changes).

The idea of a "REPL plot mode" (better name is more than welcome) would introduce a size constraint relative to the viewport size. In theory this is not needed with correct SIXEL rasterization or an alternative metric based on cell extends (which I would favor for a new image protocol), as appside can always derive the full viewport size from `ioctl(TIOCGWINSZ)` and adjust the image accordingly. Still thats inconvenient for appside, if it just pushs images forward. A designated plotting mode on TE side would make that alot easier.

About possible details of such a mode:
- Most simple way could be provided under these assumptions - appside is a REPL in scrolling buffer, thus never gonna try to write over previous lines (non "canvas mode"). Here it is easy to allow scaling in terms of viewport width with stable aspect ratio, we can simply use the scrollling feature of the buffer to deal with overflowing height. Also a multiplexer can deal with that under the assumption, that a text cell extend is typically 1:2 (e.g. a rectangle of x pixels scaled to full viewport width in a 80x25 terminal would take 40 cols in height). It can even decide, whether to just pass along that mode plus the image data and let the target TE deal with the details (preferred), or can go into single cell handling and send image slices for single line updates (tricky due to possible rounding issues and banding artefacts).
- Things get more troublesome for apps in text canvas mode on alternate buffer. Here a stable aspect ratio will always cut overflows, if the shorter dimension should be aligned (furthermore sixelScrolling `on` would cut off at the top, `off` at the bottom). And there is no way for the user to access the cutoff anymore. Now it is arguable, what the goal of an easy plot mode should be -  do we want to give  appside an easy way to just dump images at its full glory - then we would have to adjust always to the overflowing dimension so the user can see the full image in the viewport. Or do we want to emphasize the alignment dimension in the first place - thus a 100% viewport width always wins cutting off in height? Hmm idk...
- Active dumping region - Imho viewport sizing is not quite correct, it prolly should be the active scrolling region (which can be limited by DECSTBM and DECSLRM). This gives multiplexers the chance to dump images into a split region without any own cumbersome image processing. But this a nasty requirement, many TEs dont support that (DECSLRM is still on my TODO list for xterm.js).

Now back to your idea - I actually like that a lot, it would bridge the issues with a way too simple "plotting mode" which I had in mind first. It also would help to overcome the current issues with partially broken SIXEL rasterization, yeah. Just one thing about a "leading size sequence" - imho it has to be right in front of a SIXEL sequence, and any other content in between should reset it. Otherwise there is a chance that a dangling size sequence will affect a much later SIXEL sequence (due to broken connection whatsoever). Lets discuss that further, and how we can get an easy viewport related sizing from it (still trying to make appside more convenient) :smile_cat:

2021-05-28 18:30 UTC, anthonypwest commented
@jerch I've been testing this addon a bit more, and I noticed an oddity (not on the image itself) that occurs after an image has been displayed: text that has been underlined using an ANSI escape code displays as a gray blocks. Once an image has displayed, underlined text before and after the image appears as gray blocks. This occurs on Safari and Firefox. On Firefox (but not Safari), if I change the zoom level, sometimes the gray blocks are offset from the underlined text as shown in the attached image. I don't know whether this relates to the "no blending/composition yet" open issue you mentioned.

![underline_image](https://user-images.githubusercontent.com/56272592/120025426-8235b900-bfa5-11eb-87b4-ceac7e73c645.png)
![underline_image2](https://user-images.githubusercontent.com/56272592/120025442-882b9a00-bfa5-11eb-91dc-98fb61d41ba8.png)

2021-05-29 08:56 UTC, jerch commented
@anthonypwest Cannot repro it, can you share the steps, what you did to get this?

The greyish pixelated blocks is the image placeholder, that the addon outputs in case there is an image linked to a text cell, that got evicted by the FIFO cache. By default the image storage is only allowed to hold 100MB of image data (see `storageLimit` in ctor options).

2021-05-29 09:20 UTC, jerch commented
@anthonypwest Should be fixed with the last commit.

2021-05-29 11:53 UTC, jerch commented
The last commit should fix the cell alignment issues of the DOM renderer by using float pixel calculations (only floored in the final drawing step). Cell coverage is now stable there as well for font size changes.

2021-05-29 14:54 UTC, jerch commented
Added a right expansion for `onResize` events:

![recorded](https://user-images.githubusercontent.com/6193135/120074429-2cdcd300-c09d-11eb-9dec-854a02b68824.gif)

Before the expansion the image would have stayed truncated at the right border after shrinking and re-enlarging the viewport. The fix re-adds lost tiles to the terminal buffer. It works well for simply image dumps, but has its issues for lines, that have text content on the line after image data, that might get wrapped during resize. Therefore images on lines with text content to the right side will not get expanded. Somewhat a heuristical approach, not sure if there are better ways to handle those edge cases.

(Ignore the bad image quality of the shown gif, it is a result of the recorder doing lousy color palette approximation.)

2021-05-29 22:21 UTC, anthonypwest commented
@jerch Your recent commit did fix the issue with the underlined text - thanks for the quick response. For my project your addon is working great!

2021-05-30 09:10 UTC, jerch commented
@anthonypwest Glad that it works for you. Also thanks for testing it this early, helps a lot to get things working.

Note that the fit width feature prolly not gonna stay as it is now, will try to get something rolling based on @klamonte's suggestion instead.

2021-05-30 17:51 UTC, jerch commented
@klamonte

Did some basic shaping of your idea. It mainly follows my early draft [here](https://github.com/xtermjs/xterm.js/blob/8a8fcbd5bdc027fa7d5b7f326820a7e84437134b/addons/xterm-addon-image/src/ImageHandler.ts) and extends it with your SIXEL embedding idea.

**General Upload and Draw**
Basic sequence to do the image upload (either for creating a reference only, draw&forget or reference&draw)
```
OSC 5000 ; width ; height ; mode? ; dx? ; dy? ; id? ; format=PNG|JPEG ; bytelength ; payload ST
```
Parameters:
- _width_ Mandatory, number of cols the image width should be rescaled to.
- _height_ Mandatory, number of cols the image height should be rescaled to.
- _mode_ Optional rescaling mode (see link above for more details).
- _dx_ Optional. If empty start outputting image at current cursor column (default). 0 skips output.
- _dy_ Optional. If empty start outputting image at current cursor row (default). 0 skips output.
- _id_ Optional. If set, create image reference for later clip-drawing.
- _format_ Optional, image format specifier (default PNG).
- _bytelength_ Mandatory, number of payload bytes.
- _payload_ Base64 encoded image data.

This works almost the same for SIXEL as image payload with one difference - the SIXEL sequence cannot go directly as payload (would terminate the upload sequence), thus we can place the payload after the upload sequence and terminate with an empty upload sequence:
```
OSC 5000 ; width ; height ; mode? ; dx? ; dy? ; id? ; format=SIXEL ; bytelength ST
DCS p ... ST
OSC 5000 ST
```

**Reference cleanup**
Additionally we might need some variant of the sequence for some cleanup tasks:
- Erase Image Reference:
  ```
  OSC 5000 id ST
  ```
- Release all References:
  ```
  OSC 5000 id=0 ST
  ```

**Clip-Drawing**
With a reference from the upload sequence we now can easily clip areas into the terminal, e.g:
```
CSI id ; width? ; height? ; sx? ; sy? ; dx? ; dy? $ I
```
Parameters:
- _id_ Image reference from previous upload.
- _width & height_ Area to be clipped (default - whole from area from upload rescaling).
- _sx & sy_ Origin on the referenced source image in col/row offset to start clipping from (default 1).
- _dx & dy_ Target col/row to start output (default: empty or 0 - current cursor position).

**Note**
There are a few more details described in my early draft (like the placeholder thingy), also some details are not yet clear to me. Also the OSC numbering and the CSI intermediate+finalizer need to be adjusted.

_What to make of it?_
Well the reference thingy is a tough subject for several reasons (esp. lifecycling), so maybe this could start with only the fire&forget variant (no `id` and no clip-drawing yet). This would work quite nice also for embedded SIXEL.

I dont want to get into too much new sequence discussions here, imho @christianparpart's repo is the better place for this. At least I think we can get the sizing issue fixed for SIXELs with a prepended sequence. And a bonus goal would be, that we dont spawn new sequences like crazy (the sketchup above tries to incorporate SIXEL just as another format type).

2021-05-31 15:28 UTC, jerch commented
Did a quick hack based on the proposal above for PNG/JPG (well with DCS instead of OSC, was faster to implement), to see whether the col/row based sizing works. Seems to the case:

![image](https://user-images.githubusercontent.com/6193135/120214634-0651a000-c235-11eb-9d6c-a0c2e9f057eb.png)

2021-06-04 21:37 UTC, jerch commented
@anthonypwest I removed the fit setting for now, will see what we can do about it within the proposal above or something similar. I'll add that with a later version, the PR is already quite big.

Up for review again.

2021-06-13 09:37 UTC, jerch commented
Normally `windowOptions` are disabled for xterm.js and need to be activated explicitly. To make life easier for appside, we should activate several reports with the addon by default:
- getWinSizePixels
- getCellSizePixels
- getWinSizeChars

Needs a ctor flag and some docs about security implications.

2021-06-13 18:43 UTC, jerch commented
@Tyriar Added a few more minor things (windowOptions, pixel limit and a basic image retrieval API) and did  some docs and FIXME cleanup.

Do you see a chance to do a basic review on the PR? I know it is quite alot already and I dont want to add any more stuff. I think we should do an alpha release first and get some user feedback, before going further down the image rabbit hole.

2021-06-14 13:32 UTC, Tyriar requested changes
I haven't really tested or reviewed the addon parts, let me know which parts i should look at in particular. Once we clean up the parts outside of the addon folder and make sure it reliably builds we can merge this into master so that we get automated publishing, more manageable PRs and so you save time with merge conflicts.

As long as core is good and build/tests are still reliable it can live as it's own sub-project without affecting core.

2021-06-14 13:32 UTC, Tyriar commented on .eslintrc.json
> +      "tsconfig.eslint.addon.test.json"
Not sure I like this as it's less clear what it's doing. How about instead having a single tsconfig in the addon root that just references the src*/test dirs?

2021-06-14 13:32 UTC, Tyriar commented on src/browser/Terminal.test.ts
> +      this.timeout(10000);
?

2021-06-14 13:32 UTC, Tyriar commented on demo/index.html
> +      </p>
If we're merging this to master soon we probably don't want this so prominent. Maybe it should live in an experimental section inside a `<details>`?

2021-06-14 13:32 UTC, Tyriar commented on demo/client.ts
> +  const limitStorageElement = (<HTMLInputElement>document.getElementById('image-storagelimit'));
querySelector supports generics which makes it a little nicer:

```suggestion
  const limitStorageElement = document.querySelector<HTMLInputElement>('#image-storagelimit');
```

2021-06-14 13:32 UTC, Tyriar commented on demo/client.ts
> +  const DEFAULT_OPTIONS: any = (addons.image.instance as any)._defaultOpts;
`any` 😱

2021-06-14 13:32 UTC, Tyriar commented on addons/xterm-addon-image/README.md
> +**Note:** This addon is still alpha, expect all sorts of weird errors at the current stage.
Serialize uses:

> ⚠️ This is an experimental addon that is still under construction ⚠️

2021-06-14 13:36 UTC, jerch commented on .eslintrc.json
> +      "tsconfig.eslint.addon.test.json"
If thats possible, sure thing. I remember fiddling around here with different approaches, but I dont exactly recall what I tried and found not working. Will see...

2021-06-14 13:37 UTC, jerch commented on src/browser/Terminal.test.ts
> +      this.timeout(10000);
Why is that there? Lol idk, prolly mixed up branches, to be removed.

2021-06-14 13:39 UTC, jerch commented on demo/index.html
> +      </p>
Yeah good idea. I kinda needed those for messing around with the settings during runtime (can also be removed, if it is too noisy).

2021-06-14 13:42 UTC, jerch commented on demo/client.ts
> +  const DEFAULT_OPTIONS: any = (addons.image.instance as any)._defaultOpts;
Woops sloppy coding. Well, using the real type here does not help much in `client.ts`, since the imports above find on type annotation and get implicit set to `any`. Sadly our demo project is pretty when it comes to TS type checks.

Nonetheless, I can at least put the right type there.

2021-06-14 15:16 UTC, jerch commented on .eslintrc.json
> +      "tsconfig.eslint.addon.test.json"
Found way with one single project file under `addons/tsconfig.eslint.addons.json`. This basically treats all addons as one single project in eslint, linting still works. This kinda boosted linting speed (doubled speed).

Ofc this comes with a catch - an addon not following our src, test folder scheme, will not work without additional changes to that file (which in turn might be incompatible again). But imho thats only a minor catch, addons in the base repo should prolly always follow a fixed folder scheme.

Plz have a look at the other settings in that file, I am already lost with tsconfig settings for TS, no clue at all, which settings eslint takes into account.

2021-06-14 15:44 UTC, jerch commented
@Tyriar 

> I haven't really tested or reviewed the addon parts, let me know which parts i should look at in particular. 

These things prolly need a closer look before merging:
- The renderer-canvas belly dance in `ImageRenderer` is kinda ugly. Currently we have no way to hook into renderer changes or `Terminal.open` calls, but I need that for proper lazy or runtime initialization of the image canvas on top of others. My current solution monkey-patches these core functions, which is pretty bad. Maybe you have a better idea how to solve that (ideally without spec'ing it all out in the API, as we prolly dont want to expose these details at all). Maybe some more internal events will do already.
- If you have some experience with TS and mixed main/worker-builds, maybe have a look at that as well. Although I came up with a working solution, it might be cumbersome. Affected:
  - worker manager in `src/WorkerManager.ts`
  - the worker itself in `src-worker/main.ts`
  - protocol definitions in `src/WorkerTypes.d.ts`
  - build customizations in `webpack.config.js` (addon path) and `../../demo/start.js` (for worker hot-reloading)

> As long as core is good and build/tests are still reliable it can live as it's own sub-project without affecting core.

I agree, the inner works of the addon can be polished/worked out over time. As long as the addon never breaks core functionality and builds, we can slowly iterate to a proper image handling. As you might have guessed from the discussions above, there are tons of conceptual flaws with images in terminals, and some of them cannot really be solved. :smile_cat:

2021-06-17 20:36 UTC, jerch commented
@ismail-yilmaz  FYI - my sixel lib copied over to C and compiled to webassembly gives me 33.8 MB/s throughput in xterm.js. And that code it not even optimized for C, pfff.

2021-06-18 05:36 UTC, christianparpart commented
> @ismail-yilmaz FYI - my sixel lib copied over to C and compiled to webassembly gives me 33.8 MB/s throughput in xterm.js for the benchmark above. And that code it not even optimized for C, pfff.

How did you do that? The copy part. And didn't you say the wasm part is not worth Performance wise for xtermjs?

2021-06-18 06:45 UTC, jerch commented
> How did you do that? The copy part.

Really, I copied the L2 decoder from node-sixel to `decoder.cpp`, replaced the class abstraction with static globals (I need only one always-active "instance") and fixed the code syntax differences. But it is not yet integrated in the addon, just lousy hacked into it to see the difference - the actual decoding runtime dropped from 5.2s to 1.4s.

> And didn't you say the wasm part is not worth Performance wise for xtermjs?

Yes I thought so, but got taught by a simple buffer copy test from u8 to u32, where wasm is way faster than a plain JS loop, see https://github.com/xtermjs/xterm.js/issues/3368#issuecomment-862247184. Esp. llvm/emscripten does a really good job with being more than twice as fast. 2ys ago I did the test only with rust/wasm, that only showed ~30% speedup. Whether a wasm rewrite is it worth for xterm.js core parts - well that's a different story (it really raises the coding barrier and tooling/maintenance complexity, thus should be carefully thought-out).

For sixel decoding things are much easier to handle - no complicated JS interactions, just buffer driven IO and the CPU intensive decoding itself. Seems to fit the wasm idea.

2021-06-18 06:53 UTC, ismail-yilmaz commented
> @ismail-yilmaz FYI - my sixel lib copied over to C and compiled to webassembly gives me 33.8 MB/s throughput in xterm.js for the benchmark above. And that code it not even optimized for C, pfff.

@jerch, That's impressive (and overall I see very nice progress you have here with sixel!). Is this raw rendering output or does it also include terminal sequence parsing + rendering + displaying of sixels? Mine can now get max. ~31 MB/s throughput for *parsing + rendering - displaying* (with single thread), on the base machine I use fo testing.  I'd like to test it on my machine to have a reference.

2021-06-18 06:56 UTC, jerch commented
@ismail-yilmaz The 33 MB/s is the full deal without any threading/worker (was to lazy to get this up just for testing). The inner decoder speed is 119 MB in 1.4 s, thus 85 MB/s.

2021-06-23 10:22 UTC, jerch commented
@ismail-yilmaz

 >  I'd like to test it on my machine to have a reference.

Created the PR for the wasm decoder in https://github.com/jerch/node-sixel/pull/20. It is not yet well integrated into the lib, thus not yet usable out-of-the-box with xterm.js. To still play around with it, you gonna need the emscripten SDK (see wasm/build.sh). If you have remarks about the C code or ideas for optimizations, lets discuss it in the PR thread.

2021-06-23 11:10 UTC, ismail-yilmaz commented
> @ismail-yilmaz
> 
> > I'd like to test it on my machine to have a reference.
> 
> Created the PR for the wasm decoder in [jerch/node-sixel#20](https://github.com/jerch/node-sixel/pull/20). It is not yet well integrated into the lib, thus not yet usable out-of-the-box with xterm.js. To still play around with it, you gonna need the emscripten SDK (see wasm/build.sh). If you have remarks about the C code or ideas for optimizations, lets discuss it in the PR thread.

Ah, great! Thank you very much! I'll look into the PR/code tonight. (Also I'd like to add your name to my acknowledgements list, with your permission, ofc.)

2021-07-30 16:34 UTC, jerch commented
Mostly done with wasm sixel decoder optimization. Once applied, the new decoder will boost the sixel throughput from the lousy 19 MB/s to 41 MB/s* in synchronous processing, have not yet tested the async/worker thingy.

---
[*] The numbers mirror things on my machine with current chrome enigne, they will differ alot for other systems and browser engines (e.g. firefox makes it only to 25 MB/s on my machine, safari/webkit cannot use it at all due to missing wasm-simd support).

2021-08-29 13:53 UTC, jerch commented
Results for the new decoder as worker with `big.sixel` (extending the table from [above](https://github.com/xtermjs/xterm.js/pull/2503#issuecomment-804102251)):

|               | SIXEL deactivated | single threaded | naive worker | worker v2 | wasm worker |
| ----------- | :------------------------ | :------------------- | :--------------- | :------------------ | :-------------|
| `hook` to `unhook` | 750 ms*  | 2200 ms* | 1300 ms* | 1000 ms* | 450 ms (750 ms)* |
| script on main | 250 ms | 1600 ms | 450 ms | 400 ms | 400 ms |
| script on worker | - | - | 1100 ms | 750 ms | 250 ms |
| `put` message excess | - | - | ~50 chunks (25%) | ~2 chunks (1%) | 0 chunks |
| async `unhook` delay | - | - | 200 ms | <20 ms | <20 ms |

Well, with the wasm decoder we reached a tipping point - it decodes faster than xterm.js can provide the data, thus the time from `hook` to `unhook` is directly limited by xterm.js' script runtime (note: the higher value (*) is with devtools opened, explanation below). In the meantime the decoder thread is only at 50% load, and the messages do not stack up in the queue anymore.
That 50% load of the worker made we wonder about different image sizes. Turns out that this is quite stable from small to big images, seems the higher data amount of bigger images grows both script loads on main and the worker fairly equal.

Note that the worker setup does not give any advantage in terms of throughput compared to sync decoding anymore. Both show a throughput of 39-42 MB/s for sixel-bench (sync is even abit faster). The reason for this is the worker overhead with the data transport itself - while above the worker script needs 250 ms to finish, it only takes 150 ms to decode in sync, so we already have 100 ms wasted for the worker data juggling. I still think the worker approach is right way to go for image decoding, as it offloads nasty work, that otherwise would stack/block on main.

**devtools runtime impact:**
In https://github.com/xtermjs/xterm.js/pull/2503#issuecomment-804102251 I stated, that getting the decoding runtime for `big.sixel` below 1000 ms will be hard. Well, we actually got it down to 750 ms with devtools opened, and 450 ms with devtools closed. Have to admit that I was not aware of that big impact of the state of devtools until recently (thus the older numbers marked with * above are with devtools open). It seems that the type of actions we measure here create a significant runtime distortion from the profiler itself. I was able to work around that to some degree by placing my own performance marks in the code not using devtools, which revealed, that the whole decoding runtime from `hook` to `unhook` is the same as the script runtime on main now (plus a tiny overhead).

2021-08-31 18:10 UTC, jerch commented
@Tyriar Any chance to finally review and add the PR soon?

2021-09-07 14:14 UTC, Tyriar requested changes
That took a while 😅

Didn't actually test it out yet since I'm on Windows and seems inconvenient/not sure how to do it. Some demo buttons would be really nice

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
The safer approach here would be either using a map from the attr to a new object or using a marker:

```ts
this._imageAttrsMap.set(marker, new ImageAttrs(imageId, tileId));
```

Feels pretty fragile atm

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +    const buffer = this._terminal._core.buffer;
Restricting the unsafe access to ImageAddon would be better:

```ts
const core = (this._terminal as any)._core as ICoreTerminal;
new ImageStorage(core, ...)
```

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +
You could use the webgl color tests as inspiration here to print palette.png and test that it prints correctly?

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    this._oldOpen = this._terminal._core.open;
`ICoreTerminal.core` is confusing

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    canvas.height = height | 0;
Was the `| 0` intentional?

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +      return new Promise(res => res(undefined));
```suggestion
      return Promise.resolve(undefined);
```

Can use async to return undefined if it works in static functions

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +  }
If you extend Disposable you can register callbacks instead of reimplementing dispose. I've started doing this more in vscode and tends to lead to less issues:

```ts
ctor() {
  this.register(() => {
    // dispose a bunch of stuff
  });
}
```

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    };
WebGL throws when activated before open is called:

```
    if (!terminal.element) {
      throw new Error('Cannot activate WebglAddon before Terminal.open');
    }
```

Should `ImageRenderer` only be created after open is called?

2021-09-07 14:14 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageAddon.ts
> +export class ImageAddon implements ITerminalAddon {
It would be nice if this works seamlessly with the serialize addon. We might need some way to register custom attributes to a cell which then support serialization?

2021-09-07 15:00 UTC, Eugeny commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +    // Default start palette (default 'ANSI256').
IIRC using jsdoc style comments (`/** */`) also explicitly marks them for extraction for tsdoc/typedoc

2021-09-07 15:03 UTC, christianparpart commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
Sorry to chime in as a stranger here. So you mean by that to introduce a CSI sequence that is just there to load this feature?

If so, that would be very Bad, but i would instead suggest to add the ability to lazy load by DCS hook instead.

2021-09-07 15:34 UTC, Tyriar commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +    // Default start palette (default 'ANSI256').
`///` might work, depends on whether tsserver would pick that up for TS

2021-09-07 15:35 UTC, Tyriar commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
I mean something like:

```
// not sure which sequences can start an image off hand
term.registerImageStartHandler(params => {
  // load the image addon
  // forward the params to the image addon to start processing it
});
```

> If so, that would be very Bad

What do you mean?

2021-09-07 15:37 UTC, Tyriar commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
The reason I suggest this is because startup time is very important in VS Code, we already defer terminal initialization until after the "wordbench" has loaded, but it would be even better if the image code only loaded when the terminal hit an image to avoid using up cpu/memory unnecessarily

2021-09-07 15:50 UTC, christianparpart commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
> What do you mean?

Hey. I mean sixel graphics is having two VT sequences, `XTSMGRAPHICS`, `DECSDM`, and the DCS. There should not be a fourth one (what should app devs do then to stay terminal Independent).

Sadly These VT sequences can come in in any order, so fully referring loading won't work i think but the actual horse is it's DCS. Maybe that part (if possible) could be tried to lazy load it's functionality. 

I am not a JS pro and just curious in here. (Disclaimer :)

2021-09-07 17:40 UTC, jerch commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
@Tyriar Why do you think that would be needed? I get like ~105 ms (+- 10 ms) for current master as loading time in the demo, with this PR ~110 ms (+- 10 ms). Sure, thats +5 ms, but comparing the difference to the total loading time, it feels like bashing the wrong horse. Do you get much worse numbers in vscode/electron?
Note that the hard work of image decoding in the worker is already lazy loading on first image. I cannot slice the basic addon functionality further into deferred parts in a sensible way, as most things are preparing xterm.js for proper image support (like implementing the needed VT sequences, set up an empty image storage and such). Making those lazy means to do the whole addon loading lazy on first sight, thats always possible, but not in a sensible way from the addon itself (mostly the additional sequence hooks would still need to be registered with some deferred loader, only the instantiation of `ImageStorage` and `ImageRenderer` could be skipped, but those are not costly by any means). For such a functionality we should think about a lazy addon loader in general. Still I think the additional 5 ms loading time above are not worth that at all.

2021-09-07 17:41 UTC, jerch commented
@Tyriar Thx for the review. Thats quite alot to go through, will need some time to do that.

2021-09-07 18:07 UTC, jerch commented on addons/xterm-addon-image/package.json
> +    "sixel": "^0.15.0"
I dont think so - the webpack thingy is a browser bundle target, the npm package is a nodejs target. If someone wants to grab the definitions and do some class inheritance on them, it wont work anymore, as nodejs will load the unbundled compiler output, which still depends on `sixel`.

2021-09-07 18:09 UTC, jerch commented on addons/xterm-addon-image/src-worker/main.ts
> +import { PALETTE_VT340_COLOR, PALETTE_VT340_GREY, PALETTE_ANSI_256 } from 'sixel/lib/Colors';
I had it like that in the beginning, but got shocked from the bundled sizes. Problem here - we dont do proper ES6 bundling yet, and webpack can only tree shaking on ES6. Thus I refer to parts of the lib - makes the final bundle much smaller.

2021-09-07 18:12 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
Nope, it will evict the image early (on entering the storage).

2021-09-07 18:15 UTC, jerch commented on addons/xterm-addon-image/package.json
> +    "png-ts": "^0.0.3"
This is used in tests to load from a png and do some byte comparison with the sixel decoded bytes.

As long as we have no genuine PNG loading way, this was faster to implement than some awkward canvas-browser replacement.

2021-09-07 18:16 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +// cat !(*_clean).six
Lol yeah, well those are just my "cmdline bookmarks". To be removed.

2021-09-07 18:18 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  private _disposables: IDisposable[] = [];
I tried to avoid to rely on any active code definitions from core (thus no function or ctor imports). I only link against expected symbols on the terminal object (with private descent).

2021-09-07 18:19 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +import { IRenderService } from 'browser/services/Services';
Not sure what you mean here?

2021-09-07 18:21 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  /**
> Can we import this from xterm-addon-image.d.ts?

Hmm can try that, I remember that it did not work in other addons though.

2021-09-07 18:21 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  [P in keyof IImageAddonOptionalOptions]-?: IImageAddonOptionalOptions[P];
Yepp :smile_cat:

2021-09-07 18:25 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  _core: {
But I need some private symbols, how would I get those from direct import?

2021-09-07 18:28 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +      '_core.buffer.x',
Still not sure, how to descent into privates from normal imports? (This is merely a private API access test, which happens to also contain publics.)

2021-09-07 18:30 UTC, jerch commented on addons/xterm-addon-image/src/WorkerManager.ts
> +}
Yes, they are not 100% symmetrical. Prolly can simply it into one or 2 interfaces in one place.

2021-09-07 18:33 UTC, jerch commented on addons/xterm-addon-image/src/WorkerManager.ts
> +    this.worker?.postMessage({
Yes, thats the deferred worker loading attempt, that might fail.

2021-09-07 18:37 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
This actually clones and extends `ExtendedAttrs` in the terminal buffer to also hold image information. This is indeed fragile, because `ExtendedAttrs` is not yet meant to get extended during runtime.

Not sure, how a marker would help here? (Also note that the marker API is rather expensive, thus I tried to avoid it as much as possible).

2021-09-07 18:40 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +
Yes, thats currently not yet tested automatically on individual terminal cell level.

2021-09-07 18:40 UTC, Tyriar commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
> Do you get much worse numbers in vscode/electron?

No but these 5ms add up, I don't know how much of that is code loading vs instantiation but we also restore terminals so if it ended up being 5ms per terminal and you had 10 terminals that's 50ms (it probably isn't the case that this is instantiation though). Basically I've been trained to minimize everything on startup because we are very restricted in what we can do.

I agree it's probably not worth it though and at least for VS Code's initial adoption we could add an opt-in switch to avoid loading the addon to mitigate risk anyway.

2021-09-07 18:42 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    canvas.height = height | 0;
Yes, cheap way to say "gimme an int32 value floored". The whole follow-up canvas paint logic floors any float values.

2021-09-07 18:42 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  private _disposables: IDisposable[] = [];
We do this elsewhere, perhaps we should have a `platform/tsconfig.json` or somewhere where importing like from addons is encouraged? 🤔

2021-09-07 18:44 UTC, Tyriar commented on addons/xterm-addon-image/src/Types.d.ts
> +import { IRenderService } from 'browser/services/Services';
Like this, being a little more explicit would cause TS to give a compile error when accidentally importing something other than a type (you might be able to import type from the top one):

```
import { Cell, BgFlags, Content } from 'common/buffer/Constants';
import type { IParams, IDcsHandler, IEscapeSequenceParser } from 'common/parser/Types';
import type { IBuffer } from 'common/buffer/Types';
import type { IBufferLine, IExtendedAttrs, IInputHandler } from 'common/Types';
import type { IOptionsService, IDirtyRowService, ICoreService } from 'common/services/Services';
import type { IColorManager } from 'browser/Types';
import type { IRenderDimensions } from 'browser/renderer/Types';
import type { IRenderService } from 'browser/services/Services';
```

2021-09-07 18:44 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +  }
As mentioned above, I tried not to import active code from core (is more cumbersome to get things right, as we dont have proper ctor types declared).

2021-09-07 18:46 UTC, Tyriar commented on addons/xterm-addon-image/src/Types.d.ts
> +  _core: {
You can't unless you expose them on the main interface, but doing this would cut down on the redefinitions that would break if we changed core's interface:

```ts
export interface IInternalCoreTerminal extends ICoreTerminal {
  _dirtyRowService: IDirtyRowService;
  _colorManager: IColorManager;
  _inputHandler: IInputHandlerExt;
  _renderService: IRenderService;
}
```

2021-09-07 18:46 UTC, Tyriar commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +      '_core.buffer.x',
Replied on the Types.d.ts comment

2021-09-07 18:46 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    };
Hmm, I think this needs another test case. (Most of `ImageRenderer` is guarded against that, but I am currently unsure, if thats the case for all methods/properties.)

2021-09-07 18:47 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +export class ImageAddon implements ITerminalAddon {
Yes, thats on the TODO list for a later version. It is really hard to get this done (basically needs an encoder path for serialization).

2021-09-07 18:48 UTC, Tyriar commented on addons/xterm-addon-image/src/WorkerManager.ts
> +}
`IImageMessageToWorker`, `IImageMessageToWindow`?

2021-09-07 18:49 UTC, jerch commented on addons/tsconfig.eslint.addons.json
> +  "compilerOptions": {
Well I basically did a c&p & merge from tsconfigs to make sure, no new rules slip into. Not sure if hose rules are needed at all.

2021-09-07 19:04 UTC, jerch commented on addons/xterm-addon-image/README.md
> +terminal.loadAddon(imageAddon);
The 110 ms is the total script eval time from devtools (contains both source reading and instantiation, no clue at which ratio though). Note thats from the demo loader, which is `ts-loader`. Prolly the numbers are lower for properly bundled things.

2021-09-07 19:16 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  private _disposables: IDisposable[] = [];
That would certainly help in this case, yeah. To me it occurs, that addons have a tendency to need more internal things than a typical user would expect from the public API, so this sounds abit like a slightly "deeper" API for addons. But is it worth shaping another API? Idk, because on the other hand it is watering the core vs. addon separation, which basically would introduce hard version dependencies between core and addons (most addons are free of those currently).
Well, unsure how to deal with that in a reliant way.

2021-09-07 19:34 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +  }
Might be misunderstanding, but you don't need types declared as it's depending on the file directly. `EventEmitter` here is pulled in and bundled as part of the addon, only including the dependent files of `EventEmitter.ts`:

https://github.com/xtermjs/xterm.js/blob/8d48616e0d4f0748db3597276b9b6a7db0e12799/addons/xterm-addon-webgl/src/WebglAddon.ts#L10

2021-09-07 19:35 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    };
If you can defer the creation of ImageRenderer all together, it will be a lot cleaner in there as you can avoid all the undefined checks and force canvas, ctx, etc, to be there on construction

2021-09-08 16:58 UTC, jerch commented on addons/tsconfig.eslint.addons.json
> +  "compilerOptions": {
Currently in master eslint will go through all addons with their project references separately, which takes alot of time and memory. With the image addon added, this does not work anymore, eslint runs into OOM. Thus waiting is no option (unless we disable eslint for addons)?

Now the idea of that additional tsconfig file is to give eslint a single project entry for all addons at once. I had to do this, because of your linked issue. With this eslint works again.

The tsconfig file is simply a merger of the single ones at individual addon level.

2021-09-08 17:21 UTC, jerch commented on addons/xterm-addon-image/package.json
> +{
I dont care about the file ending, but it seems it was `six` in the old days. Changed it.

2021-09-08 17:34 UTC, christianparpart commented on addons/xterm-addon-image/package.json
> +{
Most likely just because of the old days of FAT FS.

2021-09-08 17:39 UTC, jerch commented on demo/client.ts
> +function initImageAddonExposed(): void {
Added 2 demo buttons (fetching files from node-sixel repo).

2021-09-08 17:42 UTC, jerch commented on demo/client.ts
> +  document.querySelector<HTMLPreElement>('#serialize-output').innerText = outputString;
Which line? Anyway, vscode wants it for both lines.

2021-09-08 17:47 UTC, jerch commented on addons/xterm-addon-image/src-worker/main.ts
> +import { PALETTE_VT340_COLOR, PALETTE_VT340_GREY, PALETTE_ANSI_256 } from 'sixel/lib/Colors';
Not gonna change that, we can do full package imports once we do ES6 bundling with proper tree shaking.

2021-09-08 19:48 UTC, jerch commented on addons/xterm-addon-image/src-worker/main.ts
> +  <T extends IImageWorkerMessage>(message: T, options?: PostMessageOptions | undefined): void;
Fixed together with remark below.

2021-09-08 19:50 UTC, jerch commented on addons/xterm-addon-image/src/WorkerManager.ts
> +}
Simplified it abit, and this way they can be handled as symmetrical (though that does not happen in all cases/directions).

2021-09-08 20:40 UTC, jerch commented on addons/xterm-addon-image/README.md
> +Image output in xterm.js.
Does a video work in the README?

Obviously here it works:

https://user-images.githubusercontent.com/6193135/132581394-0bc118d8-06b4-4501-a917-2304add6eba4.mp4

Alternatively this will do:
![grafik](https://user-images.githubusercontent.com/6193135/132582135-c928635d-30a5-4439-ac71-154407b0b167.png)

2021-09-08 21:08 UTC, jerch commented on addons/xterm-addon-image/src-worker/main.ts
> +// FIXME: set memoryLimit from addon setting
Fixed.

2021-09-08 21:09 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +    workerPath?: string;
Yes, gonna change that.

2021-09-08 21:27 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  }
But it saves a lot of `this._disposables.push` "decorations" (better readable and less code).

2021-09-08 21:30 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +import { IRenderService } from 'browser/services/Services';
Oh wow, wasnt aware of that feature.

2021-09-08 22:15 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +export class ImageAddon implements ITerminalAddon {
Thinking again about that - imho this should wait until we have settled with some PNG or JPG capable sequence. While re-encoding a previous sixel image into sixel again can be done, it is really cumbersome for other formats due to the additional quantization step, which we will never get done in a performant way in JS (not even in wasm, due to lousy SIMD support currently).

Once we support a PNG/JPG capable sequence we can simply use the browser blob interface for the conversion.

2021-09-09 10:56 UTC, Tyriar commented on addons/tsconfig.eslint.addons.json
> +  "compilerOptions": {
eslint hits oom 🤯 

It's probably fine like this if there's performance issues, not sure if eslint would need anything specific from the tsconfig.json to do its thing anyway.

2021-09-09 10:56 UTC, Tyriar commented on addons/xterm-addon-image/README.md
> +Image output in xterm.js.
Let's stick to a screenshot, don't think videos work in GH readmes

2021-09-09 10:57 UTC, Tyriar commented on demo/client.ts
> +  document.querySelector<HTMLPreElement>('#serialize-output').innerText = outputString;
The `<HTMLPreElement>` since `innerText` exists on HTMLElement I think

2021-09-09 10:58 UTC, Tyriar commented on demo/client.ts
> +  document.querySelector<HTMLPreElement>('#serialize-output').innerText = outputString;
If it still wants it, use HTMLElement instead as then we could change the <pre> without needing to update the ts

2021-09-09 10:58 UTC, jerch commented on addons/xterm-addon-image/package.json
> +{
Idk, those 3-letter endings were also pretty common on OpenVMS, my guess is it comes from there, because it was DEC's most successful OS. (Imho both DOS and OpenVMS derived that 3 letter thingy from TOPS-10.)

2021-09-09 10:59 UTC, Tyriar commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
Should we `throw` or `console.warn` or do you think the comment is enough?

2021-09-09 11:03 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  private _disposables: IDisposable[] = [];
For common classes like EventEmitter/Disposable which won't change there's very little risk in depending on them.

> Idk, because on the other hand it is watering the core vs. addon separation

Yes this does exist but we're CI protects us from breakages since the repo is shared, this was one of the main benefits to not going with an actual generic renderer API and just building all the renderers ourselves. That way we didn't need to expose a host of APIs that probably only we would use.

> But is it worth shaping another API?

`Disposable` and `EventEmitter` are the main candidates here and they're both relatively simple that I don't think we need an API, plus it's the xterm.js/vscode way of doing things and other embedders probably have their own way.

2021-09-09 11:03 UTC, Tyriar commented on addons/xterm-addon-image/src/Types.d.ts
> +import { IRenderService } from 'browser/services/Services';
It's relatively new 🙂

2021-09-09 11:06 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
just worried about the headaches this could cause if we change how `_extendedAttrs` works in an unrelated PR, someone may need to fix up a bunch of stuff in the image addon. Related to the serialize question, this could get deferred to a debt item if it'll take a while. I was thinking something like this:

```ts
IBufferCell.registerExtendedAttr(...): Disposable
```

Would be a little extra overhead which should be fine as it's just done once per cell per image (not on every frame?) but it would protect us from the above problems.

2021-09-09 11:21 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
Hmm yeah, prolly at least a logged warning as feedback would be good. Throwing seems a bit to harsh, as it is within in expected behavior and can be handled gracefully.

2021-09-09 11:25 UTC, jerch commented on addons/xterm-addon-image/package.json
> +    "png-ts": "^0.0.3"
Thinking again about it - if you feel uneasy because of another foreign lib being imported here, well it is only used in api tests. This still has a small risk of doing nasty things during tests run - I can mark it as a FIXME to be replaced once we have the PNG sequence path implemented.

2021-09-09 11:29 UTC, Tyriar commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
If it's expected then perhaps change the working to avoid "should"? It could do with a rephrase as well since it's a bit confusing with the maths involved in determining valid values:

> When pixelLimit * 4 exceeds storageLimit * 1024 * 1024, the value of storageLimit * 1024 * 1024 / 4 will be used?

2021-09-09 11:39 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
True, indeed a nasty entanglement. I started to think about runtime extensible extended attrs, but was under the impression that it might be too much for this PR. Also the early playground PR for OSC 8 hyperlinks in #2904 will be affected by that.

Imho we should do that in a separate PR (and some discussion, what it should be capable of), what you think?

2021-09-09 11:43 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
Oh ok, yeah will change that. (Indeed, the pixel vs byte size is abit confusing, maybe I can get this more aligned to one side.)

2021-09-09 11:48 UTC, Tyriar commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
👍

2021-09-22 22:53 UTC, j4james commented on addons/xterm-addon-image/src/ImageAddon.ts
> +          break;
FYI, this is the wrong way around. Mode 80 is actually _Sixel Display Mode_, which is the exact opposite of the _Sixel Scrolling_ option. When it's set, scrolling is _disabled_, and when it's reset, scrolling is _enabled_ (which is the default). I know some of the DEC documentation got this wrong, but this behaviour has recently been confirmed on an actual DEC VT340 terminal. And I know XTerm also had this the wrong way around initially, but that has been corrected in the latest release (see https://github.com/ThomasDickey/xterm-snapshots/commit/b40e561404bf35c180e15ea975139e813d3c45b5).

2021-09-23 09:04 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +          break;
Thx for the headsup, will flip the setting accordingly.

2021-09-23 12:47 UTC, j4james commented on addons/xterm-addon-image/src/ImageAddon.ts
> +          break;
I just realised this mode is the wrong way around too. When mode 7730 is set, the cursor should move to the beginning of the line (this is compatible with the current XTerm implementation), and when reset, it should remain in the starting column, i.e. in line with the left of the image (which is more compatible with the original DEC terminals, at least in terms of column position).

You can find the Mintty documentation here: https://github.com/mintty/mintty/wiki/CtrlSeqs#graphics-end-position

2021-09-23 12:53 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +          break;
Wow, thx for bug hunting. Yeah I know the docs of it, but could not quite get the proper directions from it (and had no way to directly test it either).

2021-09-28 10:48 UTC, jerch commented
@j4james I flipped the settings for DECSET 80 and 7730.

There is another issue with `lsix` about the reported sixel geometry. Currently the addon always reports the max possible geometry (as thats what I found to be reported from xterm). But `lsix` uses this as the current window extend. Not sure, what is appropriate here, maybe you or @hackerb9 have a better idea, how this value is meant to be used from app side? (If not I prolly gonna change it to the current window x/y extend as long as the product stays below the max allowed pixel value.)

2021-09-28 12:47 UTC, jerch commented on addons/tsconfig.eslint.addons.json
> +  "compilerOptions": {
Not sure either. Tbh I dont like the fact, that the linter operates on a fake project, that never gets used/built by TS, but it was the only way I found avoid the OOM. The linting though works correctly across lib borders (tested manually by doing forth and back changes at various places).

If you have no other ideas how to circumvent the OOM by some simpler settings, I'd leave it that way for now.

2021-09-28 13:06 UTC, jerch commented on demo/client.ts
> +  document.querySelector<HTMLPreElement>('#serialize-output').innerText = outputString;
Changed.

2021-09-28 13:55 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +    workerPath?: string;
Removed `workerPath` from options and made it a mandatory argument of the ctor.

2021-09-28 14:23 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> + */
Created https://github.com/xtermjs/xterm.js/issues/3488.

2021-09-28 14:25 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +export class ImageAddon implements ITerminalAddon {
Created https://github.com/xtermjs/xterm.js/issues/3488 as follow-up issue.

2021-09-28 14:26 UTC, jerch commented on demo/index.html
> +              </label>
See https://github.com/xtermjs/xterm.js/issues/3488.

2021-09-28 14:32 UTC, j4james commented
> @j4james I flipped the settings for DECSET 80 and 7730.

Fantastic. Thank you.

> Changed the geometry report to real active area on GA_READ (vs. output of squared pixel limit for GA_READ_MAX).

I think this is the right choice. Most terminals don't report a geometry value at all, and the few that do are not consistent - some report the max geometry and some the current screen size. XTerm reports the current screen size unless it's larger than the max value, in which case it's clamped (but I think that's unlikely to be an issue for most others, because they usually don't have a max, or if they do, it's fairly large).

Personally I don't think those queries are worth supporting - their only real purpose is to work around a limitation of XTerm's architecture - so if you don't share that limitation, I don't see the point. But if you do, returning the current screen size clamped to the max values seems most appropriate.

> But `lsix` uses this as the current window extend.

I don't think that's a good idea, but there's not really a great solution for this. In my ideal world, everyone would be emulating the VT340 10x20 cell size, in which case you could simply scale the text grid size (which is universally queryable with `CPR`) by 10x20. But I know that's never going to happen (and it gets more complicated with things like 132-column mode), so you have to rely on one of the non-standard queries.

I think the most widely supported is `CSI 14 t`, but then you have to deal with the fact that some terminals interpret that as querying the application window size (including window borders, scroll bars, etc), so it's only really an approximation. You can get a more accurate result querying the cell size with `CSI 16 t`, and multiply that by the  text grid size, but that is not quite as widely supported.

As a terminal, though, I think you can be most helpful to apps by returning cell size in `CSI 16 t`, and the pixel size of the text grid in `CSI 14 t`. As an app, I'd query `CSI 16 t` first, `CSI 14 t` if that fails, and fallback to 10x20 as a last resort. I don't think any of the other size/position queries are worth bothering with.

2021-09-28 15:06 UTC, christianparpart commented
> > @j4james I flipped the settings for DECSET 80 and 7730.
> 
> Fantastic. Thank you.

Da heck? What is `7730`? Okay, I googled it, something invented from mlterm, and now I see there are plenty of 77xx extensions from mlterm. Is it really worth implementing these? (I'm just curious, also - I am not a great fan of these really huge numbers in comparison to the rest. We may want to try to collect all DEC modes (and maybe who is supporting them / who introduced it) so we have a better overview of what mode numbers are still free. Otherwise I fear another day someone will invent DEC mode numbers like 14xxx).

> > Changed the geometry report to real active area on GA_READ (vs. output of squared pixel limit for GA_READ_MAX).
> 
> I think this is the right choice. Most terminals don't report a geometry value at all, and the few that do are not consistent - some report the max geometry and some the current screen size. 
I tried to explicitly implement what `ctlseqs.txt` of xterm told me. If anything is differing, I'm really happy to converge (I don't like too much divergence in the TE world :-) )

> I think the most widely supported is `CSI 14 t`, but then you have to deal with the fact that some terminals interpret that as querying the application window size (including window borders, scroll bars, etc), so it's only really an approximation. You can get a more accurate result querying the cell size with `CSI 16 t`, and multiply that by the text grid size, but that is not quite as widely supported.

I quite much like these two VT seqs. It seems like you know (or barely remember at least) what TEs do not or only weirdly support these. Maybe it is worth filing a ticket in those and request for convergence here?

Greetings,
Christian.

2021-09-28 15:17 UTC, jerch commented
@j4james Thx for the detailed response.

> ... XTerm reports the current screen size unless it's larger than the max value, in which case it's clamped ...

Hmm thats weird, I always get 1000 x 1000 from xterm, no matter how big the xterm window is. Guess I should test against a newer version lol.

> Personally I don't think those queries are worth supporting - their only real purpose is to work around a limitation of XTerm's architecture - so if you don't share that limitation, I don't see the point. But if you do, returning the current screen size clamped to the max values seems most appropriate.

Yeah well, for xterm.js the geo stuff is totally artificial. Ofc we have a limit, but thats in terms of total pixels to be decoded and held in the storage (more like a memory limit to not run into OOM).

About CSI 14/16 t:
Those are abit tricky with xterm.js - first we disable window reports by default for security reasons (integrators have to enable them explicitly, but I already overloaded that with a convenient behavior for this addon to enable 14|16|18). Then we are a pure "library widget", thus we dont have any concept of a window and/or window decorations. Thats the reason why most `CSI ... t` commands are abstract and need a real implementation by integrators. But I think no one really cares for those (idk anyone overloading those commands), which puts most xterm.js integrations back to not supporting CSI t at all (and we cant do much about it).
But I second that those are better suited for viewport size requests.

About the 10x20 idea:
I know that this comes along with the SSU idea, which introduces another indirection in graphics to screen pixels. I like the greater expressiveness it gives, already thought about using this or something similar for a PNG protocol, but made no good progress there yet. There is an issue about it here: https://github.com/contour-terminal/terminal-good-image-protocol/issues/13 (I called it addressing mode for images, as it mainly raises the question, how image pixel should be related to cols/rows and/or screen pixels in terms of initial offset and/or extends).

@christianparpart I added 7730 because of some discussion about it in that nasty image thread in terminal-wg, where most ppl found such a mode very helpful for app side.

2021-09-28 18:07 UTC, jerch commented on addons/xterm-addon-image/typings/xterm-addon-image.d.ts
> +     * Note:`pixelLimit` * 4 should not exceed `storageLimit` in bytes.
Changed the description. Also changed the eviction behavior that way: a single image is allowed to be bigger than `storageLimit`, adding such an image will drain the whole storage, the image gets added, but will get evicted as soon as another image enters the storage.

2021-09-28 18:10 UTC, j4james commented
> What is `7730`? Okay, I googled it, something invented from mlterm, and now I see there are plenty of 77xx extensions from mlterm. Is it really worth implementing these?

I'm not sure that's mlterm. I believe the 77xx range is mostly used by Mintty. As for whether they're worth implementing, that depends on whether your user base has a need for any of that functionality. I certainly wouldn't consider trying to implement every single mode that other terminals have defined, just for the sake of it. 7730 in particular I think is a complete waste of time - it's essentially just the equivalent of a carriage return after the image as I understand it.

> I quite much like these two VT seqs. It seems like you know (or barely remember at least) what TEs do not or only weirdly support these. Maybe it is worth filing a ticket in those and request for convergence here?

It's not like everyone isn't already aware of this. It's just that there isn't a standard that anyone can agree on, so I doubt anyone is willing to change. I think XTerm tried to address the issue by introducing more variants, so in addition to the `CSI 14 t`, there's also a `CSI 14;1 t`, and a `CSI 14;2 t` (one of which gives the text area size, and one of which is the full window size). But I think those just ended up being implemented inconsistently as well (i.e. some treat 14;1 as the text area size, and size treat it as the window size).

Basically it's a huge mess, and when it comes to proprietary sequences like this, I prefer not to get involved - it's hard enough trying to persuade people to follow real standards. That said, I did file an issue with VTE, since they had the dimensions completely backwards, and that has at least been fixed.

2021-09-28 18:24 UTC, jerch commented on addons/xterm-addon-image/src/ImageAddon.ts
> +  private _disposables: IDisposable[] = [];
Thinking about this again, how would you want this to look like? I dont want to import them directly from main repo code, as this copies the definitions over, which leads to nonsense code doubling. With my current appraoch I save around 2kB on the output end.
What would work - the ctor symbols being exposed from xterm.js under some code path, so I could use it directly from within the xterm.js built. How could this look like? Maybe some endpoint under the current API as:
```
// on xterm API:
interface helpers {
  Disposable: IDisposableCtor;
  EventEmitter: IEventEmitterCtor;
  ...
}
```
In any case I think this should not be done within this PR, but by a separate one.

2021-09-28 18:28 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  /**
Tried different things but tbh - idk how to do that. TS does not want to import anything from the `declare module ...` construct. Is that possible somehow?

2021-09-28 18:34 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  [P in keyof IImageAddonOptionalOptions]-?: IImageAddonOptionalOptions[P];
Simplified it with Partial<...>.

2021-09-28 18:56 UTC, jerch commented on addons/xterm-addon-image/src/Types.d.ts
> +  _core: {
Changed.

2021-09-28 19:00 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +  before(async function(): Promise<any> {
changed.

2021-09-28 19:12 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +    await page.setViewportSize({ width, height });
changed.

2021-09-28 19:16 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +      '_core.buffer.x',
Shortened the list.

2021-09-28 19:20 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +async function getDim(): Promise<IDim> {
Renamed.

2021-09-28 20:05 UTC, jerch commented on addons/xterm-addon-image/src/WorkerTypes.d.ts
> +  payload: 'ping' | 'alive';
Change the message type to a const enum.

2021-09-28 20:08 UTC, jerch commented on addons/xterm-addon-image/src/WorkerManager.ts
> +  private _poolChecker: any | undefined;
Changed.

2021-09-28 20:18 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +        line._extendedAttrs[x] = new ExtendedAttrsImage(old.underlineStyle, old.underlineColor, imageId, tileId);
See https://github.com/xtermjs/xterm.js/issues/3489.

2021-09-28 20:21 UTC, jerch commented on addons/xterm-addon-image/src/ImageStorage.ts
> +    const buffer = this._terminal._core.buffer;
How is this less unsafe? (Because I mostly do more deeper private access later on...)

2021-09-28 20:22 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    this._oldOpen = this._terminal._core.open;
Renamed the types.

2021-09-28 20:24 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +  }
Yes, but that would copy over the definitions doubling code output (also see my comment above about a more internal addon API endpoint).

2021-09-28 20:29 UTC, jerch commented on addons/xterm-addon-image/src/ImageRenderer.ts
> +    };
Double checked this - there is no need to defer the renderer creation, the addon will still work without any real browser element attached - it will just store things with a default cell size to be shown later.

2021-09-28 20:46 UTC, jerch commented on addons/xterm-addon-image/test/ImageAddon.api.ts
> +
Added to follow-up issue https://github.com/xtermjs/xterm.js/issues/3488.

2021-09-28 20:48 UTC, jerch commented
@Tyriar Went through all of your remarks, was able to fix most of them. Plz see above. :smile_cat:

2021-09-29 01:39 UTC, hackerb9 commented
> @j4james I flipped the settings for DECSET 80 and 7730.
> 
> There is another issue with `lsix` about the reported sixel geometry. Currently the addon always reports the max possible geometry (as thats what I found to be reported from xterm). But `lsix` uses this as the current window extend. Not sure, what is appropriate here, maybe you or @hackerb9 have a better idea, how this value is meant to be used from app side? (If not I prolly gonna change it to the current window x/y extend as long as the product stays below the max allowed pixel value.)
> 
> Edit: Changed the geometry report to real active area on GA_READ (vs. output of squared pixel limit for GA_READ_MAX). With this `lsix` gets the width correctly.

`lsix` uses two sources to get width in pixels that can be rendered. The preferred way is to use the XTSMGRAPHICS sequence I suggested to Thomas Dickey and that he implemented in XTerm. It is unambiguous about what it is referring to (sixels) and what it means (visible area). 

<details><summary>XTSMGRAPHICS from ctlseqs</summary>

From https://invisible-island.net/xterm/ctlseqs/ctlseqs.html:
```
CSI ? Pi ; Pa ; Pv S
          Set or request graphics attribute (XTSMGRAPHICS), xterm.  If
          configured to support either Sixel Graphics or ReGIS Graphics,
          xterm accepts a three-parameter control sequence, where Pi, Pa
          and Pv are the item, action and value:

            Pi = 1  ⇒  item is number of color registers.
            Pi = 2  ⇒  item is Sixel graphics geometry (in pixels).
            Pi = 3  ⇒  item is ReGIS graphics geometry (in pixels).

            Pa = 1  ⇒  read attribute.
            Pa = 2  ⇒  reset to default.
            Pa = 3  ⇒  set to value in Pv.
            Pa = 4  ⇒  read the maximum allowed value.

            Pv is ignored by xterm except when setting (Pa == 3 ).
            Pv = n ⇐  A single integer is used for color registers.
            Pv = width ; height ⇐  Two integers for graphics geometry.

          xterm replies with a control sequence of the same form:

               CSI ? Pi ; Ps ; Pv S

          where Ps is the status:
            Ps = 0  ⇐  success.
            Ps = 1  ⇐  error in Pi.
            Ps = 2  ⇐  error in Pa.
            Ps = 3  ⇐  failure.

          On success, Pv represents the value read or set.

          Notes:
          o   The current implementation allows reading the graphics
              sizes, but disallows modifying those sizes because that is
              done once, using resource-values.
          o   Graphics geometry is not necessarily the same as "window
              size" (see the dtterm window manipulation extensions).
              For example, xterm limits the maximum graphics geometry at
              compile time (1000x1000 as of version 328) although the
              window size can be larger.
          o   While resizing a window will always change the current
              graphics geometry, the reverse is not true.  Setting
              graphics geometry does not affect the window size.
```
</details>

If a terminal doesn't respond to that, then `lsix` falls back to the dtterm window manipulations ("WindowOps"), which is what I believe you are saying jsterm is using now. The original purpose of those sequences appears to have been to allow window manager type operations — move, resize, tile — for which the outside of the window (including the frame) was a more relevant measure than the inside (the drawable part). That's led to different terminals implementing them differently:

1. Size of window including title bar, borders, and other widget frippery. 
2. Size of largest images that can be rendered.
3. Size of largest images that can be viewed.

While WindowOps sometimes "works", it has no clear relationship with sixels and could easily change. For example, @j4james is a big fan of defining sixels as always 10x20 pixels per character, regardless of the underlying screen resolution. While I don't yet agree with him on that approach, at least I can trust that XTSMGRAPHICS will work correctly under his implementation because the response specifies exactly the size of the sixel window.  However, WindowOps has no reason to return a fake resolution meant only for sixel graphics since WindowOps are not sixel specific.

2021-09-29 09:47 UTC, jerch commented
@hackerb9 Thx for your answer.

> It is unambiguous about what it is referring to (sixels) and what it means (visible area).

Well the meaning was not so clear to me in the first place, since xterm always reported 1000x1000. But thats a version issue (v330), newer xterm versions indeed refer to the visible area changing the values on window resizes.

> If a terminal doesn't respond to that, then lsix falls back to the dtterm window manipulations ("WindowOps"), which is what I believe you are saying jsterm is using now.

No, `lsix` always used XTSMGRAPHICS for us, but before with the max allowed sixel canvas dimensions returned, and now with the visible sixel area in the active viewport. We only implement the sequence partially (also max dimensions are artificial for us, as we dont have upper 2-d limits). In that sense the sequence feels weirdly implementation dependent, how xterm solves graphical things internally.

As noted above we have with the CSI t reports a different issue - as a widget library we have no window concept at all, thus cannot fullfill these commands in a sensible way - we dont know anything about the embedding page/window. That is left to integrators, but I am not aware of any ever filling those implementation gaps. Thus I went with partially implementing XTSMGRAPHICS, to have at least one channel to announce the sixel canvas size.

2021-09-29 14:28 UTC, hackerb9 commented
> > It is unambiguous about what it is referring to (sixels) and what it means (visible area).
> 
> Well the meaning was not so clear to me in the first place, since xterm always reported 1000x1000. But thats a version issue (v330), newer xterm versions indeed refer to the visible area changing the values on window resizes.

Ah, I see where the confusion came from. When I first worked with Mr. Dickey on implementing XTSMGRAPHICS, I must have worded my request poorly as he misunderstood me as wanting to know the maximum possible geometry. I think there was only one release of XTerm that behaved that way before it was ironed out.

> No, `lsix` always used XTSMGRAPHICS for us, but before with the max allowed sixel canvas dimensions returned, and now with the visible sixel area in the active viewport. 

Oh, good! That sounds right.

> We only implement the sequence partially (also max dimensions are artificial for us, as we dont have upper 2-d limits). 

Do you mean "partially implemented" in that you cannot respond to a request for maximum dimensions (`Pa=4`)? If so, I suggest returning zero. I'll ask @ThomasDickey to update ctlseqs.ms to add a note that implementations with no maximum graphics geometry may return `Pv=0;0`.

2021-09-29 14:39 UTC, jerch commented
> Do you mean "partially implemented" in that you cannot respond to a request for maximum dimensions (Pa=4)?

Currently implemented:
- read/read_max/change palette limits (max is 4096)
- read/read_max SIXEL canvas geometry (I shimmed read_max as a square of our pixelLimit, e.g. SQRT(pixelLimit), which is as 4096x4096, but we are not really bound to the square shape here)
- everything else returns either `CSI ? Pi ; 1 S` (item error, for ReGIS stuff) or `CSI ? Pi ; 2 S` (action error, like changing sixel geo is not allowed)

> If so, I suggest returning zero. I'll ask @ThomasDickey to update ctlseqs.ms to add a note that implementations with no maximum graphics geometry may return Pv=0;0.

Yes clarifying the correct failstate handling would be helpful.

2021-09-29 22:49 UTC, j4james commented
> For example, @j4james is a big fan of defining sixels as always 10x20 pixels per character, regardless of the underlying screen resolution. While I don't yet agree with him on that approach, at least I can trust that XTSMGRAPHICS will work correctly under his implementation because the response specifies exactly the size of the sixel window.

Just to be clear, when I'm using a 10x20 cell size I intend to respond to all pixel queries with that same virtual resolution. For example, if the text area is 80x24, I would report the `CSI 14 t` screen size as 800x480 pixels, regardless of how many physical pixels that is. The only value that is relevant to an application is the emulated size - the physical screen size is none of their business.

Also I wasn't intending to support the `XTSMGRAPHICS` sequence unless it was absolutely necessary, and so far I've yet to find an application that depended on those size queries. I know notcurses depends on the color query, but I'm hoping there may still be a way to avoid that too.

2021-09-29 23:08 UTC, j4james commented
> `lsix` uses two sources to get width in pixels that can be rendered. The preferred way is to use the XTSMGRAPHICS sequence I suggested to Thomas Dickey and that he implemented in XTerm. It is unambiguous about what it is referring to (sixels) and what it means (visible area).

Just FYI, I know of at least one other terminal (Alacritty) that was also reporting the max image size for `XTSMGRAPHICS` rather than the visible area. If you're relying on that in preference to `CSI 14 t`, your app is probably not going to work on Alacritty. Despite all its problems, I think `CSI 14 t` is still the best choice right now (although as I mentioned earlier, I'd probably query `CSI 16 t` first with `CSI 14 t` as a fallback).

2021-09-30 04:37 UTC, hackerb9 commented
> > For example, @j4james is a big fan of defining sixels as always 10x20 pixels per character, regardless of the underlying screen resolution. While I don't yet agree with him on that approach, at least I can trust that XTSMGRAPHICS will work correctly under his implementation because the response specifies exactly the size of the sixel window.
> 
> The only value that is relevant to an application is the emulated size - the physical screen size is none of their business.

Precisely. That's why, from an application developer point of view, XTSMGRAPHICS is the right sequence to use. If it's available, it is always the proper size for sixel rendering. I can't speak to Alacritty as last I checked it couldn't handle sixels at all, but I'm very glad to see that xterm.js has support for XTSMGRAPHICS.

2021-09-30 10:33 UTC, jerch commented
Imho there is some sexiness in @j4james "virtual unit size" idea. It gives a fixed promise, how graphics pixel sizes will translate to covered cols/rows. It solves the very bad flaw of changing cell coverage after a font resize in all TEs implementing sixel with 1:1 pixel mapping (including the PR here). I partially worked around that for images, that are already in the scrollbuffer (will get rescaled without keeping aspect ratio to preserve coverage), but still - entering the same sequence with a font resize in between will lead to different cell coverage, which is really bad for app side/user experience in terms of deterministic/reliable behavior.
(I still dont follow the idea trying to make that the new default behavior for all TEs for several reasons, but I think we already discussed that to some extend.)

Regarding XTSMGRAPHICS vs. windowOps:
For xterm.js XTSMGRAPHICS is the only reliable way to to announce the geometry, as I dont know, how to talk xterm.js integrators into proper overloading of the needed windowOps counterparts (most take the lib as granted not caring for the details, but that problem is even more evident at other ends like IO encoding or security constraints). In an ideal world `WindowOps.getWinSizePixels` should be enough to derive the visible canvas size. Still XTSMGRAPHICS fills an important gap - the color register (max) size. I understand, that apps might want to get better quality output, if the TE supports more colors than 256, so a queryable setting is the logical consequence (and terminfo would be way too static to hold that info).

2021-09-30 18:27 UTC, hackerb9 commented
> Imho there is some sexiness in @j4james "virtual unit size" idea.

Oh, it definitely has benefits. I have a lot of respect for @j4james as he has unsurpassed knowledge of how sixel systems have worked in the past. That's why I say I don't agree with his 10x20 idea _yet_. I'm completely open to the idea that I'm too dense at the moment and someday I'll realize that he was right all along. However, in the meantime, I see the benefits as limited with high (and permanent) costs.

2021-09-30 19:01 UTC, j4james commented
For the record, I'm not pushing for all TEs to default to 10x20 any more. I've accepted that's not going to happen, and for my own implementation I'm also happy to leave that decision up to the users. But if you want your terminal to function as a VT340 emulator, it's essential that's at least an option. Not all terminals are going to care about VT340 emulation, though, and that's also OK.

However, I would still encourage _apps_ to support 10x20 as a fallback cell size when they can't detect the size through any other means. This seems like a no-brainer, since it won't hurt modern terminals that do reply to size queries, while it'll gain you support in a number of terminals that don't respond to those queries (including the real VT340).

2021-11-02 13:36 UTC, hackerb9 commented
> (Reason: The demo app does not come with any flow control, thus the output from `sixel-bench` would run into xtermjs' OOM parachute.)

I thought sixel-bench waited for a response from the terminal after each frame was rendered. Is xtermjs replying to it asynchronously?

I'm curious if you get the same problem if you use my [sixvid](https://github.com/hackerb9/sixvid) program with [a larger video file](https://github.com/hackerb9/sixvid/blob/main/media/spring.webm) for benchmarking.

```sixvid -b spring.webm```

2021-11-02 14:19 UTC, jerch commented
> I thought sixel-bench waited for a response from the terminal after each frame was rendered. Is xtermjs replying to it asynchronously?

Yes it does to prevent false high throughput rate from aggressive data buffering. Thats what happens in xterm.js if the server part has no proper flow control to stall the data flow, and `sixel-bench` is more or less just a `cat big_pile_of_data` thus would try to move everything with ~1GB/s into xterm.js. To not run into a browser crash, xterm.js has a threshold of 50MB of incomming and not yet processed data. Since the payload of `sixel-bench` is ~150 MB, xterm.js will discard the latter 100 MB, including the cursor report, thus never would respond.

The problem does not exit with `sixvid`.

Note that sixel-bench is pretty dumb - it just dumps data in a single write call through a raw tty (yes this makes ~10% difference). Here I cannot rely on process time itself, as the process might return much sooner than the terminal finished digesting the data, just because of buffering layers on the way to the terminal. So I added the final CPR to get an "ACK" roundtrip.

2021-11-02 15:52 UTC, j4james commented
> Note that sixel-bench is pretty dumb - it just dumps data in a single write call through a raw tty

This is a bit of a problem on some terminals, because they end up processing the whole animation in one chunk and then only render the final frame. You get great performance that way, but you don't get to see much of the video, so I wouldn't consider it a fair benchmark.

I've been using a slightly modified version that writes out each frame in a separate chunk, which I think produces a fairer measure of real-world performance.

2021-11-02 16:36 UTC, jerch commented
> This is a bit of a problem on some terminals, because they end up processing the whole animation in one chunk and then only render the final frame. You get great performance that way, but you don't get to see much of the video, so I wouldn't consider it a fair benchmark.

Well I created that dumb test mainly to test the sixel decoder speed, not for the full chain with screen output. On xtermjs its not even possible to get higher rates than 60-80 fps, the browser would simply refuse to draw faster. While the decoder provides frames at ~250 fps on my machine - so yeah, xtermjs is also cheating here.

On which TEs did you see that? I wonder which metric they use to skip frame output - any clue about that? My guess would be that they do some sort of fps down-scaling on high input pressure, to get more CPU time for data processing. Tbh - a TE completely freezing on that 150MB chunk and just returning the last frame, I would see as broken in the processing vs. output balance. 150MB of instant data is not weird these days anymore, and I'd expect a terminal to still do some output feedback while chewing on the data.

Can you share a few numbers of other TEs? Just curious about the ballpark...

2021-11-02 18:03 UTC, j4james commented
> On which TEs did you see that? I wonder which metric they use to skip frame output - any clue about that?

Well in the Windows console the parser locks the buffer for the entire time that it's processing incoming data, and the renderer can't render anything while the buffer is locked. So if it receives a massive chunk like this, it basically hangs until it's finished processing it all.

Other terminals that behaved similarly included st and rxvt, although possibly not for the same reasons. And Yaft looked like it was dropping lots of frames, but at least it showed more than one.

> Tbh - a TE completely freezing on that 150MB chunk and just returning the last frame, I would see as broken

I totally agree, yes. I've been meaning to file a bug report about this for the Windows console, but I couldn't come up with a simple test case that would demonstrate the problem outside of my sixel implementation. I suspect it's not a very common use case to output a 150MB data stream with a single write operation, but I still would expect the terminal to handle the situation better.

> Can you share a few numbers of other TEs?

I posted a few in the thread here: https://github.com/hackerb9/lsix/issues/49#issuecomment-907719422

But as I noted there, I wouldn't read too much into those results. And bear in mind that I'm testing in a VM.

2021-11-02 18:35 UTC, jerch commented
@j4james Eww, those numbers are indeed quite high (beside VTE, which looks awesome), prolly a side effect of the VM.

Thats what I get for on my machine (old haswell i7 under ubuntu 18):
```
xtermjs    2.98s (39.79 MB/s, 229.81 fps)
mlterm     3.65s (32.53 MB/s, 187.91 fps)
yaft       6.18s (19.18 MB/s, 110.79 fps)  # fb version
xterm      9.7s (12.22 MB/s, 70.6 fps)
WezTerm    225.69s (0.53 MB/s, 3.04 fps)   # no clue going on here
```
I dont know how to get the VTE lib with sixels installed here, so cannot test it.

2021-11-02 19:22 UTC, PerBothner commented
I'm curious how DomTerm compares - it probably depends on which browser/front-end is used.  There is a new [DomTerm.AppImage](https://github.com/PerBothner/DomTerm/releases/tag/2.9.4) which is probably the easiest way to try it on Ubuntu (assuming your system libraries aren't too old).  (This still uses your older pre-WebAssembly version.)

2021-11-02 19:29 UTC, jerch commented
@PerBothner Sure thing. With the app image build I get these numbers:
```
DomTerm    21.13s (5.61 MB/s, 32.41 fps)
```
(Also adding it in the list above.)

2021-11-02 20:31 UTC, PerBothner commented
For comparison, [this snapshot](http://per.bothner.com/tmp/DomTerm-2.9-4-newsixel.AppImage) uses the new version (sixel/dist/decode.esm.js from `npm install sixel`).

If you want to try with different browsers, start the application [with the -B option](https://domterm.org/domterm-application.html#browser-specifier).

The main issue (in terms of using the new decoder) is startup - ideally I'd like to load it lazily (as needed), but that requires some thought.  (The linked-to snapshot loads the decoder on DomTerm startup - which is probably OK.)

2021-11-02 20:37 UTC, hackerb9 commented
> Thats what I get on my machine (old haswell i7 under ubuntu 18):
> 
> ```
> xtermjs    2.98s (39.79 MB/s, 229.81 fps)  # with chrome and webkit, firefox is only at ~26 MB/s
> mlterm     3.65s (32.53 MB/s, 187.91 fps)
> yaft       6.18s (19.18 MB/s, 110.79 fps)  # fb version
> xterm      9.7s (12.22 MB/s, 70.6 fps)
> DomTerm    21.13s (5.61 MB/s, 32.41 fps)   # with JS based decoder
> WezTerm    225.69s (0.53 MB/s, 3.04 fps)   # no clue wots going on here
> ```

Xtermjs seems quite impressive! What were the FPS when you ran sixvid?

> Got `sixvid` working with an mp4 file - yes it has the same OOM parachute issue after ~10s of running. But note - thats nothing you should worry much from app side about, its the demo app for xterm.js missing proper flow control/blocking semantics.

Out of Memory on *unprocessed* data? This should not happen with Sixvid. It waits until the terminal has responded to an inquiry, meaning xterm.js has finished processing the sixel data, before sixvid sends the next frame. That may give slightly lower FPS due to network latency, but I think it would be a more useful measure of a sixel engine's performance. It also means, unless you're doing some wacky out of order processing, there is no way sixvid should ever trigger your OOM parachute.

Even if you run `sixvid -b -e media/spring.webm` (which creates over 300M of sixel data), only one frame of data is in the pipeline at a time. Each frame of 2048 bx 858 pixels is only about half a megabyte, so the 50MB cap should have been way more than enough.

It's quite possible I've got something wrong here, but are you sure the OOM is getting triggered correctly?

2021-11-02 20:43 UTC, jerch commented
@PerBothner This one does not load for me:

```
./DomTerm-2.9-4-newsixel.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./DomTerm-2.9-4-newsixel.AppImage)
./DomTerm-2.9-4-newsixel.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./DomTerm-2.9-4-newsixel.AppImage)
./DomTerm-2.9-4-newsixel.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./DomTerm-2.9-4-newsixel.AppImage)
```
I have this version installed:
```
(Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27
```

@hackerb9 Ok gimme 1h to finish work, then I will test again with your file converted to mp4 (seems my toolchain wont digest webm directly). The file I was testing before is sintel.mp4 (the same I pulled the data for `sixel-bench from), with much different frame size (so the fps wont help here much), well and that stopped after 10s. Needs some investigation...

2021-11-02 20:55 UTC, hackerb9 commented
> @PerBothner Sure thing. With the app image build I get these numbers:
> 
> ```
> DomTerm    21.13s (5.61 MB/s, 32.41 fps)
> ```
> 
> Note thats still slightly faster than `mpv` created the stream (imho was ~4.5 MB/s), thus DomTerm qualifies for video playback at that size.

Video can be extremely bursty since certain scenes compress well and others not at all. You can see this in sixvid as the FPS go up and down during video playback. That means a sixel engine which is right on the line in the average case would likely have extra CPU cycles to spare some of the time and be unable to keep up some of the time.  

[Note to self: I should add minimum FPS to the statistics shown by sixvid.]

2021-11-02 21:07 UTC, hackerb9 commented
> @hackerb9 Ok gimme 1h to finish work, then I will test again with your file converted to mp4 (seems my toolchain wont digest webm directly). The file I was testing before is sintel.mp4 (the same I pulled the data for `sixel-bench from), with much different frame size (so the fps wont help here much), well and that stopped after 10s. Needs some investigation...

No rush. I converted spring.webm to spring.mp4 in the sixvid/media directory. You should now be able to do:

    ./sixvid -b -e media/spring.mp4

After it unpacks everything into /tmp (which can take a while if you don't have many CPU cores) it'll start the clock on benchmarking. When you quit it'll show you the overall FPS.

2021-11-02 21:23 UTC, PerBothner commented
I rebult [this version](https://per.bothner.com/tmp/DomTerm-2.9.4-f33.AppImage) on an older laptop running Fedora 33. However, I realize that may not help - it's not old enough ... Even my ancient Fedora 30 laptop was updated recently enough to be running libc 2.29 ...

Maybe it's time you updated your OS?

2021-11-02 22:34 UTC, jerch commented
@PerBothner Yep, that version works for me and gives (with Chrome):
```
16.5s (7.19 MB/s, 41.52 fps)
```

2021-11-02 22:43 UTC, jerch commented
@hackerb9 Sweet that worked, giving me:
- ~130 fps with DOM renderer
- ~120 fps with canvas renderer
- ~105 fps with webgl renderer

2021-11-02 23:00 UTC, PerBothner commented
Thanks for trying out DomTerm.

I tried running sixvid.  Nyatocat got upto about 200 fps. spring.mp4 didn't print a number (even after `-b -e`) but seemed a rather slower than it should be.

It does look like increasing buffer size (at least the buffer in the server for reading pty output) might be a good idea.  However, I do get occasional exceptions: `Failed to construct 'ImageData': The input data length is not equal to (4 * width * height).` I don't know (yet) what causes this - data loss, corruption, a logic error, or something else.

2021-11-02 23:02 UTC, jerch commented
> However, I do get occasional exceptions: ...

With the new or the old lib version?

2021-11-02 23:17 UTC, PerBothner commented
I get exceptions with the new version.

This is the logic - maybe you can see something wrong:

            let six = window.SixelDecoder;
            six.init();
            six.decode(bytes, 1);
            let w = six.width, h = six.height;
            let next = ...;
            const reuseCanvas = next instanceof Element
                  && next.tagName == "CANVAS"
                  && next.width >= w && next.height >= h;
            const canvas = reuseCanvas ? next
                  : document.createElement("canvas");
            if (! reuseCanvas) {
                canvas.setAttribute("width", w);
                canvas.setAttribute("height", h);
            }
            const ctx = canvas.getContext('2d');
            const idata = new ImageData(new Uint8ClampedArray(six.data32.buffer), w, h);
            ctx.putImageData(idata, 0, 0);

2021-11-02 23:41 UTC, jerch commented
@PerBothner Ah see, yepp the intermediate `Uint8ClampedArray` must be clamped to `4 * width * height`. Maybe try this:
```typescript
new ImageData(new Uint8ClampedArray(buffer, 0, width * height * 4), width, height)
```
(Reason: The lib returns a borrowed Uint32Array, which might have a bigger buffer underneath from a previous run, then it will not fit into the `ImageData` without the slice on the `.buffer`.)

2021-11-03 02:20 UTC, PerBothner commented
@jerch Your proposed seems to fix the problem.

_"Btw that -B switch is pure magic, no clue how you do that, very impressive."_

The `domterm` command starts (if need be) a server that (among other things it does) is an http+WebSockets server.  When a new terminal is requested, the server forks a shell in the normal TE way. It creates a custom URL that points back at itself, and includes in the hash-value a unique number for the shell process. It also forks a front-end/browser, as specified by the `-B` option, passing it that unique URL on the browser command-line. The browser gets a skeletal HTML file that just loads a bunch of JavaScript from the server, initializes the session, and opens up a WebSockets connection with the server, passing back the shell process number, so the server can associate the connection with the correct process.  Process input/output is sent over this WebSockets connection, as are internal server/browser notifications and requests.

There is of course more to it (`domterm` includes more-or-less the functionality of `tmux`), but that's the basic idea.

If you're interested in hooking up xterm.js with the domterm server, that is quite reasonable.  In fact there is code in the domterm sources to support just that; however I haven't been maintaining it.  It should even be possible for the same server to manage at the same time both DomTerm sessions (for rich text, html, images etc) and xterm.js sessions (for higher speed and perhaps some other features), though I haven't tried that.

2021-11-03 10:57 UTC, jerch commented
@PerBothner Ah ic, so DomTerm basically provides it own terminal server infrastructure, that holds the pty connections and uses installed browsers as frontend directly spawned from there. That a very sensible approach and gives you control over things xtermjs kinda lacks as pure frontend component. We get tons of issues regarding proper page embedding, and many integrations get the server part wrong missing properly delegated flow control, encoding handling or securing the websocket transmission (including our demo, but thats only meant to be used for development of xtermjs itself, ppl should not simply c&p that to their production envs).

2021-11-03 11:31 UTC, PerBothner commented
@jerch The current `domterm` backend is a much-rewritten fork of [ttyd](https://github.com/tsl0922/ttyd), which uses xterm.js. However. with `domterm` has a lot more bells and whistles.

2021-11-05 01:00 UTC, hackerb9 commented
> Out of Memory on _unprocessed_ data? This should not happen with Sixvid. It waits until the terminal has responded to an inquiry, meaning xterm.js has finished processing the sixel data, before sixvid sends the next frame. [....] there is no way sixvid should ever trigger your OOM parachute.

Mea culpa! I just noticed that the `main` branch of sixvid did not actually behave the way I described. It indeed was simply splatting frames as fast as possible until you ran out of memory. I've merged the changes to fix that.

If you would, please try again with the current version of [sixvid](https://github.com/hackerb9/sixvid). It should not trigger the OOM parachute. I'm curious what the FPS results will be now that they will be accurate.

2021-11-06 19:01 UTC, jerch commented
@hackerb9 Eww, now we talking about "a long line" kicking in - gives me 51 fps on DOM with intel embedded graphics.

2021-11-11 22:52 UTC, jerch commented
Converting back to draft to resolve these issues before going live:
- remove private / shared palette separation, instead always carry entries forward
- think about a less invasive palette reset than RIS/DECSTR (maybe hook into some XTSMGRAPHICS action)
- transit to VT340 cursor positioning, remove all others
- update tests & docs regarding changes

2021-12-08 15:15 UTC, jerch commented
Closing this PR and #3488, as it is unlikely to be added in near future.

State: Beside the low level sixel issues above (see last comment) it is a working condition. It can easily be extended by other image protocols using the same internal image storage handling once there is a good candidate. Also see #3488 for remaining issues for a neater overall integration with xterm.js.

In theory this PR can be used from another repo to build the addon independently. But be aware, that it heavily relies on internal data structures (mainly for perf and non-duplication reasons), thus might create quite a high maintenance overhead to keep it on par with new xterm.js versions, which somewhat qualifies it to keep in main repo. At least it can be used as a source of ideas for similar approaches/extensions of xtermjs.

2021-12-08 15:15 UTC, closed without merging

2021-12-08 18:06 UTC, hackerb9 commented
Oh, that's too bad. I was looking forward to using sixel graphics in xtermjs. Will this affect that fork (I forget the name, but it used a terminal server so one could connect from any web browser) that used this sixel implementation?

2021-12-09 13:23 UTC, jerch commented
@hackerb9 Gimme a few days and I will see if an external repo is a viable workaround (depends on how much can be automatized on new releases of the main repo, and whether needed shims grow too big).

2021-12-11 03:38 UTC, hackerb9 commented
Yeah, DomTerm was what I was thinking of. Is there a github page for the sixel lib it uses?

2021-12-11 13:44 UTC, jerch commented
@hackerb9 Yes you can find the sixel lib here https://github.com/jerch/node-sixel (disclaimer - I am the author, and it is still WIP. The decoder has some test coverage, and I'd consider the tested features as beta quality. It still lacks true paletted mode as in terminal vs. printer mode, which I am unsure to add at all. The encoder is mostly untested, more in early alpha state.)

2021-12-11 20:34 UTC, PerBothner commented
The [DomTerm master](https://github.com/PerBothner/DomTerm/) (as of November 3) uses the new node-sixel 0.15 implementation.  The minimized source is in `hlib/sixel-decode.js`.

(The DomTerm-2.9.4 release uses the old sixel implementation.  I hope to make a DomTerm-2.9.5 after some more testing and polishing.)

2021-12-30 23:44 UTC, jerch commented
@hackerb9 Here the experimental addon repo: https://github.com/jerch/xterm-addon-image.