fix: fit addon proposing infinite dimensions
xtermjs/xterm.js pull request #3088
Opened 2020-09-10 16:33 UTC by UziTech

fixes https://github.com/xtermjs/xterm.js/issues/3085#issuecomment-690318136

2020-09-10 19:41 UTC, Tyriar requested changes
Looks like the new test is failing in CI?

2020-09-10 19:41 UTC, Tyriar commented on addons/xterm-addon-fit/test/FitAddon.api.ts
> +      await loadFit(0, 0, false);
Should there also be a test for `loadFit(0, 0, true)`?

2020-09-10 19:59 UTC, UziTech commented on addons/xterm-addon-fit/test/FitAddon.api.ts
> +      await loadFit(0, 0, false);
I'm not sure how to test this. Changing the terminal div to `display: none;` makes `fit()` fail in x-terminal but not in the tests. I'll have to dig deeper on x-terminal and see what is making the dimensions equal to 0.

2020-09-10 20:18 UTC, UziTech commented on addons/xterm-addon-fit/test/FitAddon.api.ts
> +      await loadFit(0, 0, false);
I found the issue. It seems that this issue only happens when the termina container div is hidden when it is attached to the terminal so the renderer doesn't have a chance to create a width before calling fit.

Now to figure out how to hide the terminal in the tests before attaching it to the terminal.

2020-09-10 21:36 UTC, UziTech commented
It looks like this solves the issue of fit erroring when the terminal is attached to a hidden div but there are still other things that go wrong with the renderer. I will create another PR to address those issues.

2020-09-10 21:50 UTC, Tyriar commented on addons/xterm-addon-fit/test/FitAddon.api.ts
> +}
We can instead move the `openTerminal` call into a `beforeEach` so the standard setup happens for each test, it's a pretty cheap action.

2020-09-10 21:50 UTC, Tyriar commented on addons/xterm-addon-fit/test/FitAddon.api.ts
> +        await page.evaluate(`document.querySelector('#terminal-container').style.display=''`);
This display change could be moved into the `beforeEach` instead, that's always seemed safer than relying on try/finally to me to handle resetting things.

2020-09-11 05:54 UTC, UziTech commented
I created #3089 to handle the other issues created when the terminal is attached to a hidden div.

2020-09-11 12:25 UTC, Tyriar approved these changes

2020-09-11 12:25 UTC, merged