Feature/xterm addon serialize restore layout and cursor
xtermjs/xterm.js pull request #3101
Opened 2020-09-16 07:01 UTC by mmis1000

This pull request.

- Fix #3098
- Fix #3090
- Implement cursor position restoration
- Add a test util to `xterm-addon-serialize` that export the screen buffer state as plain object for testing.

Tested on a few full screen console programs to make sure the layout is identical to original state.
- htop
- vim
- nano
- sl

More unit test required

2020-09-16 13:34 UTC, mmis1000 commented
WTF, how do the same byte computation result in -0 instead of 0 in firefox?

2020-09-16 13:46 UTC, mofux commented
I didn't even know this was possible. `0` and even `Infinity` can be signed!
And guess what, while `-0 === 0`, `-Infinity !== Infinity`:

<img width="188" alt="Screenshot 2020-09-16 at 15 44 05" src="https://user-images.githubusercontent.com/2785983/93345886-a4cadc00-f833-11ea-8957-5c99a5d1decd.png">

2020-09-16 13:53 UTC, mmis1000 commented
It looks like either xtermjs did something undefined behavior during computation (but i think js seldom do that?), or the firefox implement js incorrectly somewhere.

2020-09-16 18:53 UTC, jerch commented
@mmis1000 
For equality check of buffer content it might be better to do the JSON comparison on the private `Bufferline` objects, as they are the source of truth for that (it is ok to access privates in test cases). This has the benefit of revealing potential bugs in API mapping code as well.

2020-09-17 14:14 UTC, mmis1000 commented
@jerch 
That probably won't work well currently, I guess?
Because I haven't handle the `isWrapped` yet (thus this is currently a draft)
And there is indeed some data in BufferLine that are not available to public api (the IExtendedAttrs).

BTW, it seems there is no way to copy a IBufferCell over another. But to handle the BCE, it seems I need to keep the cursor style as background style to decide whether ECH or not. Should I just implement one fake class with it?

2020-09-17 15:48 UTC, jerch commented
Ah ok, yeah true. Sorry thought that is handled already.

2020-09-18 14:22 UTC, mmis1000 commented
This should do a complete layout restore now (include line wrap).
The code probably still need some clear up for the left over during try and error.

About the performance, it handles about 5000 rows in 200ms on chrome.
(I am not sure whether it is fast enough. But given this is not designed to run on every tick, it is probably fast enough?)

2020-09-18 15:57 UTC, jerch commented
@mmis1000 Imho speed is an issue for a serializer (as it has to be blocking to obtain a correct state). We already had quite the discussion about it when reshaping the buffer API (see #2369). The fastest serializer version I was able to find for basic serialization (doing only colors and flags) is at ~25MB/s for final string output (doing 100k scrollbuffer in roughly ~1s for single unoptimized run). Much higher than that is almost impossible with JS, as pure string concatenation power of JS gets the limiting factor. See https://github.com/xtermjs/xterm.js/pull/2369#issuecomment-526160555, there is also a private where you can look at the code. But note that I used very different code than the final serializer.

Roughly estimated your current version should be somewhat around ~2MB/s, prolly 4MB/s for optimized runs.

2020-09-18 17:36 UTC, mmis1000 commented
![圖片](https://user-images.githubusercontent.com/2993977/93625503-a56e9880-fa14-11ea-8770-20e58e71cc62.png)
I actually test for it a bit early today.

But the result it weird.

Profiler shows that most time was used on the `_nextCell` itself (the self is 81.3ms).
Even the complex check at line end use less time than it. (the 'self' is 1.3ms)
But the `_nextCell` is just a bunch of if else used to update current cursor style/position or `_currentRow`.

The only object it create is a array to hold sgr sequence which isn't different from the original code.
Do access `this` itself enough to slow down the v8?
Or due to string concatenation?

2020-09-19 07:41 UTC, jerch commented
@mmis1000 Yes profiling JS is abit cumbersome, as all profilers I know do only sampling (snapshotting into callstack from time to time). Furthermore the JS engine might decide to inline hot functions, thus you would never see them being called, instead they add on top of the caller's time. The latter gets really annoying if you try to optimize hot paths, as they simply wont show up in the profiler records anymore.

Hand-waving rules I found to be working with V8:
- avoid object re-creation at any cost, instead resort to re-using previous ones (otherwise GC will kill perf)
- never change object shape by adding or removing properties (it will de-opt the whole function forever)
- deep nested branching is bad (similar as in C), this actually applies here, as a good JS engine will try to JIT hot functions
- Slicing logic into several sub functions is good, this gives the engine the freedom to decide, whether that particular logic is hot and should be inlined.

Inlining on its own is a tough topic and might be handled very different by various engines/optimizers. I only tested this with V8/crankshaft years back, but my guess is, that most ideas still apply to newer optimizers as well. For stable inlining it is important, that the arguments and the return values never change the types (e.g. if you expect a string as argument it is better to deal with an empty string instead of `undefined`, `null`, whatsoever). Ideally those functions are real functions in a functional programming sense (re-entrant), otherwise the optimizer might bail out later on for non obvious reasons. This can be achieved by a simple rule of thumb - calculate your function result only from arguments to avoid side effects while keeping the return type stable. Furthermore the function to be inlined should not be overly long in code size, otherwise the optimizer would not try to inline it at all (was about ~600 chars back then).

About string creation/concat:
Yes thats hard to do for JS. What looks nice and easy on code level, is a tough thing to achieve for the engine underneath in a speedy manner. Esp. there is a big difference between engines in loop-concat like `for (c in arr) res += c;` and array string joining as `arr.join('')`. The latter is much faster in V8, while loop-concat sucks big time. For Firefox it is the opposite where the loop is twice as fast compared to array join suggesting they have a special optimization for that.
I did not dig much further into this, as I mostly tested on V8, thus went with array join most of the time. Overall the array join is nearly the same on both, thus gives the most reliable results without penalizing one engine too much. It might be possible to speed this up further by collecting codepoints first and postponing the real string creation (idk, did not test that, also I'd see this as a premature optimization, as I would not expect much of a speed gain here).

2020-10-24 21:50 UTC, jerch commented
@mmis1000 Is this in a review state yet or do you need some more bits/info to be addressed?

2020-10-25 03:02 UTC, mmis1000 commented
@jerch This is already in a review state. The part I mostly concern about is performance, but that part of code (create a array and join) is already existed current code base. So I think it is better to left it for future pr instead of this.

2020-10-30 16:39 UTC, Tyriar commented
Hoping to do a release next week, I'll try review before then.

2021-01-22 17:52 UTC, Tyriar requested changes
Looks good and seems to work, a few comments. Sorry about the delay, I was out of work for a bit.

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    };
Can this util be moved into the test file?

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +  private _diffStyle (cell: IBufferCell, oldCell: IBufferCell): number[] {
```suggestion
  private _diffStyle(cell: IBufferCell, oldCell: IBufferCell): number[] {
```

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    const cursorMoved =  (realCursorRow !== this._lastCursorRow || realCursorCol !== this._lastCursorCol);
```suggestion
    const cursorMoved = (realCursorRow !== this._lastCursorRow || realCursorCol !== this._lastCursorCol);
```

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +  constructor (private _cell: IBufferCell) {}
```suggestion
  constructor(private _cell: IBufferCell) {}
```

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +export class MyBufferCell implements IBufferCell {
It's not clear what the purpose of this class is? It kind of looks like an adapter but it just exposes the same interface `IBufferCell`, any reason the addon doesn't just use that?

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +import { IBufferCell } from 'xterm';
Let's add the copyright notice

2021-01-22 17:52 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +  constructor(private _buffer1: IBuffer,private _terminal: Terminal) {
```suggestion
  constructor(private _buffer1: IBuffer, private _terminal: Terminal) {
```

2021-01-23 02:06 UTC, mmis1000 commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +export class MyBufferCell implements IBufferCell {
The only reason for a separate class is because in line it directly will be messy, there are too many fields and methods.

It can be also refactored to a function that returns IBufferCell objects.

2021-01-23 02:12 UTC, mmis1000 commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    };
I am not really sure. 
Because this function need to be called in the browser context.
Is there a way to side loading script into browser context of tests?

2021-01-23 03:59 UTC, mmis1000 commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +export class MyBufferCell implements IBufferCell {
Remove it in favor of just remember where was the _cursorStyle comes from

2021-01-23 06:28 UTC, mmis1000 commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    };
Figured out how to move it into separate file in test

2021-01-23 06:28 UTC, mmis1000 commented on addons/xterm-addon-serialize/src/MyBufferCell.ts
> +import { IBufferCell } from 'xterm';
File no longer exist

2021-01-25 03:31 UTC, mmis1000 commented
@Tyriar 
I removed the separate dummy buffer cell in favor of just remember where did the cursor style comes from.
And also, the test utility is moved into separate file. (Is it proper to put it in the test directory?)

I am not sure whether there is some edge case that I didn't handle correctly.
Probably it needs a fuzz test someday to check whether it will choke on some specified pattern.

2021-01-28 15:00 UTC, Tyriar commented
@mmis1000 busy with VS Code endgame, I plan on getting to this next week.

2021-02-01 17:35 UTC, Tyriar approved these changes
Thanks @mmis1000, this works great. For the test change I moved it into `page.evaluate`, I mainly just wanted it inside the test/ folder

2021-02-01 17:46 UTC, merged

2021-05-23 10:00 UTC, cyrus-and commented
Hi, sorry for bumping an old thread but, how does the cursor restoration work? I mean, it *just* works or do I have to enable it somehow? I don't see any difference in my use case (except for the background restoration part, which works as expected).

2021-05-23 10:43 UTC, cyrus-and commented
Never mind, it was an issue on my side. Sorry for the noise.