Using putout linter on xterm codebase part 2
xtermjs/xterm.js pull request #3133
Opened 2020-10-19 05:13 UTC by coderaiser

Latest PR (https://github.com/xtermjs/xterm.js/pull/2953) was successfully merged, so I decide to do more checks with updated version of [putout](https://github.com/coderaiser/putout) and discuss improving codebase with rules approved earlier and I can disable any of rules that not fits to current code style :).

So here is config:

```json
{
    "rules": {
        "strict-mode": "off",
        "remove-useless-spread/object": "off",
        "remove-console": "off",
        "remove-unused-variables": "off",
        "remove-useless-variables": "off",
        "apply-destructuring": "off",
        "merge-if-statements": "off",
        "convert-apply-to-spread": "off",
        "convert-math-pow": "off",
        "convert-for-to-for-of": "off",
        "convert-template-to-string": "off",
        "remove-empty": "on",
        "convert-index-of-to-includes": "on",
        "convert-for-each-to-for-of": "on",
        "apply-shorthand-properties": "on",
        "apply-numeric-separators": "on"
    }
}

2020-10-24 15:32 UTC, jerch requested changes
Thx for looking into that - looks good to me for most changes, but a few remarks below.

2020-10-24 15:32 UTC, jerch commented on src/browser/Terminal.test.ts
> +      this.timeout(10_000);  // This is needed because istanbul patches code and slows it down
I think this notation is still way too new and we should not yet rely on it. Same goes for the other occurrences.

2020-10-24 15:32 UTC, jerch commented on src/common/Platform.ts
> +export const isFirefox = !!userAgent.includes('Firefox');
Since `.includes` already returns a boolean, the `!!` type conversion gets redundant.

2020-10-24 15:32 UTC, jerch commented on src/common/tsconfig.json
> +      "es2017"
Whats the reason for ES2017? I have no strong obligations against ES2017, but would not like to change that for a non-obvious reason. Being more vanilla/old-school is not a bad thing in terms of supported targets while maintaining the same functionality.

2020-10-24 21:53 UTC, coderaiser commented on src/common/tsconfig.json
> +      "es2017"
The thing is `es2017` needs to be set to have ability to build files that contains `includes` with `typescript`.

2020-10-24 21:58 UTC, jerch commented on src/common/tsconfig.json
> +      "es2017"
@coderaiser :+1:  Ah ok, well I'm fine to move on to ES2017 then, but would like to hear @Tyriar and @mofux 's opinion in this regard first.

2020-10-30 16:37 UTC, Tyriar requested changes

2020-10-30 16:37 UTC, Tyriar commented on src/common/tsconfig.json
> +      "es2017"
My only thought is if we commit to this, that we also update all the other tsconfig.json files so they're not inconsistent. Since we only target evergreen browsers, I think this is safe to do?

2020-10-30 18:39 UTC, jerch commented on src/common/tsconfig.json
> +      "es2017"
@Tyriar I think it will change certain output shims. Imho our codebase is not really affected by that (Was it around generators? Or promises with async/await? Cant remember...)

2020-10-30 18:43 UTC, Tyriar commented on src/common/tsconfig.json
> +      "es2017"
Well that's for the target, the lib is just which typings to include. I see there is a lib `"ES2016.Array.Include"`, that sounds like exactly what we want without needing to think about changing es2015.

2020-10-31 13:14 UTC, coderaiser commented on src/common/tsconfig.json
> +      "es2017"
@Tyriar, I updated `browser/tsconfig.json`. Should I update`tsconfig.json` in addons directories? They don't have lib option right now.

2020-10-31 18:47 UTC, Tyriar commented on src/common/tsconfig.json
> +      "es2017"
@coderaiser no need if they don't use lib, does `ES2016.Array.Include` work instead of `es2017`?

2020-11-01 07:47 UTC, coderaiser commented on src/common/tsconfig.json
> +      "es2017"
@Tyriar yes, it works, just pushed

2020-11-02 13:15 UTC, Tyriar approved these changes
Thanks for the clean up 🙂

2020-11-02 13:15 UTC, merged