Make alt+click behavior configurable
xtermjs/xterm.js pull request #3181
Opened 2020-11-21 01:54 UTC by awmottaz

Adds a new Boolean option `altClickMovesCursor` which enables/disables the alt+click behavior that moves the prompt cursor to the location of the mouse.

Closes #3145

2020-11-21 01:57 UTC, awmottaz commented
Just a note: I am working on adding a couple of tests:

- alt+click moves the cursor when option is enabled
- alt+click does not move cursor when option is disabled
- option is enabled by default

But I thought I would push up the PR with the implementation right away to get feedback on that.

2020-11-21 03:42 UTC, awmottaz commented
I am struggling with writing tests for this. It appears that interaction with the DOM is explicitly disabled in the `TestSelectionService`. Adding it back in causes lots of issues. Any advice for how to write these tests? Or would you consider this contribution without tests?

2020-11-21 14:34 UTC, matthias-ccri commented
Just wondering if we want to make this a breaking change. Before, the alt-click behavior was enabled by default. With this change it's disabled by default and must be enabled.

It may be that we should disable it; I don't know, but I thought I'd ask.

2020-11-21 20:21 UTC, awmottaz commented
> Just wondering if we want to make this a breaking change. Before, the alt-click behavior was enabled by default. With this change it's disabled by default and must be enabled.

I meant for this not to be a breaking change. I set the default value to `true`. Is there more I need to do to ensure it's enabled by default?

https://github.com/xtermjs/xterm.js/pull/3181/files#diff-d156a9a2b47b63f41faf54f727fc23ffd0ee8fa672cbfe8b77ce20dffa846082R53

2020-11-22 00:11 UTC, mofux requested changes
Thanks for the contribution! Looks good so far, IMO no additional tests for this feature are required. There are still some missing bits though:

Please add the new option here:
https://github.com/xtermjs/xterm.js/blob/84fa6be370f9a6b6ced5ece234d2ed1046f0229e/src/browser/public/Terminal.ts#L173

and here:
https://github.com/xtermjs/xterm.js/blob/84fa6be370f9a6b6ced5ece234d2ed1046f0229e/src/browser/public/Terminal.ts#L185

and here:
https://github.com/xtermjs/xterm.js/blob/84fa6be370f9a6b6ced5ece234d2ed1046f0229e/src/common/services/Services.ts#L186

2020-11-22 16:01 UTC, awmottaz commented
Thanks @mofux, I made all of your requested changes

2020-11-23 16:00 UTC, matthias-ccri commented
@awmottaz I see, my mistake! 
Thanks for the contribution.

2020-11-24 17:03 UTC, Tyriar approved these changes

2020-11-24 17:03 UTC, Tyriar commented on typings/xterm.d.ts
> +     */
```suggestion
    /**
     * If enabled, alt + click will move the prompt cursor to position
     * underneath the mouse. The default is true.
     */
```

2020-11-24 17:04 UTC, Tyriar commented
Thanks @awmottaz 🙂

2020-11-24 17:04 UTC, merged