Avoid innerHTML usages
xtermjs/xterm.js pull request #3190
Opened 2020-12-02 16:28 UTC by jrieken

This PR tackles most (all?) innerHTML usages inside xterm.js so that it can used in a trusted types compliant context. Fixes  https://github.com/xtermjs/xterm.js/issues/3189 for more details.

2020-12-06 20:08 UTC, jerch requested changes
Thx for looking into this. :+1: 

Imho there is one little bug hidden in the changes (see below).

2020-12-06 20:08 UTC, jerch commented on src/browser/AccessibilityManager.ts
> +          element.innerText = '\u00a0;';
Shouldn't this be just `'\u00a0'` without the `;` (as `&nbsp;` is the HTML enitity for that byte value)?

2020-12-09 08:58 UTC, jrieken commented on src/browser/AccessibilityManager.ts
> +          element.innerText = '\u00a0;';
Yes - you are right. That was a copy&paste mistake

2020-12-09 09:09 UTC, jrieken commented
fixed the bad whitespace replacement

2021-01-02 18:21 UTC, jerch approved these changes
LGTM :+1:

2021-01-02 18:21 UTC, merged