emit onScroll events when user is scrolling
xtermjs/xterm.js pull request #3205
Opened 2021-01-05 22:28 UTC by schrej

This changes the onScroll handler of the Viewport to no longer suppress onScroll events when the Viewport is scrolled by the user. I've removed the argument in the Viewport as its no longer needed.

fixes #3201

2021-01-07 18:10 UTC, Tyriar requested changes

2021-01-07 18:10 UTC, Tyriar commented on src/browser/Viewport.ts
> +    this._scrollLines(diff);
Without the suppress, this ends up calling `Terminal.onScroll` which calls `Viewport.syncScrollArea`. It's needed to avoid the cyclic refreshing there. A new event may be needed.

2021-01-07 18:11 UTC, Tyriar commented on src/browser/Viewport.ts
> +    this._scrollLines(diff);
To clarify; a new internal event (src/browser/Terminal.ts), not a new API event (src/browser/public/Terminal.ts)

2021-01-08 21:00 UTC, schrej commented on src/browser/Viewport.ts
> +    this._scrollLines(diff);
I've taken another look, you're of course right. This cyclic refreshing then even causes some graphical glitches. A new internal event would be almost identical to the onScroll event though.

I see two options to solve this in a clean way:

- Extend the onScroll event emitter to contain a boolean as it's second value (which is unused right now) to indicate whether the event originated from the Viewport.
- Use a richer `ScrollEvent`s that include information about the source

Both cases will require a second EventEmitter for the public facing onScroll method that "forwards" the events to avoid an API change.

2021-01-11 17:34 UTC, Tyriar commented on src/browser/Viewport.ts
> +    this._scrollLines(diff);
Could you put together the change for the second option? That's probably the best as it's more maintainable.

2021-01-12 22:38 UTC, schrej commented on src/browser/Terminal.ts
> +    this._onScroll.fire({position: this.buffer.ydisp, source: ScrollSource.TERMINAL });
Or would you prefer a proper class for this?

2021-04-01 15:40 UTC, Tyriar commented on src/browser/Terminal.ts
> +    this._onScroll.fire({position: this.buffer.ydisp, source: ScrollSource.TERMINAL });
Interface is fine

2021-04-01 19:11 UTC, merged

2022-06-15 19:41 UTC, AndreSilva1993 commented
Curious about this as I have the xterm v4.9.0 and scrolling the terminal does not fire the `onScroll` event. Do I need to do anything?

2022-06-16 00:57 UTC, Tyriar commented
@AndreSilva1993 that was a long time ago so I don't remember 😅. You should probably update as I don't think there are any breaking changes, if your build does break when updating it's normally just making TS types stricter.

2022-06-16 08:32 UTC, AndreSilva1993 commented
I must've been sleeping when I wrote this, we're on the 4.18.0 already 🤦‍♂️

2022-06-16 15:11 UTC, Tyriar commented
You're right this doesn't happen anymore, it's only firing `onScroll` when the "base" changes. Can you create an issue if one doesn't exist since that doesn't match up with the docs https://github.com/Tyriar/xterm.js/blob/fb950fcbe54b392c6aef268b899c33bcc9c3122f/typings/xterm.d.ts#L862-L867

2022-06-16 15:43 UTC, AndreSilva1993 commented
Here's the [issue](https://github.com/xtermjs/xterm.js/issues/3864).