Add hover and leave callbacks for linkprovider
xtermjs/xterm.js pull request #3233
Opened 2021-01-25 23:53 UTC by marvinthepa

Fixes #3056.

I guess this needs another breaking change when LinkMatchers are removed, to replace the `ILinkMatcherOptions` argument to the `WebLinksAddon` constructor with something not referring to LinkMatchers..

2021-02-02 20:49 UTC, Tyriar requested changes

2021-02-02 20:49 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
I think it would be better if we has link provider-specific options:

```ts
export interface ILinkProviderOptions {
  hover?(event: MouseEvent, text: string): void;
  leave?(event: MouseEvent, text: string): void;
}

...

private _options: ILinkMatcherOptions | ILinkProviderOptions = {}
```

2021-02-02 20:49 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinkProvider.ts
> +  private _addCallBacks(links: ILink[], hover?: (event: MouseEvent, uri: string, location: IViewportRange) => void, leave?: (event: MouseEvent, uri: string) => void): ILink[] {
```suggestion
    callback(this._addCallbacks(links, this._options.tooltipCallback, this._options.leaveCallback));
  }

  private _addCallbacks(links: ILink[], hover?: (event: MouseEvent, uri: string, location: IViewportRange) => void, leave?: (event: MouseEvent, uri: string) => void): ILink[] {
```

2021-02-02 20:49 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinkProvider.ts
> +    return links.map((link): ILink => {
I think we can avoid the type annotation?

```suggestion
    return links.map(link => {
```

2021-02-02 20:49 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinkProvider.ts
> +      return { ...link, leave, hover: hoverCallback };
I think we're safe here to add the props directly to the same object, rather than creating a new one?

```suggestion
      link.leave = leave;
      link.hover = hoverCallback;
      return link;
```

2021-02-02 21:57 UTC, marvinthepa commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
> ```ts
> private _options: ILinkMatcherOptions | ILinkProviderOptions = {}
> ```

Do you want to allow both types as arguments on `WebLinksAddon`?
I am afraid my knowledge of typescript is not sufficient to get that to compile.

Or do you want to allow both as argument to `WebLinksProvider`?

As a suggestion, I will push an alternative that I could get working:
Converting from `ILinkMatcherOptions` to `ILinkProviderOptions` in `WebLinksAddon.activate`.
If you do not like that I am afraid I will need a little help.

2021-02-02 22:00 UTC, marvinthepa commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      };
When linkmatchers are removed, this can go and the ILinkMatcherOptions argument can be replaced by ILinkProviderOptions..

2021-02-03 13:19 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
I don't think TS would fuss about this because all properties on both interfaces are optional, so essentially any object matches the interface, it should however provide nice intellisense when something is using the API.

2021-02-03 13:27 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
Ah I see the problem you were hitting now, I'll push a fix using a cast as it should be safe to do that since the interfaces only have optional props.

2021-02-03 13:28 UTC, Tyriar approved these changes

2021-02-03 13:31 UTC, marvinthepa commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
> I don't think TS would fuss about this because all properties on both interfaces are optional, so essentially any object matches the interface, it should however provide nice intellisense when something is using the API.

It did fuss about it in my experience 🙁.

E.g.:

```
  constructor(
    private _handler: (event: MouseEvent, uri: string) => void = handleLink,
    private _options: ILinkMatcherOptions | ILinkProviderOptions = {},
    private _useLinkProvider: boolean = false
  ) {
    this._options.matchIndex = 1; //  Property 'matchIndex' does not exist on type 'ILinkProviderOptions'.ts(2339)
  }
```

I will try to solve this in a different way.

2021-02-03 13:33 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      this._linkProvider = this._terminal.registerLinkProvider(new WebLinkProvider(this._terminal, strictUrlRegex, this._handler, this._options));
@marvinthepa yeah that's what I ended up seeing, you can check the change I just pushed for an alright workaround

2021-02-03 13:35 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      const options = this._options as ILinkProviderOptions;
@marvinthepa normally using `as` is bad, but it doesn't matter much here since the objects are definitely compatible.

2021-02-03 13:35 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      options.matchIndex = 1;
I moved this here to avoid setting it when the object gets used for a link provider

2021-02-03 13:35 UTC, merged

2021-02-03 13:36 UTC, marvinthepa commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      const options = this._options as ILinkProviderOptions;
I knew there was something about TS that I didn't know.

However, this will break clients that pass their callbacks as `tooltipCallback` and `leaveCallback` (instead of `hover` and `leave`, and then switch `_useLinkProvider` to `true`. Shouldn't there be at least a warning in this case?

2021-02-03 13:48 UTC, Tyriar commented on addons/xterm-addon-web-links/src/WebLinksAddon.ts
> +      const options = this._options as ILinkProviderOptions;
I think it's fine like this since link matchers should be going away soon.

TS wasn't as clever as I thought it was by not narrowing the options type when you enter in `hover`, which makes sense now that I think about it:

![image](https://user-images.githubusercontent.com/2193314/106755415-f5748300-65e2-11eb-8d48-5af2ab5b275b.png)

If people are confused about the API in the meantime, they can go into the types to view the definition and/or look at the object type in intellisense:

![image](https://user-images.githubusercontent.com/2193314/106755547-1b9a2300-65e3-11eb-8dd7-6d5dea5870ff.png)

Passing the object `as ILinkProviderOptions` makes it act nicely:

![image](https://user-images.githubusercontent.com/2193314/106755718-4d12ee80-65e3-11eb-929d-6bcdcff72d09.png)

I personally don't think it's worth adding warnings since link matchers are deprecated and it's such a simple addon API.