fix length calculation of wide unicode chars
xtermjs/xterm.js pull request #3236
Opened 2021-01-29 04:28 UTC by gera2ld

Fix #3235

2021-02-11 19:24 UTC, rheh commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        resultIndex = this._stringLengthToBufferSize(line, resultIndex);
Would that be better named something other than resultIndex?  As it is called col on the return that sound reasonable? e.g.

```
const col = this._stringLengthToBufferSize(line, resultIndex);
```

2021-02-11 19:24 UTC, rheh commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        length = this._stringLengthToBufferSize(line, length, resultIndex);
Same here, is length the write variable to use maybe introduce a new one instead of reusing the one passed in as a parameter.

```
const bufferSize = this._stringLengthToBufferSize(line, length, resultIndex);
```

2021-02-11 20:29 UTC, jerch requested changes
Thx for looking into this.

Some remarks form my side:
- Could you move the changes to a separate branch? That would make testing of the PR alot easier (it is currently on master :fearful:).
- Imho this still does not work correctly, repro:
  - input `￥￥￥hello ￥￥￥hello##########café éé ééécafcaféééééécafcaféééééécaf𝄞𝄞𝄞𝄞𝄞𝄞𝄞𝄞𝄞𝄞𝄞ééhello` into the terminal
  - search for `￥`, `é` and `hello`
  - result: not all occurances found, some selections are totally off

Imho this needs a more fundamental rewrite - one way to approach it would be to get rid of the regexp positioning at all and search only on buffer indices. This would eliminate the string to buffer position errors. It is abit more implementation work but should run fine perfwise as well.

Another way is to stick with initial regexp search and also to translate the beginning string offset into a buffer index. This is needed as only the very first cell of a new line is guaranteed to have the same index position in the string and the buffer (index 0). Note that this also does not apply to wrapped lines (you basically have to start the buffer index translation always from the very first char of a wrapped line, which might span several buffer rows).

2021-02-22 08:48 UTC, gera2ld commented
Sorry for the late response.

I don't think it's a good idea to get rid of the regexp positioning because in that case we can hardly search by user provided regexp.
I've added a new method to translate buffer index to string offset so that the searching process only depends on string indices and works well with regexp.

But I noticed that searching in wrapped line does not work if the line contains special chars like emojis, because the `.substring` here cuts the string at `terminal.cols`, while such emojis occupies only one column but the string length is larger than 1:

https://github.com/xtermjs/xterm.js/blob/187f072f4336bb595539a3653e07e2cc97b3d2bd/addons/xterm-addon-search/src/SearchAddon.ts#L375

I'm wondering if the `.substring` can be removed safely.

2021-02-22 08:51 UTC, gera2ld commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        resultIndex = this._stringLengthToBufferSize(line, resultIndex);
done

2021-02-22 08:53 UTC, gera2ld commented
>     * Could you move the changes to a separate branch? That would make testing of the PR alot easier

Sorry for that, but it seems not possible to change branch name now. I can create another PR if you want.

2021-02-22 23:22 UTC, jerch commented
@gera2ld Yes, removing regexp would be big loss in flexibility, its better find a solution that keeps working them.

> [...] I'm wondering if the .substring can be removed safely.

Hmm looking at `_translateBufferLineToStringWithWrap` as a whole imho it does not the right thing and needs a rewrite (and yes without substring) for several reasons:
1. A search term might be split over several wrapped lines.
2. A wrapped line might end earlier if the next char does not fit anymore (a wide char at `term.col - 1` would flow to the next line because of taking 2 cells leaving one cell empty).
3. Any position deduction of string index <---> buffer index has to be done via the full wcwidth translation.

Esp. the last point is tricky to get done right, as any non 1:1 mapping char will create offsets - combining chars on BMP chars will create +1 offsets on the string index, while BMP wide chars will create -1 offsets (relative to buffer index). The only fixpoint in both metrics we have are real new lines at index 0 (lines that have no following `isWrapped` flag set).

Idea to revamp `_translateBufferLineToStringWithWrap`:
- Whenever a new line is found, consume all follow-up wrapped lines into one single (unwrapped) string. Thats pretty much what it does atm, but without substring. This will also correctly deal with 1. above.
- Special case early wrapping wide char (2. above): If the first char on the next line is a wide char and the current line is only `term.cols - 1` in length, treat it as early wrapping - ignore the empty cell, otherwise count empty cell as whitespace. This leads to a faulty handling, if the empty cell was indeed meant to stay empty. We already had an issue report about that, but sadly we have currently no way to track that special edge case.
- Whenever some match was found in the full (unwrapped) string, translate all string positions (start and end index) back by walking buffer positions + wcwidth continuing from the last saved match buffer position. This "buffer replay" will ensure 3. above.

> Sorry for that, but it seems not possible to change branch name now. I can create another PR if you want.

Hmm I think changing a PRs source branch is not possible. Guess creating a new one is the only option.

2021-02-23 04:39 UTC, gera2ld commented
Update: 
- the string offsets of the first char in each buffer row as well as the string of the whole line is cached now, so the buffer column can be calculated easily from the beginning of the corresponding row, no matter whether it's early wrapped or for whatever reason the string length does no match the buffer columns.

2021-11-16 16:47 UTC, jerch commented
Please review someone else, as it seems I wont get down to it.

2021-12-22 17:31 UTC, Tyriar approved these changes
Thanks @gera2ld and sorry about how long this took to merge in. I made a few minor doc related changes but since the tests pass and changes seem reasonable lgtm.

2021-12-22 17:31 UTC, merged

2021-12-23 02:49 UTC, JasinYip commented
This is the best news for me for Christmas and the New year, thank you all you guys fix this!