Update local fonts query
xtermjs/xterm.js pull request #3337
Opened 2021-05-13 07:19 UTC by LabhanshAgrawal

The local fonts api has changed a bit
`navigator.fonts.query()` now returns a Promise for Array of font metadata instead of async iterator
See https://github.com/WICG/local-font-access/blob/main/README.md#enumerating-local-fonts

2021-05-13 11:53 UTC, Tyriar requested changes

2021-05-13 11:53 UTC, Tyriar commented on addons/xterm-addon-ligatures/src/font.ts
> -        const fontsIterator: AsyncIterableIterator<IFontMetadata> = (navigator as any).fonts.query();
Let's move all the types to the top of the file so the API is all together:

```ts
interface IFontAccessNavigator {
  fonts: ...,
  permissions: ...
}
```

2021-05-13 15:48 UTC, Tyriar approved these changes

2021-05-13 15:48 UTC, merged

2021-05-18 09:32 UTC, LabhanshAgrawal commented
Can you please do a patch release of this?
Ligatures addon not working at all right now, without this.

2021-06-02 17:58 UTC, Tyriar commented
@LabhanshAgrawal sorry, drowning in notifications. You can jump on the beta build if you ever need to get a change early. We'll probably release the new version next week some time.

2021-06-15 07:59 UTC, LabhanshAgrawal commented
@Tyriar the latest release has ligatures addon 0.5.0 same as last release.

2021-06-15 11:02 UTC, Tyriar commented
Updated: https://github.com/xtermjs/xterm.js/commit/094bcbd81d1f080d204331088aa99f4d7173d56c, release incoming

2021-06-17 17:44 UTC, LabhanshAgrawal commented
@meganrogge @Tyriar any update? The release notes are updated but there's no new release on npm.

2021-06-17 20:09 UTC, Tyriar commented
@LabhanshAgrawal the release build failed?

```
src/font.ts(40,31): error TS2352: Conversion of type 'Navigator' to type 'IFontAccessNavigator' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'fonts' is missing in type 'Navigator' but required in type 'IFontAccessNavigator'.
```

https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=4348&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=7a29959a-6c04-5e83-f8f0-319180787bbf

2021-06-18 03:01 UTC, LabhanshAgrawal commented
Oh, strange that it didn't get detected in earlier ci runs
have opened #3371 for this