chore: lint using putout
xtermjs/xterm.js pull request #3341
Opened 2021-05-14 10:32 UTC by coderaiser

After successfully merged linting sessions [part1](https://github.com/xtermjs/xterm.js/pull/2953), [part2](https://github.com/xtermjs/xterm.js/pull/3133) and [part3](https://github.com/xtermjs/xterm.js/pull/3269), the time is come for part 4 :).

As usual, any rule can be disabled.
Command used:

```sh
putout {src,addons}/**/*.ts --fix
```

Applied rules:
- [apply-optional-chaining](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-apply-optional-chaining)
- [apply-shorthand-properties](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-apply-shorthand-properties)
- [apply-as-type-assertions](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-apply-as-type-assertions)
- [simplify-ternary](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-simplify-ternary)
- [simplify-logical-expressions](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-simplify-logical-expressions)
- [remove-useless-array-constructor](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-useless-array-constructor)
- [remove-useless-async](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-useless-async)
- [remove-useless-operand](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-useless-operand)
- [remove-useless-types-from-constants](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-useless-types-from-constants)
- [remove-boolean-from-assertions](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-boolean-from-assertions)

Current config for [putout v17](https://github.com/coderaiser/putout):

```json
{
    "rules": {
        "apply-shorthand-properties": "on",
        "strict-mode": "off",
        "remove-useless-spread/object": "off",
        "remove-iife": "off",
        "convert-generic-to-shorthand": "off",
        "convert-assignment-to-comparison": "off",
        "remove-console": "off",
        "remove-unused-variables": "off",
        "remove-useless-variables": "off",
        "apply-destructuring": "off",
        "merge-if-statements": "off",
        "convert-apply-to-spread": "off",
        "convert-math-pow": "off",
        "convert-for-to-for-of": "off",
        "convert-template-to-string": "off",
        "apply-numeric-separators": "off",
        "promises/add-missing-await": "off"
    },
    "match": {
        "SerializeAddon.benchmark.ts": {
            "remove-unused-expressions": "off"
        }
    },
    "plugins": [
        "apply-shorthand-properties"
    ]
}
```

2021-05-14 13:16 UTC, Tyriar requested changes

2021-05-14 13:16 UTC, Tyriar commented on src/common/Clone.ts
> +    clonedObject[key] = val[key] || clone(val[key], depth - 1);
Looks like this change is a little too aggressive and changes the behavior

2021-05-14 13:16 UTC, Tyriar commented on src/browser/Terminal.ts
> +    if (this._customKeyEventHandler && !this._customKeyEventHandler(event)) {
Not sure about this rule, typically I would explicitly use `false` when I think it's called for. This particular function is provided by embedders so it's a little more explicit when checking - perhaps internally it should return `unknown` 🤔

2021-05-14 13:16 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    this._allRows = Array<string>(rows);
Not a fan of removing the `new`

2021-05-14 15:16 UTC, coderaiser commented on src/browser/Terminal.ts
> +    if (this._customKeyEventHandler && !this._customKeyEventHandler(event)) {
OK, I'll better disable the rule `remove-boolean-from-assertions`

2021-05-14 15:16 UTC, coderaiser commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    this._allRows = Array<string>(rows);
Not problem, at all, I'll disable `remove-useless-array-constructor` :).

2021-05-14 15:18 UTC, coderaiser commented on src/common/Clone.ts
> +    clonedObject[key] = val[key] || clone(val[key], depth - 1);
About this code, we can rewrite it like this:

```js
const clone = () => {
    if (depth <= 1) {
        return val[key];
    } else {
        if (val[key]) {
            clone(val[key], depth - 1);
       } else {
           return val[key];
      }
    }
}
```

And simplify like this:

```js
const clone = (val, key, depth) => {
    if (val[key] && depth > 1)
       return clone(val[key], depth - 1);
    
    return val[key];
}
```

Yes, you absolutely right!

Just fixed `simplify-ternary`, will update PR.

2021-05-14 15:37 UTC, coderaiser commented
Just disabled rules:
-  [remove-useless-array-constructor](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-useless-array-constructor)
- [remove-boolean-from-assertions](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-remove-boolean-from-assertions)

And fixed:
- [simplify-ternary](https://github.com/coderaiser/putout/tree/v17.4.0/packages/plugin-simplify-ternary)(`@putout/plugin-simplify-ternary@v2.5.1`)

And updated `PR`, thanks a lot for quick response @Tyriar :)!

2021-05-14 16:50 UTC, Tyriar requested changes

2021-05-14 16:50 UTC, Tyriar commented on src/common/Clone.ts
> +    clonedObject[key] = depth <= 1 ? val[key] : (val[key] || clone(val[key], depth - 1));
This still isn't quite right as it clones the key if it's there

2021-05-14 16:50 UTC, Tyriar commented on src/browser/TestUtils.test.ts
> +  public getJoinedCharacters(row: number): Array<[number, number]> {
We prefer [] to Array<>, I think this is an eslint rule but not sure if we use it

2021-05-14 22:04 UTC, coderaiser commented on src/common/Clone.ts
> +    clonedObject[key] = depth <= 1 ? val[key] : (val[key] || clone(val[key], depth - 1));
You right! Fixed [simplify-ternary](
https://github.com/coderaiser/putout/tree/master/packages/plugin-simplify-ternary )([@putout/plugin-simplify-ternary@2.5.2](https://github.com/coderaiser/putout/commit/1ab404f33bf8ae89ab2933868f810326292aa622#diff-0ce4998d3f3a3d0ab4c56865edd5c0733ff26196f8c1f39bf14ca27e5e1386bd)).

2021-05-14 22:19 UTC, coderaiser commented on src/browser/TestUtils.test.ts
> +  public getJoinedCharacters(row: number): Array<[number, number]> {
Looks like it's related to https://github.com/xtermjs/xterm.js/commit/8c65fcacb37e729da5f4c0307065bbe3b89252f2, maybe I had old `master` 🤔

2021-05-17 11:28 UTC, jerch commented on src/browser/TestUtils.test.ts
> +  public getJoinedCharacters(row: number): Array<[number, number]> {
That was a weirdo before - we an array rule in place, but the older eslint version did not care much about it. After upgrading I got several linting warnings, and had to change the rule in 8c65fca to pass without warnings.

2021-05-17 11:56 UTC, jerch reviewed
Just some comments/Questions from my side.

2021-05-17 11:56 UTC, jerch commented on addons/xterm-addon-serialize/test/SerializeAddon.api.ts
> +      array[i] = (initial as (index: number) => T)(i);
@Tyriar Do we have a preference here? Could/should this be an eslint rule?

I admit, that I like the `xy as Z` more than `<Z>xy`, its imho easier to grasp with less syntax overhead (makes me less thinking). But thats just me.

2021-05-17 11:56 UTC, jerch commented on addons/xterm-addon-webgl/src/GlyphRenderer.ts
> +        fg &= ~(Attributes.CM_MASK | Attributes.RGB_MASK | FgFlags.INVERSE);
:+1: for shorthand notation where possible.

Minor sidenote - in some older engines those were actually slower than the explicit long versions.

2021-05-17 11:56 UTC, jerch commented on src/browser/Linkifier.test.ts
> +            ++count;
@coderaiser Is there a reason for `++count` instead of `count++`? In C I kinda always use the latter, if I dont bind the result, which leads to same ASM code, but always use the first in loops (which used to make a difference in old compilers, not anymore though). Is there a difference in JS?

2021-05-17 11:56 UTC, jerch commented on src/common/InputHandler.test.ts
> +    it('SL (scrollLeft)', () => {
Eww, guess I created a code smell here:

Your tool correctly found the asyncs to be stripped. The code smell happens at those `parseP` calls, those should have `await` in front to be consistent on code level. Created #3347 for that. (You can keep the rule as it is, gonna re-add the async keywords over there.)

2021-05-17 14:17 UTC, Tyriar commented on src/browser/Linkifier.test.ts
> +            ++count;
I always prefer the postfix as well, with the only exception being if I actually need the updated value

2021-05-17 14:38 UTC, coderaiser commented on addons/xterm-addon-serialize/test/SerializeAddon.api.ts
> +      array[i] = (initial as (index: number) => T)(i);
The thing is `Babel` can’t parse code that have both `react` and `typescript` enabled, for `xterm.js` it’s not a thing, but [new construction is preferable](https://basarat.gitbook.io/typescript/type-system/type-assertion#as-foo-vs-less-than-foo-greater-than).

2021-05-17 14:41 UTC, coderaiser commented on src/browser/Linkifier.test.ts
> +            ++count;
There is only one reason: you see what’s going on the variable in the first place, so you can understand it faster:

`aVeryLongVariable++`

Anyways, it’s not a problem, I’ll add an option or change to postfix and disable a rule.

2021-05-17 14:45 UTC, coderaiser commented on src/browser/Linkifier.test.ts
> +            ++count;
Just updated

2021-06-04 13:14 UTC, Tyriar commented on addons/xterm-addon-serialize/test/SerializeAddon.api.ts
> +      array[i] = (initial as (index: number) => T)(i);
I prefer `as` more, more readable and a little easier to type. Looks like there is an eslint rule https://github.com/xtermjs/xterm.js/issues/3359

2021-06-04 13:25 UTC, Tyriar approved these changes
Looks good, let's wait until https://github.com/xtermjs/xterm.js/pull/3360 is merged to merge this in since it fixes more `as` problems and also some typing bugs (like setTimeout instead of window.setTimeout)

2021-06-04 13:25 UTC, Tyriar commented on src/browser/Terminal2.test.ts
> +      ++counter;
postfix?

2021-06-04 16:31 UTC, coderaiser commented on addons/xterm-addon-serialize/test/SerializeAddon.api.ts
> +      array[i] = (initial as (index: number) => T)(i);
Yes, this is the same rule, with the only difference: [it cannot fix](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/src/rules/consistent-type-assertions.ts) :). Anyways  it will keep codebase in a clean state warning developers about assertions type used, so I think it is useful.

2021-06-04 16:38 UTC, coderaiser commented on src/browser/Terminal2.test.ts
> +      ++counter;
done ✅

2021-06-04 20:03 UTC, Tyriar commented on addons/xterm-addon-serialize/test/SerializeAddon.api.ts
> +      array[i] = (initial as (index: number) => T)(i);
Yeah I noticed that when I did the PR ☹️

2021-06-04 20:03 UTC, merged