Add a Time-Based Debouncer to update Screen Readers at most once per second
xtermjs/xterm.js pull request #3399
Opened 2021-07-29 20:24 UTC by pattch

This change makes it so that screen readers are announced to based on the most recent update to Screen Readers, as opposed to every possible animation frame. Previously, the very frequent updates to screenreaders in conjunction with the unbounded internal character buffer for announcements caused full page crashes due to out of memory errors when screen reader refreshes weren't fast enough to keep up with fast updates to Terminals. This change ensures that Screen Readers are refreshed at most once per second, but preserves the behavior for visual Terminal refreshes by introducing a second debouncer based on the existing RenderDebouncer.

2021-07-31 16:25 UTC, pattch commented
Note: this pull request DOESN'T trim any content from the Accessibility Manager's internal character buffer, as was previously intended. In practice, throttling the frequency of updates is sufficient in practice to prevent the screen reader updates from causing the crashes as before. As a precaution, I still think the internal buffer should still have a cap on the size it can grow to, but that's not addressed in this PR.

Closes #3376

2021-08-16 19:00 UTC, pattch commented
Just wanted to double check and see if there is any update here, and see whether this change is an acceptable fix for xterm.js?

2021-08-17 11:48 UTC, Tyriar requested changes
Sorry about the delay, approach looks good overall 👍

2021-08-17 11:48 UTC, Tyriar commented on src/browser/TimeBasedDebouncer.ts
> +      setTimeout(() => {
We'll want to dispose of this timeout if it's set on dispose.

2021-08-17 11:48 UTC, Tyriar commented on src/browser/TimeBasedDebouncer.ts
> +export class TimeBasedDebouncer implements IDisposable {
Can you make an `IRenderDebouncer` interface in browser/Types.d.ts and use that as the prop type and where `RenderDebouncer` is used?

```ts
export interface IRenderDebouncer extends IDisposable {
  refresh(rowStart: number | undefined, rowEnd: number | undefined, rowCount: number): void;
}
```

2021-08-17 11:48 UTC, Tyriar commented on src/browser/TimeBasedDebouncer.ts
> +const RENDER_DEBOUNCE_THRESHOLD_MS = 1000; // 1 Second
Passing this into the ctor will help make it a little more reusable

2021-08-17 22:21 UTC, pattch commented on src/browser/TimeBasedDebouncer.ts
> +      setTimeout(() => {
I've implemented clearing the timeout that gets scheduled on dispose if it's set here.

2021-08-17 22:21 UTC, pattch commented on src/browser/TimeBasedDebouncer.ts
> +const RENDER_DEBOUNCE_THRESHOLD_MS = 1000; // 1 Second
I've made this configurable as requested.

2021-08-17 22:22 UTC, pattch commented on src/browser/TimeBasedDebouncer.ts
> +export class TimeBasedDebouncer implements IDisposable {
I've created an IRenderDebouncer interface that both RenderDebouncer and TimeBasedDebouncer now implement, and they're typed accordingly where they're used.

2021-08-17 22:23 UTC, pattch commented
No worries on the delay - thanks for the constructive feedback! I've done my best to address the issues you brought up, and so this PR should now conform to those expectations. Let me know if there's anything else missing from this fix, thanks

2021-08-18 13:09 UTC, Tyriar approved these changes
Perfect, thanks! CI test is a flake

2021-08-18 13:09 UTC, merged