Issue #3425 (Terminal controls shifted to the right of the demo)
xtermjs/xterm.js pull request #3439
Opened 2021-08-30 09:52 UTC by simran916

Issue: #3425

All the terminal controls have been shifted to the side of the demo with a toggling tab bar for Options, AddOns, and Style. The screenshots of the modified UI have been attached for reference. Hope this would help to resolve issue #3425
![Capture_Options](https://user-images.githubusercontent.com/64780093/131321377-a9517f87-ae27-4c6f-9c2c-4d785a80d02c.PNG)
![Capture_Add0ns](https://user-images.githubusercontent.com/64780093/131321373-9eb5b9ab-cdb9-4e7e-af47-6c2383b6b08c.PNG)
![Capture_Style](https://user-images.githubusercontent.com/64780093/131321371-e9eb2c07-eefd-487e-92a1-8114b88ea3c8.PNG)

2021-08-30 14:15 UTC, Tyriar requested changes
This is really nice 👍

2021-08-30 14:15 UTC, Tyriar commented on demo/index.html
> +      <button id="custom-glyph" title="Write custom box drawing and block element characters to the terminal">Test custom glyphs</button>
Let's put these in a "Test" tab

2021-08-30 14:15 UTC, Tyriar commented on demo/index.html
> +          </p>
These would be better presented on new lines now (wrap each in `<p>`?)

2021-08-30 14:15 UTC, Tyriar commented on demo/index.html
> +      <button id="custom-glyph" title="Write custom box drawing and block element characters to the terminal">Test custom glyphs</button>
It would be really cool if we could save the last tab and open to it, no need to do in this PR unless easy though.

2021-08-30 14:15 UTC, Tyriar commented on demo/style.css
> +}
How about setting up the options sidebar such that it fills the full height like this?

![image](https://user-images.githubusercontent.com/2193314/131353330-985939d2-9654-46d2-999e-bd62221baadd.png)

2021-08-30 18:26 UTC, simran916 commented on demo/index.html
> +      <button id="custom-glyph" title="Write custom box drawing and block element characters to the terminal">Test custom glyphs</button>
Yes, okay give me some time to give it a try!

2021-08-31 06:29 UTC, simran916 commented on demo/index.html
> +      <button id="custom-glyph" title="Write custom box drawing and block element characters to the terminal">Test custom glyphs</button>
Done!

2021-08-31 06:31 UTC, simran916 commented on demo/style.css
> +}
Yes, please check if it is okay!
![Capture_Height](https://user-images.githubusercontent.com/64780093/131453244-5debd9c6-834a-42c8-8583-ae05c3fac4a4.PNG)

2021-08-31 14:29 UTC, Tyriar approved these changes
Very nice, thanks for the contribution 👍

2021-08-31 14:29 UTC, merged