Passing cols or rows into ctor as undefined will break terminal
xtermjs/xterm.js pull request #3453
Opened 2021-09-01 13:48 UTC by silamon

https://github.com/xtermjs/xterm.js/blob/554f7dab724cf63ad7b0197304eabf37992b9a68/src/common/services/BufferService.ts#L39-L40
Passing `undefined` to cols or rows would result in NaN. Passing `null` works as expected. 

Fixes #3329

2021-09-02 23:03 UTC, meganrogge commented on src/common/services/OptionsService.test.ts
> +      console.error = () => { };
should undo this formatting change

2021-09-02 23:04 UTC, meganrogge commented on src/common/services/OptionsService.test.ts
> +      assert.equal(new OptionsService({ tabStopWidth: 0 }).getOption('tabStopWidth'), DEFAULT_OPTIONS.tabStopWidth);
```suggestion
      assert.equal(new OptionsService({tabStopWidth: 0}).getOption('tabStopWidth'), DEFAULT_OPTIONS.tabStopWidth);
```

2021-09-02 23:05 UTC, meganrogge commented on src/common/services/OptionsService.ts
> -  bellSound:  DEFAULT_BELL_SOUND,
undo

2021-09-02 23:05 UTC, meganrogge commented on src/common/services/OptionsService.ts
> -        // Fall through for bounds check
undo

2021-09-02 23:06 UTC, meganrogge requested changes
looks good, thanks - a few formatting changes should be reverted

2021-09-03 14:53 UTC, Tyriar approved these changes
Thanks!

2021-09-03 14:53 UTC, merged