Halloween Lint using Putout (part 5)
xtermjs/xterm.js pull request #3538
Opened 2021-11-02 17:20 UTC by coderaiser

After successfully merged linting sessions [part 1](https://github.com/xtermjs/xterm.js/pull/2953), [part 2](https://github.com/xtermjs/xterm.js/pull/3133) and [part 3](https://github.com/xtermjs/xterm.js/pull/3269), [part 4](https://github.com/xtermjs/xterm.js/pull/3341) the time is come for part 5 :).

As usual, any rule can be disabled.

Command used:

```sh
putout . --fix
```

Applied rules:
- [regexp/optimize](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-regexp);
- [apply-optional-chaining](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-apply-optional-chaining);
- [convert-index-of-to-includes](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-convert-index-of-to-includes);
- [convert-array-copy-to-slice](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-convert-array-copy-to-slice);
- [remove-useless-escape](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-escape);
- [remove-useless-return](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-return);
- [remove-unused-expressions](https://github.com/coderaiser/putout/tree/v21.1.0/packages/remove-unused-expressions);
- [remove-useless-type-conversion/with-double-negations](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-type-conversion);
- [remove-useless-operand](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-operand);
- [remove-useless-types-from-constants](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-types-from-constants);
- [remove-typeof-to-is-type](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-convert-typeof-to-is-type);
- [remove-useless-new](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-new);
- [apply-is-array](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-apply-is-array);
- [promises/remove-useless-async](https://github.com/coderaiser/putout/tree/v21.1.0/plugin-promises);

Current config for [putout v21](https://github.com/coderaiser/putout):

```json
{
    "rules": {
        "apply-shorthand-properties": "off",
        "apply-destructuring": "off",
        "apply-numeric-separators": "off",
        "convert-assignment-to-comparison": "off",
        "convert-apply-to-spread": "off",
        "convert-math-pow": "off",
        "convert-for-to-for-of": "off",
        "convert-template-to-string": "off",
        "strict-mode": "off",
        "remove-useless-spread/object": "off",
        "remove-useless-array-constructor": "off",
        "remove-boolean-from-assertions": "off",
        "remove-iife": "off",
        "remove-console": "off",
        "remove-unused-variables": "off",
        "remove-useless-variables": "off",
        "merge-if-statements": "off",
        "promises/add-missing-await": "off",
        "simplify-ternary": "off"
    },
    "match": {
        "*.benchmark.ts": {
            "remove-unused-expressions": "off"
        }
    },
    "plugins": [
        "apply-shorthand-properties"
    ],
    "ignore": [
        "*.md",
        "*.json",
        "*ignore",
        "*.yml",
        "*.rc",
        "*.css",
        "out",
        "out-test",
        "demo"
    ]
}
```

Happy Halloween 🎃!

2021-11-04 14:21 UTC, Tyriar requested changes
Looks like this caused tsc strict errors:

```
src/common/InputHandler.ts(64,18): error TS7006: Parameter 'a' implicitly has an 'any' type.
src/common/InputHandler.ts(561,45): error TS2339: Property 'substring' does not exist on type 'string | Uint8Array'.
  Property 'substring' does not exist on type 'Uint8Array'.
src/common/InputHandler.ts(562,43): error TS2339: Property 'subarray' does not exist on type 'string | Uint8Array'.
  Property 'subarray' does not exist on type 'string'.
src/common/input/WriteBuffer.test.ts(12,18): error TS7006: Parameter 'a' implicitly has an 'any' type.
src/common/input/WriteBuffer.test.ts(49,75): error TS2345: Argument of type 'string | Uint8Array' is not assignable to parameter of type 'Uint8Array'.
  Type 'string' is not assignable to type 'Uint8Array'.
src/common/parser/EscapeSequenceParser.test.ts(17,18): error TS7006: Parameter 'a' implicitly has an 'any' type.
src/common/parser/EscapeSequenceParser.test.ts(1737,7): error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.
  Type 'unknown' is not assignable to type 'string'.
addons/xterm-addon-attach/src/AttachAddon.ts(10,18): error TS7006: Parameter 'a' implicitly has an 'any' type.
addons/xterm-addon-attach/src/AttachAddon.ts(32,24): error TS2345: Argument of type 'string | ArrayBuffer' is not assignable to parameter of type 'string | Uint8Array'.
  Type 'ArrayBuffer' is not assignable to type 'string | Uint8Array'.
    Type 'ArrayBuffer' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteOffset, copyWithin, and 22 more.
addons/xterm-addon-attach/src/AttachAddon.ts(32,63): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'string | ArrayBuffer' is not assignable to parameter of type 'ArrayBuffer'.
      Type 'string' is not assignable to type 'ArrayBuffer'.
error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions
error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions
error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions
error TS2688: Cannot find type definition file for '../../../out-test/api/TestUtils'.
  The file is in the program because:
    Entry point of type library '../../../out-test/api/TestUtils' specified in compilerOptions
```

2021-11-04 16:03 UTC, coderaiser commented
Disabled:
-  [`remove-useless-types-from-constants`](https://github.com/coderaiser/putout/tree/master/packages/plugin-remove-useless-types-from-constants);
- [`convert-typeof-to-is-type`](https://github.com/coderaiser/putout/tree/master/packages/plugin-convert-typeof-to-is-type);

2021-11-04 16:23 UTC, jerch commented
@coderaiser

On a sidenote: most promises removed from tests, are actually needed to force the return of a promise testing promise handling in the parser. So they should not be removed there.

2021-11-04 19:18 UTC, coderaiser commented
@jerch just got back promises

2021-11-05 08:10 UTC, coderaiser commented
Disabled:
- [remove-useless-type-conversion/with-double-negations](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-type-conversion);

2021-11-05 13:33 UTC, Tyriar requested changes
Lots of good changes here, I especially like the optional chaining.

2021-11-05 13:33 UTC, Tyriar commented on addons/xterm-addon-serialize/benchmark/SerializeAddon.benchmark.ts
> +    })), { fork: false }).showAverageThroughput();
This was more readable before imo, also it doubled up the params for some reasons.

2021-11-05 13:33 UTC, Tyriar commented on addons/xterm-addon-ligatures/src/font.ts
> +          throw Error('Permission to access local fonts not granted.');
I kind of prefer `new Error` and `new Array`, let's remove that rule as well so this PR becomes a lot smaller. This is something a compiler should remove if they are equivalent imo.

2021-11-05 13:33 UTC, Tyriar commented on src/common/CircularList.ts
> +    const newArray = Array(newMaxLength);
Not sure this was a safe thing to do removing the type here?

2021-11-05 13:33 UTC, Tyriar commented on src/common/parser/Params.ts
> +} = Array;
Can we inline `Array.isArray` instead?

2021-11-05 19:35 UTC, coderaiser commented
Disabled:
- [`remove-useless-new`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-new);
- [`remove-useless-return`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-return);

2021-11-05 19:36 UTC, coderaiser commented
Disabled:
- [`remove-useless-new`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-new);
- [`remove-useless-return`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-return);

2021-11-05 19:36 UTC, coderaiser commented
Disabled:
- [`remove-useless-new`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-new);
- [`remove-useless-return`](https://github.com/coderaiser/putout/tree/v21.1.0/packages/plugin-remove-useless-return);

2021-11-05 19:37 UTC, coderaiser commented on src/common/parser/Params.ts
> +
```suggestion
```

2021-11-06 16:23 UTC, coderaiser commented on src/common/parser/Params.ts
> +} = Array;
Landed `inline` option to [`@putout/plugin-apply-is-array`](https://github.com/coderaiser/putout/tree/master/packages/plugin-apply-is-array#-correct-code-example) `v2.1.0`

2021-11-08 15:47 UTC, Tyriar approved these changes
Thanks, always appreciated 🙂

2021-11-08 15:47 UTC, merged