Resolve perf regression from OptionsService.options
xtermjs/xterm.js pull request #3559
Opened 2021-11-20 14:59 UTC by silamon

Fixes #3556

2021-12-21 20:08 UTC, silamon commented
I might come with a better solution, since a proxy isn't supposed to work in Internet Explorer.

2021-12-22 16:24 UTC, Tyriar requested changes

2021-12-22 16:24 UTC, Tyriar commented on src/common/services/OptionsService.ts
>    public options: ITerminalOptions;
I think the proxy object might be a little overkill for what we're after here, what if we had this interface:

```
interface IOptionsService {
  readonly rawOptions: Readonly<ITerminalOptions>;
}
```

This interface could be mapped to the actual underlying object and essentially be a fast readonly path for accessing options internally, since many reads is the perf concern, not writes. The implementation would look something like this:

```
export class OptionsService implements IOptionsService {
  // Note that it's not Readonly<ITerminalOptions> in the impl as the interface protects it
  readonly rawOptions: ITerminalOptions;
  // The defineProperty object (or Proxy?) that includes validation
  options: ITerminalOptions;
}
```

Lack of IE support doesn't bother me so much as we call out partial support in the readme. Someone that uses a terminal that is using IE at this point probably deserves a broken experience tbh 😉

2022-01-04 20:11 UTC, Tyriar requested changes

2022-01-04 20:11 UTC, Tyriar commented on src/common/services/OptionsService.test.ts
> +      assert.notEqual(Object.keys(optionsService.options).length, 0);
This assertion is failing

2022-01-04 20:11 UTC, Tyriar commented on src/common/services/Services.ts
> +  readonly rawOptions: Readonly<ITerminalOptions>;
```suggestion
  /**
   * Read only access to the raw options object, this is an internal-only fast path for accessing
   * single options without any validation as we trust TypeScript to enforce correct usage
   * internally.
   */
  readonly rawOptions: Readonly<ITerminalOptions>;
```

2022-01-04 20:11 UTC, Tyriar commented on src/common/services/OptionsService.ts
> +    this.options = { ... defaultOptions };
I think this looks good if it does what it looks like, we would just now want to replace all accesses internally with `rawOptions` instead of the slower `options`. This is mainly important for "hot" code paths like within the parser/inputhandler, but we should just use it everywhere.

2022-01-11 15:26 UTC, Tyriar approved these changes
Great work @silamon 👍

2022-01-11 15:26 UTC, merged