HTML serialization
xtermjs/xterm.js pull request #3619
Opened 2022-01-29 19:14 UTC by silamon

Fixes #1883 
Makes use of the existing serialize addon and the templates

2022-02-01 18:14 UTC, meganrogge commented
Thanks for working on this.

Could you please:
- add information about how embedders are expected to hook this up to copy from selection 
- revert the formatting changes made to `client.ts`
- maybe I'm doing something wrong, but the demo doesn't seem to work for me 
  - the button says it copies, but it doesn't. 
  - when I copied the output manually and pasted it in:
      -  the vscode editor, it didn't produce the expected result or any red text
      ![Screen Shot 2022-02-01 at 12 13 01 PM](https://user-images.githubusercontent.com/29464607/152026441-189ddd3b-4991-4b3e-8193-32f7f4475f29.png)
      - apple notes, it didn't produce the expected result - all of the text was colored red
![Screen Shot 2022-02-01 at 12 12 28 PM](https://user-images.githubusercontent.com/29464607/152026361-818d1d2a-fa2b-4c81-bd1e-d0854996c28e.png)

2022-02-02 17:05 UTC, silamon commented
Selection has been added, but unfortunately broke some existing tests. I'll fix that when I have time. :)
I've used the new asynchronous clipboard api, but a lot of browsers don't support it. I've replaced that with a deprecated alternative, which seems to be more supported anyway.

2022-02-02 17:26 UTC, meganrogge commented
from what I've read, it looks like an embedder would have to intercept the `copy` event, set the data format as `'text/html'` and provide the serialized data. is that how you are testing this @silamon ?

2022-02-02 17:28 UTC, silamon commented
When you click the 'serialize' button, it should add a html code onto your clipboard of the selected part of the terminal. Don't copy the html in the visible window, that's there for debugging or to save as html manually if copy to clipboard doesn't work. From as soon as the button is clicked, you should be able to paste the selected part in an editor that supports pasting html like word or something like that.

2022-02-02 17:31 UTC, meganrogge commented
Doesn't work for me in edge, but I see it working for some cases that I've tried in Chrome 👍🏼.

2022-02-02 18:55 UTC, Eugeny commented
Copying itself does work reliably for me in Chrome, however when the alternate screen is active, it still copies random content from the primary screen.

2022-02-02 20:12 UTC, meganrogge commented
It actually does work in edge for me as well. I was expecting the background color to match that of the terminal, but perhaps that's not necessary.

2022-02-02 20:36 UTC, Tyriar requested changes
Thanks for the PR @silamon, looks pretty close 😍

2022-02-02 20:36 UTC, Tyriar commented on demo/client.ts
> +  const output = addons.serialize.instance.htmlserialize();
We'll need the new API changes reflected in https://github.com/xtermjs/xterm.js/blob/master/addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts

2022-02-02 20:36 UTC, Tyriar commented on demo/client.ts
> +            = "Copied to clipboard";
```suggestion
  document.getElementById("htmlserialize-output-result").innerText = "Copied to clipboard";
```

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +        content.push('background-color: ' + bgHexColor + ';');
Can background color be disabled? I think in VS Code copying with syntax highlighting originally had this but it got removed as it was annoying.

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +      ];
I don't think this does what you expect, do you mean this instead?

```suggestion
      const rgb = [
        (color >> 16) & 255,
        (color >>  8) & 255,
        (color      ) & 255
      ];
```

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +      + '<meta http-equiv=\'Content-Type\' content=\'text/html; charset=UTF-8\'/></head><body><!--StartFragment--><pre>';
Is the extra metadata/comments here needed? In particular: `meta name=generator`, `StartFragment`, `EndFragment`

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +    padString = String(typeof padString !== 'undefined' ? padString : ' ');
You can use `padString !== undefined` here, I stopped caring about people who want to override `undefined` years ago 😉. Also I think the `String()` is redundant and this could be simplified:

```suggestion
    padString = padString ?? ' ';
```

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +  private _dimStyle = 'opacity: 0.5;';
If these are fixed we can put them in a `const enum`, this will make tsc inline all the values so the members won't end up existing:

```ts
const enum CssStyles {
	Inverse = 'color: #000000; background-color: #BFBFBF;',
	Blink = 'text-decoration: blink;',
	Bold = 'font-weight: bold;',
	Italic = 'font-style: italic;',
	Underline = 'text-decoration: underline;',
	Strikethrough = 'text-decoration: line-through;',
	Invisible = 'visibility: hidden;',
	Dim = 'opacity: 0.5;'
}
```

2022-02-02 20:36 UTC, Tyriar commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +  public htmlserialize(options?: Partial<IHtmlSerializeOptions>): string {
`serializeAsHtml` seems like a better more descriptive option

2022-02-02 20:36 UTC, Tyriar commented on demo/client.ts
> +  // Deprecated, but the most supported for now.
Since we're a devtool I think it's fine to use the newer APIs like the clipboard API, writing to the clipboard API should work on all modern browser, just not IE. That will future proof this code and give a better example of how to use the new feature.

2022-02-02 20:36 UTC, Tyriar commented on demo/client.ts
> +    e.clipboardData.setData("text/plain", output);
I think `text/plain` should actually be set to the original string, that means the application in question can decide which mime type it prefers.

2022-02-02 21:03 UTC, Eugeny commented
BG/FG colors were correct in the HTML I got, although when I first tested it by pasting into Word, it turned out inverted - that's Word's problem though, the HTML itself is correct and opening it in Chrome gets the colors right.

2022-02-03 02:14 UTC, meganrogge commented
Yes @Eugeny I saw the same - it was inverted in apple notes, but not in chrome.

2022-02-03 18:15 UTC, silamon commented on addons/xterm-addon-serialize/src/SerializeAddon.ts
> +      + '<meta http-equiv=\'Content-Type\' content=\'text/html; charset=UTF-8\'/></head><body><!--StartFragment--><pre>';
StartFragment and EndFragment seems needed, meta tags have been removed.

2022-02-03 18:18 UTC, silamon commented on demo/client.ts
> +  // Deprecated, but the most supported for now.
I've left the code as it is, since it seems more supported. 
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write vs
https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

2022-02-03 18:45 UTC, silamon commented
I can't seem to reproduce the text being pasted inverted. Do you see colored text in that paste or is it just clear text in black?

2022-02-03 18:59 UTC, Eugeny commented
@silamon it's all colored with the exception of black and white being inverted. I don't even think it's your fault - my custom HTML copy implementation suffers from the same if background and foreground are #000 and #fff respectively.

2022-02-10 17:20 UTC, Tyriar commented on demo/client.ts
> +  document.removeEventListener("copy", listener);
> I've used the new asynchronous clipboard api, but a lot of browsers don't support it. I've replaced that with a deprecated alternative, which seems to be more supported anyway.

It would be better if we moved on to more modern APIs like `navigator.clipboard`, it looks like just IE doesn't support writing to the clipboard which doesn't matter https://caniuse.com/async-clipboard

2022-02-10 17:21 UTC, Tyriar commented on demo/index.html
> +            <button id="htmlserialize">Serialize the content of terminal in HTML</button>
I'm seeing Edge not copy the whole buffer when no selection is made. Should this button be changed to say serialize the selection instead?

2022-02-10 17:25 UTC, Tyriar commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +     * is pasted with style options retained.
```suggestion
     * Serializes terminal content as HTML, which can be written to the clipboard using the
     * `text/html` mimetype. For applications that support it, the pasted text should then retain
     * its colors/styles.
```

2022-02-10 17:26 UTC, Tyriar commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +    scrollback: number;
This should mention `{@link IHTMLSerializeOptions.onlySelection}`

2022-02-10 17:28 UTC, Tyriar commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +    onlySelection: boolean;
I don't think this should mention the false case as it overrides that. Also having a true by default _optional_ setting is a bit weird, let's make this false by default.

2022-02-10 17:29 UTC, Tyriar commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +    includeGlobalBackground: boolean;
Let's also change this to false by default.

2022-02-10 17:31 UTC, Tyriar commented
Looks good other than those comments 👍

2022-02-13 18:51 UTC, silamon commented on demo/client.ts
> +  document.removeEventListener("copy", listener);
I've tested with navigator.clipboard in the first commit and Firefox doesn't support it. The caniuse link does mention that as well.

2022-02-13 18:53 UTC, silamon commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +    public serializeAsHTML(options?: Partial<IHTMLSerializeOptions>): string;
I'll write some unit tests as soon as I have time. :)

2022-02-19 13:19 UTC, silamon commented on addons/xterm-addon-serialize/typings/xterm-addon-serialize.d.ts
> +    public serializeAsHTML(options?: Partial<IHTMLSerializeOptions>): string;
Tests have been added. Unfortunately, not as playwright tests since I couldn't get it to work at this moment.

2022-02-22 20:11 UTC, merged