add Decorations
xtermjs/xterm.js pull request #3630
Opened 2022-02-08 18:02 UTC by meganrogge

fixes #1852

2022-02-08 20:39 UTC, meganrogge commented
originally, we were thinking that we'd need `IGutterDecorationOptions` and `IBufferDecorationOptions`, but now think that both can be described using the same set of options - `IDecorationOptions`

2022-02-08 21:59 UTC, meganrogge commented on test/api/Terminal.api.ts
> +    it.skip('should throw when a negative x offset is provided', async () => {
this should be passing, but doesn't - saying the function doesn't throw. 

when I provide a -x value in the demo, it throws. maybe the error isn't propagated for some reason?

2022-02-08 22:05 UTC, Tyriar requested changes

2022-02-08 22:05 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  public get marker(): IMarker { return this._marker; }
Something I've started doing recently to avoid duplication is to just make properties like these public as we only expose `IDecoration` outside this file so setting them in protected already. That way we don't need to create the property and get the (small) perf hit associated with them.

So this instead and removing the prop:

```
readonly id: number = Decoration._nextId++;
```

2022-02-08 22:05 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  }
I've been preferring to move the dispose handling for objects that extend `Disposable` into the ctor in the form of:

```
this.register({ dispose: () => {
  ...
}});
```

That way we won't accidentally forget to call `super.dispose()` which has happened before.

2022-02-08 22:05 UTC, Tyriar commented on typings/xterm.d.ts
> +  export interface IDecorationOptions {
Let's add jsdoc

2022-02-08 22:05 UTC, Tyriar commented on typings/xterm.d.ts
> +     *  @throws if the @param decorationOptions includes a negative x offset.
```suggestion
     *  @throws when options include a negative x offset.
```

2022-02-08 22:07 UTC, Tyriar commented on test/api/Terminal.api.ts
> +    it.skip('should throw when a negative x offset is provided', async () => {
Until we move to `@playwright/test` we need to do something like this to check throws: https://github.com/Tyriar/xterm.js/blob/65182176b9de63a4d369dfc4cb33b040d41983a7/test/api/Terminal.api.ts#L36-L43

```ts
    await page.evaluate(`
      try {
        window.term.buffer;
      } catch (e) {
        window.throwMessage = e.message;
      }
    `);
    await pollFor(page, 'window.throwMessage', 'You must set the allowProposedApi option to true to use proposed API');
```

2022-02-09 02:28 UTC, meganrogge commented on src/browser/Terminal.ts
> +    this.register(this._renderService.onRefreshRequest(() => this._decorationService?.refresh()));
that's outdated

2022-02-09 02:42 UTC, meganrogge commented on css/xterm.css
> +.xterm-screen canvas .xterm-decoration {
yeah that's outdated. it's now 

https://github.com/microsoft/vscode/blob/7adaf3ab0ef1d5c6a120b0b69af2a643f04a0b1c/src/vs/workbench/contrib/terminal/browser/media/xterm.css#L181

2022-02-09 02:43 UTC, meganrogge commented on demo/client.ts
> +  decoration.element.style.position = 'absolute';
outdated

2022-02-09 02:58 UTC, meganrogge commented on src/browser/public/Terminal.ts
> +    return this._core.registerDecoration(decorationOptions);
I had the validation in Terminal.ts to begin with and thought you said to move it within `DecorationService`? Also don't we want to allow non-integers?

2022-02-09 03:00 UTC, meganrogge commented on src/browser/public/Terminal.ts
> +    return this._core.registerDecoration(decorationOptions);
I think we want to allow decimal values for width and height - since you might want it to be smaller than the cell width/height. I'll do that for decorationOptions.x though

2022-02-09 03:14 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +        decoration.element.style.top = `${(decoration.marker.line - this._bufferService.buffers.active.ydisp) * this._renderService.dimensions.scaledCellHeight}px`;
thought we wanted to avoid consts

2022-02-09 03:17 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +    private readonly _bufferService: IBufferService
outdated

2022-02-09 12:48 UTC, Tyriar commented on css/xterm.css
> +.xterm-screen canvas .xterm-decoration {
Just so they're more contained, inspecting screen is a pretty common thing we do right now when investigating renderer problems.

2022-02-09 13:09 UTC, Tyriar requested changes

2022-02-09 13:09 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +      this._element.style.right = this._decorationOptions.x ? `${this._decorationOptions.x * this._renderService.dimensions.scaledCellWidth}px` : '';
I think this is equivalent but simpler:

```ts
this._element.style.right =`${(this._decorationOptions.x ?? 0) * this._renderService.dimensions.scaledCellWidth}px`;
```

Maybe better actually is to store the options properties including their default values during the ctor and not keep options as a property. Otherwise embedders could change decoration options after registering the decoration which could lead to weird behavior:

```ts
  constructor(
    options: IDecorationOptions,
    private readonly _screenElement: HTMLElement,
    @IBufferService private readonly _bufferService: IBufferService,
    @IRenderService private readonly _renderService: IRenderService
  ) {
    super();
    this._marker = options.marker;
    this.x = options.x ?? 0;
    ...
```

2022-02-09 13:09 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +      }
Could be simpler to defer all this to the Decoration so this just ends up being:

```ts
for (const decoration of this._decorations) {
  decoration.render();
}
```

Then it's up to the decoration to lazily create the element if needed, show/hide, update position, etc.

2022-02-09 13:09 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +    @IRenderService private readonly _renderService: IRenderService
Actually since we want to allow registering decorations before open is called (so shell integration works on backgrounded terminals that haven't been opened yet), these may be undefined so we'll want to pass them into the `Decoration.render` call instead of keeping them as properties.

2022-02-09 14:41 UTC, meganrogge commented on test/api/Terminal.api.ts
> +  });
add a test to make sure decorations can be registered before open is called

2022-02-09 20:39 UTC, Tyriar approved these changes

2022-02-10 01:30 UTC, merged