Make registerMarker's cursor offset optional
xtermjs/xterm.js pull request #3663
Opened 2022-02-26 06:51 UTC by childrentime

#3611

2022-02-26 16:20 UTC, Tyriar requested changes
Thanks, just a minor comment

2022-02-26 16:20 UTC, Tyriar commented on src/browser/public/Terminal.ts
> -  public registerMarker(cursorYOffset: number): IMarker | undefined {
Let's add `: number` back here (personal preference)

2022-02-26 16:20 UTC, Tyriar commented on src/headless/public/Terminal.ts
> -  public registerMarker(cursorYOffset: number): IMarker | undefined {
Same

2022-02-27 05:28 UTC, childrentime commented
Done！

2022-02-28 13:33 UTC, Tyriar approved these changes

2022-02-28 13:33 UTC, merged