Replace all getOption/setOption usage with options
xtermjs/xterm.js pull request #3667
Opened 2022-03-01 04:13 UTC by childrentime

#3526

2022-03-01 16:00 UTC, Tyriar requested changes
Looks good, just one comment

2022-03-01 16:00 UTC, Tyriar commented on typings/xterm.d.ts
> -    getOption(key: 'bellSound' | 'bellStyle' | 'cursorStyle' | 'fontFamily' | 'logLevel' | 'rendererType' | 'termName' | 'wordSeparator'): string;
We'll have to bring this, the xterm-headless types and the public/Terminal.ts implementation back as we can only remove a deprecated feature in a major version.

2022-03-02 03:51 UTC, childrentime commented on typings/xterm.d.ts
> -    getOption(key: 'bellSound' | 'bellStyle' | 'cursorStyle' | 'fontFamily' | 'logLevel' | 'rendererType' | 'termName' | 'wordSeparator'): string;
got it. done.

2022-03-02 15:00 UTC, Tyriar approved these changes
Thanks 👍

2022-03-31 16:09 UTC, merged