add scroll bar decoration canvas
xtermjs/xterm.js pull request #3676
Opened 2022-03-09 14:49 UTC by meganrogge

2022-03-09 14:51 UTC, meganrogge commented on src/browser/Terminal.ts
> +    // TODO: make this opt in, must be done before the scroll area in order to show up
not sure how can I make this opt in given that this canvas element must be appended to the viewport before the scroll area is to work

2022-03-09 14:52 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +  WIDTH = 7
should this be `actualCellWidth` instead?

2022-03-09 18:45 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +  WIDTH = 7
or passed in via the `DecorationOptions`?

2022-03-11 06:02 UTC, meganrogge commented on src/browser/Terminal.ts
> +    // TODO: make this opt in, must be done before the scroll area in order to show up
seems like this messes with things/ causes api tests to fail

2022-03-11 20:28 UTC, Tyriar requested changes
One theme I've noticed that I think we should move away from is the idea of buffer decorations vs scroll bar decorations. Instead there are decorations, all decorations are rendered in the buffer and some get rendered in the scroll bar. I think the latter is how it works but most of the code is structured in the other direction.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/Terminal.ts
> +    // TODO: make this opt in, must be done before the scroll area in order to show up
Before the `this._viewportScrollArea` you mean? You can use `insertBefore` instead of `appendChild`. That combined with an option like `overviewRuler? boolean` should do the trick.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  WIDTH = 7
Here's monaco's API:

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.IModelDecorationOverviewRulerOptions.html

You can set a color, a darkColor and a position (full, left, right, center). Getting that same granularity around positioning would be good, I don't think we need a dark color though.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
>  export class DecorationService extends Disposable implements IDecorationService {
It looks like this class does a little too much now, how about splitting it up like this?

<img width="715" alt="Screen Shot 2022-03-11 at 12 06 50 pm" src="https://user-images.githubusercontent.com/2193314/157951655-0e0f7ecb-ed1d-4c27-ab4c-b8e846cb41af.png">

That way all DecorationService does is collects and manages all the decorations and fires events for components that depend on decorations.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  private _scrollbarDecorationNode: HTMLCanvasElement | undefined;
Naming that aligns with other areas:

```ts
  private _scrollbarDecorationCtx: CanvasRenderingContext2D | null = null;
  private _scrollbarDecorationCanvas: HTMLCanvasElement | undefined;
```

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  private _scrollbarDecorations: ScrollbarDecoration[] = [];
There should only be a single list of decorations imo, it's up to the consumer of the decoration to filter out appropriately:

```ts
// Imagine after overview ruler refactor
for (const decoration of decorationService.decorations) {
  if (!decoration.scrollbarDecorationColor) {
    continue;
  }
  // do the thing
}
```

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +      this._scrollbarDecorationNode!.style.display = this._bufferService.buffer === this._bufferService.buffers.alt ? 'none' : 'block';
`!` is unsafe here since `_scrollbarDecorationNode` is not read only. Another reason splitting out the service from view is good is we could initialize the overview ruler only after `open` has been called so it could be readonly.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +  public get color(): string { return this._color!; }
More `!` we want to avoid

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
>      }
`_element` could be merged into `_canvas`?

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +      window.devicePixelRatio
This will make the line blurry when 1 < dpr < 2.

2022-03-11 20:28 UTC, Tyriar commented on src/browser/services/DecorationService.ts
> +    );
Because of the blurriness, this probably won't be sufficient. If multiple decorations are around the same zone and devicePixelRatio is a decimal, this `clearRect` could end up clearing other decorations as well. I think instead of getting the exact decimal value, you'll want to get the closest pixel on the canvas and fill that in, then maybe use `Math.round(window.devicePixelRatio)` for the line size to ensure that's a crisp pixel-perfect rectangle regardless of zoom.

2022-03-11 22:02 UTC, meganrogge commented on css/xterm.css
> +    position: sticky;
as we discussed, `sticky` can work here, but going to go with absolute in order to avoid the native scrollbar overlay issue

2022-03-11 22:04 UTC, meganrogge commented on src/browser/services/DecorationService.ts
>      }
thought we wanted `decoration.element` to be undefined until the first `render` happens?

2022-03-12 02:46 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +  WIDTH = 7
not sure we need to support `center` as I don' think that's practical for the terminal.

2022-03-12 02:50 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +  private _scrollbarDecorations: ScrollbarDecoration[] = [];
didn't want to have to filter them out, but yeah the services refactor will prevent that

2022-03-14 13:45 UTC, meganrogge commented on src/browser/services/DecorationService.ts
> +    );
by the line size, do you mean `lineWidth`?

2022-03-15 16:44 UTC, meganrogge commented
To do or to defer:

- api tests

2022-03-15 17:24 UTC, Tyriar reviewed
Sorry forgot to post this, most are probably out of date

2022-03-15 18:20 UTC, Tyriar requested changes

2022-03-15 18:20 UTC, Tyriar commented on src/browser/Decorations/OverviewRulerRenderer.ts
> +    this._ctx.strokeRect(
In monaco the height of the decoration depends on the position:

![image](https://user-images.githubusercontent.com/2193314/158442602-9dd827e2-8ccf-4f06-81bc-f9d3671f5136.png)

Looks like full has a height of 2 CSS pixels and non-full has a height of 6 CSS pixels.

The decorations are also really large when the file has little contents, I think we can avoid doing that though. This is showing a 5 line file with a single word highlighted:

![image](https://user-images.githubusercontent.com/2193314/158442847-3d02fd76-34ba-4ee2-b07f-af63e6cba082.png)

2022-03-15 18:20 UTC, Tyriar commented on src/browser/Terminal.ts
>    private _mouseService: IMouseService | undefined;
Actually, I changed my mind about this overnight. Since we're not supporting decorations in xterm-headless at all, this should live in the `browser/` file so code that never runs doesn't end up showing up in the headless bundle. I'm a little on the fence about whether `DecorationService` should live in common or browser, let's keep it in common for now since it won't be included in the compiled bundle unless it's referenced.

```suggestion
  // browser services
  private _decorationService: DecorationService;
  private _charSizeService: ICharSizeService | undefined;
  private _mouseService: IMouseService | undefined;
```

2022-03-15 18:20 UTC, Tyriar commented on src/browser/Terminal.ts
> +    this._instantiationService.createInstance(BufferDecorationRenderer, this.screenElement);
```suggestion
    this.register(this._instantiationService.createInstance(BufferDecorationRenderer, this.screenElement));
```

2022-03-15 18:20 UTC, Tyriar commented on src/browser/tsconfig.json
> +],
I might have caused this 🤷 

```suggestion
  ],
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
> +     * The width, in pixels, of the canvas for the overview ruler.
```suggestion
     * The width, in pixels, of the canvas for the overview ruler. The overview
     * ruler will be hidden when not set.
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
> +   * Represents a disposable with an
```suggestion
   * Represents a disposable that tracks is disposed state.
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
> +     * after the first _onRender call, or undefined if accessed before
```suggestion
     * The element that the decoration is rendered to. This will be undefined
     * until it is rendered for the first time by @{link IDecoration.onRender}.
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
> +     * is provided.
```suggestion
     * The width of the decoration in cells, defaults to 1.
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
>       * cell height
```suggestion
     * The height of the decoration in cells, defaults to 1.
```

2022-03-15 18:20 UTC, Tyriar commented on typings/xterm.d.ts
> +     */
```suggestion
    /**
     * When defined, renders the decoration in the overview ruler to the right
     * of the terminal. {@link ITerminalOptions.overviewRulerWidth} must be set
     * in order to see the overview ruler.
     * @param color The color of the decoration
     * @param position Tge position of the decoration.
     */
```

2022-03-15 21:55 UTC, meganrogge commented on src/browser/Decorations/OverviewRulerRenderer.ts
> +    }
we also want to do this the first time the decoration is rendered I think? went with `updateAnchor`

2022-03-15 22:02 UTC, meganrogge commented on src/browser/Decorations/OverviewRulerRenderer.ts
> +    this._ctx.strokeRect(
it looks really weird when I do 2 and 6 pixels for the height
![Screen Shot 2022-03-15 at 6 02 27 PM](https://user-images.githubusercontent.com/29464607/158479915-e14fa44a-4a58-46f8-ba55-576b8547d62e.png)

2022-03-16 00:11 UTC, Tyriar approved these changes

2022-03-16 00:11 UTC, Tyriar commented on demo/client.ts
>    const decoration = term.registerDecoration({ marker });
Can we add overview ruler options to this one too?

2022-03-16 00:11 UTC, Tyriar commented on demo/client.ts
> +  term.registerDecoration({marker: term.addMarker(7), overviewRulerOptions: { color: '#729fcf', position: 'right' }});
The alignment seems off with these:

![image](https://user-images.githubusercontent.com/2193314/158492225-caf2d6c1-bcbd-4dbf-9be8-5ed2cbe6d672.png)

Also blue/right is being drawn largest?

2022-03-16 00:45 UTC, meganrogge commented on demo/client.ts
> +  term.registerDecoration({marker: term.addMarker(7), overviewRulerOptions: { color: '#729fcf', position: 'right' }});
yeah thought we shouldn't add a bunch of listeners to update that based on when zoom happens etc. it is correctly aligned when zoom level is 100%
![Screen Shot 2022-03-15 at 8 44 28 PM](https://user-images.githubusercontent.com/29464607/158495070-64e7bc4f-fbcd-4285-a37e-ec35c151cb5d.png)

2022-03-16 00:47 UTC, meganrogge commented on demo/client.ts
> +  term.registerDecoration({marker: term.addMarker(7), overviewRulerOptions: { color: '#729fcf', position: 'right' }});
spent awhile and am sort of stumped about what's going on with the ones on the same line - they're all too large, but the widths that get set and x positions are correct/ what I'd expect
![Screen Shot 2022-03-15 at 6 10 25 PM](https://user-images.githubusercontent.com/29464607/158495234-9033f039-a3d9-4eb1-8bec-f3270c62707b.png)

2022-03-16 01:13 UTC, merged