find all
xtermjs/xterm.js pull request #3698
Opened 2022-03-18 18:47 UTC by meganrogge

fixes #134790

2022-03-18 19:17 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (row) {
currently improving the name

2022-03-18 19:17 UTC, Tyriar requested changes

2022-03-18 19:17 UTC, Tyriar commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
Is this new API needed? VS Code builds on the current API with the `incremental` option to implement this behavior.

I was expecting a new `highlightAllMatches?: boolean` option or something to turn it on.

2022-03-18 19:17 UTC, Tyriar commented on css/xterm.css
> +   opacity: 60%;
nit

```suggestion
   opacity: 0.6;
```

2022-03-18 19:17 UTC, Tyriar commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
`overviewRulerResultDecorationColor` and `overviewRulerSelectionDecorationColor` are missing from the options

2022-03-18 19:17 UTC, Tyriar commented on demo/client.ts
> +    term.options.overviewRulerWidth = 10;
Let's leave this out and only turn the overview ruler on when the existing button is pressed.

2022-03-18 19:17 UTC, Tyriar commented on typings/xterm.d.ts
> +    registerMarker(cursorYOffset?: number, row?: number): IMarker | undefined;
I've contemplated an API like this but it couldn't be another optional arg like this. Can create an issue about it to discuss there and in the meantime always do the math (`ybase + cursory - row`)

2022-03-18 19:17 UTC, Tyriar commented on src/browser/Types.d.ts
> +  addMarker(cursorYOffset: number, col?: number, row?: number): IMarker | undefined;
Accident to include col? Also see other comment about this.

2022-03-18 19:17 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._terminal.onData(() => this._dataChanged = true);
Need to track the event listener disposable and dispose it when the addon is disposed.

2022-03-18 19:17 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
Why are these needed?

2022-03-18 19:17 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        e.style.color = color;
Think we only want bg color

2022-03-18 19:22 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (row) {
actually, I think `row` is the most appropriate here.

2022-03-18 19:25 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
I thought we wanted them in terminal.options, but believe you said add them to ISearchOptions instead?

2022-03-18 19:26 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
try:
- search for something "a"
- add lines to the buffer
- press enter
- the decorations are added to the existing ones and the search only had to start at the last covered row/col

https://github.com/meganrogge/xterm.js/blob/66dcd1694c915bcf56e08b354d0037407b0e4194/addons/xterm-addon-search/src/SearchAddon.ts#L100-L105

2022-03-18 19:29 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
since this API won't exist, it makes sense to put them in the terminal options instead

2022-03-18 19:30 UTC, meganrogge commented on demo/client.ts
> +    term.options.overviewRulerWidth = 10;
That would make it hard to test from a clean state though
![Screen Shot 2022-03-18 at 3 30 18 PM](https://user-images.githubusercontent.com/29464607/159071619-1b7d9a63-c195-42bf-b58f-ffc2a574e549.png)

2022-03-18 19:39 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
okay will think about that

2022-03-18 20:10 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
working on it

2022-03-18 21:54 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
Oh I see, I think this is done with `incremental` using the selection right now? How about tracking the active marker line and offset to know where to pick up instead?

2022-03-18 22:41 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
that's essentially what this is doing, but yeah can set those as class variables instead of passing them in

2022-03-18 22:47 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
Better to keep state like that out of the DOM, can it be tracked by keeping a reference to the decoration, marker or index of decoration in an array, etc.?

2022-03-18 23:39 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  startCol?: number;
that's what this is doing, but yeah I've made that more globally stored now

```
// set start row and col to avoid redoing work
      const key = Array.from(this._searchResults.keys()).pop()?.split('-');
      if (key?.length === 2) {
        startRow = Number.parseInt(key[0]);
        startCol = Number.parseInt(key[1]) + 1;
      }
```

2022-03-21 18:39 UTC, Tyriar requested changes

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +interface IDecorationColor {
Let's make this `IDecorationOptions` so it's more flexible if we need to add non-color things in the future without breaking the API.

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
We removing this one in favor of findNext/findPrevious?

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    });
This should get debounced to ensure we're not doing this every 200 ms, but only 200ms after no event

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      }, 200);
This create a new timeout on every onData event, there should only be a single timeout active at any time.

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +          this._highlightAllMatches(this._cachedSearchTerm, this._lastSearchOptions,'previous');
```suggestion
          this._highlightAllMatches(this._cachedSearchTerm, this._lastSearchOptions, 'previous');
```

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  private _highlightAllMatches(term: string, searchOptions: ISearchOptions, selectionType: 'next' | 'previous'): boolean {
I prefer const enums for strictly internal params like `selectionType`. I believe equality checks in Blink at least are O(1) as strings of the same value all share the same backing string, but I don't know if that's global for all javascript engines. For a const enum the backing values could be 0/1 which are guaranteed to be fast.

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  public clear(): void {
Does this need to be on the .d.ts? Should this be named `clearDecorations`?

2022-03-21 18:39 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._resultDecorations.clear();
This is done in 2 places, let's move it into a helper private function and also switch to using for const of loops

2022-03-21 18:41 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
>    incremental?: boolean;
Incremental isn't working correctly when highlighting all matches. Notice how the selection changes on every incremental search.

![Recording 2022-03-21 at 11 40 13](https://user-images.githubusercontent.com/2193314/159341892-d3bc98fd-449e-4b51-b653-b43564180c63.gif)

Unless enter is pressed the active search term should remain the same but just expand to the right

2022-03-21 19:35 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +interface IDecorationColor {
thought about that, but we already have an `IDecorationOptions`... will think of a different name so it's not confusing and is more generic though

2022-03-21 19:36 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +interface IDecorationColor {
went with `ISearchDecorationOptions`

2022-03-21 19:38 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +      public find(term: string, searchOptions?: ISearchOptions): boolean;
yep good catch, unused

2022-03-21 19:44 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._resultDecorations.clear();
tried to do that and it wouldn't let me because it's a map

2022-03-21 19:45 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._resultDecorations.clear();
made a helper though

2022-03-21 23:00 UTC, Tyriar requested changes

2022-03-21 23:00 UTC, Tyriar commented on css/xterm.css
> +
The addons should be self contained, we should move this and do `element.opacity = '0.6'`

2022-03-21 23:02 UTC, Tyriar commented on css/xterm.css
> +
Also should we assume the color that's used as the background includes the alpha channel instead?

2022-03-21 23:03 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    const marker = terminal.registerMarker(-terminal.buffer.active.baseY - terminal.buffer.active.cursorY + result.row);
hmm, but the decoration gets disposed of here anytime `highlightAllMatches` gets called

https://github.com/meganrogge/xterm.js/blob/7350d1b4a32edf4d4c0ec90cc22e8931457c5233/addons/xterm-addon-search/src/SearchAddon.ts#L93-L97

2022-03-21 23:04 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    const marker = terminal.registerMarker(-terminal.buffer.active.baseY - terminal.buffer.active.cursorY + result.row);
oh I see yeah the marker not the decoration, yeah that seems like a problem

2022-03-21 23:05 UTC, Tyriar commented on css/xterm.css
> +
I'll move forward and bring this up with you tomorrow.

2022-03-22 00:01 UTC, Tyriar approved these changes

2022-03-22 00:01 UTC, merged