Add search result count to SearchAddon
xtermjs/xterm.js pull request #3716
Opened 2022-03-28 19:40 UTC by meganrogge

fixes #1659

2022-03-28 19:41 UTC, meganrogge commented
We can either do it this way or could return the count from findNext/findPrevious instead of a boolean

2022-03-28 20:16 UTC, Tyriar reviewed
Do we only know the total count if decorations are on? What would this return if it's off so only a single result is selected?

2022-03-28 20:59 UTC, meganrogge commented
Yes we only know this if decorations are on. I think that's what we want because otherwise don't want to do all of this processing. When decorations are on, all of that work has already been done, so might as well leverage it.

2022-03-29 16:53 UTC, meganrogge commented
We discussed and agreed upon:
- using a property instead of a function  (✔️ )
- only enabling this when decorations are provided as an option (✔️ )
- returning from findNext/findPrevious instead of a separate API (decided against to keep things clear)

2022-03-29 19:37 UTC, Tyriar requested changes

2022-03-29 19:37 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +interface IListener<T, U = void> {
You can see the webgl addon for how to pull in parts for xterm.js core:

https://github.com/Tyriar/xterm.js/blob/eca36458b394ce980957518f23d53c10af7e13ff/addons/xterm-addon-webgl/src/tsconfig.json#L31-L38

Just need to be very careful only to include low level platform things as all code pulled in will get duplicated in the search addon's js bundle.

2022-03-30 01:38 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +interface IListener<T, U = void> {
not sure if I did that right - bunch of errors

2022-03-30 01:52 UTC, meganrogge commented on addons/xterm-addon-search/tsconfig.json
> +    { "path": "./test" },
```suggestion
    { "path": "./test" }
```

2022-03-30 01:53 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    // this._terminal?.clearSelection();
```suggestion
```

2022-03-30 01:58 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      this._onDidChangeResults.fire();
```suggestion
      // When data is added to the buffer that yields new search results, fire this so the match result count can be updated
      this._onDidChangeResults.fire();
```

2022-03-30 16:03 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      const incremental = searchOptions && !(searchOptions.decorations && this._previousWasLastCall) ? searchOptions.incremental : false;
This fixes a problem sometimes where the selection is wrong when switching between find previous/next. I''m not sure why that's required and will investigate further. 

The result index is also sometimes not quite right when switching between find next / previous

2022-03-30 16:38 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        if (this._lastSearchOptions?.decorations && this._cachedSearchTerm && this._resultDecorations?.size && this._resultDecorations.size > 0 && this._lastSearchOptions) {
move decorations above the timeout

2022-03-30 16:40 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        if (this._lastSearchOptions?.decorations && this._cachedSearchTerm && this._resultDecorations?.size && this._resultDecorations.size > 0 && this._lastSearchOptions) {
override search options incremental

{ ...this._lastSearchOptions, incremental: true }

2022-03-30 16:42 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._searchResults?.clear();
set searchResults to undefined and resultDecorations

2022-03-30 16:43 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this._searchResults?.clear();
after dipsoseDecorations, also clear resultDecorations

2022-03-30 16:46 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    } else if (searchOptions?.decorations) {
pull if above other if

2022-03-30 16:54 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      const incremental = searchOptions && !(searchOptions.decorations && this._previousWasLastCall) ? searchOptions.incremental : false;
check if incremental is true here

2022-03-30 16:55 UTC, meganrogge commented on addons/xterm-addon-search/src/tsconfig.json
> +        "../../../src/browser/*"
try to remove this

2022-03-30 16:55 UTC, meganrogge commented on addons/xterm-addon-search/src/tsconfig.json
> +      "path": "../../../src/browser"
try to remove browser

2022-03-30 16:56 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +     * @returns the result index and result count if decorations are provided or a boolean
fix

2022-03-30 16:56 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +     * indicating if there was a match
revert

2022-03-30 16:56 UTC, meganrogge commented on addons/xterm-addon-search/typings/xterm-addon-search.d.ts
> +    onDidChangeResults: IEvent< { resultIndex: number, resultCount: number } | undefined>;
only fires when decorations are enabled
readonly and fix space

2022-03-30 17:49 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +  private readonly _onDidChangeResults = new EventEmitter<{resultIndex: number, resultCount: number} | undefined>();
I don't think this actually needs to be registered because isn't used anywhere other than for testing / logging

2022-03-30 18:10 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    } else if (searchOptions?.decorations) {
and do same for the previous

2022-03-30 18:10 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this.onDidChangeResults((e) => console.log(e));
remove

2022-03-30 21:31 UTC, Tyriar approved these changes

2022-03-30 21:31 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this.onDidChangeResults((results) => console.log(results));
Missed this one

2022-03-31 00:08 UTC, merged

2022-03-31 00:59 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +    this.onDidChangeResults((results) => console.log(results));
think that was outdated as I don't see it there