share animation frame with renderService
xtermjs/xterm.js pull request #3796
Opened 2022-05-12 22:39 UTC by meganrogge

2022-05-13 13:20 UTC, Tyriar requested changes

2022-05-13 13:20 UTC, Tyriar commented on src/browser/decorations/BufferDecorationRenderer.ts
> -    });
I was expecting a similar structure to `window.requestAnimationFrame` here:

```ts
if (this._animationFrame !== undefined) {
  return;
}
this._animationFrame = this._renderService.requestAnimationFrame(() => {
  this.refreshDecorations();
  this._animationFrame = undefined;
});
```

I don't think the current change will fix the problem as refreshing the buffer decoration renderer would be skipped if the renderer is doing something, otherwise it would refresh in the frame that requested it, which is bad since it's not an animation frame.

2022-05-13 16:51 UTC, Tyriar requested changes

2022-05-13 16:51 UTC, Tyriar commented on src/browser/Types.d.ts
> +  requestAnimationFrame(callback: FrameRequestCallback): number | undefined;
I guess it doesn't make sense to have this on `TimeBasedDebouncer`, shall we remove it from the interface and have `RenderService` use the concrete `RenderDebouncer` instead?

2022-05-13 16:51 UTC, Tyriar commented on src/browser/RenderDebouncer.ts
> +  public requestAnimationFrame(callback: FrameRequestCallback): number | undefined {
We want to keep track of an array of callbacks here and call them all at the end of `_innerRefresh`, that will guarantee the callbacks are run in the same animation frame as `_renderCallback`

2022-05-13 18:25 UTC, meganrogge commented on src/browser/Types.d.ts
> +  requestAnimationFrame(callback: FrameRequestCallback): number | undefined;
I'm not sure what you mean by use the concrete `RenderDebouncer`, but i've added an interface which extends IRenderDebouncer instead

2022-05-13 18:32 UTC, Tyriar commented on src/browser/Types.d.ts
> +  requestAnimationFrame(callback: FrameRequestCallback): number | undefined;
@meganrogge the time based debouncer doesn't use an animation frame but a set timeout instead, so you should not be able to request an animation frame for it

2022-05-13 18:49 UTC, meganrogge commented on src/browser/Types.d.ts
> +  requestAnimationFrame(callback: FrameRequestCallback): number | undefined;
yeah updated the code so I don't have that on there anymore

2022-05-13 18:59 UTC, Tyriar requested changes

2022-05-13 18:59 UTC, Tyriar commented on src/browser/RenderDebouncer.ts
> +  }
This should return `number` instead of `number | undefined` and trigger a new animation frame if _animationFrame isn't set yet. This could happen if a decoration is added but there are no calls to trigger a refresh in the renderer, we may have other code that prevents that from happening elsewhere by decorations forcing a refresh but that could change/be refined:

```suggestion
  public addRefreshCallback(callback: FrameRequestCallback): number | undefined {
    this._refreshCallbacks.push(callback);
    if (!this._animationFrame) {
          this._animationFrame = window.requestAnimationFrame(() => this._innerRefresh());
    }
    return this._animationFrame;
  }
```

That alone won't work though since currently refreshes are only valid if they have rowStart/end/count set:

https://github.com/xtermjs/xterm.js/blob/2fa125904a5677c42d8676900dc9a3a858179fa7/src/browser/RenderDebouncer.ts#L46-L49

I'm thinking for that case we should still trigger all the callbacks and clear them out. Something like:

```ts
private _innerRefresh(): void {
  if (this._rowStart !== undefined && this._rowEnd !== undefined && this._rowCount !== undefined) {
    // refresh buffer
  }
  for (const callback of this._refreshCallbacks) {
    callback(0);
  }
  this._refreshCallbacks = [];
}
```

2022-05-13 19:02 UTC, meganrogge commented on src/browser/RenderDebouncer.ts
> +  }
okay yeah that makes sense.

2022-05-16 19:09 UTC, meganrogge commented
tests are passing when I run them locally.

2022-05-17 14:27 UTC, Tyriar approved these changes

2022-05-17 16:52 UTC, merged