if cached line is empty, translate buffer line to string
xtermjs/xterm.js pull request #3811
Opened 2022-05-14 00:52 UTC by meganrogge

fixes #3794

2022-05-16 14:54 UTC, Tyriar requested changes

2022-05-16 14:54 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
This will end up causing a lot of re-checking empty rows, the root of the issue seems to be listening to the public `onData` API (ie. onKey press). I think we actually want to listen debounced to either when write data is parsed or when the buffer changes.

2022-05-16 15:20 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
ok, will have to add a new event for either of those as currently (and to my surprise), `onBufferChange` currently fires when the buffer type changes from `active` to `alt` or vice-versa - not when the buffer changes.

listening to when write data is parsed is probably better bc I think it would be the same issue with `onBufferChange` since the buffer would change (a new empty row would be added) and that value of `""` would be stored and then never updated.

2022-05-16 15:26 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
It's `onBufferChange` vs `onRenderedBufferChange` that might be confusing? We don't want either at the latter is only when the viewport changes but we want when anywhere in the buffer changes. Let's talk about better names and the right fix for this offline.

2022-05-16 17:36 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
`onRenderedBufferChange` => `onRenderedViewportChange`

new one: `onBufferContentsChange`

2022-05-16 17:42 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
fire event at end of innerWrite in writeBuffer
onWriteBufferParsedData

expose public API `onParseData` in

2022-05-16 17:48 UTC, meganrogge commented on addons/xterm-addon-search/src/SearchAddon.ts
> +      // line is empty, check it again to avoid issues like #3794
track aboslute cursor position and then always refresh the line that it searched up to and everything below

2022-05-16 23:01 UTC, Tyriar requested changes

2022-05-16 23:01 UTC, Tyriar commented on typings/xterm.d.ts
> +    onBufferContentsChange: IEvent<void>;
Was just writing up some jsdoc to also call out the fact that this isn't entirely correct. I think the better thing here is to make the event name more correct so we don't need to call out caveats.

```suggestion
    /**
     * Adds an event listener for when data has been parsed by the terminal,
     * after {@link write} is called. This event is useful to listen for any
     * changes in the buffer.
     * 
     * This fires at most once per frame, after data parsing completes. Note
     * that this can fire when there are still writes pending if there is a lot
     * of data.
     */
    onWriteParsed: IEvent<void>;
```

2022-05-17 14:18 UTC, Tyriar approved these changes

2022-05-17 17:00 UTC, merged