Support setting extended ansi colors (16-255)
xtermjs/xterm.js pull request #3905
Opened 2022-07-18 15:54 UTC by silamon

The API is slightly different than proposed in #3601. It is aligned with the current ITheme variables and taking a string[] array of hex values. 

Fixes #3601

2022-07-18 16:21 UTC, Tyriar requested changes
Looks good, just one suggestion 👍

2022-07-18 17:46 UTC, merged

2022-07-18 18:58 UTC, Tyriar commented on src/browser/ColorManager.ts
> +    }
Yeah there was an issue with my code above, I think it was fixed in https://github.com/xtermjs/xterm.js/pull/3905/commits/c786c6a072721c8eda3cf66a1b0a792712978956 though

2022-07-18 21:54 UTC, jerch commented on src/browser/ColorManager.ts
> +    }
Yeah partially (though I dont like `i-16` on indexes, but thats just my defensive coding style to avoid potential underruns). Whats with `max` vs. `min`? 

Another minor code smell:
It might be a good idea not to limit on a magic number of 256. Could this be pulled from `this.colors.ansi.length` or some setup value of the default containers? Again defensive style - just in case the number of colors might change in the future. Always fun to debug magic numbers later on, that seemed so obvious in the first place.

2022-07-19 15:58 UTC, silamon commented on src/browser/ColorManager.ts
> +    }
I see the following-up pull request has been made and merged already. But I think we also forgot the case where consecutive setTheme makes it unpossible to reset the extendedAnsi to default?

For example:
```js
setTheme({extendedAnsi: ["#000000", "#000000"]})
setTheme({}) // should this reset the extendedAnsi back to default?
```

2022-07-19 16:04 UTC, jerch commented on src/browser/ColorManager.ts
> +    }
@silamon Oh well, this seems to be a rather good idea, otherwise thats not possible at all from outside?

2022-07-19 16:38 UTC, jerch commented on src/browser/ColorManager.ts
> +    }
Wouldn't a simple `this.colors.ansi = DEFAULT_ANSI_COLORS.slice();` infront of all ansi color code do?

2022-07-19 16:50 UTC, Tyriar commented on src/browser/ColorManager.ts
> +    }
> Wouldn't a simple this.colors.ansi = DEFAULT_ANSI_COLORS.slice(); infront of all ansi color code do?

`setTheme` does indeed reset everything after looking at the code, so this would be the right approach. That makes sense as taking VS Code as an example, a theme may not specify some colors, in which case we would want the defaults not the previously active theme colors.

2022-07-19 17:09 UTC, silamon commented on src/browser/ColorManager.ts
> +    }
I'll create a PR to address this.