Fix memory leak
xtermjs/xterm.js pull request #3916
Opened 2022-07-21 19:35 UTC by SvanT

https://github.com/microsoft/vscode/issues/155232

After doing v8 heap profiling I found out that using terminal references
in the atlas cache makes it impossible for js to garbage collect the
terminals after disposal, causing both gpu and ram memory leak, therefore
switching to a simpler solution by just using an immutable id to break
the reference chain.

2022-07-21 19:38 UTC, Tyriar reviewed
Thanks for digging into this, do you think we could use [`WeakRef`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#avoid_where_possible) here instead to fix it so we could avoid adding the id prop?

2022-07-21 19:51 UTC, SvanT commented
Thanks for the fast review :)

I think that could be a good fit here perhaps (I haven't used it before but seems to tackle this kind of problems), but it seems like you have kind of IE11 support. Introducing a polyfill and [probably using ESNext](https://stackoverflow.com/a/66256279) as target for typescript could be a bit overkill for just an "identifier"?

Whatever you choose I can give it a try if you want, or feel free to refactor if you wish.

2022-07-21 22:24 UTC, Tyriar requested changes
IE11's end of life was in June so I wouldn't let that stop us. I'm going to remove that note in the README now 😎

Let's try `WeakRef`, I haven't used it before so let me know if there are problems.

2022-07-22 12:11 UTC, Tyriar approved these changes

2022-07-22 12:11 UTC, Tyriar commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    removeTerminalFromCache(this._terminal);
Wonder why we didn't do that to begin with... Maybe because dispose in WebGL was only really properly done after your initial report? Thanks for looking into this! 👍

2022-07-22 12:11 UTC, merged