Dispose events
xtermjs/xterm.js pull request #3919
Opened 2022-07-23 11:34 UTC by SvanT

https://github.com/microsoft/vscode/issues/155232

The events that is setup for needs to be disposed for js to be able
to garbage collect the terminals.

2022-07-23 11:35 UTC, SvanT commented
@Tyriar this combined with https://github.com/microsoft/vscode/pull/155976 seems to finally make it so that vscode garbage collects terminals directly after they are closed :)

2022-07-27 11:54 UTC, Tyriar requested changes
Great finds, just some clean up/best practices

2022-07-27 11:54 UTC, Tyriar commented on addons/xterm-addon-webgl/src/renderLayer/CursorRenderLayer.ts
> +    }
Little more concise:

```suggestion
    this._cursorBlinkStateManager?.dispose();
    this._cursorBlinkStateManager = undefined;
```

2022-07-27 11:54 UTC, Tyriar commented on src/browser/Linkifier.ts
> +  }
The preferred way here is to have the class `extend Disposable` and register the emitters:

```ts
private _onShowLinkUnderline = this._register(new EventEmitter<ILinkifierEvent>());
```

2022-07-27 11:54 UTC, Tyriar commented on src/browser/Types.d.ts
> +  dispose(): void;
If we extend `Disposable` this interface could extend `IDisposable`

2022-07-27 11:54 UTC, Tyriar commented on src/browser/Terminal.ts
> +    this.linkifier2.dispose();
When extending Disposable:

```ts
    this.linkifier = this.register(this._instantiationService.createInstance(Linkifier));
    this.linkifier2 = this.register(this._instantiationService.createInstance(Linkifier2));
```

Looks like `linkifier2` is already getting registered.

2022-07-27 11:54 UTC, Tyriar commented on src/browser/Terminal.ts
> +    this._overviewRulerRenderer = undefined;
Best registered when it's created too

2022-07-27 12:28 UTC, SvanT commented
@Tyriar Thanks for the feedback, I've updated the PR with the changes and I did a test that the disposal still works as expected.

Just a quick question, what is the difference of creating instances of a class through the InstantiationService instead of creating them using new Class() ?

2022-07-28 14:03 UTC, Tyriar commented
@SvanT the instantiation service is used for dependency injection, when you call createInstance it will automatically fill in the params with the `@I...Service` decoration, like this:

https://github.com/xtermjs/xterm.js/blob/d2be5f992a639884f93520dd5f1ae2e9ae8c4730/src/browser/renderer/dom/DomRendererRowFactory.ts#L36-L44

2022-07-28 14:04 UTC, Tyriar commented
I merged in the big v5 changes into master and this PR, `Linkifier` doesn't exist anymore so that's no longer needed here

2022-07-28 17:52 UTC, Tyriar approved these changes

2022-07-28 17:52 UTC, merged