Allow markers on the alt buffer
xtermjs/xterm.js pull request #3924
Opened 2022-07-24 09:44 UTC by silamon

Fixes #3918 

An additional event to trigger on buffer change wasn't needed, since the onWriteParsed is being triggered.

2022-07-29 14:26 UTC, Tyriar requested changes
One special thing that comes to mind here is for alt buffers we want to dispose all buffers as soon as the active buffer switches back to the normal buffer. I think the fix for that would be to call `clearAllMarkers()` here:

https://github.com/xtermjs/xterm.js/blob/055bcce18de91f329f61261aa1c81c1da231f7a9/src/common/buffer/BufferSet.ts#L83-L86

2022-07-31 07:42 UTC, silamon commented
> 

Without clearAllMarkers, you can see that the alt buffer decorations persist on the screen until the normal buffer is rendered. The search addon disposes the decorations/markers then on the onWriteParsed() event. Adding clearAllMarkers disposes them before clearing the all buffer. 

It might be even better to add clearAllMarkers to the clear function of the buffer (?)

2022-07-31 21:32 UTC, Tyriar commented
@silamon since markers are changing to work also in the alt buffer we'll need to cover all marker use cases, this means making them invalid when alt -> normal happens. To validate which solution is best you could also run this while the alt buffer is up:

```ts
const m = term.registerMarker();
```

Switch the the normal buffer and make sure `m` is now disposed.

2022-07-31 21:37 UTC, Tyriar approved these changes
Seems to work as expected 👍

2022-07-31 21:37 UTC, Tyriar commented on src/common/buffer/BufferSet.test.ts
> +
```suggestion
```

2022-07-31 21:38 UTC, Tyriar commented
> The search-addon decorations are very hard to see with the background changes.

Do you mean the demo theme changes? The demo's options.theme isn't tied to the search theme currently and it's probably overkill for the demo. You can always switch the theme now though:

<img width="161" alt="Screen Shot 2022-07-31 at 2 38 25 pm" src="https://user-images.githubusercontent.com/2193314/182046354-f8d2d984-1a6f-4e5f-bdaf-097f77e1c1a1.png">

2022-07-31 21:39 UTC, Tyriar commented
> It might be even better to add clearAllMarkers to the clear function of the buffer (?)

Adding to `clear` would call it in the normal buffer as well and I think there might be a problem with that. Just doing it for the alt buffer is the safer approach.

2022-07-31 21:39 UTC, merged