Fix typo and remove unnecessary eslint comments
xtermjs/xterm.js pull request #4055
Opened 2022-08-23 07:20 UTC by GreenMashimaro

### Description
fix typo and remove unnecessary eslint comments

### What is the purpose of this pull request?

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

2022-08-23 14:05 UTC, Tyriar requested changes

2022-08-23 14:05 UTC, Tyriar commented on src/browser/LocalizableStrings.ts
> -export let tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
This actually needs to be `let`, it's exposed to embedders of xterm.js so they can change the strings to localize xterm.js. It's exposed (as non-readonly) here https://github.com/xtermjs/xterm.js/blob/c0ef2ccb5a0b2f22f28ed594f3962d75cc83da00/src/browser/public/Terminal.ts#L242-L244

2022-08-23 14:05 UTC, Tyriar commented on src/common/buffer/BufferSet.ts
>    public get normal(): Buffer {
👍 this is a problem

2022-08-24 02:01 UTC, GreenMashimaro commented on src/browser/LocalizableStrings.ts
> -export let tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
Thanks for your reply, I have a few questions.

I verified it myself within the project.

### Question1: From the compilation results, the two are the same.

original code
``` typescript
export let promptLabel = 'Terminal input';
export let tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
```
after compilation code
``` javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tooMuchOutput = exports.promptLabel = void 0;
exports.promptLabel = 'Terminal input';
exports.tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
//# sourceMappingURL=LocalizableStrings.js.map
```
------
original code
``` typescript
export const promptLabel = 'Terminal input';
export const tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
```
after compilation code
``` javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.tooMuchOutput = exports.promptLabel = void 0;
exports.promptLabel = 'Terminal input';
exports.tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
//# sourceMappingURL=LocalizableStrings.js.map
```


------
### Question2: Use `let` to declare variables; the value cannot be modified in the import place.

![image](https://user-images.githubusercontent.com/23225539/186300790-e1cebf1f-b2eb-4eb9-8a26-b6e9879cc38d.png)

2022-08-24 12:14 UTC, Tyriar commented on src/browser/LocalizableStrings.ts
> -export let tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
Ah I see, still using const shows the wrong intent here. `const` means this value should not change, and while currently TypeScript outputs is as mutable, it may not in the future. So I think we should keep this as it was

2022-08-24 14:45 UTC, GreenMashimaro commented on src/browser/LocalizableStrings.ts
> -export let tooMuchOutput = 'Too much output to announce, navigate to rows manually to read';
I think your idea is good, and I suggest adding a comment. I re-updated the submission, please review it.

2022-08-24 15:55 UTC, Tyriar approved these changes
Thanks!

2022-08-24 15:55 UTC, merged