Handle WebGL context loss/restore events in WebGL addon.
xtermjs/xterm.js pull request #4075
Opened 2022-08-26 23:55 UTC by kenrussell

Define a new WebglAddon.onNeedsRedraw event which signals to embedders
that the terminal needs to be refreshed. Fire this event upon a
webglcontextlost / webglcontextrestored event pair internally, first
reinitializing WebglRenderer's internal state.

Respond to the event in the demo's client by refreshing the terminal.

Tested in Chrome Canary on macOS by running the demo in one window,
and visiting the internal URL about:gpucrash in another window. The
terminal now recovers and redraws properly.

2022-08-26 23:59 UTC, kenrussell commented
Note to maintainers: this was originally developed in the context of VS Code's embedded terminal, attempting to make it more robust. It's expected that context losses would be rare, but they can happen due to issues out of the browser's control.

If this PR is accepted, I'd be interested in rolling forward VS Code's xterm.js reference and upstreaming the needed patch there to respond to the new `onNeedsRedraw` event.

2022-08-29 16:49 UTC, kenrussell commented
@Tyriar would you be able to review this? It improves robustness of the Terminal in the face of external graphics issues.

2022-08-30 13:02 UTC, Tyriar requested changes
Idea looks good overall 👍. Also I didn't know about `about:gpucrash`, pretty handy!

2022-08-31 02:47 UTC, kenrussell commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +  private _contextRestorationTimeout: number = 0;
Thanks! Done.

2022-08-31 02:49 UTC, kenrussell commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +      this._onNeedsRedraw.fire(e);
Ah, great! Thanks for pointing this out. Have removed now-unneeded changes.

2022-08-31 02:49 UTC, kenrussell commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    this._glyphRenderer = new GlyphRenderer(this._terminal, this._colors, this._gl, this.dimensions);
Thanks, done.

2022-08-31 05:22 UTC, kenrussell commented
Thanks for your review! All feedback addressed. It's much simpler and completely self-contained now!

2022-08-31 12:45 UTC, Tyriar approved these changes
Looks good, thanks!

2022-08-31 12:56 UTC, merged