protection flag support
xtermjs/xterm.js pull request #4098
Opened 2022-09-03 21:53 UTC by jerch

Fixes #3651.

2022-09-07 16:26 UTC, Tyriar requested changes
Haven't tested but looks good other than my clean up comment

2022-09-07 16:26 UTC, Tyriar commented on src/common/InputHandler.ts
> +    line.fill(this._activeBuffer.getNullCell(this._eraseAttrData()), protect);
I was a little confused reading the PR initially because it seemed like `protect` here was a cell's protection attribute being applied to the entire line. Would these be better as `respectProtect`? Also `@param` docs here would help

2022-09-07 17:48 UTC, jerch commented on src/common/InputHandler.ts
> +    line.fill(this._activeBuffer.getNullCell(this._eraseAttrData()), protect);
Changed.

2022-09-12 12:52 UTC, Tyriar approved these changes

2022-09-12 12:52 UTC, merged