Lint using 🐊Putout: part 7
xtermjs/xterm.js pull request #4118
Opened 2022-09-14 23:21 UTC by coderaiser

![image](https://user-images.githubusercontent.com/1573141/190278168-969be0a5-f70f-4376-80c2-05ae6ee317f7.png)

>**Throughout your life advance daily, becoming more skillful than yesterday more skillful than today. This is never-ending.**
>
> **(c) Yamamoto Tsunetomo "Hagakure"**

The time is come for a new report of **Xterm** linting by 🐊[**v27**](https://github.com/coderaiser/putout/releases/tag/v27.0.0):

☝️ *As usual, any rule can be disabled.*

Command used:

```sh
putout . --fix
```

Applied rules:
- ✅ [apply-comparison-order](https://github.com/coderaiser/putout/tree/v27.8.0/packages/plugin-apply-comparison-order#readme)
- ✅ [convert-for-each-to-for-of](https://github.com/coderaiser/putout/tree/v27.8.0/packages/plugin-convert-for-each-to-for-of)
- ✅ [remove-useless-escape](https://github.com/coderaiser/putout/tree/v27.8.0/packages/plugin-remove-useless-escape)
- ✅ [typescript/remove-useless-parens](https://github.com/coderaiser/putout/tree/v27.8.0/packages/plugin-typescript#remove-useless-parens)
- ✅ [regexp/optimize](https://github.com/coderaiser/putout/tree/v27.8.0/packages/plugin-regexp#regexpoptimize)

Current config for 🐊[Putout v27](https://github.com/coderaiser/putout):

```json
{
    "rules": {
        "apply-is-array": ["on", {
            "inline": true
        }],
        "new/remove-useless": "off",
        "remove-useless-return": "off",
        "typescript/remove-useless-types-from-constants": "off",
        "remove-useless-type-conversion/with-double-negations": "off",
        "convert-typeof-to-is-type": "off",
        "apply-shorthand-properties": "off",
        "apply-destructuring": "off",
        "apply-numeric-separators": "off",
        "convert-assignment-to-comparison": "off",
        "convert-apply-to-spread": "off",
        "convert-math-pow": "off",
        "convert-for-to-for-of": "off",
        "convert-template-to-string": "off",
        "strict-mode": "off",
        "remove-useless-spread/object": "off",
        "remove-useless-array-constructor": "off",
        "remove-boolean-from-assertions": "off",
        "remove-iife": "off",
        "remove-console": "off",
        "remove-unused-variables": "off",
        "remove-useless-variables": "off",
        "merge-if-statements": "off",
        "promises/add-missing-await": "off",
        "promises/remove-useless-async": "off",
        "simplify-ternary": "off",
        "nodejs/convert-dirname-to-url": "off",
        "nodejs/declare-after-requir": "off",
        "declare-imports-first": "off",
        "apply-array-at": "off",
        "try-catch": "off"
    },
    "match": {
        "*.benchmark.ts": {
            "remove-unused-expressions": "off"
        },
        "SerializeAddon.test.ts": {
            "regexp/optimize": "off"
        },
        "Terminal.ts": {
            "logical-expressions/remove-duplicates": "off"
        }
    },
    "plugins": [
        "apply-shorthand-properties"
    ],
    "ignore": [
        "addons/*/lib/*.js",
        "*.benchmark.js",
        "*.md",
        "*.json",
        "*ignore",
        "*.yml",
        ".npmrc",
        "*.css",
        "out",
        "out-test",
        "demo"
    ]
}
```

Previous reports: 
- [1](https://github.com/xtermjs/xterm.js/pull/2953)
- [2](https://github.com/xtermjs/xterm.js/pull/3133)
- [3](https://github.com/xtermjs/xterm.js/pull/3269)
- [4](https://github.com/xtermjs/xterm.js/pull/3341)
- [5](https://github.com/xtermjs/xterm.js/pull/3538)
- [6](https://github.com/xtermjs/xterm.js/pull/3674)

2022-09-15 11:14 UTC, jerch reviewed
@coderaiser Went only halfway through and have 2 remarks:
- Imho turning left/right side of conditionals is mostly unwanted. I think we want the local changing part on the left side, comparing to a more static right side.
- Some conditionals do border testing against a left and a right side. Imho thats easier to grasp, if the the numbers stay in mathematically logical order. (thus `left < var < right`, which translates to `left < v && v < right` in JS).

If we can agree on my remarks above, I think the changelist will get much shorter.

2022-09-15 11:14 UTC, jerch commented on src/common/Color.ts
> +    if (css.match(/#[\da-f]{3,8}/i)) {
Minor nitpick - should also let pass upper case hex digits?

2022-09-15 11:14 UTC, jerch commented on src/common/InputHandler.ts
> +        } while (subparams.length > ++i && accu.length > i + advance + 1 + cSpace);
I would not touch this and the following similar cases, as the execution order is very important. (The inline `++i` in a conditional would even generate a warning in C/C++ for that reason).

2022-09-15 12:11 UTC, Tyriar commented on addons/xterm-addon-canvas/src/GridCache.ts
> +  public cache: T[] | undefined[][];
Plus this doesn't feel like an improvement to me

2022-09-15 12:12 UTC, Tyriar commented on addons/xterm-addon-search/test/SearchAddon.api.ts
> +          .replace(/'/g, `'`);
This is a code scanning alert for the PR now, it does nothing in its current state

2022-09-15 12:14 UTC, Tyriar commented on addons/xterm-addon-search/src/SearchAddon.ts
> +        this._terminal.cols <= result.col + result.term.length ? 0 : result.col + 1,
Not a fan too, this rule would best be ignored

2022-09-15 12:16 UTC, Tyriar commented on src/common/Color.ts
> +    if (css.match(/#[\da-f]{3,8}/i)) {
`//i` = case insensitive

2022-09-15 14:26 UTC, coderaiser commented
Just disabled unneeded rules :).

2022-09-15 15:30 UTC, Tyriar commented on addons/xterm-addon-canvas/src/GridCache.ts
> +  public cache: T[] | undefined[][];
I find the former easier to read and less error prone; `info` is an array of things, where things = `Info | SuperInfo | MagicInfo`

2022-09-15 15:32 UTC, Tyriar requested changes

2022-09-15 15:32 UTC, Tyriar commented on src/common/services/InstantiationService.ts
> +        callback(key, value);
Wrong indent level:

```
/home/vsts/work/1/s/src/common/services/InstantiationService.ts
  33:1  warning  Expected indentation of 6 spaces but found 8  @typescript-eslint/indent
```

2022-09-15 19:53 UTC, coderaiser commented on src/common/services/InstantiationService.ts
> +        callback(key, value);
Just fixed

2022-10-04 16:51 UTC, Tyriar approved these changes

2022-10-04 17:45 UTC, merged