Adds logs again in server.js
xtermjs/xterm.js pull request #4194
Opened 2022-10-09 12:22 UTC by silamon

When I opened the demo terminal, the first line was missing. The terminal is functioning whatsoever. Looks like the terminal first line is sent before the terminal frontend is connected. Thanks to `ws.send(logs[term.pid]);` that line is sent to the terminal frontend when the terminal gets connected. 

This commit introducing this: https://github.com/xtermjs/xterm.js/commit/193d305dcd37537aa47758e580059ffd220b8723
This reverts it but keeps the higher timeout.

2022-10-09 13:23 UTC, Tyriar requested changes
Thanks! I saw this but had no idea why it was happening.

2022-10-09 13:23 UTC, Tyriar commented on demo/server.js
> +    });
Can we dispose of this listener once the terminal is connected? So after right that `ws.send` call? That will give us the best of both worlds.

We could then rename logs to something more descriptive to prevent this accident in the future, like `unsentOutput`?

2022-10-09 18:59 UTC, jerch commented on demo/server.js
> +    });
Oh well - yeah I removed it because it is a nuisance during perf measuring (backend constantly dies after testing a serious amount of data) - and I wasnt aware of the race condition (never happened for me). I think removing the aggregation buffer once the connection was successful would give us both advantages.

2022-10-15 17:17 UTC, Tyriar approved these changes
Thanks 😃

2022-10-15 17:17 UTC, merged