Add support to ANSI OSC52
xtermjs/xterm.js pull request #4220
Opened 2022-10-19 19:06 UTC by aymanbagabas

Add support to ANSI OSC52 sequence to manipulate selection and clipboard data. The sequence specs supports multiple selections but due to the browser limitations (Clipboard API), this PR only supports manipulating the clipboard selection.

Reference: https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
Fixes: https://github.com/xtermjs/xterm.js/issues/3260

2022-10-20 13:06 UTC, jerch commented
@aymanbagabas Thx for looking into this. A few notes from my side:

The service cannot go into `/common`, as this is also used for headless lib builds without a browser frontend. Thus the service with navigator notions should be under `/browser`, while `/common` may hold a stub, where integrators can hook in their own clipboard backend.

Furthermore clipboard access needs some thinking about the security implications. Imho it should be disallowed by default, and only granted explicitly by a user interaction (maybe also customizable, so integrators can disable the user feedback, if they have other measures in place). This is especially important for websites with xterm.js, as the browser clipboard might hold totally different content, that should not be accessible by some random terminal app.

2022-10-24 00:59 UTC, aymanbagabas commented
> @aymanbagabas Thx for looking into this. A few notes from my side:
> 
> The service cannot go into `/common`, as this is also used for headless lib builds without a browser frontend. Thus the service with navigator notions should be under `/browser`, while `/common` may hold a stub, where integrators can hook in their own clipboard backend.

Very reasonable, do you think exposing `attachClipboardService(IClipboardService)` in `/common/CoreTerminal.ts` is reasonable?

> Furthermore clipboard access needs some thinking about the security implications. Imho it should be disallowed by default (xterm even puts it under windowOps security setting), and only granted explicitly by a user interaction (maybe also customizable, so integrators can disable the user feedback, if they have other measures in place). This is especially important for websites with xterm.js, as the browser clipboard might hold totally different content, that should not be accessible by some random terminal app.
> 

I think adding an option to allow clipboard access makes sense. Perhaps add `allowClipboardAccess` as a terminal option? In `/browser` for more security, something like `confirm('Allow xterm.js to read from the clipboard?')` could be added in the service implementation when a clipboard read is performed. 

> Edit: Also the focus issue mentioned in https://github.com/xtermjs/xterm.js/issues/3260 needs some workaround for the browser part.

Will look into that once the API is in place.

2022-11-14 03:00 UTC, ghuntley commented
Howdy from https://coder.com ala https://github.com/coder. Dropping on by to say _thank-you_ for picking up this item. OSC52 support has been [requested by our community](https://github.com/coder/coder/issues/5001) and I'm opening up an open-source bounty payable when this item ships. Our way of saying thank-you. ❤️

2022-11-14 14:02 UTC, Tyriar commented
I probably won't be able to review this until early December, sorry about the delay.

2022-12-11 15:45 UTC, Tyriar requested changes

2022-12-11 15:45 UTC, Tyriar commented on src/common/InputHandler.ts
> +  private _clipboardService: IClipboardService | undefined;
Instead of an optional service here it would be better to first an onRequest event

2022-12-15 06:51 UTC, aymanbagabas commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
I'm using `Buffer` here to encode strings in base64. The browser comes with `atob()` and `btoa()`. We can achieve the same with `Buffer` here though. We can't encode strings to base64 with ArrayBuffer.

2022-12-15 10:14 UTC, jerch commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
Why base64 in the first place? Is this needed by the clipboard interfaces?

2022-12-15 13:11 UTC, aymanbagabas commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
Yes, base64 is needed by the OSC52 clipboard protocol.

> The second parameter, Pd, gives the selection data.  Normally
          this is a string encoded in base64 (RFC-4648).  The data
          becomes the new selection, which is then available for pasting
          by other applications.

2022-12-15 13:34 UTC, jerch commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
Then we need another workaround for this, prolly based on `atob/btoa` in the browser and `Buffer` in nodejs. We cannot use a foreign `Buffer` impl brigding this, as it would introduce a 3rd-party dependency at runtime. 

Furthermore our underlying data is codepoints in UTF-32, which lets me think that we might need a custom base64 encoder here, means  encode to utf-8 first (is the byte level meant to be in utf-8?), then encode to base64. Such an encoder also might have to deal with special characters like NUL (from empty cells), cannot find anything regarding that in the OSC 52 docs. Does anyone know?

2022-12-15 14:14 UTC, jerch reviewed
Just commenting for now, as I think that this still needs several iterations...

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +  public setOrReportClipboard(data: string): Promise<boolean> {
I'm not sure, if we are all happy with the promise return value here - as mentioned in last paragraph here: https://github.com/xtermjs/xterm.js/issues/3260#issuecomment-804228282 (note: the promise return here basically stops in-band progression of the terminal until the promise got resolved the good or the bad way).

On overall return values:
Where possible, the return value should by a sync value of `true|false` to not slow down the data processing too much. Furthermore, since this is a default handler in `InputHandler`, it should always return a true-ish value to not into exhaustion check in the parser.

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +  private _setOrReportClipboard(data: string): Promise<boolean> {
Return value should be `Promise<boolean> | boolean` (or just `boolean`, if we dont want to stop in-band processing at all).

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +      return Promise.resolve(false);
Return value should be flat `true`.

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +      return Promise.resolve(false);
Return value should be flat `true`.

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +    return Promise.resolve(false);
Return value should be flat `true`.

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +            });
If we stick with promises in OSC52 - it also needs a `.catch(e => true)` clause.

(Also below in more places.)

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +          return this._clipboardService.putData(pc, buf.toString()).then(() => true);
Needs a `.catch(e => true)` clause.

2022-12-15 14:14 UTC, jerch commented on src/common/InputHandler.ts
> +        return this._clipboardService.clearData(pc).then(() => true);
needs a `.catch(e => true)` clause.

2022-12-18 13:13 UTC, aymanbagabas commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
To avoid introducing the bridging dependency, we could detect if we're running NodeJS using `typeof window === 'undefined'` and use `Buffer.from`, otherwise, use `atob/btoa`. With this approach, we still need https://github.com/xtermjs/xterm.js/pull/4220/commits/a8856804ca6b937b6c46923e89c4f82afdfdab6c to make it compatible with both NodeJS and the browser. cc/ @Tyriar

2022-12-18 15:13 UTC, jerch commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
Well the distinction via `window` is unfortunate, as it might lead to issues in workers. How about something like that:
```js
const b64enc = (typeof btoa !== 'undefined') ? btoa : s => Buffer.from(s).toString('base64');
```
(Still would need some testing, whether it produces the same output for all allowed chars/control codes in OSC 52.)

2022-12-18 20:08 UTC, aymanbagabas commented on src/common/InputHandler.ts
> +  public setOrReportClipboard(data: string): Promise<boolean> {
Reading/writing from and to the [clipboard is an asynchronous](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#instance_methods) operation, thus the promise returns here.

2022-12-18 20:11 UTC, aymanbagabas commented on src/common/InputHandler.ts
> +  private _clipboardService: IClipboardService | undefined;
Could you please expand on this?

2022-12-19 12:17 UTC, jerch commented on src/common/InputHandler.ts
> +  public setOrReportClipboard(data: string): Promise<boolean> {
I think we dont need in-band processing here (means - synchronous to position in the input data), imho we can just spawn an internal event here, that gets digested by follow-up code (sync or async handled). Ofc this might lead to issues, if an app would spawn multiple OSC 52 sequences in a row (might stack up), or even expects it to be synchronous to a certain terminal buffer state. But the latter assumption should never be made on app side, as the terminal interface for back reporting is async by definition (and might not even respond to all requests).

Pros: We dont stop the parser at all (all sync return values), instead delegate processing to a later event handler invocation.
Cons: Possible stacking of OSC 52 requests, thus this needs a logic to throw away older not yet processed requests (maybe enqueued if it makes sense for the OSC52 actions).

2022-12-19 12:21 UTC, jerch commented on src/common/InputHandler.ts
> +              this._onClipboard.fire(Buffer.from(data).toString('base64'));
Ah sorry for the sloppy snippet - it still misses the unicode string to utf8 bytestring conversion for the `btoa` path. (would be needed for both `Base64.decode` and `Base64.encode`).

2022-12-19 12:48 UTC, jerch commented
@aymanbagabas To make that event idea more clear:

Imho all it needs in `common`, is a sync inputhandler function for OSC52 with two abstract interface "endpoints" - retrieve and place clipboard data. For maximum flexibility the endpoints can be feed from an clipboard event, to illustrate that:

```typescript
const enum ClipboardEventType {
  QUERY = 0,
  SET = 1
}
interface IClipboardEvent {
  type: ClipboardEventType;
  payload: string;
}

// in OSC52 function
// for request: emit {type: ClipboardEventType.QUERY, payload: ''}
// for set: emit {type: ClipboardEventType.SET, payload: 'unicode string data'}
```
Now all that needs to be done, is to interface that in way, so embedders can hook into it with their clipboard logic. Ideally we create a public API endpoint for this, e.g. `onClipboard((ev: IClipboardEvent) => void)`.

In a second step we can discuss, whether a default implementation should be provided from core repo  under `/browser` (I am not a big fan of this idea for security reasons), it is prolly a better idea to outsource the clipboard handler logic into an addon. This way embedders have explicit to hook their logic (hoopefully with security in mind), or explicit to load the addon, where we can place further security warnings and such.

2022-12-26 19:57 UTC, aymanbagabas commented
@jerch I've made the default implementation into a new addon `xterm-addon-clipboard`. You still need to enable the `allowClipboardAccess` option before the addon can work. Using the addon is as simple as loading it into xtermjs.

2022-12-28 05:22 UTC, jerch reviewed
Nice, looks really good already. Have not yet tested it, so first a few code comments from my side.

2022-12-28 05:22 UTC, jerch commented on src/common/Base64.ts
> +      btoa(data) :
Both `Base64.decode` and `Base64.encode` still need the patch for correctly handling higher unicode chars, eg. in encode:
- grab unicode string
- encode it to utf-8 bytes
- convert bytes to bytestring
- apply `btoa`

2022-12-28 05:22 UTC, jerch commented on src/common/Base64.ts
> +      Buffer.from(data, 'binary').toString('base64');
Shouldn't `binary` be `utf-8` here? I think we lose unicode support with binary here.

2022-12-28 05:22 UTC, jerch commented on src/common/InputHandler.ts
> +          if (Base64.encode(str) === pd) {
This decode->encode comparison will most likely create issues later on, as base64 is not stable/strict in its encoding rules, thus it might reject good cases, where the padding/whitespace settings used differ.

2022-12-28 05:22 UTC, jerch commented on typings/xterm.d.ts
> +  }
I think `const enum` is not a good idea in d.ts? Also it hides the real values, which makes it much harder to work with from JS side. Suggestion:
```typescript
  export interface IClipboardEvent {
    type: 'query' | 'set';
    selection: 'clipboard' | 'primary';
    payload?: string;
  }
```
and remove the enums.

Also what is this selection clipboard/primary thingy about? Is this important to keep working on all platforms or can we just drop the X11 only definition?

2023-01-05 11:21 UTC, aymanbagabas commented
> Nice, looks really good already. Have not yet tested it, so first a few code comments from my side.

I'm thinking of moving the whole Osc logic to the addon and relying on an external package like [js-base64](https://github.com/dankogai/js-base64) for base64. This way all the security stuff is left out of the base package and implementers would have to opt-in and activate the addon for it to work.

2023-01-05 12:44 UTC, aymanbagabas commented on addons/xterm-addon-clipboard/src/ClipboardAddon.ts
> +      return navigator.clipboard.readText();
Chrome uses Permissions API ([`clipboard-read`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#security) and [`clipboard-write`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText#security)) and then prompts the user to allow read access every time the clipboard is read, writing to the clipboard is permitted without permission in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation).

Firefox allows writing text to clipboard in secure contexts. Reading the clipboard requires enabling the `dom.events.asyncClipboard.readText` config. Then, every time the clipboard is read, the browser pops up a "paste" option to read from clipboard.

2023-07-16 14:26 UTC, hh commented
Is there anything I can do to help test this PR? Is there general agreement on the approach?

2023-08-02 19:08 UTC, PerBothner commented
Whether the clipboard api is available is going to depend on which browser is used and its security settings. So we will almost certainly want a way to plug in an alternative mechanism. This might mean having to run a command, such as `pbpaste` (macOS) or `wl-copy` (Wayland).

2023-09-20 18:46 UTC, aymanbagabas commented
@Tyriar @jerch I've updated the PR to use an addon for the base64 implementation and read/write logic. Now, the `InputHandler` implements a clipboard event listener that listens to OSC52 events only if the `allowClipboardAccess` option is enabled (disabled by default). Any external module can hook into the listener to receive OSC52 events.

The changes made to `src/browser` allow registering a `ClipboardProvider` that handles incoming read/write events from the clipboard event listener. It then uses the registered `ClipboardProvider` to handle the clipboard event.

Let me know if you have any feedback :)

2023-09-20 19:06 UTC, PerBothner commented
It would be helpful for the `README.md` to include skeletal code for how to call out to an external service - which may be asynchronous. For example on some platforms DomTerm will send a side-channel request to the backend server, which will execute a helper program, which will send a response using a special escape sequence.  For "paste"  the example could call a `requestClipboardData` hook (implemented by the application), and handle a `handleRequestedClipboardData` callback (called by the application, implemented by the example).

2023-09-20 19:14 UTC, aymanbagabas commented
> It would be helpful for the `README.md` to include skeletal code for how to call out to an external service - which may be asynchronous. For example on some platforms DomTerm will send a side-channel request to the backend server, which will execute a helper program, which will send a response using a special escape sequence. For "paste" the example could call a `requestClipboardData` hook (implemented by the application), and handle a `handleRequestedClipboardData` callback (called by the application, implemented by the example).

There is a `README.md` for the addon. I just updated it to include an example of using a custom clipboard provider.

2023-09-20 20:10 UTC, PerBothner commented
Thanks for the example. It's not fully clear to be what I would need to do, but I think I can figure it out, when teh time comes.

2023-09-21 13:00 UTC, Tyriar requested changes
Sorry, I neglected this PR a bit 🙁

2023-09-21 13:00 UTC, Tyriar commented on src/common/InputHandler.ts
> +    this._parser.registerOscHandler(52, new OscHandler(data => this.setOrReportClipboard(data)));
@jerch I was thinking this should maybe be in the `Terminal.parser` API, but it might be better to just make it entirely an addon which registers the OSC 52 handler? I think that follows our general way of core has things that almost all terminals would want, and addons (whose code can easily be lazy loaded via code splitting) include optional behavior that not all terminals may want. If we did this we could remove `allowClipboardAccess` as well as a warning could be on the clipboard readme. Thoughts?

If we did this I think the base64 dependency should just be in the readme example, not as a true dep, since vscode for example would probably share its impl.

2023-09-21 14:28 UTC, aymanbagabas commented on addons/xterm-addon-clipboard/package.json
> +    "prepackage": "npm run build",
This already matches the format of other addon packages

2023-09-21 14:30 UTC, Tyriar commented on addons/xterm-addon-clipboard/package.json
> +    "prepackage": "npm run build",
Oh I was looking at image which is one of the different ones 😅

2023-09-21 14:36 UTC, aymanbagabas commented on typings/xterm.d.ts
> +  }
Added a little comment explaining each enum. IMO system clipboard is clearer as it refers to the _system_ clipboard which is the same on all platforms. Plus `ClipboardSelection.CLIPBOARD` stutters and feels redundant.

2023-10-20 17:04 UTC, hh commented
woohoo!

2023-10-20 20:58 UTC, jerch commented on src/common/InputHandler.ts
> +    this._parser.registerOscHandler(52, new OscHandler(data => this.setOrReportClipboard(data)));
Yes making it fully provided from addon side sounds good to me.

2023-10-22 17:39 UTC, hh commented
@Tyriar I think merge is blocked until your review is cleared?

2023-10-22 17:46 UTC, hh commented
Or maybe it's merged but the Pr is stuck open?

![image](https://github.com/xtermjs/xterm.js/assets/31331/00114fc2-a45d-40f0-931e-9536ff5e9efd)

2023-11-03 18:23 UTC, Tyriar commented
Trying to update branch now

2023-11-03 20:20 UTC, Tyriar requested changes
I brought this up to date, including to use the new `@xterm` scoped modules. The only thing left to do here is move the stuff out of core and into the addon, so this:

```ts
this._parser.registerOscHandler(52, new OscHandler(data => this.setOrReportClipboard(data)));
```

And would be implemented on the addon side since it's a purely optional addition that we shouldn't include in core as the currently addon API is sufficient to implement it. I like the clipboard provider abstraction which would let an embedder use their own `base64` lib and customize the clipboard calls 👍

2023-11-03 20:44 UTC, aymanbagabas commented
> I brought this up to date, including to use the new `@xterm` scoped modules. The only thing left to do here is move the stuff out of core and into the addon, so this:
> 
> ```ts
> this._parser.registerOscHandler(52, new OscHandler(data => this.setOrReportClipboard(data)));
> ```
> 
> And would be implemented on the addon side since it's a purely optional addition that we shouldn't include in core as the currently addon API is sufficient to implement it. I like the clipboard provider abstraction which would let an embedder use their own `base64` lib and customize the clipboard calls 👍

We still need to access `this._onClipboard` to send clipboard events. Can we do that using the addon API? In the case of a clipboard read, we need to access `this.coreService.triggerDataEvent` to print the clipboard content to terminal see [this](https://github.com/xtermjs/xterm.js/pull/4220/files#diff-324424747eb9d66c9516d29665ad2ceadd440fcb275ea8f1128f146deb7ec11cR1309).

2023-11-03 20:59 UTC, jerch commented
> We still need to access `this._onClipboard` to send clipboard events. Can we do that using the addon API? In the case of a clipboard read, we need to access `this.coreService.triggerDataEvent` to print the clipboard content to terminal see [this](https://github.com/xtermjs/xterm.js/pull/4220/files#diff-324424747eb9d66c9516d29665ad2ceadd440fcb275ea8f1128f146deb7ec11cR1309).

Imho the easiest solution here would be to expose `triggerDataEvent` on the external API, maybe as `xterm.input(...)`? (Technically thats the "opposite" of `term.write` and the same as writing input to the backend)

2023-12-22 19:35 UTC, l1n commented
@aymanbagabas anything that would be useful for others to help with? would love to see this get in

2024-01-29 17:54 UTC, hh commented
I'l like to ring in here and keep this PR visible. Is there mailing list or community meeting we could use to get some final reviewers? OR create a new PR with necessary changes?

2024-02-04 17:05 UTC, jerch commented
reminder: Starting from v 5.4 `this.coreService.triggerDataEvent` is exposed as `Terminal.input` on the official API.

2024-04-07 23:53 UTC, aymanbagabas commented
I've updated the branch, however, I couldn't get the demo to work :/ Am I missing something? I keep getting this error:

```
TypeError: Cannot read properties of undefined (reading 'writeText')
    at OscHandler._setOrReportClipboard [as _handler] (ClipboardAddon.ts:51:33)
    at OscHandler.end (OscParser.ts:223:18)
    at OscParser.end (OscParser.ts:159:45)
    at EscapeSequenceParser.parse (EscapeSequenceParser.ts:777:43)
    at InputHandler.parse (InputHandler.ts:486:35)
    at WriteBuffer._action (CoreTerminal.ts:146:99)
    at WriteBuffer._innerWrite (WriteBuffer.ts:164:27)
    at WriteBuffer.ts:124:29
```

CC/ @Tyriar @jerch

2024-04-18 12:54 UTC, jerch commented
@aymanbagabas Sorry just saw your last comment - does that error still happen?

2024-04-18 13:14 UTC, aymanbagabas commented
> @aymanbagabas Sorry just saw your last comment - does that error still happen?

yes

2024-04-18 19:44 UTC, jerch commented on addons/addon-clipboard/src/ClipboardAddon.ts
> +    this._disposable = terminal.parser.registerOscHandler(52, this._setOrReportClipboard);
You error happens, because you insert `this._setOrReportClipboard` here unbound, thus the access to `this._provider` will fail. (And all other `this...` attempts)

Fix: Set the method via an arrow function, that way `this` will not mutate:
```typescript
terminal.parser.registerOscHandler(52, data => this._setOrReportClipboard(data));
```

2024-04-18 20:17 UTC, aymanbagabas commented on addons/addon-clipboard/src/ClipboardAddon.ts
> +    this._disposable = terminal.parser.registerOscHandler(52, this._setOrReportClipboard);
```suggestion
    this._disposable = terminal.parser.registerOscHandler(52, data => this._setOrReportClipboard(data));
```

2024-04-19 07:54 UTC, aymanbagabas commented
This is ready for squash and merge 🙂

2024-04-19 16:13 UTC, jerch requested changes
Really nice, guess it is almost there. :+1: 

Sorry for playing the nitpicker here, but I have a few restructuring ideas, esp. around the custom provider API (I really like that concept):

- To me it seems reasonable to move the base64 stuff out of the provider, this way the provider would only have to care for its main task - read or write data from clipboard system xy (e.g. move base64 handling one level up close to the OSC handler).
- Provider API should also allow to return values in sync (e.g. return type would be `string | Promise<string>` for read), a certain provider impl can then pick whatever is suitable for its clipboard backend.
- Imho there are superfluous try-catch blocks - we typically dont catch sync errors in parser handlers, just let them bubble (terminal is still partially self-healing due to its chunk/callback-based nature).
- Other than sync errors, async errors (`.catch` path on a promise) should be handled explicitly, otherwise the stack trace gets messed up and hard to debug later on.
- The OSC handler should not filter out anything yet, but instead forward `pc` to the provider - this way a provider can also implement those other buffer types mentioned in the xterm docs. The default browser provider can just skip/ignore those requests and stick to handling `'c'` as clipboard selection type.
- default provider: I'd rename it to `BrowserClipboardProvider` to make clear, that it implements what a browser offers. The base64 argument should be removed, I'd also apply the limit setting to the reading side and give it a sane default (maybe 1 MB).

2024-04-20 15:24 UTC, aymanbagabas commented
Pushed the changes

> * default provider: I'd rename it to `BrowserClipboardProvider` to make clear, that it implements what a browser offers. The base64 argument should be removed, I'd also apply the limit setting to the reading side and give it a sane default (maybe 1 MB).

I've removed the limit because the xterm.js parser already limits the size of an OSC sequence data there's no need to have one in the default browser provider, custom providers can define their implementation with a limit.

2024-04-22 09:26 UTC, Tyriar approved these changes
This is looking good to me, I was careful to review the data we send over the pty and it looks like it's safe. It also doesn't touch anything in `./src` so it's low risk to merge.

@jerch any other comments before we merge?

2024-04-22 09:34 UTC, jerch commented
@Tyriar Nope, I think the PR is now good to be merged. I dont have a good understanding of the browser security measures applied for clipboard access. I think there might be a chance, that an earlier given permission will be auto-revoked by the browser, which might cause frictions for long running apps like vim, that try to do something with OSC 52. But as I am unsure about the impact of that, I think we should not try to fix it upfront, but if and when we get followup issues.

@aymanbagabas Thx a lot for getting this done, and your patience with us :heart:

2024-04-22 09:35 UTC, jerch approved these changes

2024-04-22 09:40 UTC, merged

2025-05-12 15:21 UTC, abliss commented
Hi! I and many others are very excited to try this out, but it still does not seem to be part of any release. Is our only option to build our own copy of xterm.js and the clipboard-addon from master?

2025-05-12 16:30 UTC, jerch commented
@abliss You can try `npm i @xterm/addon-clipboard`. For beta versions, see the list here: https://www.npmjs.com/package/@xterm/addon-clipboard?activeTab=versions.

Addons have a lifecycle if its own to some degree, so they are not tightly coupled to xterm.js releases.