Add option scrollOnKeypress
xtermjs/xterm.js pull request #4289
Opened 2022-12-06 03:33 UTC by JasonXJ

Note that we also change the existing behavior a bit: CoreService.triggerDataEvent() will not scroll to the bottom unless `wasUserInput` is also true. This actually seems to be the intended behavior according to the doc just above
ICoreService.triggerDataEvent().

Also see issue #1824

2022-12-06 18:38 UTC, Tyriar requested changes
Looks good, just some minor comments

2022-12-06 18:38 UTC, Tyriar commented on src/common/services/Services.ts
>     * @param wasFromUser Whether the data originated from the user (as opposed to
Could you fix this name?

2022-12-06 18:38 UTC, Tyriar commented on typings/xterm.d.ts
> +    scrollOnKeypress?: boolean;
I think `scrollOnUserInput` would be more accurate here as it's not necessarily a keypress that could trigger this.

2022-12-08 23:12 UTC, JasonXJ commented
I think this is good to merge now?

2022-12-11 15:31 UTC, Tyriar approved these changes
Looks good, thanks!

2022-12-11 15:31 UTC, merged