attach and detach accessibility tree root element
xtermjs/xterm.js pull request #4382
Opened 2023-01-23 21:10 UTC by meganrogge

Explains why navigation mode was not working and gets the output reading back to the state it was in - only announcing when text is too long to read

[172007](https://github.com/microsoft/vscode/issues/172007)

2023-01-23 22:47 UTC, Tyriar requested changes

2023-01-23 22:47 UTC, Tyriar commented on src/browser/AccessibilityManager.ts
> +    this._terminal.element?.appendChild(this._accessibilityTreeRoot);
Can we switch this to what it was before?

https://github.com/xtermjs/xterm.js/blob/19c760a20470c26666efad770fe82496c4a9bf1e/src/browser/AccessibilityManager.ts#L87

If that position isn't good, at least to the same line?

2023-01-23 22:47 UTC, Tyriar commented on src/browser/AccessibilityManager.ts
>        this._accessibilityTreeRoot.remove();
This should be covered already by `this._accessibilityTreeRoot.remove();`

2023-01-24 15:35 UTC, meganrogge commented on src/browser/AccessibilityManager.ts
> +    this._terminal.element?.appendChild(this._accessibilityTreeRoot);
good find, yes 👍🏼 looks like that happened in Dec

2023-01-24 15:38 UTC, meganrogge commented on src/browser/AccessibilityManager.ts
> +      this._terminal.element?.removeChild(this._accessibilityTreeRoot);
```suggestion
```

2023-01-24 15:38 UTC, meganrogge commented on src/browser/AccessibilityManager.ts
> +    this._terminal.element?.appendChild(this._accessibilityTreeRoot);
```suggestion
    this._terminal.element.insertAdjacentElement('afterbegin', this._accessibilityTreeRoot);
```

2023-01-24 15:40 UTC, Tyriar commented on src/browser/AccessibilityManager.ts
> +    this._terminal.element?.appendChild(this._accessibilityTreeRoot);
Looks like my prototype broke it: https://github.com/xtermjs/xterm.js/commit/41dc93a008dc7bc4044020cfa483210891770b50

2023-01-24 15:44 UTC, meganrogge commented
so this was due to our accessibility buffer changes

https://github.com/xtermjs/xterm.js/commit/41dc93a008dc7bc4044020cfa483210891770b50#diff-7904a8cc1e295a78532b41608480fddf931f80c485c53b78f99ae8cd5759dedcL86

2023-01-24 15:53 UTC, merged