defer focus when accessibility buffer is active
xtermjs/xterm.js pull request #4384
Opened 2023-01-25 16:06 UTC by meganrogge

When `escape` or `tab` is pressed, exit the accessibility buffer. Otherwise, disallow focusing of the terminal text area

2023-01-25 16:11 UTC, meganrogge commented on src/browser/AccessibilityManager.ts
> +    }
```suggestion
    }
```

2023-01-25 16:12 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
better way? don't like that it's in this general code area

2023-01-25 16:16 UTC, Tyriar requested changes

2023-01-25 16:16 UTC, Tyriar commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
What is this needed for? We don't want Terminal to know about internals of AccessibilityManager

2023-01-25 21:55 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
needed to prevent the `textarea` from stealing the focus when the `.xterm-accessibility-buffer` is focused. what's weird is that the `z-index` should be preventing that from happening on click

2023-01-25 21:58 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
also tried 

```
 this._accessiblityBuffer.addEventListener('click', (ev: MouseEvent) => {
      ev.stopImmediatePropagation();
    });
```

but it still goes to the `textarea`

2023-01-26 18:58 UTC, Tyriar commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
There should be some way of preventing this, we definitely don't want to mention the `xterm-accessibility-buffer` class outside of AccessibilityManager.ts

2023-01-26 18:58 UTC, Tyriar commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
There should be some way of preventing this, we definitely don't want to mention the `xterm-accessibility-buffer` class outside of AccessibilityManager.ts

2023-01-26 19:08 UTC, meganrogge commented on src/browser/Terminal.ts
> +    if (document.querySelector('.xterm-accessibility-buffer:focus')) {
yep I agree, wip

2023-01-31 17:37 UTC, closed without merging