on tab or escape, allow leaving the buffer
xtermjs/xterm.js pull request #4426
Opened 2023-03-01 20:55 UTC by meganrogge

fixes 
https://github.com/microsoft/vscode/issues/175764
https://github.com/microsoft/vscode/issues/175765

2023-03-01 20:58 UTC, meganrogge commented on src/browser/public/Terminal.ts
> +  // to do
```suggestion
```

2023-03-01 20:59 UTC, meganrogge commented on src/browser/public/Terminal.ts
> +
```suggestion

```

2023-03-01 23:20 UTC, Tyriar requested changes

2023-03-01 23:20 UTC, Tyriar commented on src/browser/AccessibleBuffer.ts
>      }
Can this instead of handled by the browser naturally for tab (listen to blur/focusout to react) and vscode keybindings for escape?

2023-03-02 17:02 UTC, meganrogge commented on src/browser/AccessibleBuffer.ts
>      }
Sure re escape in VS Code, though we might want that hear as well.

As for handling tab naturally, I don't think we want to do that because then when you focus out IE click in the editor, the xterm's text-area will get focused - making the accessible buffer hide. That's specifically what this fixes.

2023-03-02 18:17 UTC, meganrogge commented
we've decided that `AccessibleBuffer` is best kept out of xterm.js

2023-03-02 18:17 UTC, closed without merging