Add smoothScroll to scrollLines
xtermjs/xterm.js pull request #4482
Opened 2023-04-19 08:15 UTC by tisilent

Fix #4121

2023-05-17 14:24 UTC, Tyriar requested changes

2023-05-17 14:24 UTC, Tyriar commented on src/browser/Terminal.ts
> +  }
This general approach seems good, but we want this logic to live in Viewport. The reasons are to keep that code in the same place, out of the main Terminal class as well as sharing the smooth scroll state object.

2023-05-17 14:24 UTC, Tyriar commented on src/browser/Terminal.ts
> +  public scrollLines(disp: number, suppressScrollEvent?: boolean, source = ScrollSource.TERMINAL): void {
We'll want to also hook up `scrollPages`, `scrollToTop`, `scrollToBottom` and `scrollToLine` which should be fairly easy once it's pulled into `Viewport`.

2023-05-18 09:18 UTC, tisilent commented on src/browser/Terminal.ts
> +  public scrollLines(disp: number, suppressScrollEvent?: boolean, source = ScrollSource.TERMINAL): void {
scrollToTop  scrollToBottom , 
Using smoothScroll may cause some time waiting, I'll give it a try first.

2023-05-18 12:41 UTC, Tyriar commented on src/browser/Terminal.ts
> +  public scrollLines(disp: number, suppressScrollEvent?: boolean, source = ScrollSource.TERMINAL): void {
It's duration based, so all scrolling no matter how large or small should take the same amount of time

2023-06-06 12:42 UTC, tisilent commented on src/browser/Terminal.ts
> +  public scrollLines(disp: number, suppressScrollEvent?: boolean, source = ScrollSource.TERMINAL): void {
add scrollline to viewport.It should be relatively easy to use.

2023-06-10 21:11 UTC, Tyriar requested changes

2023-06-10 21:11 UTC, Tyriar commented on src/browser/Viewport.ts
> +  }
I was expecting these to just use the logic that was already there, so the main thing being setting the `_smoothScrollState` if needed when calling into `scrollLines`?

2023-06-11 09:46 UTC, tisilent commented on src/browser/Viewport.ts
> +  }
I seem to have thought of something.try try.

2023-06-30 06:36 UTC, tisilent commented on src/browser/Terminal.ts
> +  public scrollLines(disp: number, suppressScrollEvent?: boolean, source = ScrollSource.TERMINAL): void {
scrollToTop example:
add to Viewport
`
public scrollToTop(): void {
  this.scrollLines(-this._bufferService.buffer.ydisp);
}
`

2023-08-01 12:32 UTC, Tyriar approved these changes
Thanks @tisilent, I made some changes to fix the tests and pass the scroll to top/bottom/line/pages calls through `scrollLines`

2023-08-01 12:48 UTC, merged

2023-08-01 16:15 UTC, tisilent commented
Oho @Tyriar , learning to write tests, I'm thinking about some of the logic of Terminal scrollLine moving to Viewport.
Terminal -> Viewport -> BufferService

2023-08-01 16:20 UTC, Tyriar commented
Test coverage is good enough currently, there are unit tests which run in node and use a Mock Viewport and then API tests that actually use the scroll apis in a browser context

2023-08-01 16:56 UTC, tisilent commented
I’am very sorry I had a wrong to sent the message. @Tyriar
<del>learning to write tests</del>
I'm learning to write tests .
:sweat: