New unicode-graphemes addon.
xtermjs/xterm.js pull request #4519
Opened 2023-05-17 01:50 UTC by PerBothner

Handle grapheme cluster lookup as well as wcwidth.

This is based on Unicode 15, and could replace the unicode11 addon.

See the discussion in issue #4513 - but not that this pull request does not change the BufferLine implementation. (Except an extra `width` parameter for `addCodepointToCell`.

Note this combines the lookup for wcwidth and grapheme-break-property in a single trie lookup, so I'm hoping there won't be a noticable performace cost. Please let me know what you think.

Here is a screenshot of DomTerm with the xterm.js emulator. This is in a Tauri/Wry window (WebKit-based).  Firefox also works. Chrome-based browsers (including Electron) mostly work - except they don't seem to handle Korean Hangul properly.  (This might be fixable by changing fonts.)   
![xtermjs-graphemes](https://github.com/xtermjs/xterm.js/assets/10293361/deadf83f-7776-4c1e-8a32-7106a288c2ec)

2023-05-17 04:48 UTC, PerBothner commented
There are some `yarn test` failues. I will look at them tomorrow.

2023-05-18 01:47 UTC, PerBothner commented
I fixed a bunch of tests.

There are 6 failures like the following.  In spite of Googling, I haven't yet figued out to fix these.
```
/home/bothner/Software/xterm.js-clusters/addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemesAddon.ts
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemesAddon.ts.
The file must be included in at least one of the projects provided
```
Except for these, `yarn tests` is working.

Still 2 errors in `yarn test-api` - plus I plan to add some tests to `addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts` once I have that working.

2023-05-18 13:22 UTC, Tyriar commented
> 0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.

You need to set the tsconfigs in .eslintrc.json:

https://github.com/xtermjs/xterm.js/blob/b7d73f63cd730bd8aeb48121ee29d9f8f1c7dc2e/.eslintrc.json#L8-L33

2023-05-18 16:08 UTC, PerBothner commented
Next problem: `yarn test-api` emits this:
```
1) UnicodeGraphemesAddon
       wcwidth V15 emoji test:
     page.evaluate: ReferenceError: UnicodeGraphemesAddon is not defined
    at eval (eval at evaluate (:178:30), <anonymous>:1:22)
    at eval (<anonymous>)
    at UtilityScript.evaluate (<anonymous>:178:30)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
      at /home/bothner/Software/xterm.js-clusters/addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts:34:16
      at /home/bothner/Software/xterm.js-clusters/addons/xterm-addon-unicode-graphemes/out-test/UnicodeGraphemesAddon.api.js:8:71
      at __awaiter (addons/xterm-addon-unicode-graphemes/out-test/UnicodeGraphemesAddon.api.js:4:12)
      at Context.<anonymous> (addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts:33:43)
```
I might have to figure this out by myself - but if someone has an insight it would be appreciated.

(I'm also seeing some `registerLinkProvider` failures, but they also fail under an unmodified master clone.)

2023-05-18 16:16 UTC, Tyriar commented
> page.evaluate: ReferenceError: UnicodeGraphemesAddon is not defined

The playwright tests use the demo, this is about exposing the addon on client.ts:

https://github.com/xtermjs/xterm.js/blob/913cb2586301d3e8322594c2bf08c0ea7d8468c9/demo/client.ts#L204-L214

2023-05-18 18:23 UTC, PerBothner commented
At this point I think this is ready for merge - or at least feedback.
It works with the demo and `yarn test-api`, and I implemented some tests in `UnicodeGraphemesAddon.api.ts`.

I'd be curious to run a performance comparison. What is the recommended way to do that?

2023-05-18 19:52 UTC, Tyriar commented
Good to see it passing 👍. It's a pretty beefy PR so it might take me a couple of weeks to get to. 

@jerch would know the best way to benchmark

2023-05-18 20:26 UTC, PerBothner commented
No hurry. It does mean I may want to put the BufferLine changes on hold since there is some overlap, mainly in the InputHandler logic. Though maybe not - the overlap is likely to be limited to a small area.

2023-05-19 08:19 UTC, jerch commented
@PerBothner For perf test you can use/alter https://github.com/xtermjs/xterm.js/blob/master/test/benchmark/Terminal.benchmark.ts, and then run it with
```
$> yarn benchmark out-test/benchmark/Terminal.benchmark.js
```

2023-05-19 08:34 UTC, jerch commented
@PerBothner 
This a quite impressive PR, thanks for looking into that nasty unicode stuff. It def. will need some time to go over it.

Imho the idea to have this first as an addon is the right choice, which gives us time to level out raw edges (if there are any, no clue yet). I was really skeptical if this could be put into an addon with a reasonable afford, so thanks for doing the hard work. :heart: 
Still in the long run I'd love to see this as a core addition, once we are done polishing things.

2023-05-19 12:25 UTC, PerBothner commented
It seems plausible that the table lookup in `unicode-trie` could be sped up using WASM. I don't know enough about WASM to know if the JavaScript/WASM transition adds significant overheads; if so, one could perhaps batch the property lookups with a single call WASM call for each `print` call.

Another possibly-worthwhile simple optimization might be to bypass the trie-lookup for ASCII (0020-007E) or below 0300 (with a few exceptions, to complicate things).

2023-05-19 13:39 UTC, jerch commented
@PerBothner Yeah wasm speedup will most likely be limited by the granularity we can call it with, and what additional data moving is needed per step.
From my experience with wasm in the image addon - I gain there most of the speedup by calling rarely into wasm with bigger batches, and by avoiding data copies where possible (almost all my wasm impls there use borrow mechs at the output stage). With this I typically get a 2 to 4 times speedup compared to a highly optimized JS implementation - sixel decoder is ~3.5 times faster, base64 decoder ~2.5 times (all non SIMD code). With data copies on both wasm IO ends you can roughly subtract 1 from these numbers, thus wasm looks no so good anymore, if alot data juggling is involved.

So while this def. worth a shot, I would not put a priority on that yet, before we settled the inner works and have a reliable test base (wasm is quite cumbersome, when it comes to testing).

2023-05-20 10:34 UTC, jerch commented
To move things forward I suggest that we should check, if and how we can activate the addon and grapheme handling during browser API tests. This would give us at least a basic regression testing against top level API. This should be possible, if we rework the API tests to boostrap its terminal instance from a common module, where we already injected the grapheme addon.

It will still miss several core tests on the unit testing level done on nodeJS side, but I am unsure, if we can get it hooked in there with a reasonable afford. This is a bit of a downside of the addon abstraction - they get mixed in late, so cannot get injected easily to existing tests on unit level (still might be possible for the `Terminal.test.ts` module).

_Why bothering with already existing tests?_ For mainly 3 reasons:
- spot regressions - if we want this to be the normal operation mode somewhat in the future, we basically have make sure, that it does not break things at other ends
- avoid writing tests all over again - we have a quite sophisticated test battery, but due to the addon nature, they currently run w'o grapheme handling being active (they currently just run as before)
- get faster to working tests - I hope that by injecting existing tests with grapheme handling we get much faster a reliable test battery, thus much faster back to API shaping and even perf considerations (e.g. wasm testing gets much easier once we have regressions covered by tests)

2023-05-20 12:04 UTC, jerch commented
About the API tests - for tests using `openTerminal` grapheme handling can easily be injected:
```patch
diff --git a/test/api/TestUtils.ts b/test/api/TestUtils.ts
index 3fd0648e..904c0d12 100644
--- a/test/api/TestUtils.ts
+++ b/test/api/TestUtils.ts
@@ -46,6 +46,11 @@ export async function timeout(ms: number): Promise<void> {
 export async function openTerminal(page: playwright.Page, options: ITerminalOptions & ITerminalInitOnlyOptions = {}): Promise<void> {
   await page.evaluate(`window.term = new Terminal(${JSON.stringify({ allowProposedApi: true, ...options })})`);
   await page.evaluate(`window.term.open(document.querySelector('#terminal-container'))`);
+  await page.evaluate(`
+      window.unicode = new UnicodeGraphemesAddon();
+      window.term.loadAddon(window.unicode);
+      window.term.unicode.activeVersion = '15-graphemes';
+    `);
   await page.waitForSelector('.xterm-rows');
 }
```

Have not checked yet, if all API tests call `TestUtils.openTerminal` before running the tests, still only one test fails here:
```text
  1) Unicode11Addon
       wcwidth V11 emoji test:

      AssertionError: expected [ '6', '11', '15-graphemes' ] to deeply equal [ '6', '11' ]
      + expected - actual

       [
         "6"
         "11"
      -  "15-graphemes"
       ]
```
(It tests unicode provider registration, but does not know about the new provider yet, thus it should have failed, hurray :smile_cat:)

2023-05-20 12:15 UTC, jerch commented
@PerBothner Should I do a PR against your branch, so you can add the perf test and the API test changes?

2023-05-20 12:24 UTC, PerBothner commented
No opinion - whatever you think is reasonable.

2023-05-20 13:30 UTC, jerch commented
Created PR: https://github.com/PerBothner/xterm.js/pull/2

2023-05-20 14:42 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts
> +const trieRaw = "AAARAAAAAABwxwAAAb4LQfTtmw+sVmUdx58LL/ffe/kjzNBV80gW1F3yR+6CvbJiypoZa0paWmAWSluErSBbFtYkkuZykq6QamGJ4WRqo2kFGy6dYWtEq6G1MFAJbRbOVTQr+x7f5+x97q/n/3me87wXzm/3s+f/7/d7/p7znnvOlvGMbQM7wI
Can we put the source of this instead, linking to a node module if needed?

2023-05-20 15:16 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts
> +const trieRaw = "AAARAAAAAABwxwAAAb4LQfTtmw+sVmUdx58LL/ffe/kjzNBV80gW1F3yR+6CvbJiypoZa0paWmAWSluErSBbFtYkkuZykq6QamGJ4WRqo2kFGy6dYWtEq6G1MFAJbRbOVTQr+x7f5+x97q/n/3me87wXzm/3s+f/7/d7/p7znnvOlvGMbQM7wI
I'm unsure the best way to do it.  The file `UnicodeProperties.ts` is generated, using the Unicode property files. That file, along with `unicode-trie.ts` and `tiny-inflate.ts`, comes from [my unicode-properties project](https://github.com/PerBothner/unicode-properties). The latter two files come from other projects, but converted to TypeScript.

If we change the data-structure used for the lookup (such as plain Uint8Array for BMP and binary search otherwise) we might not need `unicode-trie.ts`  anymore. We might still want to use `tiny-inflate.ts` to the reduce the size of the JavaScript code loaded.

One option is to create a node module that includes the generated files. I don't have any experience with that, but I could figure it out.

Another option is that the xterm.js build process (yarn) can generate the table(s).  The script to do so (`src/generate.ts` in the `unicode-properties` project) is a `node` script that is reasonably fast and modest size. I have no objections to just checking the script into the xterm.js source if you think that makes sense.

2023-05-20 15:25 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts
> +const trieRaw = "AAARAAAAAABwxwAAAb4LQfTtmw+sVmUdx58LL/ffe/kjzNBV80gW1F3yR+6CvbJiypoZa0paWmAWSluErSBbFtYkkuZykq6QamGJ4WRqo2kFGy6dYWtEq6G1MFAJbRbOVTQr+x7f5+x97q/n/3me87wXzm/3s+f/7/d7/p7znnvOlvGMbQM7wI
> ... Another option is that the xterm.js build process (yarn) can generate the table(s). ...

Well we have a `fixture` folder in the base repo and a `bin` folder. How about doing the same in the addon repo, along with a npm task, that creates the table data once and puts it as a json file under `fixtures`? From there you can import it into source files as needed.
Imho this approach has one big advantage - the data creation tooling also resides in the repo and can be changed as needed. The json file itself can be checked in, so the task does not have to run over and over. And once we decide to switch to the next unicode version, just re-run it to build the new data set.

2023-05-21 16:37 UTC, jerch commented
Oh well, the linter is picky again (sorry, always forget to test that locally :crying_cat_face: )

2023-05-21 20:32 UTC, jerch commented
@PerBothner Your recent codepoint change makes it much faster and we are almost back to the old speed :smile_cat::
- utf8: 24.14 MB/s (~21% slower)
- JS strings: 19.65 MB/s (~28% slower)


Hmm, the grapheme injection causes the API tests to timeout, weird. It all worked for me locally, we prolly have to increase the poll timeout on CI. Did the API tests work for you locally? (You can run them with `yarn test-api` at the repo base.)

2023-06-15 05:14 UTC, microhobby commented on typings/xterm.d.ts
>      wcwidth(codepoint: number): 0 | 1 | 2;
I get this patch and applied on my fork to try this, I'm facing some annoying issues of emoji overlapping. The interesting is that the patch itself does not work, well it made everything more buggy in fact, even "normal" characters were overlapped. So, checking it more deeply if I change here to:

```
wcwidth(codepoint: number): 0 | 1 | 2 | 3 | 4;
```

Fix it, no more overlapping ...

2023-06-15 05:24 UTC, PerBothner commented on typings/xterm.d.ts
>      wcwidth(codepoint: number): 0 | 1 | 2;
I'd like to understand why these larger widths happen and why this change is desirable.

2023-06-15 17:46 UTC, PerBothner commented on typings/xterm.d.ts
>      wcwidth(codepoint: number): 0 | 1 | 2;
What made you look at the wcwidth return type  Was there some bug that appears when the return type is `0 | 1 | 2` and goes away if you change it to `0 | 1 | 2 | 3 | 4`? If so, can you describe it how the bug is triggered?

2023-06-27 21:31 UTC, PerBothner commented
Just a reminder that it has been 5 weeks since I heard anything.

2023-06-28 19:59 UTC, jerch commented
@PerBothner There is still a bug in the current state, as I pointed out in

> Edit2: The API tests work again, if I comment out the change in [fa89e17](https://github.com/xtermjs/xterm.js/pull/4519/commits/fa89e1776b107fd602213af42c5f8dc6e722b668).

which causes the tests to fail.

2023-06-28 22:49 UTC, PerBothner commented
Oops. I don't remember seeing that comment.  It turns out the "inlined" value of `1` - should have been `2`.  Double oops. Don't know how I let that slip - perhaps because the optimization was last-minute.

I fixed it by using a pre-calculated static field, which is much more robust. (Though it could be very slightly slower, depending on compiler/packager/jit optimizations.)

2023-06-30 16:45 UTC, microhobby commented on typings/xterm.d.ts
>      wcwidth(codepoint: number): 0 | 1 | 2;
@PerBothner sorry for the delay, I was trying to reproduce here, but to be honest I do not know anymore if this is something on my side only, take a look what happens when I try to use the demo with your patch applied:

https://github.com/xtermjs/xterm.js/assets/2633321/9e001192-87ee-4211-8575-16f6d856a979

2023-06-30 17:14 UTC, PerBothner commented on typings/xterm.d.ts
>      wcwidth(codepoint: number): 0 | 1 | 2;
Did you do a `git pull` and rebuild? I fixed an embarrassing bug June 28 - make sure you have that.
If the problem persists, can you try with just a simple prompt (no Powershell or similar), so we can see if that is relevant to the issue?

2023-07-28 14:16 UTC, Tyriar commented
Sorry, I've been struggling to keep up with my notifications. I'm down to about 200 from ~400 a week or so ago. Typically one week out of the month is my catch up/debt week which also pulls me in several directions which is why PRs sometimes build up 🙁. I hope to do a pass over all the xterm.js PRs next week but it could slip again.

2023-07-28 20:26 UTC, PerBothner commented
No big hurry. I'm continuing to work on the BufferLine rewrite, but in a [new branch](https://github.com/PerBothner/xterm.js/tree/buffer-cell-cursor) that doesn't include the unicode-graphemes changes. There will be some conflict between the branches, but mostly localized to `InputHandler.ts`. Getting unicode-graphemes resolved will be desirable when it comes time for performance work on the BufferLine re-design, but I'm not close to that being an issue.

2023-07-28 21:46 UTC, jerch commented
@PerBothner Same from my side - sorry for taking so long. I prolly get down to it after the dom renderer and image addon PRs.

2023-08-03 20:05 UTC, PerBothner commented
It is worth noting that how well the new "Grapheme clusters" test works will depend on the browser, the font, and the renderer. Preliminary results suggest that clusters work best on Firefox, though even on Firefox the default renderer adds extra space in some cases. More information later.

2023-08-04 05:54 UTC, PerBothner commented
I checked in a fix for the extra spaces.

2023-08-05 13:46 UTC, Tyriar commented on .eslintrc.json
> +    "addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts",
Instead of ignoring random files how about we have a src/vendor/ folder and put third party non-node_modules that we don't want to format into that/

2023-08-05 13:46 UTC, Tyriar commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
Can you add a jsdoc comment explaining what this does?

2023-08-05 13:47 UTC, Tyriar commented on typings/xterm-headless.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
Can you add a jsdoc comment explaining what this does?

2023-08-05 13:47 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
:eyes:

2023-08-05 13:48 UTC, Tyriar commented on test/api/TestUtils.ts
> +  `);
Why does this need to happen here? Tests in core aren't meant to depend on addons, I would have expectedt his only to live in UnicodeGraphemesAddon.api.ts

2023-08-05 13:49 UTC, Tyriar commented on src/common/InputHandler.ts
> +    private readonly _parser: EscapeSequenceParser = new EscapeSequenceParser()
Can we revert this? I'd prefer us to depend on the interface rather than the implementation

2023-08-05 13:52 UTC, Tyriar commented on src/common/InputHandler.ts
> +    let precedingInfo = this._parser.precedingCodepoint === 0 ? 0
This is very generic, can this variable be more descriptive? `precedingCharProperties`? `precedingJoinState`?

2023-08-05 13:53 UTC, Tyriar commented on src/common/InputHandler.ts
> +      precedingInfo = currentInfo;
Is this going to result in slowing down the path for unicode 6/11? Should charProperties be optional so we don't need to touch the older addons?

2023-08-05 13:54 UTC, Tyriar commented on src/common/InputHandler.ts
> +          if (oldWidth > 0 && bufferRow instanceof BufferLine) {
Is the instanceof check needed? Isn't this a `IBufferLine | undefined`?

2023-08-05 13:55 UTC, Tyriar commented on src/common/InputHandler.ts
> +        const offset = bufferRow.getWidth(this._activeBuffer.x - 1) ? 1 : 2;
@jerch your help would be great in this file in particular as I think you're more familiar with this code

2023-08-05 13:56 UTC, Tyriar commented on src/common/parser/EscapeSequenceParser.ts
> +  public precedingJoinState: number = -1; // UnicodeJoinProperties
Could this live in InputHandler instead?

2023-08-05 13:57 UTC, Tyriar commented on src/common/services/Services.ts
> +   * in that case result specifies if characters should be joined. */
```suggestion
  /**
   * Return character width and type for grapheme clustering. If preceding != 0, it is the return
   * code from the previous character, in that case the result specifies if the characters should be
   * joined.
   */
```

2023-08-05 13:59 UTC, Tyriar commented on src/common/services/Services.ts
> +export type UnicodeCharProperties = number;
I see https://www.unicode.org/Public/14.0.0/ucd/auxiliary/GraphemeBreakTest.html but after skimming the document it doesn't seem to map to a number?

2023-08-05 14:02 UTC, Tyriar commented on src/common/services/Services.ts
> +export type UnicodeCharProperties = number;
Is this a bit field? A more descriptive jsdoc would be handy, similar to https://github.com/perbothner/xterm.js/blob/42042155d4e1c701f9296c2fd9e830722dced6c5/src/common/buffer/BufferLine.ts#L12-L18

2023-08-05 14:05 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
Should we just call this unicode15 instead for consistency and explain in the readme that it adds grapheme cluster support?

2023-08-05 14:05 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "version": "0.5.0",
0.1.0?

2023-08-05 14:06 UTC, Tyriar commented on demo/client.ts
> +\x1b[m     \x1b[41m     \x1b[42m     \x1b[43m     \x1b[44m     \x1b[45m     \x1b[46m     \x1b[47m
I think the trailing whitespace here was intentional

2023-08-05 14:06 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/LICENSE
> +Copyright (c) 2019, The xterm.js authors (https://github.com/xtermjs/xterm.js)
2023

2023-08-05 14:08 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts
> +  });
nit: Splitting these into independent tests would be preferable so the impact and root cause is more obvious when they fail, the comments can be the test names

2023-08-05 14:09 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      : (w >= 2 && (w === 3 || this.ambiguousCharsAreWide)) ? 2 : 1;
Can we split this into ifs with early returns? The nested ternaries is a bit hard to read

2023-08-05 14:13 UTC, Tyriar requested changes
Here's a full review. WIth any large change like this it will be more risky to merge, so anything that can be removed from core and into the addon to minimize changes in core will make it less risky since the new addon will be opt-in initially.

2023-08-05 15:15 UTC, PerBothner commented on demo/client.ts
> +\x1b[m     \x1b[41m     \x1b[42m     \x1b[43m     \x1b[44m     \x1b[45m     \x1b[46m     \x1b[47m
Would it make sense to use a variable to make the spaces explicit:
```
const sp4 = '    ';
...
\x1b[m${sp4}\x1b[41m${sp4}\x1b[42m${sp4}\x1b[43m${sp4}\x1b[44m${sp4}\x1b[45m${sp4}\x1b[46m${sp4}\x1b[47m${sp4}

2023-08-05 15:41 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
I think having the Unicode version be baked into the addon name is a mistake. I think the default should be "latest supported version", and we should make that easiest to select - and tracking that shouldn't require changing client code. If people want to stick to a *specific* Unicode version, that should be possible, but it doesn't have to be as easy.

Furthermore, having distinct addons for different Unicode version leads to a lot of code duplication, unless we can factor out the common code. That would be easier if we can move the actual logic into the main `src` directory.

That said, the way the tables (in `src/UnicodeProperties.ts`) are generated in an external project and imported is awkward.

2023-08-05 15:46 UTC, Tyriar commented on demo/client.ts
> +\x1b[m     \x1b[41m     \x1b[42m     \x1b[43m     \x1b[44m     \x1b[45m     \x1b[46m     \x1b[47m
Sounds good as I can see this happening again if not

2023-08-05 15:46 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
How about `unicode-latest` then?

2023-08-05 15:55 UTC, PerBothner commented
Social obligation prevent me working on this more today. Tomorrow I'll have a bit more time.

2023-08-05 16:32 UTC, Tyriar commented
@PerBothner np of course

2023-08-06 15:21 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/LICENSE
> +Copyright (c) 2019, The xterm.js authors (https://github.com/xtermjs/xterm.js)
Fixed.

2023-08-06 15:22 UTC, PerBothner commented on demo/client.ts
> +\x1b[m     \x1b[41m     \x1b[42m     \x1b[43m     \x1b[44m     \x1b[45m     \x1b[46m     \x1b[47m
Checked in fix along this line. (It's actually sp5, since it's 5 spaces.)

2023-08-06 15:34 UTC, PerBothner commented on src/common/services/Services.ts
> +   * in that case result specifies if characters should be joined. */
I added the missing word, and fixed the formatting.  However, I'm pretty sure semi-colon is more correct than comma as this is written. Also, I think it is nice if the line breaks follow sentence structure, when convenient.

2023-08-06 15:42 UTC, jerch commented on test/api/TestUtils.ts
> +  `);
I added it there to be able to spot regressions early. As the addon changes several aspects of internals I found this to be easier than to wait for a full test coverage by unit or explicit addon tests. It should not stay there, once we have to appropriate tests, it can be removed again (thus it is just a test WIP to speed up PR development).

2023-08-06 15:59 UTC, PerBothner commented on src/common/parser/EscapeSequenceParser.ts
> +  public precedingJoinState: number = -1; // UnicodeJoinProperties
IIRC this was for consistency: `precedingCodepoint` is in `EscapeSequenceParser` so it seems plausible that `precedingJoinState` also be.
It's not clear to me what belongs in `EscapeSequenceParser.ts` and what belongs in `InputHandler.ts`.

2023-08-06 16:08 UTC, PerBothner commented on src/common/InputHandler.ts
> +          if (oldWidth > 0 && bufferRow instanceof BufferLine) {
`copyCellsFrom` is only in `BufferLine`, not `IBufferLine`.

(FWIW, my plan for the BufferLine rewrite is for a line that wraps each `BufferLine` would share a single `_data` array, just with different starting offset. In that implementing you wouldn't need to copy cells when lines are broken or joined.)

2023-08-06 18:07 UTC, PerBothner commented on src/common/InputHandler.ts
> +      precedingInfo = currentInfo;
I don't see how these changes would slow things down measurably.  The `charProperties` just re-encodes the `wcwidth` result as a `UncodeCharProperties` integer while `extractWidth` and `extractShouldJoin` extract parts of the bit field. So, yes some extra function calls and some extra bit fiddling, but no extra object allocation, object mutation, or table searching.

You probably could make `charProperties` be optional by using different code paths but I think that would be more fragile and complicated. (Though I haven't really thought about alternatives.)

2023-08-06 18:09 UTC, PerBothner commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
Would it make sense to just remove `IUnicodeVersionProvider` from `typings/*.d.ts`? Possibly also `IUnicodeHandling`? Maybe make the latter an opque type (`unknown`)?

2023-08-06 18:54 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "version": "0.5.0",
I changed this.

2023-08-06 19:48 UTC, PerBothner commented on src/common/InputHandler.ts
> +    private readonly _parser: EscapeSequenceParser = new EscapeSequenceParser()
We can do that if we move precedingJoinState from EscapeSequenceParser to InputHandler - which you prefer anyway. So I did that.

2023-08-07 18:16 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      : (w >= 2 && (w === 3 || this.ambiguousCharsAreWide)) ? 2 : 1;
Changed this.

(If have mixed feelings about the best style, given JavaScript's limitations - Rust handles this better. I would prefer 'if-else if-else' as being closer to preferred "structured programming" style, but lint complains about "Unnecessary 'else' after 'return'  no-else-return".)

2023-08-07 18:22 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
I'll go along with whatever name you prefer, but `unicode-latest` would not be my recommendation. It implies it's the latest version of Unicode, which may not always be the case. Slightly better `unicode-current` as in "the version of Unicode that we're currently supporting and recommending". But I think a descriptive name like `unicode-graphemes` or `unicode-clusters` or `unicode-rich` is better.

2023-08-07 18:58 UTC, PerBothner commented on src/common/services/Services.ts
> +export type UnicodeCharProperties = number;
I expanded the documentation. I prefer a more compact style, with less whitespace than your two examples, but I can certainly re-format it if you want.

2023-08-07 19:17 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
I get your point, let's keep as is 👌

2023-08-07 19:21 UTC, Tyriar commented on src/common/parser/EscapeSequenceParser.ts
> +  public precedingJoinState: number = -1; // UnicodeJoinProperties
`precedingCodepoint` is used in parser. The rule I'd follow is since `InputHandler` depends on `EscapeSequenceParser`, if the property is not used in `EscapeSequenceParser` at all it should be moved to `InputHandler` so only one class needs to know about it, not two.

2023-08-07 19:42 UTC, PerBothner commented on src/common/parser/EscapeSequenceParser.ts
> +  public precedingJoinState: number = -1; // UnicodeJoinProperties
I changed this at the same time I changed the type of _parser in InputHnandler. Sorry for not updating my response here.

2023-08-07 20:10 UTC, PerBothner commented on src/common/InputHandler.ts
> +    let precedingInfo = this._parser.precedingCodepoint === 0 ? 0
Renamed precedingInfo to precedingJoinState.

2023-08-07 21:20 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
This is related to the test/api/TestUtils.ts change discussed below: `UnicodeGraphemesAddon` (and `Unicode11Addon`) access `terminal.unicode`, which calls `_checkProposedApi`.

It seems reasonable to allow either the unicode-graphemes or unicode11 addon without triggering `_checkProposedApi`.  That probably requires a new non-public "backdoor" API that addons can use.  I can look into that.

 Regardless, it seems we should revert the TestsUtils.ts changes, though that may require other changes (that I haven't looked into).

2023-08-07 21:22 UTC, PerBothner commented on test/api/TestUtils.ts
> +  `);
For what it's worth: Reverting that changes seems to cause some more testsuite failures relating to registerLinkProvider. I haven't looked into that. I'm hoping @jerch knows what to do.

2023-08-08 04:47 UTC, PerBothner commented on .eslintrc.json
> +    "addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts",
I agree those should be moved. I'm leaning to a sub-directory named `unicode-properties`.  E.g. `addons/xterm-addon-unicode-graphemes/src/unicode-properties/UnicodeProperties.ts`. However, a more generic/conventional subdirectory-name such as `imported` or `upstream` could also make sense. In that case `.eslintc.json` could use a generic pattern like `"addons/*/src/imported/**/*.ts"`.

2023-08-08 13:46 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      : (w >= 2 && (w === 3 || this.ambiguousCharsAreWide)) ? 2 : 1;
I prefer early returns to minimize indentation as you can then to things like this which are very readable imo:

```ts
function x() {
  if (!a) {
    return;
  }
  if (!b) {
    return;
  }
  // do the thing
}
```

This is just a personal preference, it doesn't really matter that much imo just as long as everything is consistent. Generally we try follow similar style to the codebase but we don't strictly enforce unless we set up a lint rule. I started wasting a lot less time when I stopped calling out style issues in PRs and instead spent that effort setting up lint rules 🙂

2023-08-08 13:54 UTC, Tyriar commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
As in it's a private API similar to how the renderers work?

@jerch thoughts? I think for the renderer API is makes more sense as it's so complex and would require changes, this however is quite small so it wouldn't be as hard to stabilize. Not having things hooked up as public API introduce does give a little more flexibility but it's easier to break.

2023-08-08 13:58 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
Since we definitely don't want to merge with these tests disabled, as a workaround until we move the addon loading we could add another arg to `openTerminal` like `disableUnicodeAddon: boolean = false`

2023-08-08 13:59 UTC, Tyriar commented on .eslintrc.json
> +    "addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts",
`vendor/` or `third_party/` would be my preference as imported/upstream are more ambiguous.

2023-08-09 01:43 UTC, PerBothner commented on .eslintrc.json
> +    "addons/xterm-addon-unicode-graphemes/src/UnicodeProperties.ts",
I moved the 3 files into `third-party`. I prefer hyphens rather than underscores in file-/directory-names. This may be partly because of my Lisp/Scheme history - but it also seems common in xterm.js. If you prefer `third_party` with underscore I'll be happy change it,

2023-08-09 04:14 UTC, PerBothner commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
How likely is it that anyone would want to write a custom IUnicodeVersionProvider or IUnicodeHandling? If that should happen, it is plausible that they would also want tweaks to the API. So might as well make the API private until there is a need to make it public.

2023-08-09 04:25 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
A simpler/cleaner approach might be not *not* require `allowProposedApi` to be true when activating `UnicodeGraphemesAddon` or `Unicode11Addon`.  The easiest fix is to remove the `_checkProposedApi` call in the `get unicode` method. Alternatively, it seems easy to add an internal `registerUnicode` method to Terminal.

2023-08-09 13:49 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
The `_checkProposedApi` call is what indicates it's an experimental API and should not be used without explicitly opting into it. Removing that would signal it's stable and we would be committed to not breaking it outside of a major version bump, since we're still discussing the shape of `Terminal.unicode` in this PR we wouldn't want to commit yet.

2023-08-09 13:54 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
I can see that user code shouldn't be using `Terminal.unicode` without explicitly opting into non-stable APIs. But should that apply to addons that are distributed as part of the main repository?

2023-08-09 19:48 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
I'm not sure rushing to stabilize a Unicode API is either needed or desirable.  I can certainly see adding functionality in the future that may or not be version-dependent: for example word-breaking or case-folding rules.

My suggestion is to add  the following to Terminal:
```
   registerUnicodeProvider(provider: IUnicodeVersionProvider): void;
```
Alternatively, I suggest we declare `IUnicodeHandling` and the `Terminal.unicode` property as non-experimental, but keep `IUnicodeVersionProvider` experimental.

2023-08-09 19:54 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
Well for this particular comment, adding that argument temporarily until we move the addon registration out of the core tests solves the problem. I created https://github.com/xtermjs/xterm.js/issues/4654 because I didn't realize until just now that you need the enable proposed API to use it, despite being the recommendation.

2023-08-09 20:55 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
Something like this?

[test-api-patch.txt](https://github.com/xtermjs/xterm.js/files/12306856/test-api-patch.txt)

(For some reason GitHub won't let me upload a file with extension `.patch` even though it claims that's a supported type. This is both Firefox and Chrome.)

2023-08-09 21:21 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
Yep just like that!

I pinged GH about .patch not working, it worked for me when I tried just now though. I have also asked them to expand the supported types as it's so easy yet really irritating to rename or zip it.

2023-08-09 21:53 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  it.skip('Proposed API check', async () => {
Checked in the patch.

The problem with uploading `patch` files is likely to be with the browser (or the tools it is using) to infer a mime type of the file. But it seems a mistake for GitHub to depend on the client-reported mime type: Since it has to sanity-check the file it after uploading anyway, perhaps it should just ignore whatever mime-type the browser reports?

2023-08-09 22:20 UTC, PerBothner commented
Summary of what I believe are still-unresolved comments - everything else has been addressed, I believe:

* InputHandler: `shouldJoin` logic - you requested help from @jerch.

* Possibly splitting the `wcwidth V15 emoji test` into multiple functions.

* Either document charProperties in xterm.d.ts/xterm-headless.d.ts or remove UnicodeVersionProvider. I suggest the latter. Another possibility is to add the type UnicodeCharProperties. I hate to duplicate the documentation of UnicodeCharProperties in Services.ts (because of the problem of making sure documentation stays consistent), but we can have xterm.d.ts refer to Services.ts. Or is there a better way to deal with this?

(Aside: It would be nice to be to generate API documentation automatically. GoldenLayout does that, though I'm not sure of the mechanism.)

2023-08-09 22:57 UTC, jerch commented
@PerBothner Prolly can look into things by tomorrow. I still have that annoying issue #4646, but that needs some work on the compiler package, so I will check this PR first.

2023-08-10 16:32 UTC, jerch commented
@PerBothner FYI - updated the PR to contain recent changes on master.

2023-08-10 19:37 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts
> +  });
I changed the comments to add a 'message' argument to each `deepEqual` call. (Actually `equal`, since `deepEqual` seems overkill.) I agree this makes it more helpful when a test fails.

However, it appears only one error is reported when multiple tests fail. Splitting into  multiple functions would presumably "fix" this - but I'm not sure that would be an improvement or worth the complication (and me figuring out more of the test API).

I'm going to declare "good enough" unless I get overruled.

2023-08-17 16:45 UTC, Tyriar commented
@jerch what was blocking on your end for this to go in?

2023-08-17 16:52 UTC, Tyriar requested changes
Looks very close 🎉 

The API discussions aren't much of an issue now due to the workaround with not loading the new addon in the tests and it's experimental, so they can be deferred.

2023-08-17 16:52 UTC, Tyriar commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
I don't think we want to auto load unicode 11 now?

2023-08-17 16:52 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
Since we're trying to go with an evergreen approach, should this just be 'graphemes'? That will then also align with the addon name.

2023-08-17 16:52 UTC, Tyriar commented on demo/client.ts
> +  term.writeln('🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣');
If you have any other good test data it would be good to stick here and in the unit tests

2023-08-17 16:52 UTC, Tyriar commented on src/common/InputHandler.ts
@jerch I didn't review this file too thoroughly as I'm relying on our tests to catch issues.

2023-08-17 16:52 UTC, Tyriar commented on test/api/Terminal.api.ts
> +  // fails with the grapheme injection, not sure why...
```suggestion
```

2023-08-17 17:02 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
We're kind of conflating two things: The graphemes support and the Unicode version we're supporting. I don't know how important it is to separate them - or to support multiple Unicode versions with or without grapheme support.

Perhaps going forward it is enough to support two combinations:
* Basic Unicode 6, without grapheme support.
* The current Unicode version (now 15), with grapheme support.

 Is it important to support more? If not, we could drop the unicode-11 addon. Presumably in a follow-on PR.

Perhaps we need two variables: `unicode.activeVersion` and `unicode.activeFeatures`?

2023-08-17 17:06 UTC, PerBothner commented on demo/client.ts
> +  term.writeln('🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣');
There is a Unicode grpheme-break testsuite, though it seems to focus on pathological edge cases, rather than real valid output. I'm not too concerned about how we render  clearly invalid sequences (as long as thy don't mess things up too much).

That said I could probably extract or come up with a few more interesting tests.

2023-08-17 17:08 UTC, PerBothner commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
Probably not, especially if we're going to deprecate the unicode11 addon, which I think makes sense.

2023-08-17 21:54 UTC, PerBothner commented on test/api/Terminal.api.ts
> +  // fails with the grapheme injection, not sure why...
Done.

2023-08-18 13:15 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
To make sure I understand things, the new addon implements unicode 15 (as the others do 6 and 11), in addition to graphemes, right?

We mentioned elsewhere that the plan was to have this addon move upgrade as unicode does, which means we cannot have the version number in the "version", otherwise changing it would be a breaking change?

> Is it important to support more? If not, we could drop the unicode-11 addon. Presumably in a follow-on PR.

Once this lands unicode 11 is less important, but dropping it completely would cause headaches to embedders trying to update.

If we're only planning on having 6 and "latest" going forward which seems reasonable, I think the best course of action would be:

- Deprecate unicode11
- Remove the experimental `unicode` API completely in the next major version (to reduce inconvenience for embedders)
- Hook up the graphemes addon via private APIs similar to the renderers as we never expect a community-based addon to exist

2023-08-18 13:16 UTC, Tyriar commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
I think it just gets replaced completely currently on this line?

```ts
typedTerm.loadAddon(addons['unicode-graphemes'].instance);
```

2023-08-18 13:37 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
> _"To make sure I understand things, the new addon implements unicode 15 (as the others do 6 and 11), in addition to graphemes, right?"_

Yes. Specifically the table used (the "unicode-trie") is generated by the [unicode-properties project](https://github.com/PerBothner/unicode-properties) from the Uncide data files, with `UNICODE_VERSION=15.0.0`. See the `Makefile` in the above project. At some point (perhaps after Unicode 16 is out) we might consider some other way to import this project.

> _"We mentioned elsewhere that the plan was to have this addon move upgrade as unicode does, which means we cannot have the version number in the "version", otherwise changing it would be a breaking change?"_

I don't know. It depends on whether you consider changing the version number to be a "breaking change"? I don't think I would be.  I mean could could break something that depends on something that changed - but that's always the case, and it doesn't seem to be a likely problem in this case.

2023-08-18 14:38 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
I mean we can change the internal version number without breaking, but if an embedder needs to set the version to 15 it will break when we change it to 16:

```
// This works currently
term.unicode.activeVersion = '15-graphemes';

// This will throw a runtime error if we change it to '16-graphemes'
term.unicode.activeVersion = '15-graphemes';
```

2023-08-18 14:54 UTC, PerBothner commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
The patch below removes unicode11 from the demo, which seems like a reasonable precursor to deprecation. For some reason I also had to remove `wcwidth V11 emoji test` from the `Unicode11Addon.api.ts` test - which seems OK. Let me know if I should check this in.

[demo-deprecate-u11.txt](https://github.com/xtermjs/xterm.js/files/12380550/demo-deprecate-u11.txt)

2023-08-18 15:07 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
> _" if an embedder needs to set the version to 15 it will break when we change it to 16"_

Unless we at that point support dynamic switching between 15 and 16, I think breaking in this case is the correct behavior: If an embedder "needs to set the version to 15" and we don't support that, it should break. Is being able to switch between 15 and 16 likely to be a use case that we need to support? If so, we can consider adding such support - later.

However, adding `unicode.activeFeatures` (set to `graphemes` if `unicode-graphemes` is loaded), and changing `unicode.activeVersion` to plain `"15"` seems more flexible and future-proof, so I suggest that. The former should probably be read-only, for now at least.

2023-08-18 15:43 UTC, PerBothner commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
Like this?
```
diff --git a/demo/client.ts b/demo/client.ts
index d733ec7e..ce6a5c64 100644
--- a/demo/client.ts
+++ b/demo/client.ts
@@ -274,7 +274,6 @@ function createTerminal(): void {
   addons.serialize.instance = new SerializeAddon();
   addons.fit.instance = new FitAddon();
   addons.image.instance = new ImageAddon();
-  addons.unicode11.instance = new Unicode11Addon();
   addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
   try {  // try to start with webgl renderer (might throw on older safari/webkit)
     addons.webgl.instance = new WebglAddon();
@@ -286,7 +285,6 @@ function createTerminal(): void {
   typedTerm.loadAddon(addons.image.instance);
   typedTerm.loadAddon(addons.search.instance);
   typedTerm.loadAddon(addons.serialize.instance);
-  typedTerm.loadAddon(addons.unicode11.instance);
   typedTerm.loadAddon(addons['unicode-graphemes'].instance);
   typedTerm.loadAddon(addons['web-links'].instance);
 
```

2023-08-18 15:44 UTC, Tyriar commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
Yep!

2023-08-18 16:32 UTC, PerBothner commented on demo/client.ts
> +  addons['unicode-graphemes'].instance = new UnicodeGraphemesAddon();
I committed that change.

2023-08-18 16:50 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
Hm. I tried to see what happens if the UnicodeGraphemesAddon is loaded, but I don't set:
```
xterm.unicode.activeVersion = '15-graphemes'
```
It doesn't work.  We probably want to fix that.

2023-08-18 17:57 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
What do you think?
```
export class UnicodeGraphemesAddon implements ITerminalAddon {
  private _provider?: UnicodeGraphemeProvider;
  private _unicode?: IUnicodeHandling;
  private _oldVersion: string = '';

  public activate(terminal: Terminal): void {
    if (! this._provider) {
      this._provider = new UnicodeGraphemeProvider();
    }
    const unicode = terminal.unicode;
    this._unicode = unicode;
    unicode.register(this._provider);
    this._oldVersion = unicode.activeVersion;
    unicode.activeVersion = '15-graphemes';
  }

  public dispose(): void {
    if (this._unicode) {
      this._unicode.activeVersion = this._oldVersion;
    }
  }
}
```

2023-08-18 20:48 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
> Hm. I tried to see what happens if the UnicodeGraphemesAddon is loaded, but I don't set:

This is a change we'll make as part of the next major version when we remove unicode11

2023-08-18 20:55 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
_"This is a change we'll make as part of the next major version when we remove unicode11"_

But it might still make sense to set `unicode.activeVersion` automatically (in the current PR), I think. That avoids a possible and needless future compatibility issue.

2023-08-18 20:57 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
While it is experimental so we're free to change it, I'm sure the unicode11 addon is used in several projects (including VS Code). Changing it will force them to potentially change that so imo we should just leave it for later when we do the bigger clean up

2023-08-18 21:01 UTC, PerBothner commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
I'm not suggesting changing the unicode11 addon. Only that if the unicode-graphames addon is activated, it handles setting unicode.activeVersion for you.

2023-08-18 21:03 UTC, Tyriar commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
Ah ok, yeah that makes sense as it should result in less work for the embedders in the end 👍. Just make sure the example is updated in the addon readme

2023-08-18 21:31 UTC, Tyriar approved these changes
Thanks @PerBothner, I think the only remaining things remaining is the merge conflict and for @jerch to sign off on the InputHandler logic

2023-08-18 21:47 UTC, PerBothner commented
@jerch Could you take at the conflict? It's in the `coloredErase` test in `demo/client.ts`. It looks like you did the same thing I did - removed some trailing whitespace.  @Tyriar thought the trailing whitespace was intentional.  If it is, I suggest using a `sp5` variable, like I did:
```
  const sp5 = '     ';
  const data = `
....
\x1b[m${sp5}\x1b[41m${sp5}\x1b[42m${sp5}\x1b[43m${sp5}\x1b[44m${sp5}\x1b[45m${sp5}\x1b[46m${sp5}\x1b[47m${sp5}
`;
```

2023-08-18 22:20 UTC, Tyriar commented
Fixed the conflict, it was intentional and someone accidentally trimmed it either via editorconfig or prettier.

2023-08-19 09:22 UTC, jerch commented
> @jerch what was blocking on your end for this to go in? 

Nothing blocking so far, its just the size of the PR which takes time to get through, and the ongoing remarks above changing things. Hope to be done soon...

2023-08-19 09:37 UTC, jerch commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
Well the unicode provider ended up on the API types exactly for that reason - if ppl want to make their own providers for different unicode versions.
There is another reason to have access to it - if ppl want to make in-browser REPLs, they need a way to anticipate correct unicode behavior applied by the terminal. For that they can use the provided `wcwidth` so far.

This somewhat changes with the more complex grapheme interfaces. I think we could keep those out of the API for now, and see if ppl will need access to it?

2023-08-19 09:48 UTC, jerch commented on test/api/TestUtils.ts
> +  `);
Yes that cannot stay there, it would introduce a hard dependency on the grapheme addon for all browser tests later on, if we checked it in. We also would lose testing on the old unicode provider interface.

This is somewhat coupled to reshaping the internal unicode provider interfaces - ideally they keep working with old providers (standard tests for now), but should also work for the grapheme enhanced provider(s).

My goal in future would be to move on to grapheme handling providers by default at some point, and just keep the oldunicode providers around as fallback cases. That will be needed often, as many cli apps dont do the grapheme handling either, thus the old providers may give better terminal output handling there.

2023-08-19 10:00 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
Agree with Per - in theory a cluster-aware provider would also be possible for our V6 and V11 providers. Or the other way around - V15 could also be offered w'o cluster support.

2023-08-19 10:11 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      : (w >= 2 && (w === 3 || this.ambiguousCharsAreWide)) ? 2 : 1;
Isn't this hot path code? I the past I found ternary to perform better in Javascript, thus I opt for ternary in hot path code normally.

2023-08-19 10:37 UTC, jerch commented on demo/client.ts
> +      term.unicode.activeVersion = '15-graphemes';
I made `unicode.ActiveVersion` a string field for exactly that reason - it does not simply map back a major version number, but should transport more information. I had it as simple integer denoting the major unicode version in the beginning, but found it cumbersome to reflect other aspects (like minor versions, or specific unicode capabilities).

So in theory it is perfectly possible to have multiple providers for `v15` w'o any higher capabilities, or `15-bidi`, `15-bidi,clusters` and so on.

Regarding V11 and V6 - imho we cannot remove them easily, as the unicode version used by the terminal ideally matches the cli apps expectations. Same with moving ` '15-graphemes'` silently on to V16 - if unicode16 contains critical changes, we break every app relying on V15 metrics.

_What we prolly should do in the long run:_
When a new unicode version comes out, check first if there are logic twists/changes, that need re-implementing of certain things. If there are - a new addon is needed anyway to reflect that.

If there are no logic twists in a new unicode version, do the following:
- use unicode property extraction tool to create new lookup table/trie
- compare the data with previous tables/trie:
- no terminal relevant changes: keep old addon, mark as compatible to new unicode version
- terminal relevant changes:
  - backwards compatible (added codepoints) - update old addon, mark as compatible to new unicode version
  - breaking changes (e.g. flips on codepoints) - create new addon
 
As for grapheme support - it would be good, if this addon gets a `graphemeSplitting: true | false` ctor option. This way we could bootstrap 2 providers from it - `15` for V15 codepoint support w'o graphemes, and `15-grapheme` with clustering. This is again needed for cli side, as many apps dont account clustering correctly. So grapheme clustering always on might introduce bad behavior there.

2023-08-19 10:41 UTC, jerch commented on src/common/InputHandler.ts
Looking into it more closely...

2023-08-19 11:03 UTC, jerch commented
@PerBothner Where does the code in `third_party` come from? It has no copyright or license claims, also I see no tests for it.

2023-08-19 11:38 UTC, Tyriar commented
@jerch they come from https://github.com/PerBothner/unicode-properties which is derived from https://github.com/foliojs/unicode-properties so we should get the license added 👍

Since it's a separate project it's fine that there's no unit tests.

2023-08-19 11:55 UTC, jerch commented
@Tyriar

Well my issue with that is - the code is copied over, but only the implementation. This creates frictions later on, if code changes are needed. M suggestion here would be - either make it an external package to depend (then everything like changes and testing can happen over there), or get the full deal copied over.

2023-08-19 14:43 UTC, jerch submitted a review, later dismissed
@PerBothner Well that took a while to get through, also I am not finished with testing various aspects, esp. around the `InputHandler.print` modifications.

My main concerns are around `InputHandler.print`, and the `UnicodeService` API.

2023-08-19 14:43 UTC, jerch commented on src/common/InputHandler.ts
> +      // therefore we can test for this._activeBuffer.x to avoid overflow left
Whats the reason for moving this below the DECAWM check? Maybe I am overlooking something, but for combining chars we dont need to eval DECAWM at all, so can it do before the check?

2023-08-19 14:43 UTC, jerch commented on src/common/InputHandler.ts
> +        }
Why is this "forward-cleanup" needed now? Shouldn't the normal char adding below already deal with that?

2023-08-19 14:43 UTC, jerch commented on src/common/InputHandler.ts
> +        bufferRow.insertCells(this._activeBuffer.x, chWidth - oldWidth, this._activeBuffer.getNullCell(curAttr), curAttr);
Can you explain, why this is needed? It kinda looks wrong to me - what happens if the base char has a width bigger than the current char?

2023-08-19 14:43 UTC, jerch commented on src/common/InputHandler.ts
> -      } else if (this._workCell.isCombined()) {
We cannot simply remove this, as it is needed for xterm compatibility.

Ofc we can discuss to lift the explicit compat settings here, but then we also should document it for REP.

2023-08-19 14:43 UTC, jerch commented on src/common/buffer/BufferLine.ts
> +    }
Why is this needed? Is the width unclear until the last codepoint got added to a segment? I always was under the impression, that the base chars basically determines the width, and we dont need the more ugly state changes in unicode? Maybe I miss here something... (Also affects some comments I made above regarding `InputHandler.print`.)

2023-08-19 14:43 UTC, jerch commented on src/common/input/UnicodeV6.ts
> +    return UnicodeService.createPropertyValue(0, width, shouldJoin);
Same as notes above for V11.

2023-08-19 14:43 UTC, jerch commented on src/common/services/UnicodeService.ts
> +  }
Can we get rid of these definitions by reshaping `UnicodeCharProperties` into:
```typescript
interface IUnicodeCharProperties {
  state: number;
  width: number;
  shouldJoin: boolean;
}
```
and pass that around by ref?

2023-08-19 14:43 UTC, jerch commented on src/common/services/UnicodeService.ts
> +  }
Suggestion:

```typescript
  public charProperties(codepoint: number, preceding: UnicodeCharProperties): void {
    this._activeProvider.charProperties(codepoint, preceding);
  }
```
where `preceding` is an object getting overloaded with new values.

2023-08-19 14:43 UTC, jerch commented on test/api/TestUtils.ts
> +  }
@Tyriar 
Should this still be removed afterwards? With this test option we can basically run the full API tests either in grapheme or non-grapheme mode, which seems handy to me.

2023-08-19 14:43 UTC, jerch commented on typings/xterm.d.ts
> +    charProperties(codepoint: number, preceding: number): number;
I think we should not expose that for now until we got the API idea straight.

2023-08-19 15:16 UTC, PerBothner commented on test/api/TestUtils.ts
> +  `);
I'm unclear what you're recommending. Take of the default loading of the UnicodeGraphemesAddon? That seems reasonable. However, note that I've tweaking the code a bit to make it a bit more robust and flexible.

When it comes to support for non-grapheme applications, I've thought a bit about it. One idea is a wrapper (an addon) where the wrapper converts between grapheme-aware world a non-grapheme-aware world.  For example Typing `Left` after a clustes consisting of 3 sub-characters would send 3 `Left` escape sequences. The addon can also translate line-wrapping behavior: The applications calculates line-wrap based on this being 3 characters (probably 6 columns) . The wrapper knows this to handle cursor positioning - but the line-breaks shown to the user are based on the correct widths.

This is a bit hand-wavy, so no need dig into it now.  The same idea of having two line-breaking states (one presented to the application, one presented to the user) can support variable-width fonts without having modify command-line applications. This sort of thing will become more feasible after the buffer rewrite.

2023-08-19 15:17 UTC, jerch commented
> @jerch Could you take at the conflict? It's in the coloredErase test in demo/client.ts. It looks like you did the same thing I did - removed some trailing whitespace. @Tyriar thought the trailing whitespace was intentional. If it is, I suggest using a sp5 variable, like I did...

Yes the space is intentionally. What causes the spaces to be removed? Some overly eager editor setting?

2023-08-19 15:51 UTC, PerBothner commented on src/common/InputHandler.ts
> +          if (oldWidth > 0 && bufferRow instanceof BufferLine) {
Probably not a hot path, as it is only when wrapping is needed.

I'm guessing meant "_add_ the missing method to the interface"?

My plan for the buffer re-write is that lines that are wrapped will share a single `_data` array. Wrapped lines will start at at offset from the beginning of the `_data` array.  So  the `copyCellsFrom` call will go away.

2023-08-19 15:54 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      : (w >= 2 && (w === 3 || this.ambiguousCharsAreWide)) ? 2 : 1;
Probably not hot-path anymore, as InputHandler no longer calls `wcwidth`.

2023-08-19 16:00 UTC, PerBothner commented on .eslintrc.json
> +    "addons/*/src/third-party/*.ts",
I wanted the "third-party" files from `unicode-properties` so it is easy to generate JavaScript from them, and also minimize divergence from the upstream projects I based it on. (Those projects seem to be unmaintained.) That it is easier if I don't have to follow xterm.js lint rules.

2023-08-19 16:11 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
Where do you draw the line? The non-grapheme variant should still handle simple clusters that consist of just a single base character followed by some modifiers. Otherwise it's a regression.

Without having examined the issue, the main differentiator is whether to ignore ZWJ (zero-width-joiner), thus treating true compounds as separate clusters. Handling of Regional Indicators (flags) is another issue. It is certainly possible to add a flag that restores the old non-standard behavior..  I'd rather not (I'm not sure it's needed), but I'll do whatever you and @Tyriar agree.

2023-08-19 16:24 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
Well the problem here is, that many cmdline apps are simply not segmentation aware, unless the system provides better unicode support for them, and instead just add `wcwidth` values to guess their content width.

Esp. macos is likely to create issues here, as it delivers a very old `wcwidth` impl (not sure, which unicode version it is created from, when I tried to deal with it 3ys ago, it still was v6)

So to separate grapheme support from non grapheme support, I would not deactivate certain segmentation rules, but the rule handling completely falling back to old wcwidth measuring. Note that grapheme handling was not even a thing in terminals until recently, so apps are very likely to get this wrong until they adopted it as well.

2023-08-19 16:25 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      w = w === 3 || this.ambiguousCharsAreWide || codepoint === 0xfe0f ? 2 : 1;
We really needed an update to the ancient [East Asian Widths TR](https://www.unicode.org/reports/tr11/tr11-6.html)  to deal with grapheme clusters and more.  In addition to VS15, it would be nice to have a recommendation on how wide en/em dashes/spaces should be.

@Tyriar If perchance you have a contact that is involved with Unicode standardization, perhaps check with them?

2023-08-19 16:35 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      w = w === 3 || this.ambiguousCharsAreWide || codepoint === 0xfe0f ? 2 : 1;
@PerBothner I think they dont feel obligated to solve the monospace issue for us:

> Note: The East_Asian_Width property is not intended for use by modern terminal emulators without appropriate tailoring on a case-by-case basis. Such terminal emulators need a way to resolve the halfwidth/fullwidth dichotomy that is necessary for such environments, but the East_Asian_Width property does not provide an off-the-shelf solution for all situations. The growing repertoire of the Unicode Standard has long exceeded the bounds of East Asian legacy character encodings, and terminal emulations often need to be customized to support edge cases and for changes in typographical behavior over time.

That note got added to TR-11 with unicode version 11. It basically says - "it is much more complicated, and we dont care to spec things out for the terminal". :see_no_evil:

2023-08-19 17:06 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
So the question is: If you paste a string containing a compound cluster into an input field in an application that just uses wcwidth and doesn't know anything about clusters, what will happen? Assume the application knows enough that wcwidth==0 means a combination. What should happen? Is this a use-case we should worry about?

In addition to spacing and alignment issues, consider what happens when  editing the input field: The application thinks the cursor is one place, while the terminal thinks it is another place.

Is this something we should support?  Is suggesting that people fall back to unicode6 or unicode11 unacceptable?

It is probably not too difficult for the addon to provide two implementations of `IUnicodeVersionProvider` which would differ in their implementation of `charProperties`. Instead of calling `UC.shouldJoin` you just check if the width of the current character is 0. You select one provider by setting activeVersion to `"15"` and the other to `"15-grpahemes"`. Presumably the latter would the default if you just load the addon.

I haven't looked into how much would be involved.

2023-08-19 17:21 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "name": "xterm-addon-unicode-graphemes",
> So the question is: If you paste a string containing a compound cluster into an input field in an application that just uses wcwidth and doesn't know anything about clusters, what will happen?

Whatever is defined in the selected unicode version + ruleset, e.g. for no-grapheme support the old wcwidth calc.

> Is suggesting that people fall back to unicode6 or unicode11 unacceptable?

Yes, it misses a lot of codepoints. V6 is even worse, as codepoints changed metrics in between.

> It is probably not too difficult for the addon to provide two implementations...

Isn't it just a bypass for the joining, as the width has to be pulled anyway?

---

I know the situation with unicode is really messed up in terminals, even worse for xtermjs, as it cannot even determine a sane default from the system it runs on (other desktop TEs can do that). Regarding grapheme support in terminals we in an "infrastructure trap" - someone has to make the first move (here either TE or app side), and the other side should follow. Thus I think grapheme handling should be on by default. But making it mandatory is imho wrong, as it is still pretty new in TE context.

2023-08-19 18:09 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemesAddon.ts
> +  }
Maybe something like this? (This of course is only the UnicodeGraphemeProvider part of the change.)
```
diff --git a/addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts b/addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
index b1c62020..b261b189 100644
--- a/addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
+++ b/addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
@@ -9,9 +9,13 @@ import { UnicodeService } from 'common/services/UnicodeService';
 import * as UC from './third-party/UnicodeProperties';
 
 export class UnicodeGraphemeProvider implements IUnicodeVersionProvider {
-  public readonly version = '15-graphemes';
+  public readonly version;
   public ambiguousCharsAreWide: boolean = false;
-  constructor() {
+  public readonly handleGraphemes: boolean;
+
+  constructor(handleGraphemes: boolean = true) {
+    this.version = handleGraphemes ? '15-graphemes' : '15';
+    this.handleGraphemes = handleGraphemes;
   }
 
   private static readonly _plainNarrowProperties: UnicodeCharProperties
@@ -36,7 +40,11 @@ export class UnicodeGraphemeProvider implements IUnicodeVersionProvider {
     }
     if (preceding !== 0) {
       const oldWidth = UnicodeService.extractWidth(preceding);
-      charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
+      if (this.handleGraphemes) {
+        charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
+      } else {
+        charInfo = oldWidth === 0 ? 1 : 0;
+      }
       shouldJoin = charInfo > 0;
       if (shouldJoin) {
         if (oldWidth > w) {
```

2023-08-19 18:18 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemesAddon.ts
> +  }
Oops - I meant:
```
+      if (this.handleGraphemes) {
+        charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
+      } else {
+        charInfo = w === 0 ? 1 : 0;
+      }
       shouldJoin = charInfo > 0;
```
I.e. checking the current width `w`, not `oldWidth`.

2023-08-19 23:20 UTC, Tyriar commented on test/api/TestUtils.ts
> +  }
TLDR of our discussions is we think we should get rid of the unicode11 addon, remove the `unicode` API, and hook unicode-graphemes up via private API similar to the renderer API. Same reasoning as the renderers, we're not expecting anyone to actually implement one.

2023-08-20 10:03 UTC, jerch commented on test/api/TestUtils.ts
> +  }
Like hard-coupling an xtermjs release to a certain unicode version? Eww, I think thats not a good idea. Also the v11 addon creates lit. no maintenance burden, as the data it contains will not change for the time being. Why would we want to dump that?

2023-08-20 21:08 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/third-party/UnicodeProperties.ts
> +const trieData = new UnicodeTrie(_dec(trieRaw));
We could so something like:
```
let trieData;
function initTable(compressedData) {
    trieData = new UnicodeTrie(_dec(compressedData));
}
```
Then `initTable` would be called when the addon is activated.

This would allow dynamic switching between Unicode versions, at least in principle - though it is probably cleaner to switch between multiple `UnicodeGraphemeProvider` instances, each with its own trieData table. Support for multiple Unicode versions leads to the question of how we bundle them: Would support for different versions use separate addons?  Probably easier to deal with if the actual logic is moved into the core.

I prefer to hold off on this for now, until we resolve how to bundle or import the unicode-properties package.

2023-08-20 21:23 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
I agree it's not the cleanest approach.  However, if we support multiple UnicodeCharProperties layouts then these functions can no longer be static, which is likely to have performance implications.  A static function can potentially be inlined - though I don't know of a way to have TypeScript actually do inlining.

2023-08-20 22:12 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts
> +    assert.equal(await evalWidth('🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣'), 20,
Well, these do test the segmentation rules - though only a few examples.

We could take the [Unicode GraphemeBreakTest.txt](https://www.unicode.org/Public/UCD/latest/ucd/auxiliary/GraphemeBreakTest.txt), parse it, and add those cases.  However, note that many of these seem to be testing edge cases of combinations that don't make sense, so I'm not convinced it's worth the effort. At least, I don't think it's a priority.

2023-08-20 22:24 UTC, PerBothner commented on addons/xterm-addon-unicode11/src/UnicodeV11.ts
> +  }
This is needed because `InputLines.ts` uses `charProperties` so the `unicode6` and `unicode11` providers have to implement `charProperties`. That seemed the cleanest way of doing things.

My goal is for InputLines to do just one table lookup per character. An API that separates the width inquiry from the join predicate would probably be cleaner, but it would require at least two table searches per character. So we use a single combined table search that returns both pieces of information encoded as a UnicodeCharProperties value.  More elegant would be for UnicodeCharProperties to be an object, but it is difficult to make that efficient.

2023-08-21 10:53 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
Hmm, as far as I am aware TS does not do that kind of optimization for us. I've never seen it inlining code blocks, I only know of the const enum trick for simple const value inlining. For functions/methods it will always keep the call, which might or might not be inlined by the JS JIT later on.

 (@Tyriar plz correct me, if I miss here something).

I have not followed all call traces of these functions in detail, but maybe reshaping `UnicodeCharProperties` into a ref passed object as described below can help here? It would also omit the additional bit packing & extraction steps, which are known to create instruction pressure (at least in C).

2023-08-21 11:00 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      w = w === 3 || this.ambiguousCharsAreWide || codepoint === 0xfe0f ? 2 : 1;
Ah well, I am not sure anymore, if VS15 should reduce emojis to 1 cell width. For VS16 it is explicitly mentioned that pictograms should be wide. There no such notion for VS15, which makes them somewhat unclear again (if width property should be applied, which can be narrow or wide for different symbols, or whether they still stick to wide). What a nonsense...

2023-08-21 11:05 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemesAddon.ts
> +  }
Yes I think that should do. Then all that is needed to be done, is to register both versions during addon loading (so both would appear under `unicode.versions`), and set the grapheme one by default. This way ppl can still opt-out the grapheme handling.

2023-08-21 11:10 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/third-party/UnicodeProperties.ts
> +const trieData = new UnicodeTrie(_dec(trieRaw));
Yeah, in fact I hope we can move the trie parsing part into core, once it is battle-tested. This gives us the ability to incorporate newer unicode versions much easier than it is now. (Also given, than we can easily create new trie definitions by some sort of a generator extarcting data from unicode relases)

2023-08-21 11:15 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/test/UnicodeGraphemesAddon.api.ts
> +    assert.equal(await evalWidth('🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣'), 20,
Well I am fine, if the main testing happens by other means, e.g. during trie generation. It is just that I want to make sure, that we dont miss out on a crucial aspect, as the unicode rules are somewhat cumbersome / convoluted.

2023-08-21 11:23 UTC, jerch commented on addons/xterm-addon-unicode11/src/UnicodeV11.ts
> +  }
> More elegant would be for UnicodeCharProperties to be an object, but it is difficult to make that efficient.

Hmm yeah, guess thats what I was suggesting below. What issues do you see with an object for efficency? If we get it working by passing a ref, it should not even create GC actions.

2023-08-21 11:39 UTC, jerch commented on src/common/InputHandler.ts
> -      } else if (this._workCell.isCombined()) {
Looking at the REP definition again, I think we can and should lift the strict xterm compat setting here:

> REP is used to indicate that the preceding character in the data stream, if it is a graphic character
(represented by one or more bit combinations)...

It clearly aims at the graphic character, and not only the previous codepoint (note the `..or more bit combinations`). In unicode terms a graphic character is most likely a "perceivable character", which would also include graphemes.

So we should extend the `precedingCodepoint` handling to a `precedingGraphicalCharacter` handling, which we can use both in REP and for the segmentation calc.

2023-08-21 11:54 UTC, jerch commented
@PerBothner 
Maybe its only me, but the review comments get somewhat hard to follow, esp. spotting all follow-up comments. Seems notifications only shows the last one added? Plz bear with me, if I missed a comment.

2023-08-21 13:33 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/package.json
> +  "repository": "https://github.com/xtermjs/xterm.js",
:+1: https://github.com/xtermjs/xterm.js/issues/4705

2023-08-21 13:35 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      charInfo = UC.shouldJoin(UnicodeService.extractCharKind(preceding), charInfo);
> For functions/methods it will always keep the call, which might or might not be inlined by the JS JIT later on.

This is my understanding but I'd need to look up the conditions in which a function is inlined. I know there's some V8 tool that lets you inspect optimizations like this.

2023-08-21 13:38 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/third-party/UnicodeProperties.ts
> +const trieData = new UnicodeTrie(_dec(trieRaw));
Definitely deferring would be nice, if it's quite expensive then even better would be to split up the task via an `IdleTaskQueue`. Consider the case where this is loaded in an IDE where a lot of things happen on start up, so we want the CPU to do as minimal work as possible when loading in the terminal code and starting it up.

2023-08-21 13:42 UTC, Tyriar commented on addons/xterm-addon-unicode-graphemes/src/tsconfig.json
> +    "target": "es2015",
Definitely, I even mentioned this in the esbuild draft PR. It just needs someone (probably me) to verify everything works with the newer version and we should get wins wrt bundle size and performance as polyfills will get removed. https://github.com/xtermjs/xterm.js/issues/4706

2023-08-21 13:47 UTC, Tyriar commented on test/api/TestUtils.ts
> +  }
Whatever you think is right here is what we should go with, you're much more knowledgeable in this area

2023-08-21 13:48 UTC, Tyriar commented
@jerch it's useful to go over the old comments and close them out as resolved, that way we have a set of unresolved comments that we need to go through (there's actually a GH repo setting that forces you to resolve all conversations too)

2023-08-21 14:00 UTC, jerch commented
> @jerch it's useful to go over the old comments and close them out as resolved, that way we have a set of unresolved comments that we need to go through (there's actually a GH repo setting that forces you to resolve all conversations too)

I kinda tried that, but now the old review comments got inter-mixed with my new ones. What makes it hard to follow, is that gh starts to fold reviews parts, thus I have to start from above unfolding all, then looking at not yet resolved parts.

Not a biggie at all, but chances are high that I miss something. Well if it gets really out of hand we still can close the PR and reopen it on a "clean slate".

2023-08-21 14:09 UTC, PerBothner commented on addons/xterm-addon-unicode11/src/UnicodeV11.ts
> +  }
I think passing a pre-allocated object as an "output parameter" is a clunkier and less natural API than a semi-opaque integer. In terms of performance with modern computers and compilers, accessing a property (and thus referencing memory, even if cached) is going to be more expensive and harder to optimize than some simple bit fiddling. The cost of the former is likely to be small - but it done for every character.

2023-08-21 14:14 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/third-party/UnicodeProperties.ts
> +const trieData = new UnicodeTrie(_dec(trieRaw));
[This](https://github.com/PerBothner/unicode-properties/blob/master/src/generate.js) is the unicode property extractor script.

2023-08-21 14:27 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/third-party/UnicodeProperties.ts
> +const trieData = new UnicodeTrie(_dec(trieRaw));
The tricky part of lazy loading when to do the loading and how to test that loading is needed. The simplest and cleanest is to do it in the `charProperties` function, but then you're adding another test in the critical path. More efficient would be to check if loading is needed when we get a block of bytes from the application, but that means some extra API-tying.

Perhaps we can add an `initializeIfNeeded` method to the `UnicodeProvider` API.

I suggest deferring this to when we move the UnicodeGraphemes code into core.

2023-08-21 15:23 UTC, jerch commented
Some notes about a possible unicode integration with xtermjs in the long run:

_What we have to deal with in general:_
Unicode changed the release strategy several years ago from the former "yep, we've collected enough pressing changes - new release has to be made" to a more regular (~yearly) release schedule with more compat in mind. So while v6 was the main release for several years on all systems (which is also the reason we cannot easily dump v6), releases from around v12+ onwards contain much smaller changesets, often only consisting of newly defined codepoints.

In summary there is a high chance to stay compatible to newer releases by just adding a few codepoints to the trie. But ofc thats not given for sure, as any new release might contain breaking changes to already existing unicode features. So in end raising unicode support to a new version always includes manual checks of the changeset and whether we are affected by the changes in a way, that needs a version split on our end.

_What does account for a version split:_
- Changes on properties we are dealing with. This happened in the past from v8 to v9 for all emojis, when they fixed their width to wide in pictogram repr. It also happened for a bunch of codepoints, when they introduced new categories for more complicated segmentation rules (multiples times, in v10, v11 and v12 mainly).
- Changes on rules, like segmentation rules. Again most changes here happened in v10 and v11. Rule changes need implementation changes on our end, thus cannot be packed easily into one code base.

_What definitely does not account for a version split:_
Newly added codepoints, that were undefined before. We are lucky here, most newer release just added codepoints as far as we are concerned with unicode. In that case we can simply update the trie to also contain the new codepoints, and can claim it to be _vX_ and _vX+1_ compatible.

_How could that work in xtermjs?_
- move v6 out of core into its own addon
- keep v11 addon (mainly for compat reasons, I am not keen to check if v12 -> v13 -> v14 -> v15 has breaking changes anywhere qualifiying for another addon creation)
- move the trie logic into core
- add v15 segmentation rules to core
- expose 2 modes - one with grapheme segmentation (default), one without (fallback to old wcwidth only)
- once a new unicode version gets released:
  - check for rule changes --> might need rule implementation update & version split
  - check for properties changes --> might need trie update & version split
  - add new codepoints to trie

The _check & version split_ part is cumbersome, as it means to create a new addon if a split is needed. Given the fact that we sailed pretty unaffected with v11 for quite some time (beside a few issues regarding new emoijs, which would be covered by the trie updates) I dont expect that we have to create a new addon every time a new unicode release comes out.

_What would the addon output look like? (some mostly silly examples, but we dont know what they come up with):_
- v16 only adds codepoints. --> Update trie and mark compat of core unicode provider as v15, v16. (not much to do here...)
- v16 changes emojis' width to 3 cells. --> Create v15 addon from core provider. Move core to v16 applying changed emoji width.
- v16 introduces new non-breaking rule for emojis following spaces. --> Create v15 addon from core. Move core to v16 implementing that silly rule.

---

Up for discussion. It sounds cumbersome and like a lot has to be done to get it right, but I think it can work given an unicode release stays within the "again only codepoints added" assumption. It also would need to move the trie handling into the core, and to have an easy trie generator somewhere at hand.
And once graphemes are not new anymore to TEs and got a critical adoption rate across cli apps, we can also remove the wcwidth fallback impl. (Note that even v6 already had grapheme rules defined, but not a single app resp. TE dealt with that.)

2023-08-21 15:24 UTC, jerch commented on test/api/TestUtils.ts
> +  }
To not clutter the review comments too much, plz see below here: https://github.com/xtermjs/xterm.js/pull/4519#issuecomment-1686540650

2023-08-21 15:46 UTC, jerch commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      w = w === 3 || this.ambiguousCharsAreWide || codepoint === 0xfe0f ? 2 : 1;
To not block on a silly thing like VS15, maybe just add a comment somewhere, that VS15 is not treated special in width handling.

2023-08-21 16:02 UTC, jerch commented on addons/xterm-addon-unicode11/src/UnicodeV11.ts
> +  }
Ah well can't say much about mem access costs here vs. function call overhead, unless explicitly tested. My guess here only results from the expedience I made during parser and bufferline rewrites:
- huge perf boost by omitting function calls (parser)
- boost by using C-style ref-loading (bufferline)

Furthermore in the parser the bit extraction there creates a lot of the perf penalty, to me it seems that JS has a hard time to "subpipeline" these - for comparison: in C the bit packed parser table is faster, while in JS an expanded table would be slightly faster, although having more mem to read. I still went with the packed table in JS because of file output size.

2023-08-21 17:40 UTC, jerch commented
@PerBothner I am kinda still stuck at the `precedingCodepoint` and the grapheme progression with or w'o split. I think if we enhance `precedingCodepoint` partially by the needed properties for segmentation eval we can reduce some of the state complexity needed in `Inputhandler.print` (not quite sure yet how to properly shape that, will try a few pattern).

2023-08-21 18:05 UTC, PerBothner commented
You mean:
```
echo -en "\U1F469\u200d" && sleep 2 && echo -en "\U1f469\u200d\U1f466"
```
You're right - that doesn't work correctly.  And it probably has something to do with one or both of `precedingCodepoint` or `precedingJoinState` not presisiting properly.

It does work in default DomTerm (i.e. if you don't specify `xtermjs=true`). It's kind-of cute to see the Emoji changing.

2023-08-21 18:42 UTC, jerch commented
@PerBothner  Eww, it also works "by accident" with the DOM renderer, seems the letter spacing is the same :rofl: .

2023-08-21 20:02 UTC, jerch commented
Mentally pressing the reset button, thus I started with a rough idea for `print` (schematically):

```typescript
print(data: Uint32Array, start: number, end: number) {
  let state = parser.prevState;
  let pos = start;
  while (pos < end) {
    const cp = data[pos++];
    if (!shouldJoin(cp, state)) {
      const width = state.width;
      // DECAWM + INSERT MODE offset changes go here
      buffer[x].addCodepoints(data, start, pos, FG, BG);  // to be written
      start = pos;
    }
  }
  if (start < end) {
    buffer[x].addCodepoints(data, start, pos, FG, BG);
  }
  parser.prevState = state;
}
```
This still needs an `buffer[x]` offset correction, if `prevState` with `data[start]` should join (makes the schematics confusing, so I skipped it here).

Isn't that all we need in `print`?

2023-08-21 20:14 UTC, PerBothner commented
I checked in a patch to provide both `"15"` (only basic modifiers that have width 0) and `"15-graphemes"` (full cluster support).

2023-08-21 21:21 UTC, PerBothner commented
@jerch Concerning your `print` outline:

This ties very much into my buffer re-write - which I've put on hold dealing with this PR. One reason I'm easer to get this PR merged is to I can update my buffer-rewrite branch to use the new character APIs.

I'm thinking that it might make sense to defer line-wrapping: The `print` function just appends characters to a temporary buffer, with no concern about line-wrapping. Line-breaking is deferred until it "needed": Cursor re-positioning or a timeout (before rendering). Then line-breaking is done for the accumulated input line, with characters moved to the actual Buffer.

Potential benefits:
* Easier to share line-breaking logic between input handling and window-resize handling. This becomes especially beneficial if we want addons to be able to plug in more complex line-breaking algorithms (pretty-printing, folding, floating right prompts to the right, etc).
* It might also make sense to batch checking for grapheme cluster boundaries (to just before line-breaking). This could allow for using WASM with reduced context-switching overhead.
* Reducing memory for BufferLine since we only need to allocate a `_data` array based on the actual line length.

2023-08-22 01:13 UTC, PerBothner commented on src/common/InputHandler.ts
> -      } else if (this._workCell.isCombined()) {
If we redefine REP from "repeat preceding character in the data stream" to "repeat character before the cursor" then we can get rid of all of the `precedingCodepoint` setting and resetting. The implementation of REP has to do a little more work (but we don't care because it is so seldom used), while the rest of the code is simpler.

This doesn't solve the issue of how to handle `precedingJoinState` across multiple `print` calls. One can use the same idea as for REP: have `print` initialize `precedingJoinState` based on the character class of the character before the cursor. However, that is expensive unless you do something clever.  The simplest approach if we get rid of `precedingCodepoint` is to change every (?) place we currently do:
```
this.precedingCodepoint = 0;
```
instead do:
```
this.precedingJoinState = -1;
```

2023-08-22 09:26 UTC, jerch commented on src/common/InputHandler.ts
> -      } else if (this._workCell.isCombined()) {
Well in REP all we need is an indicator, if we are behind a previous char print on the band data, so we can repeat it. This indicator does not need to be the char itself, in fact a boolean is enough because, as you pointed out - we can grab that char from the last cursor pos (cursor pos will not have changed yet by other means than normal left-right progression, otherwise the indicator is false anyway).

With the segmentation rules we kinda have the same continuation problem, but now on print itself - we somehow need a way to inform the next invocation, whether to continue an already started codepoint cluster or to start over from scratch.

And I think they both indeed follow the same continuation exit rules - REP shall not repeat anything, if there was any other (spurious) sequence/command in between, also a cluster would break on control chars. So yeah, both can be handled by that.

Now to what the indicator may contain - as a minimum both only need a boolean to indicate whether to continue or not (as both can bootstrap the info from last cursor cell). At best REP would need the full cell content (better than xterm) or the first codepoint (only xterm compat mode possible), and the cluster either needs the cell content (where it started to write out the dangling cluster) but is also good with the prev cluster state.

Now REP is a very rare sequence, we dont need to optimize things here, so we are prolly good with a boolean and REP itself doing more work.
On the other hand `print` is hot path, there we should aim for fastest processing (less instructions, less branchy). So it seems logical, to put as much data in the indicator to ease the cluster continuation decision, yeah.

Propsal - reshape `precedingCodepoint` into a `printContinuation` like this (schematically):

```typescript
print(data, start, end) {
  // at print start - calc cell offset to continue writing
  buffer.x -= parser.printContinuation & 3;
  // now x is either a new cell or the old one to continue with
  for (...) {
    // char loop
    ...
  }
  // always move cursor forward at the end
  buffer.x += lastClusterWidth;
  ...
  // at print end
  parser.printContinuation = char_state << x | shouldJoin << y | lastClusterWidth;
}
```
The parser then can simply set `printContinuation` to zero to indicate a non-continuation. Also REP is pretty easy (eval non zero, pull width, load cell content at cursor - width, fanout content).

2023-08-22 09:47 UTC, jerch commented
> I'm thinking that it might make sense to defer line-wrapping: The print function just appends characters to a temporary buffer, with no concern about line-wrapping. Line-breaking is deferred until it "needed": Cursor re-positioning or a timeout (before rendering).

Well basically any other sequence will need to trigger the line wrapping then, so I am not sure, if we can win a lot here. What might work though - defer line wrapping until end of print. But then a temp buffer isn't needed either, just an interim buffer marking cluster splits, widths and softwraps from DECAWM.

(Btw I implemented a similar idea in my C playground - the buffer there just stores incoming utf8 directly, and marks attrib changes and wraps. The inner cell assignment gets not realized until really needed by a sequence. Thats pretty fast for dumping tons of data, and also smaller in memory. Well as soon as cursor sequences come in, it is missing the flat memory access and thus is slower...)

2023-08-22 10:09 UTC, PerBothner commented
_"Well basically any other sequence will need to trigger the line wrapping then"_

Style changes do not need to trigger line-wrapping. In practice: non-interactive output will only need line-wrapping on seeing crlf.

2023-08-22 10:16 UTC, jerch commented
> Style changes do not need to trigger line-wrapping. In practice: non-interactive output will only need line-wrapping on seeing crlf.

Then you are talking about a totally different terminal implementation. The issue here - we dont know, if the following sequence needs a proper grid being assigned, thus you either have to mark sequences as grid-critical (cumbersome and error-prone, esp. for custom made sequences) or need to "grid-out" at the beginning of the next sequence.

2023-08-23 15:11 UTC, PerBothner commented
This seems to work in with limited manual testing, but I'm haveing problems running the tests or starting the demo. (Some seeminly-unrelated wasm problem.) So there might still be some testsuite failures, though I updated what I can.

This changes REP to work on grapheme clusters, as discussed above. The `precedingCodepoint` field is gone. Instead we use `precedingJoinState` for both clustering and REP.

[preceding-state-patch.txt](https://github.com/xtermjs/xterm.js/files/12420702/preceding-state-patch.txt)

2023-08-23 17:40 UTC, Tyriar commented
FYI @DHowett is involved with the Unicode Consortium who are discussing how unicode graphemes should work in the terminal. He's a little concerned about this landing. @DHowett can you set up @PerBothner and @jerch any relevant details?

2023-08-23 20:33 UTC, jerch commented
@PerBothner Thx for the REP patch, LGTM :+1:

I suggest to stall things here, until we some informed feedback from @DHowett. (Many unicode aspects and terminals dont work well together, maybe they are up to something to fix this in a different way...)

2023-08-27 19:06 UTC, PerBothner commented on addons/xterm-addon-unicode-graphemes/src/UnicodeGraphemeProvider.ts
> +      return UnicodeGraphemeProvider._plainNarrowProperties;
While my TypeScript knowledge is limited, I'd be surprised if you could initialize a const enum value to that of an expression involving a function call. However, it is "const global data" in that it is a value that would not depend on Unicode version.

We can manually pre-compute the value, and use that to define an enum const. We can depend on the test suite to confirm that we didn't mess up the calculation.

2023-09-07 19:21 UTC, PerBothner commented
How much longer do we wait for @DHowett? (I also sent him an email, which he hasn't responded to. Perhaps @Tyriar could make another attempt to contact him?

I updated the branch from upstream. GitHub  reports some weird testsuite-failures, including lint running out of memory. (`yarn lint` works fine locally.)

2023-09-11 12:45 UTC, Tyriar commented
You're right, I can have that discussion internally and unblock merging this if we just mark it as experimental in the readme.

2023-09-11 12:45 UTC, Tyriar commented
I'll have a look at the CI failures, OOM is quite surprising.

2023-09-11 13:07 UTC, Tyriar commented
@jerch I'll do a once over of the core files, any concerns on your end to get this merged given we have a warning in the readme now?

2023-09-11 13:10 UTC, jerch commented
@Tyriar If there are no surprising changes in the newer commits (did only a quick peek) I think it is good to go as it is.

2023-09-11 13:22 UTC, Tyriar commented
@jerch I'll bring it up in our next monthly sync

2023-09-11 13:24 UTC, Tyriar commented
@PerBothner fixed the CI issues:

- I guess eslint just takes a lot of memory and we hit the threshold, that was fixed by increasing node's memory limit https://github.com/xtermjs/xterm.js/pull/4519/commits/a003034b0264283b4030a7a2cf3fc2a0b061f261
- The API/playwright test failures were just because we weren't uploading the build artifacts of the new addon https://github.com/xtermjs/xterm.js/pull/4519/commits/1b5756c1b10a6c58b29d1d1bfaf32fbb95623e24

Sorry about all the conflicts, we have a pretty sweet CI setup now though 😅

2023-09-12 20:56 UTC, Tyriar commented
Merging! We'll set up publishing https://github.com/xtermjs/xterm.js/issues/4797

2023-09-12 20:56 UTC, merged

2023-09-12 21:06 UTC, PerBothner commented
Thanks! Next I will "rebase" the BufferLine re-write to use the grapheme-cluster API.

2023-09-12 21:15 UTC, Tyriar commented
@PerBothner 👌, I think I mentioned it before but we'll want to chat about the high level ideas in the proposed buffer line rewrite before investing too much time to make sure we're all on the same page.

2023-09-12 22:32 UTC, PerBothner commented
@Tyriar _"we'll want to chat about the high level ideas in the proposed buffer line rewrite"_

I agree. There was some discussion in issue #4513, but mixed in with the clustering issue,
I suggest closing #4513, and either creating a new Issue or a "work-in-progress" Pull Request. The former probably makes more sense, as the current state of my branch needs quite a bit of work to be usable.

This issue is pretty important to me. I am seriously considering switching DomTerm engine to xterms.js for various reasons (mainly performance and community). However, DomTerm has a very ambitious vision and already has a lot of features that xterm.js doesn't have. (Hence a lot of DomTerm features would have to be ported or re-implemented.) The existing BufferLine representation is simple but quite limited, and not a good match for some of the things I want to do, including things that DomTerm currently supports.

2023-09-12 22:38 UTC, Tyriar commented
@PerBothner closed, yes please create the issue and we can chat there. It's a bit tough to filter through all this info quickly so it would be good to separate the discussions.

The main goals on my end of the buffer system is fast access and tight packing of the data. The major things I'd like that come to mind for the buffer are deferred clean up/reflow of the arrays (https://github.com/xtermjs/xterm.js/issues/4232) and leveraging less, larger array buffers to store the data (I think this might be something you were after too). We also have the decoration system which adds a lot of extensibility capabilities which are slower but very flexible.

2023-09-12 22:55 UTC, PerBothner commented
FWIW DomTerm already does deferred re-flow. (Partly because re-flow is fairly expensive in the general case, which may include non-trivial pretty-printing and variable-width fonts.) I will cover re-flow in my proposal.

I'll write up the design, goals, and features in a new Issue, hopefully later today or possibly tomorrow.

2023-09-13 21:40 UTC, PerBothner commented
See new issue #4800 about a `BufferLine` re-design.