Fix overline not working on certain fonts
xtermjs/xterm.js pull request #4543
Opened 2023-05-31 18:48 UTC by ChaseKnowlden

Fix #4541

2023-05-31 19:51 UTC, Tyriar requested changes

2023-05-31 19:51 UTC, Tyriar commented on css/xterm.css
> +    padding-top: 0.05em;
We shouldn't touch padding as that would change the size of the elements/grid. It's a bit of a shame not using the real overline decoration, but perhaps we should just use border-top. If we do, we would need to make sure that `box-sizing` = `border-box` and then undo all the `text-decoration`-related styles introduced for overline (eg. `.xterm-overline.xterm-underline-1`).

2023-06-07 19:18 UTC, ChaseKnowlden commented on css/xterm.css
> +    padding-top: 0.05em;
Removed the padding.

2023-07-31 20:14 UTC, jerch commented
Imho this PR addresses the issue from the wrong side (its a visual hack). We should instead make sure, that the DOM renderer paints the lines high enough to display all decorations in a proper way.

2023-08-01 12:39 UTC, closed without merging