Faster DOM renderer
xtermjs/xterm.js pull request #4605
Opened 2023-07-21 17:47 UTC by jerch

Early PoC, very much WIP. :smile_cat:

2023-07-21 17:55 UTC, willmcgugan commented
Looking forward to this one! 😀

2023-07-21 18:43 UTC, jerch commented
Geez, the branch/commit history is very broken (prolly from my older attempts), needs serious rebasing...

2023-07-22 09:15 UTC, jerch commented
@willmcgugan Indeed, this promises some serious perf boost for DOM renderer. Still it creates quite some glitches, idk yet if they all can be worked around.

2023-07-22 11:38 UTC, jerch commented
@Tyriar Plz have a look at this profiler stats:

![grafik](https://github.com/xtermjs/xterm.js/assets/6193135/fdad80d8-d277-4c54-bb49-6f62167ffd61)

Is there a specific reason, why the selection service calls into `renderRows`, although I have nothing selected at all? Note that it also takes twice as long as from the render debouncer. This kinda  looks like a big perf smell to me, but idk the inner works of the selection service.

2023-07-22 13:16 UTC, jerch commented
@Tyriar The last commit can fix the superfluous paints from the selection service, saving ~1s runtime for my test. Would be good if you can have a look at it and check, whether thats a viable way to debounce the selection refreshs.

2023-07-22 15:39 UTC, jerch commented
Eww - the link underline logic for mouse hovers needs a full rework with the merged spans, it simply cannot be done that way anymore :cry:

2023-07-23 22:05 UTC, jerch commented
@Tyriar The following test is failing on windows only for no obvious reason: https://github.com/xtermjs/xterm.js/blob/1c98037eede9b6cb9610e20372ec43b6b19e69b7/addons/xterm-addon-search/test/SearchAddon.api.ts#L245-L261

Tested it manually under linux, where it works as expected. Since I have no working windows installation I cannot look into it. Any clue why this might be failing?

2023-07-23 22:29 UTC, jerch commented
About ligature joins (all manually tested):
- View composition works as expected.
- View on selection from the left side works as expected. From the right side the right-most chars still get blacked-out until the left-most of the ligature is selected too. Thats a quite weird behavior, not quite sure yet, whats causing this.
- Moving the cursor into a a ligature shows a similar misbehavior - on the left-most cell the whole ligature gets "cursored", for any other cell to the right the cursor vanishes.

2023-07-23 22:34 UTC, jerch commented
I'd say this implementation is ready for first alpha tests. It would be very helpful if anyone interested in testing this could run it with any sort of complicated cmdline tools, so we can spot left-over regressions.

2023-07-24 14:33 UTC, jerch commented
Not sure yet what to do about the bold, italic and bold&italic font variants. Currently it is assumed, that a proper monospace font wont have different glyph widths for those, but this gonna break really bad if only the regular variant is available and the font renderer has to use a fallback font.

The issues with also calculating these variants are:
- they are pretty rare in a terminal context, might not be worth to bother at all
- multiplies calc runtime by 4 to [regular, bold, italic, bold&italic] - currently regular takes ~500ms for codepoint 32 to 1423
- merge logic gets more cumbersome

Possible solutions:
- blacklist them from the merge dropping back to single cell spans (re-introduces ugly glyph cuts in italic)
- calc them as well, but on a smaller codepoint range (e.g. ASCII only, should still address >>90% of terminal chars)

2023-07-25 09:51 UTC, jerch commented
@Tyriar Gonna blacklist bold & italic variants for now - does not seem worth it for the runtime penalty it would introduce.

2023-07-25 12:56 UTC, mofux commented
> Currently it is assumed, that a proper monospace font wont have different glyph widths for those, but this gonna break really bad if only the regular variant is available and the font renderer has to use a fallback font

Yep, this will likely happen. When I implemented my own DOM based xterm renderer a while back, I worked around this problem the following way:
- the default character width is based on the measured with of a test character, e.g. "W"
- measure the actual width of every character that should be drawn and remember it in a map for caching (most should have the same width as your test character)
- similar to how you are splitting multiple characters based on different attributes, you now also have to split them based on their width. Whenever one character has a different width to the width of its predecessor, it needs to go into a separate span.
- and now comes the trick: if the character width is not the same as your test character width, calculate the offset, and then apply this offset to the span using the `letter-spacing` css rule. This rule allows you to add a positive or negative offset to a character in `px`. This will make sure that those non-standard width characters get the same width as your default character. And it even works if you have multiple non-standard width characters in the same span, just as long as they have the SAME non-standard width.

I hope you get the idea.

2023-07-25 13:20 UTC, jerch commented
@mofux Oh hi there! Your `letter-spacing` rings a bell - have we talked about that in the past? Gonna look into that.

> When I implemented my own DOM based xterm renderer a while back...

Now I am curious - how does your implementation compare to the current DOM renderer? Do you treat all characters that way or do you pre-limit chars to account? I found that the width measuring is very expensive, thus I limited it to ASCII + latin1 supplement, while everything else still gets its own span. This helps for >90% if terminal data, but ofc not for content outside of latin.

2023-07-26 09:52 UTC, jerch commented
The width calculation is still very expensive. Currently it uses `requestIdleCallback` to do the full roundtrip of adding measure elements + getting the bounding rects, which causes alot of forced layouting. I can only do ~30 codepoints/call this way to not introduce alot of blocking time, overall it takes ~2s for 4096 codepoints. Hmm.

There are still a few ideas to get this faster:
- Bind to `requestAnimationFrame` instead and slice work into a placement and a measuring step. I hope to get higher codepoints/call by aligning the measurement to normal render cycles.
- desperate: Check if painting to a canvas yields the same widths, if so thats prolly much faster.
- desperate & last resort: Put things into an iframe. There we can operate in much bigger batches, as blocking time is no concern. Well thats only a last resort creating a lot of fuzz like issues from security settings or how to correctly set up all needed CSS rules there.

I def. wanna try mofux's `letter-spacing` idea - it opens the field for handling a bigger codepoint range in a neat way. My idea is now to warm up with ASCII range only and to do higher BMP codepoints lazy on-the-fly.

2023-07-26 13:56 UTC, mofux commented
> Now I am curious - how does your implementation compare to the current DOM renderer? Do you measure all characters that way or do you pre-limit chars to account

I'm measuring any character as it appears for the first time. No warm-up. I'm using the [monaco API](https://github.com/microsoft/vscode/blob/96ebd364f01c62305037073a1e994110d5f378c6/src/vs/editor/browser/config/charWidthReader.ts#L140-L143) for this measurement which already utilizes a caching layer, so chances are that a lot of characters are already measured because of a previously opened editor.

I did not notice any performance issue with this. Filling a 1000 line scrollback with random chars spends about 50ms on the measure call in total (over the course of 1s) - but I might be missing something. There's a lot going on behind the scenes of the monaco editor itself that is rendering out the lines.

2023-07-26 14:49 UTC, jerch commented
@mofux Thx for the pointer to the monaco API. I am pretty sure that this isnt faster than my current approach, as the API measures chars one-by-one, which I did before as well. I already optimized that to batches of 30 chars at once, which is ~5 times faster than before.
There are still perf smells in my setup though (like complicated CSS rules), monaco's code doesn't need them and I can prolly simplifiy things as well.

> I'm measuring any character as it appears for the first time. No warm-up.

Hmm, gonna try that, maybe the penalty isnt that big. Didn't even think about this obvious way, as doing the measuring in the render call creates much more relayouting stress, thus looked like an anti-pattern to me.

2023-07-27 14:25 UTC, Tyriar requested changes

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> +  private _linkState = new Uint8Array(3);
It's not clear what this represents

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> +    container.remove();
Would it be better to split this into its own class which manages cached `container` and its children until the task is done?

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> +      this._fontMetrics[i + this._metricsPos] = +(width < lower || width > upper);
🤨 is this setting 1 if not `lower < width < upper`? A comment or clearer code would be good as I'm just guessing 😅

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> +    this._cacheMetrics();
`_warmUpFontMetrics`? Does this check if they aren't measured yet when it needs to be used? A class could help this too by caching a codepoint synchronously at the time of its use.

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> -     * - (async) render update: brings term metrics and render state back in sync
Does this not happen anymore?

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRenderer.ts
> +      const lineData = this._bufferService.buffer.lines.get(row);
Declaring the variables outside the loop will save some memory getting allocated

2023-07-27 14:25 UTC, Tyriar commented on src/browser/renderer/dom/DomRendererRowFactory.test.ts
> +const EMPTY_METRICS = new Uint8Array(1024);
I was expecting `(256)`?

2023-07-27 14:46 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +    container.remove();
Yeah, thats already in the making, as the letter spacing idea changes too much, and I need myself something like an API :smile:

2023-07-27 14:49 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +      this._fontMetrics[i + this._metricsPos] = +(width < lower || width > upper);
Yeah the old logic just separates between 1|0 state for being at default span width or outside. With letter spacing this gonna be a float offset container, thus this hackish line prolly gets removed.

2023-07-27 14:50 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +    this._cacheMetrics();
Class is in the making, gets too confusing already for myself.

2023-07-27 14:51 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> -     * - (async) render update: brings term metrics and render state back in sync
This still happens, guess I forgot to copy over the comments (clamping code is still the same).

2023-07-27 14:52 UTC, jerch commented on src/browser/renderer/dom/DomRendererRowFactory.test.ts
> +const EMPTY_METRICS = new Uint8Array(1024);
To be hidden within a class (thus not being exposed anymore here).

2023-07-27 14:54 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +  private _linkState = new Uint8Array(3);
Oh and thats even the wrong typed array type :blush:. To be reworked...

2023-07-28 17:46 UTC, jerch commented
The basic rework to letter-spacing is done - up for alpha tests again.

So far the performance is really good (well as long as a monospace font is set) - it is much faster than the canvas renderer on my machine, and almost as fast as the webgl renderer (but more CPU hungry). The output and things like scrolling is really smooth now.

Still left to do:
- more unit & API tests
- ligature joiner still not working correctly
- cleanup

2023-07-28 18:07 UTC, jerch commented
some profiler graphics (tested with `ls -lR /usr` with one warm up call before):
- this PR
  ![grafik](https://github.com/xtermjs/xterm.js/assets/6193135/6ca6b3b9-8d01-4a15-93cd-e84f892081f1)
- webgl
  ![grafik](https://github.com/xtermjs/xterm.js/assets/6193135/5fca9950-6799-4ad9-8282-b8897f76520d)
- canvas
  ![grafik](https://github.com/xtermjs/xterm.js/assets/6193135/9bd7ff6f-a870-42be-8ef0-786a82748d8f)

The DOM renderer seems to render all frames fine, even the CPU is not at 100% anymore (upper greyish graph show bulges).
The canvas renderer is the slowest now, with several frames not finishing in time (that yellow-greenish areas in frames). It also has very high JS runtime compared to the others (prolly due accounting `drawImage` under JS).

2023-07-28 20:01 UTC, Tyriar commented on src/browser/renderer/dom/SpacingCache.ts
> +  private _holey = new Map<string, number>();
Doesn't need to be done in this PR, but sharing it between terminals similar to the texture atlas would be nice. Managing them is a matter of acquiring and releasing depending on the terminals font config.

2023-07-28 21:34 UTC, jerch commented on src/browser/renderer/dom/SpacingCache.ts
> +  private _holey = new Map<string, number>();
Sure, we can also abstract it further to meet a better font config interface. My font family string + a pixel size is quite lousy still (I saw that monaco expects here more style settings, which prolly helps to avoid surprising render issues by awkward css rules on the global document.)

2023-07-29 12:34 UTC, jerch commented
The single letter based letter-spacing method has one drawback - it cannot deal with kerning of proportional fonts, thus might create tiny offsets for fonts doing this. Ofc in a terminal a non-monospace font is ugly and should not be used in the first place.

I still wonder though, if we can address this issue by a second measuring of the merged span and applying a correction value. This will penalize render speed a lot, but maybe it is possible to do this additional measuring on degenerated spans only.

2023-07-29 13:40 UTC, jerch commented
The last commit disables font kerning, with this even fonts like Arial etc. align correctly to a grid. I dont see a perf penalty from this, but I am not sure if it will have other negative side effects (if so, then we should prolly make this an explicit setting to be used with certain fonts only).

2023-07-29 15:27 UTC, jerch commented
@Tyriar I changed the cache into a width cache, this way it can be re-used for the same font settings (before with px value differences it was also tied to the unicode provider).

2023-07-29 15:53 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> -     * - (async) render update: brings term metrics and render state back in sync
I re-added the notes about the edge cases. Though the new code needs less range checks, as the data structures that would overflow from this are not needed anymore.

Also the explicit re-rendering of hyperlink lines avoids a faulty in-between state. It still cannot handle a late render update by other means, which might steal the underline/link state right after. Imho thats a rather rare edge case and not worth to work around (would need state holding of active hyperlink in renderer).

2023-07-29 16:36 UTC, jerch commented
@Tyriar Seems the faulty test from above works again, weird.

2023-07-29 21:06 UTC, jerch commented
@Tyriar Found the reason for the selection refresh above - during lots of input with terminal scrolling a refresh gets called unconditionally here: https://github.com/xtermjs/xterm.js/blob/17b8247c3dc33c457e950da9f67ad137a74de069/src/browser/Terminal.ts#L534-L537

Since there was no additional selection check in `refresh` before, it would trigger the whole update cascade into the renderers. And the DOM renderer does a full viewport re-rendering on the selection event causing significant render stress.

I dont good other options than preventing the overhead at `refresh` itself.

2023-07-30 14:09 UTC, jerch commented
@Tyriar I think the selection handling of the DOM renderer needs some rewrite. The issue currently is that my debouncer in `SelectionService.refresh` omits any (empty) updates, but these updates are also relevant in DOM renderer to adjust previous selection elements, be it for resize, font size changes or dpr changes. In the end there is logic linked to `handleSelectionChanged` that has nothing to do with changed selections.

A possible fix would involve:
- store active selection in renderer
- create a `renderSelection` method with diff update from prev to current selection
- bind method to resize, dpr and charWidth change

2023-07-31 13:24 UTC, jerch commented
There is another issue hidden in the DOM renderer, that would fix several rendering glitches and be more performant - `inline-block` vs `inline` display for spans. We currently do `inline-block` on rows with a fixed height with `overflow: hidden`, which creates several glitches like cutting off over or underlines for certain font sizes or dpr. Also `inline-block` has a render penalty:
- current PR state with `inline-block` **~53 FPS** (750 frames in ~14s)
- spans with `inline` **~56 FPS** (780 frames in ~14s)
- compared to webgl **~57 FPS** (800 frames in ~14s)

This PR already achieves really good FPS compared to master (**~17 FPS**, 420 frame in ~25s), so we already dealt with the low hanging fruit. Imho the `inline` issue can be addressed in a later PR (also this is not a regression, it is just broken the same certain way).

2023-07-31 14:17 UTC, jerch commented
@Tyriar FYI - The last 2 commits revert the `inline` display and the selection service debouncer. This adds ~1.5s to the runtime again lowers the frame rate to ~50 FPS on my machine.

2023-07-31 15:57 UTC, jerch commented
About ligatures - with the letter-spacing merging ligatures work automatically, if a ligature font is installed. In fact the ligature addon should not be used anymore, as it makes things worse (the line on the right is a box border to see if there are offset glitches):
- w'o ligature addon the cursor can address single chars (temporarily breaking the ligature):
![recorded](https://github.com/xtermjs/xterm.js/assets/6193135/4ff843a5-c797-4ea8-b6dd-41ebd3fac4bd)

- with ligature addon the cursor vanishs until reaching the leading ligature char, then highlighting the whole ligature:
![recorded](https://github.com/xtermjs/xterm.js/assets/6193135/e83d0f4e-7aa3-4876-b7a9-18f175556566)


Idk know whats the desired bahavior here, we prolly should document the difference though.

2023-07-31 18:09 UTC, jerch commented on addons/xterm-addon-search/test/SearchAddon.api.ts
> +      it.skip('should fire when writing to terminal', async () => {
No clue why this happened, no clue how it got resolved, its gone. :smile_cat:

2023-07-31 18:11 UTC, jerch commented on src/browser/renderer/dom/SpacingCache.ts
> +  private _holey = new Map<string, number>();
Listed for follow-up PR.

2023-08-01 11:41 UTC, mofux approved these changes
I gave it a good test and it works very well for me (Linux with Edge and Firefox). The performance is impressive - well done! It's really only the block characters where the WebGL renderer is still superior. There certainly are ways to also add those custom-drawn block elements to the DOM renderer, but that is a task for another day :)

2023-08-01 12:04 UTC, jerch commented
@mofux Yeah the performance is quite impressive for the fact, that it is still DOM manipulations going on. Thx again for the letter-spacing trick, it is def. the better way to deal with it. As noted above, there are ~20% more perf bonus possible, if we manage to get the spans into `inline`, thus completely rely on the layouter to do its job. And it would solve all the over-/underline issues, and make Bidi partially work too.

About the block chars - yeah kinda all font renderer libs have issues with those in monospace, as far as I am aware almost all other TEs render those themselves to overcome the font lib shortcomings. I have not thought about a workaround for the DOM renderer yet, surely we can find here something.

2023-08-01 15:27 UTC, Tyriar requested changes
Did a thorough review, looks close

2023-08-01 15:27 UTC, Tyriar commented on src/browser/services/CharSizeService.ts
> +const CHAR_REPEAT = 32;
Let's make this a `const enum` so it's inlined at compile time

2023-08-01 15:27 UTC, Tyriar commented on src/browser/renderer/dom/WidthCache.ts
> +}
Can we use `/** */` style comments here so they show up in autocomplete?

2023-08-01 15:27 UTC, Tyriar commented on src/browser/renderer/dom/WidthCache.ts
> +    private readonly _document: Document
Let's remove private readonly as it's only used in the ctor

2023-08-01 15:27 UTC, Tyriar requested changes
Did a thorough review, looks close

2023-08-01 15:31 UTC, jerch commented on src/browser/renderer/dom/WidthCache.ts
> +}
Sure, gonna change it.

2023-08-01 15:31 UTC, jerch commented on src/browser/renderer/dom/WidthCache.ts
> +    private readonly _document: Document
Woops, left-over from before.

2023-08-01 15:33 UTC, jerch commented on src/browser/renderer/dom/WidthCache.ts
> +    this._container.style.width = '50000px';
Hmm idk, I basically took that idea from monaco. Can make it smaller, maybe more within typical `fontsize * measureRepeat`.

2023-08-01 15:39 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +      ` display: inline-block;` +   // TODO: find workaround for inline-block (creates ~20% render penalty)
Yeah, its already listed above under the "create follow-up issues" TODO.

I already tested this locally, but it touched too many aspects (e.g. dimension calc needs rework), thus I left it out of this PR.

2023-08-01 15:48 UTC, Tyriar commented on src/browser/renderer/dom/WidthCache.ts
> +    this._container.style.width = '50000px';
If it's in monaco I'm sure it's fine

2023-08-01 15:48 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +    );
Yeah well, I already thought to move the measure logic to the `CharSizeService`, which already receives the needed events. Then all thats needed, is to clear the cache on metrics changes. Should I move it over and merge with the measure logic there?

2023-08-01 15:48 UTC, Tyriar commented on src/browser/renderer/dom/WidthCache.ts
> +    this._container.style.top = '-50000px';
Yeah, but if monaco does this it's fine

2023-08-01 15:53 UTC, jerch commented on src/browser/renderer/dom/DomRenderer.ts
> +    );
Yeah prolly better as follow-up, it also will be affected by the yet to come shared API.

2023-08-01 19:32 UTC, Tyriar approved these changes
Looks like everything is checked off and comments resolved so let's merge and I'll pull it into VS Code so we can get some early testing. @jerch can you make the followup issues when you get a chance?

2023-08-01 19:32 UTC, merged

2023-08-01 20:31 UTC, jerch commented
> can you make the followup issues when you get a chance?

Yeah all done. :smiley_cat: