fix double underline, upwards
xtermjs/xterm.js pull request #4648
Opened 2023-08-08 12:46 UTC by tisilent

fix #4476

2023-08-08 13:39 UTC, Tyriar requested changes

2023-08-08 13:39 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
>            Math.abs(imageData.data[offset + 1] - g) +
Can you revert these? The intent here is to double-indent wrapped lines to easily differentiate them from the lines inside the block. You might need to disable prettier if you're using that.

2023-08-08 13:39 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
>              this._tmpCtx.lineTo(xChRight, yTop);
Since we're fixing a limitation of the canvas renderer, we still want the old ideal behavior on the webgl renderer. So this should be based on a flag passed into `_drawToCache`, something like `restrictToCellHeight: boolean`

2023-08-08 16:26 UTC, tisilent commented on src/browser/renderer/shared/TextureAtlas.ts
>            Math.abs(imageData.data[offset + 1] - g) +
ou.....I restore it. 😶‍🌫️

2023-08-09 13:44 UTC, Tyriar approved these changes
Works great 👍 

I created https://github.com/xtermjs/xterm.js/issues/4653 as we want a similar fix to curly too, ideally we would have a generic solution for this problem that ensures all underlines are within the cell for that.

2023-08-09 13:45 UTC, merged