Add cursorInactiveStyle option
xtermjs/xterm.js pull request #4657
Opened 2023-08-10 08:44 UTC by tisilent

fix #4566

2023-08-10 13:56 UTC, tisilent commented
The identifier declared by cursorInactiveStyle is somewhat different from that of cursorStyle. The displayed effect is consistent.

2023-08-10 14:02 UTC, Tyriar requested changes

2023-08-10 14:02 UTC, Tyriar commented on demo/client.ts
> +    cursorInactiveStyle: ['outline', 'line', 'underline', 'none'],
Let's copy cursorStyle:

```json
cursorInactiveStyle: ['outline', 'block', 'underline', 'bar', 'none']
```

We may as well add block as it's trivial and we want to align the naming of bar and line

2023-08-10 14:02 UTC, Tyriar commented on src/browser/renderer/dom/DomRendererRowFactory.ts
> +  CURSOR_INACTIVE_STYLE_NONE_CLASS = 'xterm-cursor-inactive-none'
We don't need special classes for underline or bar do we, since they should look the same as the regular styles?

2023-08-11 20:04 UTC, Tyriar commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    }
We can now get rid of this function if we standardize on 'outline'

2023-08-11 20:10 UTC, Tyriar approved these changes
Great PR 👏 I made a few small changes

2023-08-11 20:16 UTC, merged