Fix transparent foreground color
xtermjs/xterm.js pull request #4667
Opened 2023-08-12 00:50 UTC by Dennnnny

fix: #4408 

Description: 

I found this transparent foreground color will affect some text when the foreground is background
And  inside the `TextureAtlas`, there are already exist some check for background transparent
So I put another check foreground transparent 

Hope this make scenes

Any feedbacks is welcome, thanks

---

Screenshot: 

For local test, I change the xtermjsTheme foreground color with transparent
```
// demo/client.ts
const xtermjsTheme = {
  foreground: '#F8F8F8CC'
}
```
And the when no doing anything, it looks like:
<img width="965" alt="截圖 2023-08-12 上午12 25 04" src="https://github.com/xtermjs/xterm.js/assets/49616195/8c92239c-d9b1-4bbc-bd66-a108b370fc76">

After change:
<img width="980" alt="截圖 2023-08-12 上午12 25 59" src="https://github.com/xtermjs/xterm.js/assets/49616195/6a97cbc6-0f28-4696-b0b7-90e13396168e">

2023-08-12 01:51 UTC, Dennnnny commented
After thought... 
I think it didn't resolve problem that if people really want to have a transparent foreground
This workaround just avoid people from seeing weird effect, but it didn't really accept transparent.
So, even it fix the weird effect, but ... not sure if it fit your ideal solution 🤔

2023-08-12 15:34 UTC, Tyriar requested changes

2023-08-12 15:34 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
I was thinking we should instead prevent foreground colors from every being transparent. The `allowTransparency` setting is only the time when these colors should be transparent and it's only about background:

https://github.com/xtermjs/xterm.js/blob/dc390ab03afc338aa57e9849a0c30b45c01b8228/typings/xterm.d.ts#L33-L39

So I was thinking instead, when setting the theme we would force the foreground colors alpha channel to 255 and do a `logService.warn`

2023-08-12 16:03 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
@Tyriar thanks for reviewing this, 
I want to tell why I change here:
this issue happened when it is in inverse mode, background colors will use the foreground colors instead.
so don't you think that if we prevent the background color to be setting with transparent is a workaround ? 

if you still think we should prevent foreground colors from every being transparent, that's fine,
I just want to make sure that we are on the same page

thanks again.

2023-08-12 16:36 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
Hmm, I guess it depends on whether transparent foreground colors work already. If you set some transparent colors in the demo theme and then run some of the test buttons does it all seem to work correctly?

2023-08-12 17:15 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
yah, I think the foreground colors work already.
this is a screenshot with default foreground is : #F8F8F866, 
<img width="1113" alt="截圖 2023-08-13 上午1 00 08" src="https://github.com/xtermjs/xterm.js/assets/49616195/02ba6ddf-1192-48fe-9874-6bc8639ce6cf">

and this is screenshot with default foreground color: #F8F8F8,
<img width="1057" alt="截圖 2023-08-13 上午1 03 20" src="https://github.com/xtermjs/xterm.js/assets/49616195/521cfc54-ca12-4f3e-8fff-d45ae088ab1b">

but yah ... I just found that some background color also change in terminal wording... 
for example: colors in colors 17-231 from 256 palette seems to be also transparent a little bit.


<img width="1059" alt="截圖 2023-08-13 上午1 09 49" src="https://github.com/xtermjs/xterm.js/assets/49616195/a4db2fb9-c244-4c7d-8334-0ea456f4a9cc">
<img width="1068" alt="截圖 2023-08-13 上午1 03 52" src="https://github.com/xtermjs/xterm.js/assets/49616195/b2ea2897-a87c-4c04-af91-fafcdf2df651">

Not sure 🤔 
so ... what's your opinion about this situation ?
I can just work on your suggestion earlier: force foreground to not be transparent and add log

2023-08-12 18:00 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
Since transparent fg works, would it work if we forced the foreground color to be opaque when used as inverse background at line 301?

2023-08-12 18:00 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
I think we have a toOpaque or similar helper

2023-08-12 18:18 UTC, jerch commented
Have not looked at the PR code, just FYI:
We have no good idea, what transparency on FG should mean or be used for in a terminal. I tried to address this several times with other terminal devs, esp. because SGR has a dedicated transparent flag (which we dont support yet), but the response on that was more like "Idk, have not yet dealt in depth with it".

So until we resolve the issue, what transparency in FG can be used for and find a real good use case, I like @Tyriar 's idea to completely strip any transparency from FG from FG/BG colors swaps, maybe with an additional lumi correction to stay on sane ground.

2023-08-13 00:18 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
thanks for advices, I'll try again.

2023-08-13 10:29 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
@Tyriar  sorry for bothering again. 
now I'm trying to use the first suggestion you provided: **force fg colors alpha channel to 255**
but I think I met some issue here with test cases.

so...
when convert fg color alpha to 255 with `color.opaque` 
it seems to transform lowercase: "00FF00" -> "00ff00"
so it fail in test

so I'm thinking ... should I just directly adjust function in `color.opaque` to make it uppercase?
and, any advice if I put console.warn directly in ThemeService ?? ( I'm not sure where should I put this log 😕 

thanks

2023-08-13 17:46 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
Sorry for all the back and forth, but since foreground seems to work based on your testing can we instead change this line:

https://github.com/xtermjs/xterm.js/blob/70f6fa2bc91e27500900d8633d7f1279feb26e24/src/browser/renderer/shared/TextureAtlas.ts#L301

To this?

```ts
result = color.opaque(this._config.colors.foreground);
```

I'm worried about regressing when users rely on this now 😅

2023-08-14 01:18 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
oh, I tried that solution, it actually can fix that origin issue too.
but right now it will cause some background color become transparent too.
for example : Colors in colors 17-231 from 256 palette
like attach 
<img width="1059" alt="截圖 2023-08-13 上午1 09 49" src="https://github.com/xtermjs/xterm.js/assets/49616195/2062b34f-3abb-4b16-9ef0-8e8289df419b">
we don't want to these example to be transparent, right ??

so... okay!! I'll find out how to fix this too!!
then after everything is fixed, I'll ask for re-request review

it's my bad to do all the back and forth, 
I'm afraid to mess this up, so sorry 😟 
and thanks for every suggestions.

2023-08-14 01:52 UTC, Dennnnny commented on src/browser/renderer/shared/TextureAtlas.ts
> +    if (this._config.allowTransparency || (inverse && !color.isOpaque(this._config.colors.foreground))) {
so sorry for all these back and forth, I just don't want to mess this up.
And I think this one works as well.
I'll change to this solution

thanks.

by the way, do you want me to squash commits before merge ?

2023-08-14 12:24 UTC, Tyriar requested changes

2023-08-14 12:24 UTC, Tyriar commented on src/browser/services/ThemeService.ts
> +    console.warn("xterm.js is not fully support foreground colors with transparent, so it will the foreground colors alpha channel to 255.")
Oh I meant having this at TextureAtlas.ts by changing this line:

https://github.com/xtermjs/xterm.js/blob/39ae0f45fdee2195382e36db0f32cbeb7c747679/src/browser/renderer/shared/TextureAtlas.ts#L302

To:

```ts
result = color.opaque(this._config.colors.foreground);
```

If that works.

2023-08-14 14:40 UTC, Dennnnny commented on src/browser/services/ThemeService.ts
> +    console.warn("xterm.js is not fully support foreground colors with transparent, so it will the foreground colors alpha channel to 255.")
oh, sorry for the misunderstood.
yah this one should work as well, 
it will stay the foreground color to be transparent and if is inverse mode, it will make it opaque as background color.

thanks

2023-08-14 19:01 UTC, Tyriar approved these changes
Thanks for investigating this 👍

2023-08-14 19:11 UTC, merged

2023-08-15 00:02 UTC, Dennnnny commented
thanks for all the help and suggestions. 
it's my honor ❤️