C ontinuous underline dotted
xtermjs/xterm.js pull request #4684
Opened 2023-08-18 11:19 UTC by tisilent

fix #4349 
trial version
Font size above 26 is unstable.
Only processed webgl.
@Tyriar Is this idea feasible?

2023-08-18 11:21 UTC, tisilent commented
emmm, file format ...... 😭

2023-08-18 11:26 UTC, tisilent commented
![企业微信截图_16923578691709](https://github.com/xtermjs/xterm.js/assets/48614781/e61cc3a3-4c5a-46ff-96e9-41a2295816dd)
![企业微信截图_16923578691709](https://github.com/xtermjs/xterm.js/assets/48614781/7ada890a-25e3-42af-8dfe-bebd29cff71e)
This should be a reasonable situation.
size 21  ,   22

2023-08-18 14:35 UTC, Tyriar requested changes

2023-08-18 14:35 UTC, Tyriar commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +            variantOffset = ((deviceCellWidth! * chWidth) - variantOffset) % (lineWidth * 2);
For dotted, I would expect there only to be _up to_ `2 * dot_size` variants. So when the dot size is 1px, these would be the 2 variants for `s`:

![image](https://github.com/xtermjs/xterm.js/assets/2193314/70a5e7df-fa54-45ab-988b-81a11b784e73)

2023-08-18 14:52 UTC, tisilent commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +            variantOffset = ((deviceCellWidth! * chWidth) - variantOffset) % (lineWidth * 2);
Yes, I also think so. The formula for calculating offset has not been written yet.

2023-08-18 16:00 UTC, tisilent commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +          this._model.cells[i + RENDER_MODEL_VARIANT_OFFSET] === variantOffset
😨   I've sorted out the code and it's a bit messy. I've already figured out how to solve 2px+.

2023-08-21 09:51 UTC, tisilent commented
??...... why.

2023-08-21 10:22 UTC, tisilent commented
close,Resubmit. :sob:.

2023-08-21 10:22 UTC, closed without merging