Use variants for underline dotted.
xtermjs/xterm.js pull request #4703
Opened 2023-08-21 12:03 UTC by tisilent

fix #4349

2023-08-21 13:01 UTC, tisilent commented
hi @Tyriar , The effect should be better this time.

2023-08-21 13:30 UTC, Tyriar requested changes
Thanks! I'll try get to a proper review in a week or 2

2023-08-21 13:30 UTC, Tyriar commented on src/common/MultiKeyMap.ts
> +export class FiveKeyMap<TFirst extends string | number, TSecond extends string | number, TThird extends string | number, TFourth extends string | number, TFive extends string | number, TValue> {
Think this can be removed

2023-08-21 14:20 UTC, tisilent commented
I need to clean up the code.
I want to fix the dashed line as well.

2023-08-22 15:20 UTC, tisilent commented
Thanks.

2023-08-23 12:04 UTC, Tyriar commented on addons/xterm-addon-canvas/src/TextRenderLayer.ts
> +    let variantOffset: number = -1;
Can all this logic live inside CellColorResolver?

2023-08-23 12:05 UTC, Tyriar commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +    const deviceCellWidth = this._charAtlas?.getDeviceCellWidth();
Same; can this be shared inside CellColorResolver?

2023-08-23 12:06 UTC, Tyriar commented on addons/xterm-addon-webgl/src/WebglRenderer.ts
> +
You should be able to pull device cell width off `this.dimensions``

2023-08-23 13:34 UTC, tisilent commented
ok.I have discovered an issue now. I will solve it first

2023-08-24 13:22 UTC, Tyriar requested changes

2023-08-24 13:22 UTC, Tyriar commented on src/browser/renderer/shared/CellColorResolver.ts
> +        $variantOffset = computeVarinatOffset(deviceCellWidth * chWidth, lineWidth, $variantOffset);
I was expecting the variant to be based on the left-most pixel of the glyph, so `chWidth` wouldn't be needed?

2023-08-24 13:22 UTC, Tyriar commented on src/browser/renderer/shared/CellColorResolver.ts
> +        const lineWidth = Math.max(1, Math.floor(fontSize! * drp / 15));
If you pass in `IOptionsService` you can use `rawOptions.fontSize` and avoid the unsafe `!`

2023-08-24 13:22 UTC, Tyriar commented on src/browser/renderer/shared/CellColorResolver.ts
> +        const lineWidth = Math.max(1, Math.floor(fontSize! * drp / 15));
```suggestion
        const lineWidth = Math.max(1, Math.floor(fontSize! * this._coreBrowserService.dpr / 15));
```

2023-08-24 13:22 UTC, Tyriar commented on src/browser/renderer/shared/CellColorResolver.ts
> +    // Compute next varinatOffset
```suggestion
    // Compute next variantOffset
```

2023-08-24 13:22 UTC, Tyriar commented on src/browser/renderer/shared/TextureAtlas.ts
> +            } else {
I don't think you need a special case for this as the main effect is `+ offsetWidth` = `+ 0`?

2023-08-24 13:22 UTC, Tyriar commented on src/common/buffer/AttributeData.ts
> +      return val ^ 4294967288;
Hex would be easier to read here

2023-08-24 13:44 UTC, tisilent commented on src/browser/renderer/shared/CellColorResolver.ts
> +        $variantOffset = computeVarinatOffset(deviceCellWidth * chWidth, lineWidth, $variantOffset);
I need to take a look at the process here.....

2023-08-25 03:53 UTC, tisilent commented on src/browser/renderer/shared/CellColorResolver.ts
> +        $variantOffset = computeVarinatOffset(deviceCellWidth * chWidth, lineWidth, $variantOffset);
I see. 😄

2023-11-02 17:46 UTC, Tyriar approved these changes
This works really well! 👏 

![image](https://github.com/xtermjs/xterm.js/assets/2193314/b54603f9-bb0f-4a91-8587-8ffc1578b5a4)

![image](https://github.com/xtermjs/xterm.js/assets/2193314/2ae1b2aa-7e5c-4cc7-804c-b1bca8dc4faa)

![image](https://github.com/xtermjs/xterm.js/assets/2193314/aafcf35f-363a-48bd-a7ff-82125b17cce6)

2023-11-02 17:55 UTC, merged

2023-11-03 04:26 UTC, tisilent commented
Next. Curve.

2023-11-03 11:34 UTC, Tyriar commented
@tisilent that would be great, I found it a bit tricky to get the curve to look good at various zoom levels.