fix url parsing for urls with percentage sign in them
xtermjs/xterm.js pull request #4937
Opened 2024-01-05 08:44 UTC by szymonkaliski

This PR fixes the issue outline and discussed in here https://github.com/xtermjs/xterm.js/issues/4934

2024-01-05 14:52 UTC, jerch requested changes
LGTM, just a minor nitpick from my side below.

2024-01-05 14:52 UTC, jerch commented on addons/addon-web-links/src/WebLinkProvider.ts
>        // - append /   also match domain urls w'o any path notion
Can you also edit the comment to reflect the code, e.g. remove the listing and mention the explicit equality testing up to the host part.

2024-01-11 19:23 UTC, szymonkaliski commented on addons/addon-web-links/src/WebLinkProvider.ts
>        // - append /   also match domain urls w'o any path notion
updated the comment, lmk what you think

2024-01-11 20:39 UTC, jerch approved these changes
Yepp LGTM, thx alot! :+1:

2024-01-11 20:43 UTC, merged