Expose API method for writing to application side (#4948)
xtermjs/xterm.js pull request #4953
Opened 2024-02-01 08:22 UTC by arencoskun

This PR adds an input method which takes data as the parameter as described in the issue. If there are any issues, you can point it out and I'll fix it.

(Sorry if there's an issue, I am a beginner.)

2024-02-01 10:50 UTC, jerch requested changes
Welcome and thank you for looking into this.

Looks really good already, only a few my remarks from my side below.

2024-02-01 10:52 UTC, arencoskun commented
Thanks for the feedback, working on it

2024-02-01 12:33 UTC, jerch approved these changes
@arencoskun With fixing the remaining linter errors, this LGTM :+1:

2024-02-01 12:56 UTC, arencoskun commented
> @arencoskun With fixing the remaining linter errors, this LGTM 👍

Oops, forgot to fix those. Will work on it in a few moments

2024-02-01 13:34 UTC, jerch commented
@arencoskun The linter is still nagging about a whitespace is in `xterm.d.ts`.

Oh and btw - the declaration also needs to be added to `xterm-headless.d.ts` (sorry forgot about that before).

2024-02-01 13:48 UTC, arencoskun commented
> @arencoskun ~The linter is still nagging about a whitespace in `xterm.d.ts`.~ (guess you were faster 😸 )
> 
> Oh and btw - the declaration also needs to be added to `xterm-headless.d.ts` (sorry forgot about that before).

No problem, also adding that

2024-02-01 13:58 UTC, arencoskun commented
Sorry, forgot to mark as draft

2024-02-01 14:01 UTC, jerch commented
Whoopsie - the headless API-bundling class in `src/headless/public/Terminal.ts` would also need the impl forwarding similar to `browser/public/Terminal.ts`.

(Why? - We basically maintain 2 versions if xterm.js Terminal class - one for browser and for headless nodejs usage. So parts of the API bundling is doubled here.)

2024-02-01 20:24 UTC, arencoskun commented
> Whoopsie - the headless API-bundling class in `src/headless/public/Terminal.ts` would also need the impl forwarding similar to `browser/public/Terminal.ts`.
> 
> 
> 
> (Why? - We basically maintain 2 versions of xterm.js Terminal class - one for browser and for headless nodejs usage. So parts of the API bundling is doubled here.)
> 
> 
> 
> 

Thanks for the info, I've been busy tonight but most probably tomorrow I'll finish it off.
(Also, seems like you can't mark PRs as drafts from the mobile app. That's weird 😀 )

2024-02-02 07:32 UTC, jerch commented
@Tyriar Could you also review this PR? Because of the API addition I dont want to merge it w'o being reviewed by you.

2024-02-02 20:07 UTC, Tyriar approved these changes
Thanks! I just tweaks the docs and removed the doc strings from the internal files to reduce duplication/bitrot

2024-02-02 20:16 UTC, merged