Working on fixing Issue #3293
xtermjs/xterm.js pull request #5137
Opened 2024-08-25 23:55 UTC by Arup-Chauhan

@Tyriar Hi, I was working on #3293 and for that I have done the following things:

1. **Terminal.ts:**
   - I added logic to save the custom cursor style (`userCursorStyle`) when the terminal initializes. This ensures that the terminal keeps my preferred cursor style even when control sequences are sent.

2. **InputHandler.ts:**
   - I adjusted the `setCursorStyle` function to apply `userCursorStyle` when handling the reset cursor style sequence (`\x1b[0 q`). I also included some console log statements to help debug the cursor style changes.

### Possible Issue with Control Sequences:

While testing, I noticed something off with how the control sequences are being processed. Specifically, the output logs don't match the expected behavior.

**Current Log Outputs:**
```
Script is running
User Cursor Style: underline
DOM fully loaded and parsed
Sending control sequence as given 1
User Cursor Style: underline
Current Style: underline
Sending control sequence as given 2
User Cursor Style: underline
Current cursor style: underline
```

**Expected Log Outputs:**
```
Script is running
User Cursor Style: underline
DOM fully loaded and parsed
Sending control sequence as given 1
User Cursor Style: underline
Current Style: bar
Sending control sequence as given 2
User Cursor Style: underline
Current cursor style: underline
```

Am I testing / emulating the term terminal it properly? 
The current output suggests that the control sequences may not be applied correctly, particularly when resetting the cursor style. This might need a closer look to figure out what's going on.

Help would be appreciated.

2024-09-20 17:24 UTC, Tyriar requested changes

2024-09-20 17:24 UTC, Tyriar commented on src/common/InputHandler.ts
> +        break;
I think the approach you're taking it likely to cause problems (maybe what's causing the issue you mention now). Instead of trying to replace `this._optionsService.options.cursorStyle` or add a new `this._optionsService.options.userCursorStyle` to `this._optionsService.options` which is an object created by the user and not meant to be touched by us, we would want some way to setting an override which starts out at undefined. Makes sense to put this override in [`IDecPrivateModes`](https://github.com/Tyriar/xterm.js/blob/cb3bd463a5aabda47c135481ba4dbf7ccf8680ab/src/common/Types.ts#L267-L275) as mentioned in https://github.com/xtermjs/xterm.js/issues/3293#issuecomment-2094590792

Then when we go to use the actual cursor style from the renderer, we would use `devPrivateModes.cursorStyle ?? this._optionsService.options.cursorStyle ?? 'block'`

2024-10-01 22:18 UTC, Arup-Chauhan commented on src/common/InputHandler.ts
> +        break;
> I think the approach you're taking it likely to cause problems (maybe what's causing the issue you mention now). Instead of trying to replace `this._optionsService.options.cursorStyle` or add a new `this._optionsService.options.userCursorStyle` to `this._optionsService.options` which is an object created by the user and not meant to be touched by us, we would want some way to setting an override which starts out at undefined. Makes sense to put this override in [`IDecPrivateModes`](https://github.com/Tyriar/xterm.js/blob/cb3bd463a5aabda47c135481ba4dbf7ccf8680ab/src/common/Types.ts#L267-L275) as mentioned in [#3293 (comment)](https://github.com/xtermjs/xterm.js/issues/3293#issuecomment-2094590792)
> 
> Then when we go to use the actual cursor style from the renderer, we would use `devPrivateModes.cursorStyle ?? this._optionsService.options.cursorStyle ?? 'block'`


That makes sense, I will do this and get back to you, give me a while, thanks!

2024-10-12 01:54 UTC, Arup-Chauhan commented on src/common/InputHandler.ts
> +        break;
Hi @Tyriar, wanted to update you that I got some academic commitments mid-way so paused work on this.
I am continuing working on this, will keep you updated.

Once again, thanks for your support!

2024-12-20 18:11 UTC, Tyriar commented
Closing off as the approach was wrong and author is busy with other stuff atm.

2024-12-20 18:11 UTC, closed without merging