progress-addon
xtermjs/xterm.js pull request #5251
Opened 2024-12-15 18:05 UTC by jerch

This addon implements ConEmu's progress sequence, for more context see #5250.

The addon tries to hide most of the sequence's shenanigans behind a convenient API:
```typescript
const progressAddon = new ProgressAddon();
terminal.loadAddon(progressAddon);
progressAddon.register({state, value} => {
  // state: 0-4 integer
  // value: 0-100 integer
  
  // do your visualisation based on state/progress here
  ...
});
```

Fixes #5250.

2024-12-16 11:29 UTC, Tyriar requested changes
Really solid 👏 

Depending on app support, this could be really nice to integrate with the VS Code tab progress:

![image](https://github.com/user-attachments/assets/b6184af3-edc7-425e-914c-c020881a654a)

2024-12-16 11:29 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
Could pull this into `type ProgressState`?

2024-12-16 11:29 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public register(handler: ProgressHandler): IDisposable;
Should this be an event instead like this?

https://github.com/xtermjs/xterm.js/blob/41e8ae395937011d6bf6c7cb618b851791aed395/addons/addon-webgl/typings/addon-webgl.d.ts#L20-L23

2024-12-16 11:29 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public progress: IProgress;
Should this not be readonly?

2024-12-16 12:06 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public register(handler: ProgressHandler): IDisposable;
Yes would be better. Is there an easy way to that in an addon w'o pulling a whole bunch of code deps into it?

2024-12-16 12:23 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public progress: IProgress;
I guess set is fine as it means we can restore state if needed like when reloading a window in VS Code 👌

2025-01-07 17:53 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public register(handler: ProgressHandler): IDisposable;
@Tyriar Changed it to an event, which bloats the addon from ~2kB to ~50kB :scream:

I think all slightly more complex addons have the same issue, which is really nasty for web terminals. Should we expose stuff from /vs/* partially via the official API to get rid of doubled impls?

2025-01-07 17:59 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public register(handler: ProgressHandler): IDisposable;
Thats what gets pulled in:
```
asset addon-progress.js 41.8 KiB [emitted] [minimized] (name: main) 1 related asset
./out/ProgressAddon.js 2.87 KiB [built] [code generated]
../../out/vs/base/common/event.js 50.6 KiB [built] [code generated]
../../out/vs/base/common/lifecycle.js 21.1 KiB [built] [code generated]
../../out/vs/base/common/errors.js 7.6 KiB [built] [code generated]
../../out/vs/base/common/functional.js 1.09 KiB [built] [code generated]
../../out/vs/base/common/arrays.js 25.6 KiB [built] [code generated]
../../out/vs/base/common/collections.js 3.16 KiB [built] [code generated]
../../out/vs/base/common/map.js 4.3 KiB [built] [code generated]
../../out/vs/base/common/iterator.js 4.46 KiB [built] [code generated]
../../out/vs/base/common/linkedList.js 3.66 KiB [built] [code generated]
../../out/vs/base/common/stopwatch.js 1.23 KiB [built] [code generated]
../../out/vs/base/common/arraysFind.js 6.72 KiB [built] [code generated]
```

On code side I only need these imports:
```typescript
import { Emitter } from 'vs/base/common/event';
import { Disposable, toDisposable } from 'vs/base/common/lifecycle';
```

2025-01-07 18:33 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    public progress: IProgress;
Indeed. While that did not came to my mind, it is a strong reason to keep this way.

2025-01-07 18:34 UTC, jerch commented
@Tyriar applied your remarks, up for review again.

2025-01-07 20:25 UTC, jerch commented
@Tyriar Found a way to borrow the emitter ctor from xterm until https://github.com/xtermjs/xterm.js/issues/5283 is resolved. With this change things are back to normal with only 1.4kB minified :muscle:  :
```
asset addon-progress.js 1.4 KiB [compared for emit] [minimized] (name: main) 1 related asset
./out/ProgressAddon.js 2.25 KiB [built] [code generated]
```

2025-01-08 18:12 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
We shouldn't be referencing src from typing files. The more isolated the better as otherwise it can cause huge problems since libraries will suddenly be looking at and maybe linting against our source code, not just the types.

2025-01-08 18:24 UTC, Tyriar requested changes
Looks great, just some small polish things

2025-01-08 18:24 UTC, Tyriar commented on addons/addon-progress/README.md
> +  ```
Best to just defer to the .d.ts for API info, less susceptible to bitrot. Also we can add `@example` comments if needed:

https://github.com/Tyriar/xterm.js/blob/408d0995dddbe7b8e078cc68fb97d3f6166df7d0/addons/addon-webgl/README.md#L22

2025-01-08 18:24 UTC, Tyriar commented on addons/addon-progress/src/ProgressAddon.ts
> +    this.onChange = this._onChange!.event;
Don' think the `!` is needed?

2025-01-09 00:01 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
Hmm yeah, good point. Gonna try to find a better workaround. Sadly enums are tricky to use with d.ts files.

2025-01-09 00:05 UTC, jerch commented on addons/addon-progress/README.md
> +  ```
Agreed. I initially added this section because of the unconventional `register` handler stuff. Since its using the event type now, which is the preferred code pattern with xterm.js anyway, things are more self-explaining. Gonna remove the section.

2025-01-09 00:25 UTC, jerch commented on addons/addon-progress/src/ProgressAddon.ts
> +    this.onChange = this._onChange!.event;
Doesnt work without. My guess - the any casting above keeps the `undefined` as part of the type, so TS doesnt see this as not undefined-guarded here.

2025-01-09 01:03 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +  }
Renamed it.

2025-01-09 01:03 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
See my comment below.

2025-01-09 01:04 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +import type { ProgressState } from '../src/ProgressAddon';
Removed.

2025-01-09 01:10 UTC, jerch commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
Tried using a const enum inside the d.ts - this worked fine for TS itself and webpack build, but not with esbuild. So I changed it back to that integer union thingy.

2025-01-09 12:43 UTC, Tyriar commented on addons/addon-progress/typings/addon-progress.d.ts
> +    state: 0 | 1 | 2 | 3 | 4;
That's fine 👌

2025-01-09 12:43 UTC, Tyriar commented on addons/addon-progress/src/ProgressAddon.ts
> +    this.onChange = this._onChange!.event;
All good, this is temporary

2025-01-09 12:58 UTC, Tyriar approved these changes
👏 

Will try adopt in vscode now https://github.com/microsoft/vscode/issues/237564

2025-01-09 13:04 UTC, merged

2025-01-09 13:09 UTC, Tyriar commented
FYI in case you didn't see this https://github.com/kovidgoyal/kitty/issues/8011#issuecomment-2452009076

2025-01-09 13:12 UTC, Tyriar commented
I see winget uses indeterminate progress, do you know of another application that implements value/% based?

2025-01-09 13:17 UTC, jerch commented
> FYI in case you didn't see this [kovidgoyal/kitty#8011 (comment)](https://github.com/kovidgoyal/kitty/issues/8011#issuecomment-2452009076)

Yeah, thats the reason why I had to exclude handle of OSC 9 that dont continue with `;4`. There is a better more advanced sepc for notifications than the old OSC 9 stuff, imho it got moved to OSC 99 with more advanced bells&whistles.


> I see winget uses indeterminate progress, do you know of another application that implements value/% based? ([cargo coming soon](https://github.com/rust-lang/cargo/pull/14615))

Nope, I dont. Systemd prolly uses that, but no clue in windows world.

2025-01-09 13:38 UTC, Tyriar commented
winget's usage is a little unexpected since it seems to break up subtasks:

![image](https://github.com/user-attachments/assets/ecb19f9a-10ab-4ce6-842d-b2a9f1443369)

Not how I would have done it. I guess the progress state change should be debounced a little on my end to avoid a spinner flickering.

2025-01-09 14:25 UTC, jerch commented
@Tyriar Yeah, debouncing might be needed. The sequence isnt all that good in its spec - it is also unclear, how long to show the progress indicator or when to remove it (I'd guess that it should be removed after some time of inactivity, or after a window focus toggle etc)

2025-01-09 14:29 UTC, Tyriar commented
In my implementation I considered clearing the state after a command is run. I guess it's kind of a necessity if the proc crashes/ctrl+c doesn't handle it, etc.

2025-01-09 14:36 UTC, jerch commented
I guess it needs a timeout running down, as we never know for sure when the terminal client app crashed or gave up for whatever reason.

2025-01-09 14:39 UTC, Tyriar commented
I have it clearing when shell integration tells us any command finished: https://github.com/microsoft/vscode/pull/237573/commits/86b257ea82bca74e1fd719f952f0a9eee658fedc

Seems like a fairly safe thing to do